### ISSUE TITLE
[FR] Include iscrowd attribute when exporting OpenImages in COCO format

### ISSUE THREAD

**Issue by mswoff** [voxel51/fiftyone#1070]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### Proposal Summary

The default exporting of Open Images in the COCO format does not convert 'IsGroupOf' from Open Images to 'iscrowd' in the COCO format.

I also do not see any way to easily do this (e.g. renaming the IsGroupOf field), without writing a custom data exporter.

### Motivation

-   Why is this use case valuable to support for your project(s) or
    organization?
Open Images is a popular object detection dataset and COCO is a common format.

-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)
There is no way to rename 'IsGroupOf' to 'iscrowd' and have it work out of the box.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

(Use this section to include any additional information about the feature. If
you have a proposal for how to implement this feature, please include it here.)

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [x] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hey @mswoff 👋 

I agree that it would be useful to allow customizing the `iscrowd` attribute when exporting in COCO format. Here's the place where `iscrowd` is currently hard-coded:

https://github.com/voxel51/fiftyone/blob/21b4784c2f55859e5c775cbebdd00c74f7df500f/fiftyone/utils/coco.py#L639-L645

If you were to parameterize this and expose it as a parameter `iscrowd="iscrowd"` on the `COCODatasetExporter` class in that module, then you could export via the syntax below:

```py
import fiftyone as fo

dataset = fo.load_dataset(...)

# Pulls crowd annotation from the `IsGroupOf` field/attribute of all Detections
dataset.export(
    "/path/for/export",
    fo.types.COCODetectionDataset,
    iscrowd="IsGroupOf",
)
```

Are you open to giving it a shot and sharing a PR? We'd be happy to get this out in the next release

**Comment by mswoff** [comment]
Thank you for the suggestion! However, I could not figure out how to make
this change.

But another potential way that is maybe more extensible would be to add the
ability to rename detection fields or dynamically make new fields.

**Comment by brimoor** [comment]
@mswoff aha, the latter is already possible! check this out:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    label_types=["detections"],
    max_samples=10,
)

# Option 1: add new attribute in a loop
for sample in dataset:
    for detection in sample.detections.detections:
        detection.iscrowd = int(detection.IsGroupOf)

    sample.save()

# Option 2 (equivalent): use views
view = dataset.set_field("detections.detections.iscrowd", F("IsGroupOf").to_int())
view.save()

dataset.export(
    "/tmp/export",
    fo.types.COCODetectionDataset,
    label_field="detections",
)
```

```
python -m json.tool /tmp/export/labels.json
```

```
        ...
        {
            "id": 47,
            "image_id": 9,
            "category_id": 19,
            "bbox": [
                539.2,
                176.0,
                329.6,
                329.6
            ],
            "segmentation": null,
            "area": 108636.2,
            "iscrowd": 0
        }
    ]
}
```

**Comment by brimoor** [comment]
Renaming and cloning fields is also possible:

```py
# rename fields via loop
for sample in dataset:
    for detection in sample.detections.detections:
        detection.iscrowd = detection.IsGroupOf
        del detection.IsGroupOf

    sample.save()

# batch rename field
dataset.rename_sample_field(
    "detections.detections.IsGroupOf",
    "detections.detections.iscrowd",
)

# batch clone (copy) field
dataset.clone_sample_field(
    "detections.detections.IsGroupOf",
    "detections.detections.iscrowd",
)
```

**Comment by brimoor** [comment]
Exporting in COCO format currenly ignores other attributes that your `Detections` may have, since the COCO format spec doesn't include them.

What's your use case for wanting to store other attributes in the COCO format? Its certainly possible, but I'm curious what workflow you have in-mind that you'd want to do that.

**Comment by mswoff** [comment]
Oh amazing!! I thought this must be possible but couldn't figure it out so
thank you!!

I meant that this feature would be useful with other datasets where you
import using one a field with some name (e.g. is IsGroupOf) and then need
to export with a different name (e.g. iscrowd), but it looks like you
already thought that was true too!

**Comment by brimoor** [comment]
As of `fiftyone==0.12.0` this is fully supported:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    label_types=["detections"],
    max_samples=10,
)

dataset.export(
    labels_path="/tmp/coco.json",
    dataset_type=fo.types.COCODetectionDataset,
    iscrowd="IsGroupOf",
    extra_attrs=False,
)
```
