### ISSUE TITLE
No module name Zoo

### ISSUE THREAD

**Issue by thiwankajayasiri** [voxel51/fiftyone#1075]
Hi there,

I've successfully pip installed fifityone via pip install fiftyone and then execute the following code snippet,  executing error is that there is no module name 'zoo' ( wonder these needed to be built by cloning the repo, etc) 

Code snippet :

`import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6", split="validation", max_samples=50
)

session = fo.launch_app(dataset)
subset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    label_types=["detections"],
    classes=["Human face"],
    max_samples=50,
)

session.dataset = subset`

Log :
`    import fiftyone.zoo as foz
ModuleNotFoundError: No module named 'fiftyone.zoo'; 'fiftyone' is not a package`

System :
Apple M1, and it's inside the virtual environment, using Pycharm as the IDE. 

Troubleshooting steps:
pip install --upgrade pip setuptools wheel
pip install fiftyone

**Comment by benjaminpkane** [comment]
Hi @thiwankajayasiri 

Perhaps you have a `fiftyone.py` or `/fiftyone/__init__.py` in your current working directory that is shadowing the `fiftyone` package?

**Comment by benjaminpkane** [comment]
The `zoo` module comes with every installation of `fiftyone`.

**Comment by benjaminpkane** [comment]
Stale, closing.

**Comment by nagarjunvinukonda** [comment]
Hi I am having same trouble.

It says:
ModuleNotFoundError: No module named 'fiftyone.zoo'

when I import the Fiftyone.zoo?

Is there any solution for this?

**Comment by benjaminpkane** [comment]
Hi @nagarjunvinukonda. What's your environment? `pip` or `conda`? What does `fo.__path__` show?

```
import fiftyone as fo

print(fo.__path__)
```

The issue usually means you are not actually importing `fiftyone` package, but something else.

**Comment by nagarjunvinukonda** [comment]
Hi Benjamin,

Thank you for your fast reply.

I am using pip and Mac as my OS

**Comment by nagarjunvinukonda** [comment]
Hi I have solved the problem.

I did:
pip install fiftyone
pip install --upgrade fiftyone

I think upgrading solves the problem.

**Comment by nagarjunvinukonda** [comment]
Hi,

I have followed the above steps to install in ubuntu 18.0.4. I am using pip version 21, python3. after installation when I try to import the fiftyone I am having trouble:

```
>>> import fiftyone as fo
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/db/bin/mongod: failed to launch (code 127): /home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/db/bin/mongod: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/__public__.py", line 11, in <module>
    _database_service = fos.DatabaseService()
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/service.py", line 203, in __init__
    super().__init__()
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/service.py", line 81, in __init__
    self.start()
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/service.py", line 288, in start
    super().start()
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/service.py", line 232, in start
    super().start()
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/service.py", line 119, in start
    + self.command,
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/service.py", line 265, in command
    DatabaseService.find_mongod(),
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/service.py", line 372, in find_mongod
    "Could not find mongod>=%s" % DatabaseService.MIN_MONGO_VERSION
RuntimeError: Could not find mongod>=4.4

```

I don't understand whats going on, since its able to install in Mac properly but not in Ubuntu.

**Comment by benjaminpkane** [comment]
It looks like you need `libcurl3`

```
sudo apt install libcurl3
```

**Comment by nagarjunvinukonda** [comment]
First I have installed libcurl3 then libcurl4.

I am having some error:

>>>import fiftyone
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

**Comment by benjaminpkane** [comment]
It's a warning. You can ignore, we'll look into it.

**Comment by skro123** [comment]
Be careful not to name the file fiftyone.py, otherwise this problem will also occur.
