### ISSUE TITLE
[BUG] fiftyone.core.service.ServerService failed to bind to port 5151

### ISSUE THREAD

**Issue by clickmouse** [voxel51/fiftyone#1096]
This is my code following the tutorials. Could you help me fix this problem? I have tried to change the port, but it didn't work.
![image](https://user-images.githubusercontent.com/36254751/124250712-b75e9980-db57-11eb-81f1-eb263d15f401.png)
![image](https://user-images.githubusercontent.com/36254751/124250909-e5dc7480-db57-11eb-8d0a-8034d68797b6.png)

**Comment by clickmouse** [comment]
It seems like to be a problem of wsl2. However, I still don't know how to handle.

**Comment by benjaminpkane** [comment]
Hi @clickmouse.

So I am not familiar wsl2. Of course, if there is another process on `5151`, that is an issue. But regarding general port availability and access, this may be hard for use to diagnose.

You can try starting the server manually with the below
```
# in your environment
python /mnt/d/miniconda3/envs/py38/lib/python3.8/site-packages/fiftyone/server/main.py
```

If that works, then this is our issue. And we'll have to dig into this.

**Comment by clickmouse** [comment]
@benjaminpkane Thanks for your reply. It now works on my mac. It must be the problem of wsl2.
