### ISSUE TITLE
[BUG] Interactive plots are not updating in response to selections in Jupyter notebooks

### ISSUE THREAD

**Issue by wingvortex** [voxel51/fiftyone#1099]
### System information

-   **OS Platform and Distribution**:  Ubuntu 18.04 (remote), Win 10 (local)
-   **FiftyOne installed from**: pip install fiftyone
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone v0.11.1, Voxel51, Inc
-   **Python version**: Python 3.7.10 ( conda env)

### Commands to reproduce

Follow the exact tutorial at:
https://voxel51.com/docs/fiftyone/tutorials/open_images.html
Except:
1) Jupyter notebook is launched in remote mode: jupyter notebook --no-browser --port=6008 --ip=0.0.0.0
2) The fifty session is started by: session = fo.launch_app(view=eval_view, auto=False), and the fifty APP is running on a new tab instead within the cell of jupyter.

### Describe the problem
When following the tutorial to interactively visualize the object detection embeddings, after Lasso selection or box selection, there is no update view in the fifty APP.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by benjaminpkane** [comment]
Thanks, @wingvortex. I'm seeing this issue, as well. Stay tuned.

**Comment by brimoor** [comment]
Hey guys, I'm not able to reproduce this on my setup (which was 

```
remote: Ubuntu 18.04.5 LTS
local: macOS 11.3.1
browser: Chrome 
Python: 3.8.10 (conda env)
FiftyOne: v0.11.1 (source build)
```

I got started like so:

```shell
# on remote
jupyter notebook --no-browser --port=1234 /path/to/open_images.ipynb
```

```shell
# on local

# connect to notebook
ssh -N -L 1234:localhost:1234 brian@voxelbb1.ddns.net

# setup App usage on default port 5151
ssh -N -L 5151:localhost:5151 brian@voxelbb1.ddns.net

# now open localhost:1234 in browser
```

Skipping to the relevant section in the notebook, I ran the following and was able to interact with plots as expected.

```py
session = fo.launch_app(view=eval_view, auto=False)
# open localhost:5151 in another browser tab

bbox_area = F("bounding_box")[2] * F("bounding_box")[3]
areas = eval_view.values("predictions.detections[]", bbox_area)

plot = results.visualize(labels="predictions.detections.label", sizes=areas)
plot.show()

session.plots.attach(plot)
```

Variables that come to mind to me are:
- Are you sure you ran `session.plots.attach(plot)`? This is required in order for the App to automatically update in response to plot selections
- Is the fact that I'm using a source build the issue? (unlikely to me)
- Is it a browser or local OS issue? (also seems unlikely to me)

**Comment by wingvortex** [comment]
Thanks, @benjaminpkane  @brimoor 
Yes, session.plots.attach(plot) has been run.  Chrome and Edge browsers were both tested. 

The complete code is:

```
import fiftyone as fo

# Load ground truth
val_dataset = fo.Dataset.from_dir(
    dataset_type=fo.types.COCODetectionDataset,
    data_path=IMG_PATH,
    labels_path=LABEL_PATH,
    label_field="ground_truth",
)
val_dataset.persistent = True

# Add predictions to dataset
val_dataset.merge_dir(
    dataset_type=fo.types.COCODetectionDataset,
    data_path=IMG_PATH,
    labels_path=PRED_PATH,
    label_field="faster_rcnn",
)

from fiftyone import ViewField as F

# Only contains detections with high confidence
high_conf_view = val_dataset.filter_labels("faster_rcnn", F("confidence") > 0.4)

# Evaluate the predictions in the `faster_rcnn` field of `high_conf_view`
results = high_conf_view.evaluate_detections(
    "faster_rcnn",
    gt_field="ground_truth",
    eval_key="eval",
    compute_mAP=True,
)

# Load the evaluation view
eval_view = val_dataset.load_evaluation_view("eval")

# Start APP
session = fo.launch_app(view=eval_view, auto=False)

# Computes the area of each predicted object
bbox_area = F("bounding_box")[2] * F("bounding_box")[3]
areas = eval_view.values("faster_rcnn.detections[]", bbox_area)

plot = results.visualize(labels="faster_rcnn.detections.label", sizes=areas)
plot.show()

# Attach plot to session
session.plots.attach(plot)
```

**Comment by brimoor** [comment]
Here's a tweaked version of the above code that is semantically correct (`compute_visualization()` is required, not `evaluate_detections()`):

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")
dataset.persistent = True

high_conf_view = dataset.filter_labels("predictions", F("confidence") > 0.4)

fob.compute_visualization(
    high_conf_view,
    patches_field="predictions",
    brain_key="pred_viz",
    num_dims=2,
    method="umap",
    verbose=True,
    seed=51,
)

results = dataset.load_brain_results("pred_viz")

session = fo.launch_app(view=high_conf_view, auto=False)
# session.open_tab()
# open localhost:5151 in new tab

bbox_area = F("bounding_box")[2] * F("bounding_box")[3]
areas = high_conf_view.values("predictions.detections[]", bbox_area)

plot = results.visualize(labels="predictions.detections.label", sizes=areas)
plot.show()

session.plots.attach(plot)
```

**Comment by brimoor** [comment]
Hey @wingvortex @benjaminpkane. I was able to reproduce the issue when using `pip install fiftyone` rather than a source install.

[It turns out](https://github.com/voxel51/fiftyone/pull/1117) that something in `plotly>=5` introduced some backwards incompatible changes.

Installing the previous version of plotly should fix the issue!

```shell
pip install plotly==4.14.3
```

**Comment by wingvortex** [comment]
Thanks, @brimoor. Yes, you are right, the 'compute_visualization()' was missed out for the 'eval_view'. As your tweaked version showed, there is no need to run the evaluation here for this interactive plot demo.

In my case, the following way fixs the bug:
```
pip install plotly==4.14.3
jupyter labextension install jupyterlab-plotly@4.14.3
jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget@4.14.3
```
Without ' labextension install',  an error would pop out:  "Error displaying widget: model not found"

**Comment by brimoor** [comment]
Good news: https://github.com/voxel51/fiftyone/pull/1981 resolves this issue! As of the next release (`fiftyone>0.16.5`), FiftyOne's plotly requirement will simply be `plotly>=4.14`.

In fact, the current FiftyOne release is actually already fully compatible with `plotly>=5.2.1`, so you can just manually install a newer plotly version and ignore FiftyOne's version complaints.
