### ISSUE TITLE
Slack link not open to public

### ISSUE THREAD

**Issue by ankandrew** [voxel51/fiftyone#1100]
When trying to access your [slack](https://fiftyone-users.slack.com/) I get:

![image](https://user-images.githubusercontent.com/61120139/124617088-09036e80-de4d-11eb-8fc8-c8fa97a84340.png)

**Comment by benjaminpkane** [comment]
Hi @ankandrew. Here is an [invitation link](https://join.slack.com/t/fiftyone-users/shared_invite/zt-s6936w7b-2R5eVPJoUw008wP7miJmPQ).

We'll have to look into how to make https://fiftyone-users.slack.com/ work for anyone. Thanks!

**Comment by benjaminpkane** [comment]
All of our links should be invitation links. Out of curiosity, did https://fiftyone-users.slack.com/ come from our website, documentation, etc.?

**Comment by ankandrew** [comment]
> All of our links should be invitation links. Out of curiosity, did https://fiftyone-users.slack.com/ come from our website, documentation, etc.?

Yep, directly from your [website](https://voxel51.com/fiftyone/):

![image](https://user-images.githubusercontent.com/61120139/124625341-1708bd80-de54-11eb-806a-149883d41142.png)

**Comment by benjaminpkane** [comment]
Thank you! Our mistake, much appreciated. Fixing that now.
