### ISSUE TITLE
[FR] polyline(poly2d) evaluation in 'evaluate_detections'

### ISSUE THREAD

**Issue by lukelin-linkernetworks** [voxel51/fiftyone#1101]
### Proposal Summary

the 'evaluate_detections' function does not offer polyline (poly2d) evaluation at this moment.

### Motivation

-   What is the use case for this feature?
     When I have two datasets with 'ground_truth' and 'predictions', but both contained poly2d annotations.

-   Why is this use case valuable to support for FiftyOne users in general?
     Because there are the situations that objects are not annotated in bounding box but more accurate in polylines.

-   Why is it currently difficult to achieve this use case?  
    The current 'evaluate_detections' only supports classification, detection, and segmentation, and only bbox can be apply to detection.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

There is a library called "shapely" which has "poly_iou".

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hey @lukelin-linkernetworks 👋 check https://github.com/voxel51/fiftyone/pull/1114 out!

You can do a source install of that branch as follows:

```shell
git clone https://github.com/voxel51/fiftyone
cd fiftyone
git checkout --track origin/poly-eval
bash install.bash
```

I'd be interested to hear what you think of the implementation there if you have a chance to try it out 😄
