### ISSUE TITLE
[BUG] session.open_tab() hangs in remote Jupyter notebooks

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1102]
When working in a [remote Jupyter notebook](https://voxel51.com/docs/fiftyone/faq/index.html#can-i-use-fiftyone-in-a-remote-notebook), `session.open_tab()` hangs indefinitely.

I don't think it's possible to open a browser tab in the remote notebook workflow, so the desired behavior would be to either raise an error or log a message explaining how to view the App instance.

More generally, there may be other methods that need remote-notebook detection (`_remote` only handles App instances created with the `remote=True` flag).

**Comment by benjaminpkane** [comment]
I think the only situation we really cannot support is "pure" remote sessions, which could warn/error. Any notebook contexts (inc. colab and remote notebooks) could be supported with the IPython API.

```
from IPython.display import Javascript

def open_tab(url):
    display(Javascript('window.open("{url}");'.format(url=url)))
```

I'll work on it.

**Comment by brimoor** [comment]
Ah good point, `IPython` usage would do nicely 👍
