### ISSUE TITLE
[FR] Add support for coloring boxes by attributes other than label

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1106]
A popular user request is the ability to color boxes in the App based on the value of attributes *other* than `label`.

A common use case would be to run evaluation and then color boxes by their TP/FP/FN status. For example, in the example below, I might use this feature to color the objects in the `ground_truth` and `predictions` field by their `eval` attribute:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset.evaluate_detections("predictions", gt_field="ground_truth", eval_key="eval")

session = fo.launch_app(dataset)
```

Once we add dynamic embedded document fields to the dataset's schema, it may be natural to add icons next to the Label attributes (`label`, `confidence`, `eval`, etc) in the filters sidebar that can be clicked to switch to coloring by that field.

<img width="1147" alt="Screen Shot 2022-05-20 at 6 14 07 PM" src="https://user-images.githubusercontent.com/25985824/169619679-67ec6cb5-881f-499a-bd35-961362e7f118.png">

We can/should also expose this setting in the [App config](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-the-app), which would allow the user to programmatically configure per-field coloring:

```py
# Reconfigure the App to color `ground_truth` objects by their `eval` attribute
session.config.color_by["ground_truth"] = "eval"
session.refresh()
```

**Comment by brimoor** [comment]
@lanzhenw summarizing the design chat we had offline for this:
- Change `Color by label` text in settings menu to `Color by value`
- Add a checkbox to the tooltip of all categorical Label attributes (StringField, BoolField, and IntField) that says `Color by ${attribute name}`. This set of checkboxes defines a mutually exclusive choice of which attribute of each label field is used to color the boxes when the App is in `Color by value` mode
- When in `Color by value` mode, default to coloring by `label` attribute (current behavior)

A separate but related feature is to add a checkbox to the tooltip of all categorical attributes of type FloatField to scale the transparency of the label according to this attributes value relative to the bounds of the field. For example, if a FloatField ranges from `[-2, 2]` and a `Detection`'s attribute has the value 1, render the box at 75% opacity.

**Comment by benjaminpkane** [comment]
Resolved with [Color Schemes](https://docs.voxel51.com/user_guide/app.html#color-schemes)
