### ISSUE TITLE
[FR] Add 'license' field to COCO2014/2017 dataset view

### ISSUE THREAD

**Issue by Yosshi999** [voxel51/fiftyone#1108]
### Proposal Summary
COCO dataset has a list of licenses in the 'licenses' field and each entry in the 'images' field has an index of the license list.
It will be useful when we can filter this dataset by licenses like:
```
dataset.match(ViewField("metadata.license").is_in(
    ("Attribution License", "Attribution-ShareAlike License", "United States Government Work")
))
```

### Motivation

-   Filtering out the images whose license is not suitable for the user's purpose.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details
I think just adding 'license' field to [ImageMetadata](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/metadata.py#L55) is simplest.
It seems there is a license field in [export_sample()](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/utils/coco.py#L711) but I'm not sure when this code is executed.

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [x] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hi @Yosshi999 👋 this is a great idea! I added support fir this in https://github.com/voxel51/fiftyone/pull/1116 😄 

You can do a source install and try it out like so:

```shell
git clone https://github.com/voxel51/fiftyone
cd fiftyone
git checkout --track origin/coco-license
bash install.bash
```
