### ISSUE TITLE
Is there has docker image all ready builted in ubuntu? then I just used just run "docker pull **image" command 

### ISSUE THREAD

**Issue by yangsuhui** [voxel51/fiftyone#1132]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
-   **FiftyOne installed from (pip or source)**:
-   **FiftyOne version (run `fiftyone --version`)**:
-   **Python version**:

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue.

```
# commands here
```

### Describe the problem

Provide the exact sequence of commands / steps that you executed before running
into the problem.

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.

**Comment by benjaminpkane** [comment]
A docker image can be found [here](https://github.com/voxel51/fiftyone/actions/runs/1705766576).

Future [releases](https://github.com/voxel51/fiftyone/releases) will have a docker image attached to them.

Official [Dockerfile](https://github.com/voxel51/fiftyone/blob/develop/Dockerfile)

**Comment by beasteers** [comment]
It looks like the docker images are published as build artifacts (and you mention github releases too), but I don't think it's possible to just do `docker pull ...` with either of those (if it is let me know!). So would it be possible to have the github actions push to docker hub? e.g. https://docs.docker.com/build/ci/github-actions/ The next best option is using git submodules which is fine but less ideal.
