### ISSUE TITLE
App launched. Point your web browser to http://localhost:5151. Unable to connect fiftyone.

### ISSUE THREAD

**Issue by nagarjunvinukonda** [voxel51/fiftyone#1135]
Hi I am having trouble unable to connect to the fiftyone online. It says to add the port. Even through I have added the port the problem remains same. I have also added my python script to open the fiftyone app. 

<img width="1680" alt="Screen Shot 2021-07-21 at 2 07 36 PM" src="https://user-images.githubusercontent.com/49041896/126539064-03ea3ecf-db5d-41a4-9df2-5894faf8c103.png">### System information

-   **OS Platform Mac
-   **FiftyOne installed from (pip **:
-   **Python version**: 3.8

### Commands to reproduce
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset, port =5151)
```

### Describe the problem

Describe the problem clearly here. Include descriptions of the expected
behavior and the actual behavior.

### What areas of FiftyOne does this bug affect?

-   [ x] `App`: FiftyOne application issue
-   [ x] `Server`: Fiftyone server issue

**Comment by benjaminpkane** [comment]
@nagarjunvinukonda Both Chrome and Safari do not work? Can you provide [browser console](https://balsamiq.com/support/faqs/browserconsole/) error outputs?

It looks like the web socket connection is not being establish, which is curious. Reloading the page may help.

**Comment by nagarjunvinukonda** [comment]
Thanks for reply. Yes. it dosnt work.

The consol output is :
WebSocket network error: The operation couldn’t be completed. Connection refused

**Comment by benjaminpkane** [comment]
I just tested on my Mac, and I can't reproduce. If you are running this in a script, please use [`session.wait()`](https://voxel51.com/docs/fiftyone/api/fiftyone.core.session.html?highlight=wait#fiftyone.core.session.Session.wait) to keep the server alive.

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset, port =5151)
session.wait()
```

**Comment by nagarjunvinukonda** [comment]
Thank you, it works. 

I have a question:

I like to count no.of samples in COCO or open Image dataset only for a particular category. Ex: Cat or Dog or Person, etc. for detection training. How can fiftyone help me out with this? Is there any code to display only particular class categories.

**Comment by benjaminpkane** [comment]
```py
from fiftyone as fo

# load dataset
dataset = ...

F = fo.ViewField

my_filter = F("label").is_in(["Cat", "Dog", "Person"])
view = dataset.filter_labels("ground_truth", my_filter, only_matches=True)

# view detection class counts for "Cat", "Dog", and "Person"
view.count_values("ground_truth.detections.label")
```

I encourage you to read through some of our [user guides ](https://voxel51.com/docs/fiftyone/user_guide/index.html) including the [Dataset Views](https://voxel51.com/docs/fiftyone/user_guide/using_views.html) guide to get a sense of the APIs and what is possible.

**Comment by nagarjunvinukonda** [comment]
Hi,

Thank you for your code. I have seen the documentation for viewing dataset. 

Your code helps me to count total of all the no.of persons in ever image for a given dataset. But not no.of images that has person in it for a given dataset. I require the later.

I have tried your code using "quickstart" dataset which has 200 sample images:

```
import fiftyone as fo
import fiftyone.zoo as foz 

dataset = foz.load_zoo_dataset("quickstart")

F = fo.ViewField
my_filter = F("label").is_in(["Cat","Dog","Person"])
view = dataset.filter_labels("ground_truth", my_filter, only_matches=True)

view.count_values("ground_truth.detections.label")

session = fo.launch_app(dataset,port=5151)
session.wait()
```

It gives 380 person of total available in the 200 images as ground truth.  

Can you please let me know how to compute the no.of images that has person in it for a given dataset?

![data](https://user-images.githubusercontent.com/49041896/126594958-124171d1-b1a6-433b-89f0-8de1ae346983.png)

Followed by, printing view in your code provides me "zero" samples.

**Comment by benjaminpkane** [comment]
Open images does not have a `ground_truth` field.

You can print a summary of a dataset or view to see the fields that exist.

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    shuffle=True,
    max_samples=500
)

print(dataset)
```
Out:
```
Name:        open-images-v6-validation-500
Media type:  image
Num samples: 500
Persistent:  False
Tags:        ['validation']
Sample fields:
    id:              fiftyone.core.fields.ObjectIdField
    filepath:        fiftyone.core.fields.StringField
    tags:            fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:        fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.Metadata)
    positive_labels: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Classifications)
    negative_labels: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Classifications)
    detections:      fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    segmentations:   fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    open_images_id:  fiftyone.core.fields.StringField
    relationships:   fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
```

The number of samples (images) in a view is shown in the summary.
```py
F = fo.ViewField

view = dataset.filter_labels("detections", F("label").is_in(["Cat"]))

print(view)
```
Out:
```
Dataset:     open-images-v6-validation-500
Media type:  image
Num samples: 4
Tags:        ['validation']
Sample fields:
    id:              fiftyone.core.fields.ObjectIdField
    filepath:        fiftyone.core.fields.StringField
    tags:            fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:        fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.Metadata)
    positive_labels: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Classifications)
    negative_labels: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Classifications)
    detections:      fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    segmentations:   fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    open_images_id:  fiftyone.core.fields.StringField
    relationships:   fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
View stages:
    1. FilterLabels(field='detections', filter={'$in': ['$$this.label', [...]]}, only_matches=True)
```

Or you can use `len()`

```py
print(f"Number of samples (images): {len(view)}")
```
Out:
```
Number of samples (images): 4
```

> Is there any other way without downloading the large OpenimageV6 dataset we can compute the result I require?

No, this is a an open source tool that requires you to use your own computer. We look forward to adding support for URLs, etc. to avoid the overhead of downloading images, though.

**Comment by nagarjunvinukonda** [comment]
Thank you for clarifying, I have already downloaded the whole train dataset for OpenImageV6. I want to download again in a new folder and view it on Fiftyone. Hence, I have tried the following code:

import fiftyone as fo
import fiftyone.zoo as foz 

```
dataset = foz.load_zoo_dataset(
              "open-images-v6",
              split="train",
              label_types=["detections"],
              classes=["Cat", "Dog"],
              max_samples=100,
          )

session = fo.launch_app(dataset, port =5151)
session.wait()
```

After running my script. The Fiftyone on browser opens but it is empty, no images. I understand from the error I need either to download into a new folder or delete my existing dataset and run the script again. But, how to download the data into a new folder?
![Screen Shot 2021-07-23 at 5 59 06 PM](https://user-images.githubusercontent.com/49041896/126845504-266f39e1-dd33-44ba-8593-26d1bbaa60c5.png)

```
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Split 'train' already downloaded
Loading existing dataset 'open-images-v6-train-100'. To reload from disk, either delete the existing dataset or provide a custom `dataset_name` to use
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
App launched. Point your web browser to http://localhost:5151
Opening in existing browser session.
```

**Comment by benjaminpkane** [comment]
You can delete a dataset with `dataset.delete()`.

Or if you can delete it by name:
```py
import fiftyone as fo

fo.delete_dataset("open-images-v6-train-100")
```

Note that there is a difference between a Zoo download, and a FiftyOne Dataset.

I don't know why there are zero samples. But I recommend just deleting the existing **Dataset**. And note that when loading a new zoo dataset you can provide a name with `foz.load_zoo_dataset(..., dataset_name="new_dataset")` so there are not naming conflicts with an existing dataset.

If you need to delete the downloaded zoo data you can with [`foz.delete_zoo_dataset()`](https://voxel51.com/docs/fiftyone/api/fiftyone.zoo.datasets.html#fiftyone.zoo.datasets.delete_zoo_dataset). You can customize the location of a zoo download when loading it for the first time. See [here](https://voxel51.com/docs/fiftyone/api/fiftyone.zoo.datasets.html#fiftyone.zoo.datasets.load_zoo_dataset). And you can find with [`foz.find_zoo_dataset()`](https://voxel51.com/docs/fiftyone/api/fiftyone.zoo.datasets.html#fiftyone.zoo.datasets.find_zoo_dataset).

**Comment by sriram-dsl** [comment]
https://github.com/voxel51/fiftyone/issues/1135#issuecomment-884461973
this helped me thankyou @benjaminpkane
