### ISSUE TITLE
[FR] Add support for exporting instance segmentations in ImageSegmentationDirectory format

### ISSUE THREAD

**Issue by kognat-docs** [voxel51/fiftyone#1139]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone v0.11.1, Voxel51, Inc.
-   **Python version**: Python 3.9.6

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

save script below as `errorrepro.py` then run `python errorrerpo.py`

```
import fiftyone as fo
import fiftyone.zoo as foz
import eta

name = "cocopeoplesegmenations"
not_complete = True
while not_complete:
    try:
        dataset = foz.load_zoo_dataset(
            "coco-2017",
            split="train",
            label_types=["segmentations"],
            classes=["person"],
            max_samples=50000,
            dataset_name=name,
        )
        not_complete = False
    except eta.core.web.WebSessionError:
        pass

label_field = "ground_truth"  # for example

dataset.peristent = True
dataset.default_classes = dataset.distinct(f"{label_field}.segmentations.label")

export_dir = f"/media/sam/trainer/datasets/{name}"

dataset.export(
    export_dir=export_dir,
    dataset_type=fo.types.ImageSegmentationDirectory,
    label_field=label_field,
)

```

### Describe the problem

Describe the problem clearly here. Include descriptions of the expected
behavior and the actual behavior.

```
Existing download of split 'train' is sufficient
Loading 'coco-2017' split 'train'
 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [158.0ms elapsed, 0s remaining, 63.3 samples/s]     
Dataset 'cocopeople' created
   0% |/-------------------------------------------------------------------------------------------------------------------------------|  0/10 [5.3ms elapsed, ? remaining, ? samples/s] 
Uncaught exception
Traceback (most recent call last):
  File "/media/sam/trainer/gitlab/kognat/rotobot-trainer-docker/openimagefo.py", line 33, in <module>
    dataset.export(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/core/collections.py", line 5502, in export
    foud.export_samples(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 290, in export_samples
    write_dataset(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 343, in write_dataset
    _write_image_dataset(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 666, in _write_image_dataset
    dataset_exporter.export_sample(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 2352, in export_sample
    etai.write(segmentation.mask, out_mask_path)
AttributeError: 'Detections' object has no attribute 'mask'
```

The exporters class does not support segmentation data.

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate
the problem.

```
import fiftyone as fo
import fiftyone.zoo as foz
import eta

name = "cocopeoplesegmenations"
not_complete = True
while not_complete:
    try:
        dataset = foz.load_zoo_dataset(
            "coco-2017",
            split="train",
            label_types=["segmentations"],
            classes=["person"],
            max_samples=50000,
            dataset_name=name,
        )
        not_complete = False
    except eta.core.web.WebSessionError:
        pass

label_field = "ground_truth"  # for example

dataset.peristent = True
dataset.default_classes = dataset.distinct(f"{label_field}.segmentations.label")

export_dir = f"/media/sam/trainer/datasets/{name}"

dataset.export(
    export_dir=export_dir,
    dataset_type=fo.types.ImageSegmentationDirectory,
    label_field=label_field,
)
```
### Other info / logs

```
Existing download of split 'train' is sufficient
Loading 'coco-2017' split 'train'
 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [158.0ms elapsed, 0s remaining, 63.3 samples/s]     
Dataset 'cocopeople' created
   0% |/-------------------------------------------------------------------------------------------------------------------------------|  0/10 [5.3ms elapsed, ? remaining, ? samples/s] 
Uncaught exception
Traceback (most recent call last):
  File "/media/sam/trainer/gitlab/kognat/rotobot-trainer-docker/openimagefo.py", line 33, in <module>
    dataset.export(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/core/collections.py", line 5502, in export
    foud.export_samples(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 290, in export_samples
    write_dataset(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 343, in write_dataset
    _write_image_dataset(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 666, in _write_image_dataset
    dataset_exporter.export_sample(
  File "/home/sam/miniconda3/envs/bigdata/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 2352, in export_sample
    etai.write(segmentation.mask, out_mask_path)
AttributeError: 'Detections' object has no attribute 'mask'
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ * ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ * ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hey @kognat-docs 👋 

The issue is that the [ImageSegmentationDirectory](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#imagesegmentationdirectory) format is for semantic segmentation data stored in a [Segmentation](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#semantic-segmentation) field, but you're trying to export [instance segmentations](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#objects-with-instance-segmentations) stored in a `Detections` field.

If you wanted to export in `ImageSegmentationDirectory` format, you'd have to do the manipulations to paint the instance data into per-image masks stored in a new `Segmentations` field.

Here's an example of exporting in [COCODetectionDataset](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#cocodetectiondataset) format, which does support instance segmentations:

(FYI your related bug #1138 is noted)

```py
import fiftyone as fo
import fiftyone.zoo as foz

# Load some person segmentations from COCO-2017 dataset
dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="validation",
    label_types=["segmentations"],
    classes=["person"],
    max_samples=10,
)

session = fo.launch_app(dataset)

# Export in COCO format
dataset.export(
    export_dir="/tmp/coco",
    dataset_type=fo.types.COCODetectionDataset,
)

# Load the instance segmentations from the export back into FiftyOne
dataset2 = fo.Dataset.from_dir(
    dataset_dir="/tmp/coco",
    dataset_type=fo.types.COCODetectionDataset,
    label_types=["segmentations"],  # necessary or else only bboxes will be loaded
)

session.dataset = dataset2
```

**Comment by kognat-docs** [comment]
So there is no way to pool all of the Instance Segmentation masks into a per image segmentation mask 

I can do this with pycocotool.

But at that stage there is no need for voxel51's toolset.

This is summarises here:

https://forums.fast.ai/t/image-segmentation-on-coco-dataset-summary-questions-and-suggestions/36816

I thought given it is possible that you would have automatic convertion from COCODetectionDataset to ImageSegmentationDirectory as it is only a down cast of type.

**Comment by kognat-docs** [comment]
The nomeclature is unclear it says "segmentations" but it means "instance segmentations" and you have made it clear that segmentations and instance segmentations called detections are not interoperable.

The docs do not explain this suitably.

**Comment by kognat-docs** [comment]
Do any of the Dataset Zoo support "Segmentations" https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#semantic-segmentation that *can* be exported to `fo.types.ImageSegmentationDirectory`

Example code for a dataset of `fo.types.ImageSegmentationDirectory` with a background class and a single label class is all I am looking for. Hopefully with more than 5000 samples.

**Comment by pdmct** [comment]
+1
I am also encountering this problem. I have a coco-dataset that has segmentation polylines for multiple instances of each class within a single image but get this error when trying to convert to `ImageSegmentationDirectory`. 
example CoCo annotation:
```
{:id 0,
 :image_id 1837509664,
 :category_id 0,
 :segmentation
 [[143
   342
   140
   341
   137
   339
   134
   336
   134
   334
   136
   333
   139
   334
   143
   336
   147
   339
   147
   341
   145
   342]],
 :iscrowd 0,
 :area 66.5,
 :bbox [134 333 13 9]}
```
This gets loaded and displayed correctly in FiftyOne with a detection (the bbox) and the segmentation mask. But convert fails.  With the same error :`AttributeError: 'Detections' object has no attribute 'mask'`

The native format that I can see after loading the COCODataset into the FiftyOne app has a mask attribute, eg.
```'ground_truth_segmentations': <Detections: {
        'detections': BaseList([
            <Detection: {
                'id': '60f914fb2e10664628a5dfe4',
                'attributes': BaseDict({}),
                'tags': BaseList([]),
                'label': 'class_1',
                'bounding_box': BaseList([
                    0.40625,
                    0.2796296296296296,
                    0.013020833333333334,
                    0.014814814814814815,
                ]),
                'mask': array([[False, False,  True,  True,  True,  True, False, False, False,
                        False, False, False, False, False, False, False, False, False,
                        False, False, False, False, False, False, False],
                       [False,  True,  True,  True,  True,  True,  True,  True, False,
                        False, False, False, False, False, False, False, False, False,
                        False, False, False, False, False, False, False],
                       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
                         True, False, False, False, False, False, False, False, False,
                        False, False, False, False, False, False, False],...
```

Do I have to convert the COCODetection into the native FiftyOne format on disk and then to ImageSegmentationDirectory?

**Comment by samhodge** [comment]
Yeah I doubt that will work either

You need to get down into the pixel array with numpy, Pillow or OpenCV and Union combine each of the instance segmentation masks and create a new segmentation mask data structure and then serialise that to disk to declare it as Segmentation rather than Detection

Then you can have the ImageSegmentationDirectory

**Comment by pdmct** [comment]
Yes, it doesn't work. 

Which is a shame because those segmentation masks look just fine in the app - seems like an export button into image masks from the app or similar might be nice feature.

Like @kognat-docs I was hoping that the convert would save me the trouble of manually doing it ....

**Comment by samhodge** [comment]
We can make it happen. But it will take some development and testing. I have been taken in by the glossy front end assuming that there is as an all singing all dancing API that could take away all details of dataset conventions. But the support has been great. I was surprised with some of the conversion that it was as only utilising a single thread , as far as I could tell from CPU occupancy. When you have 48 threads available and a RAID NVMe being bottle necked by a single thread to end up in an error twenty times trying to work out if you are using the API wrong is more expensive than writing 20 lines of PyCOCO code and wrapping it in some worker threads .

**Comment by brimoor** [comment]
Hi @kognat-docs and @pdmct:

Conversion from instances/polylines to semantic segmentation format definitely makes sense. Indeed, it is our goal with FiftyOne to abstract away as many nitty gritty details of dataset curation as we can.

IN FACT, check this out https://github.com/voxel51/fiftyone/pull/1142.

You can try it out for yourself via a [source install](https://github.com/voxel51/fiftyone#installing-from-source):

```shell
git clone https://github.com/voxel51/fiftyone
cd fiftyone
git checkout --track origin/to-segmentation
bash install.bash
```

**Comment by kognat-docs** [comment]
I have been iterating on semantic segmentations from COCO 2017 using the sample code you have supplied with a model that is well suited to the `ImageSegmentationDirectory` export data format.

The install was via a wheel and I think you should drop this into the docs ASAP and merge it into the main branch.

Thanks so much.
