### ISSUE TITLE
[BUG] Cannot install fiftyone (Apple M1)

### ISSUE THREAD

**Issue by gordon-lim** [voxel51/fiftyone#1165]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 11.3.1 (Apple M1)
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: n.a
-   **Python version**: 3.9.6

### Describe the problem

```
ERROR: Cannot install fiftyone==0.1.0, fiftyone==0.1.0.1, fiftyone==0.1.2, fiftyone==0.1.3, fiftyone==0.10.0, fiftyone==0.11.0, fiftyone==0.11.1, fiftyone==0.11.2, fiftyone==0.11.2.1, fiftyone==0.2.0, fiftyone==0.2.1, fiftyone==0.3.0, fiftyone==0.4.0, fiftyone==0.4.1, fiftyone==0.5.0, fiftyone==0.5.1, fiftyone==0.5.2, fiftyone==0.5.2.1, fiftyone==0.5.3, fiftyone==0.5.3.1, fiftyone==0.5.4, fiftyone==0.5.5, fiftyone==0.5.5.1, fiftyone==0.5.6, fiftyone==0.7.0.1, fiftyone==0.7.1, fiftyone==0.7.1.1, fiftyone==0.7.1.2, fiftyone==0.7.1.3, fiftyone==0.7.1.4, fiftyone==0.7.2, fiftyone==0.7.3, fiftyone==0.7.3.1, fiftyone==0.7.3.2, fiftyone==0.7.3.3, fiftyone==0.7.3.4, fiftyone==0.7.4, fiftyone==0.8.0, fiftyone==0.8.0.1, fiftyone==0.9.0, fiftyone==0.9.1, fiftyone==0.9.2, fiftyone==0.9.3 and fiftyone==0.9.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    fiftyone 0.11.2.1 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.11.2 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.11.1 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.11.0 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.10.0 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.9.4 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.9.3 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.9.2 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.9.1 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.9.0 depends on fiftyone-brain<0.7 and >=0.6
    fiftyone 0.8.0.1 depends on fiftyone-brain<0.6 and >=0.5
    fiftyone 0.8.0 depends on fiftyone-brain<0.6 and >=0.5
    fiftyone 0.7.4 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.3.4 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.3.3 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.3.2 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.3.1 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.3 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.2 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.1.4 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.1.3 depends on fiftyone-db<0.3 and >=0.2.1
    fiftyone 0.7.1.2 depends on fiftyone-db<0.4 and >=0.3.0
    fiftyone 0.7.1.1 depends on fiftyone-db<0.4 and >=0.3.0
    fiftyone 0.7.1 depends on fiftyone-db<0.4 and >=0.3.0
    fiftyone 0.7.0.1 depends on fiftyone-db<0.3 and >=0.2
    fiftyone 0.5.6 depends on fiftyone-db<0.2 and >=0.1.1
    fiftyone 0.5.5.1 depends on fiftyone-gui<0.6 and >=0.5.5
    fiftyone 0.5.5 depends on fiftyone-gui<0.6 and >=0.5.5
    fiftyone 0.5.4 depends on fiftyone-db<0.2 and >=0.1.1
    fiftyone 0.5.3.1 depends on fiftyone-db<0.2 and >=0.1.1
    fiftyone 0.5.3 depends on fiftyone-db<0.2 and >=0.1.1
    fiftyone 0.5.2.1 depends on fiftyone-db<0.2 and >=0.1.1
    fiftyone 0.5.2 depends on fiftyone-db<0.2 and >=0.1.1
    fiftyone 0.5.1 depends on fiftyone-gui<0.6 and >=0.5.1
    fiftyone 0.5.0 depends on fiftyone-brain>=0.1.6
    fiftyone 0.4.1 depends on fiftyone-gui>=0.2.3
    fiftyone 0.4.0 depends on fiftyone-brain>=0.1.5
    fiftyone 0.3.0 depends on fiftyone-gui>=0.2.0
    fiftyone 0.2.1 depends on fiftyone-gui>=0.2.0
    fiftyone 0.2.0 depends on fiftyone-gui>=0.2.0
    fiftyone 0.1.3 depends on fiftyone-db
    fiftyone 0.1.2 depends on fiftyone-db
    fiftyone 0.1.0.1 depends on fiftyone-db
    fiftyone 0.1.0 depends on fiftyone-db

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

### Code to reproduce issue

`pip install fiftyone`

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [X] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @gordon-lim 👋 

The issue here is that installing `fiftyone` requires the `fiftyone-db` package, which contains the MongoDB binary [for your environment](https://github.com/voxel51/fiftyone/blob/a8f52fa278540565481dd584588773225333663c/package/db/setup.py#L27-L41).

Unfortunately, MongoDB [does not yet provide](https://www.mongodb.com/community/forums/t/support-for-apple-m1-silicon/12442) a prebuilt binary for M1 macs, so `pip` isn't finding a suitable version of `fiftyone-db` to install.

I haven't tested this myself, but the previous link states that M1 Mac users have found success running the MongoDB v4.4.2 build for x86-64 macs with Rosetta.

Can you try installing MongoDB v4.4.2 yourself on your machine and then `pip install --no-deps fiftyone` (to ignore unsatisfied `fiftyone-db` package)?

FiftyOne is designed to support manually MongoDB installs, so if you can get MongoDB running, then you should be able to use FiftyOne. We have a [docs page on this topic]( https://voxel51.com/docs/fiftyone/getting_started/troubleshooting.html#mongodb-compatibility-issues-on-linux).

**Comment by gordon-lim** [comment]
UPDATE:

I ran `brew install mongodb-community@4.4` and got 4.4.6 installed. 

`MongoDB shell version v4.4.6
Build Info: {
    "version": "4.4.6",
    "gitVersion": "72e66213c2c3eab37d9358d5e78ad7f5c1d0d0d7",
    "modules": [],
    "allocator": "system",
    "environment": {
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}`

I was manually pip installing the dependencies as shown in the No Module Found errors I was getting from the Quickstart code and it seems that I can't pip install other packages as well such as scikit-image and scikit-learn. I believe this is likely also due to the lack of support for M1 Macs. Here are some of the error message:

`Collecting scikit-image
  Using cached scikit-image-0.18.2.tar.gz (30.8 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/soymilk/Desktop/seq-tagging/bin/python /private/var/folders/z9/wjm53w_n3jl4wfzcyxrn54dm0000gn/T/pip-standalone-pip-whbqblfi/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/z9/wjm53w_n3jl4wfzcyxrn54dm0000gn/T/pip-build-env-uyxib2p5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools<=51.0.0' 'Cython>=0.29.18' 'numpy==1.19.2; python_version=='"'"'3.6'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.19.2; python_version=='"'"'3.7'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.19.2; python_version=='"'"'3.8'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.16.5; python_version=='"'"'3.6'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.16.5; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation`

I recognise however this is no longer under the domain of fiftyone so I will be closing this thread.

**Comment by brimoor** [comment]
To anyone reading this, please see https://github.com/voxel51/fiftyone/issues/1268 for updates.
