### ISSUE TITLE
[FR] Add confidence thresholds to tooltips of PR/ROC curves

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1196]
It would be helpful to see confidence thresholds (if possible, see below) in the tooltips of PR/ROC curves plotable via
- [BinaryClassification.plot_pr_curve()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/classification.py#L990)
- [BinaryClassification.plot_roc_curve()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/classification.py#L1024)
- [COCODetectionResults.plot_pr_curves()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/coco.py#L372)
- [OpenImagesDetectionResults.plot_pr_curves()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/openimages.py#L384)

In the first two, `skm.precision_recall_curve()` and `skm.roc_curve()` are used to compute the curves and they return thresholds, so it'll be trivial to get the data.

For detection evaluation, there are some nuances. See https://github.com/voxel51/fiftyone/issues/1195 for details.

In terms of adding the threshold data to the plot tooltips, you can see in [fiftyone.core.plots.plotly.plot_pr_curves()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/core/plots/plotly.py#L284-L290) how to customize the tooltip. A similar thing should be possible to add for the other PR/ROC curve plotting methods for the `plotly` backend.

Tooltips aren't supported by the `matplotlib` backend, so this would be a feature only supported by the `plotly` backend. But that's okay, there is already precedent for backend-specific arguments to plotting functions, e.g., [this code](https://github.com/voxel51/fiftyone/blob/c6dce6763c454eed727400b8c005b2e5b47eb16b/fiftyone/core/plots/base.py#L65-L77). Also, we would like to remove the `matplotlib` backend altogether in the future.

**Comment by pradkrish** [comment]
Hello, a newcomer to this project looking for good first issues. is someone working on this? Otherwise, I can give it a go.

**Comment by brimoor** [comment]
Hi @pradkrish 👋 No one is working on this yet so please do give it a go! Happy to assist if needed

**Comment by pradkrish** [comment]
I looked briefly at the implementation and also looked around for any available tests in the `tests/ `directory that uses `plot_pr_curve()` and `plot_roc_curve()` and found none, to my surprise. do you think it's a good idea to test those functions and if yes, can we make it part of this issue?

**Comment by brimoor** [comment]
Yeah we don't have good test coverage for graphical things like plots or the App (difficult to ensure plots are rendering as expected). Though I would certainly be onboard with adding basic unit tests to ensure the code runs without error (excluding `plot.show()`).

In terms of testing you work, the primary existing way is just to verify that the examples in the docs in places like the following work as expected: https://voxel51.com/docs/fiftyone/user_guide/evaluation.html

**Comment by pradkrish** [comment]
Will it be equivalent to making sure all the tests in `tests/intensive/evaluation_tests.py` pass after changes?

**Comment by brimoor** [comment]
yes, good point. I forgot about those because the tests in `intensive/` are not automatically included in our CI workflow. But, yes, running those tests manually (and adding new ones as necessary) is a good way to verify plotting-related functionality is working as expected

**Comment by pradkrish** [comment]
I have never worked with Plotly before and I have a basic question. This task is about adding a tooltip, does it mean  when I move the mouse cursor over the PR or ROC curve, I should be able to see a box with values for precision, recall and the corresponding threshold? In that case, it looks like I need to create a dataframe with columns for precision, recall and threshold and pass it into plot function. is that the right approach? Thanks.

**Comment by brimoor** [comment]
yes exactly. The plotly functions have something called `customdata` that you can use to store extra data (confidences, in this case) that you can use to define a custom tooltip that shows the confidence value when you hover over a point.

This snippet shows an example of doing that elsewhere in our codebase:
https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/core/plots/plotly.py#L1685-L1724

If you get stuck, forget about FiftyOne for a second and just try to make a plotly plot directly that does what you want. Then you can get it integrated into the FiftyOne codebase.
