### ISSUE TITLE
[BUG] display of segmentation masks with dype uint8 is broken

### ISSUE THREAD

**Issue by falckt** [voxel51/fiftyone#1204]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux, Ubuntu 21.04 and 18.04.5
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone v0.12.0, Voxel51, Inc.
-   **Python version**: Python 3.8.10 (fresh conda environment)

### Commands to reproduce

[Example data](https://github.com/voxel51/fiftyone/files/7012549/test.tar.gz)

```bash
fiftyone datasets create --name uint_mask --dataset-dir $TEST_DIR --type fiftyone.types.ImageSegmentationDirectory
fiftyone app launch uint_mask
```

### Describe the problem

Segmentation masks that are added with dtype `unit8` appear broken in the app. This is the case when importing a dataset using `ImageSegmentationDirectory` as above, as well as when manually adding such a sample to a dataset (c.f. example code below). When changing the dtype to `int` everything works as expected as seen in the code example below.

The behavior is easiest to observe with the code example below. If you look at the segmentation mask in the app, `int_mask` shows as expected, while `uint8_mask` is completely broken. There are a few pixels visible in a the upper left part of the image, but the label values are completely off. Probably something in the serialization/deserealization logic goes wrong and the data is unpacked incorrectly.

A quick fix is changing https://github.com/voxel51/fiftyone/blob/7c061ea22030ea355357df78a8c61598d784ea02/fiftyone/utils/data/importers.py#L2717 to
```python
    mask = etai.read(mask_path, cv2.IMREAD_UNCHANGED).astype(int)
```

### Code to reproduce issue

```python
# generate test data
import cv2
import numpy as np

img = np.zeros((400, 400, 3), np.uint8)
img = cv2.circle(img, (200, 200), 100, (255, 255, 255), -1)

mask = img[..., 0]

EXAMPLE_PATH = "/tmp/test_img.png"
cv2.imwrite(EXAMPLE_PATH, img)

# minimal example
import fiftyone as fo

ds = fo.Dataset()

ds.add_sample(
    fo.Sample(
        EXAMPLE_PATH,
        uint8_mask=fo.core.labels.Segmentation(mask=mask),
        int_mask=fo.core.labels.Segmentation(mask=mask.astype(int)),
    )
)

session = fo.launch_app(ds)

input("any key")
```

### Other info / logs

```
❯ pip list
Package                     Version
--------------------------- ---------
anyio                       3.3.0
appdirs                     1.4.4
argcomplete                 1.12.3
backports.zoneinfo          0.2.1
black                       21.7b0
boto3                       1.18.24
botocore                    1.21.24
certifi                     2021.5.30
charset-normalizer          2.0.4
click                       8.0.1
cycler                      0.10.0
dataclasses                 0.8
Deprecated                  1.2.12
dill                        0.3.4
dnspython                   1.16.0
eventlet                    0.31.1
fiftyone                    0.12.0
fiftyone-brain              0.6.2
fiftyone-db                 0.2.1
future                      0.18.2
glob2                       0.7
greenlet                    1.1.1
h11                         0.12.0
httpcore                    0.13.6
httpx                       0.18.2
idna                        3.2
imageio                     2.9.0
Jinja2                      3.0.1
jmespath                    0.10.0
joblib                      1.0.1
kaleido                     0.2.1
kiwisolver                  1.3.1
MarkupSafe                  2.0.1
matplotlib                  3.4.3
mongoengine                 0.20.0
motor                       2.5.0
mypy-extensions             0.4.3
ndjson                      0.3.1
networkx                    2.6.2
numpy                       1.21.2
opencv-python-headless      4.4.0.46
packaging                   21.0
pandas                      1.3.2
pathspec                    0.9.0
patool                      1.12
Pillow                      8.3.1
pip                         21.2.4
plotly                      4.14.3
pprintpp                    0.4.0
psutil                      5.8.0
pymongo                     3.12.0
pyparsing                   2.4.7
python-dateutil             2.8.2
pytz                        2021.1
PyWavelets                  1.1.1
PyYAML                      5.4.1
regex                       2021.8.3
requests                    2.26.0
retrying                    1.3.3
rfc3986                     1.5.0
s3transfer                  0.5.0
scikit-image                0.18.2
scikit-learn                0.24.2
scipy                       1.7.1
setuptools                  57.4.0
six                         1.16.0
sniffio                     1.2.0
sortedcontainers            2.4.0
tabulate                    0.8.9
threadpoolctl               2.2.0
tifffile                    2021.8.8
tomli                       1.2.1
tornado                     6.1
typed-ast                   1.4.3
typing-extensions           3.10.0.0
tzlocal                     3.0
universal-analytics-python3 1.1.1
urllib3                     1.26.6
voxel51-eta                 0.5.2
wheel                       0.37.0
wrapt                       1.12.1
xmltodict                   0.12.0
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.
-   [x] Maybe, depends on complexity.

**Comment by brimoor** [comment]
Hey @falckt thanks for reporting this. We'll tweak the App-side code to handle segmentation masks with any integer-type, so that users can store and work with masks in any integer type they prefer.
