### ISSUE TITLE
[FR] add support for captum / salience maps

### ISSUE THREAD

**Issue by DanTaranis** [voxel51/fiftyone#1231]
### Proposal Summary

add a way to see salience maps as overlay or next to images that were selected for inspection.

### Motivation

usually it's not as obvious as "dogs being tagged as cats" - getting salience maps is really helpful in that situation. 
The combination of being able to quickly get to relevant images + see in detail what is causing the model to get it wrong would be very synergistic. 

### What areas of FiftyOne does this feature affect?

-   [?] App: FiftyOne application
-   [?] Core: Core `fiftyone` Python library
-   [?] Server: FiftyOne server

### Details

check out captum if you are not familiar with it.

### Willingness to contribute

-   [ ] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [x] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
@DanTaranis good news, saliency maps will be visualizable when you store them in the `Heatmap` label field which is in-progress in https://github.com/voxel51/fiftyone/pull/1229 and will likely be included in the next release!

**Comment by DanTaranis** [comment]
incredible! 
how long would you expect it to take till it's released? like 2 weeks or so?

**Comment by brimoor** [comment]
> how long would you expect it to take till it's released? like 2 weeks or so?

yes I'd say within 2 weeks, that's about our cadence right now. As soon as #1229 is merged you can always use it immediately via a [source build](https://github.com/voxel51/fiftyone#installing-from-source) though 😄

**Comment by benjaminpkane** [comment]
Resolved by #1229
