### ISSUE TITLE
[FR] Allow classes to have unique attributes in the annotation label schema

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#1238]
At the moment, the `label_schema`, `classes`, and `attributes` arguments for `SampleCollection.annotate()` will take a list of classes and list of attributes. Every attribute is then available for annotation for every class.

A common workflow in CVAT is to annotate multiple label types in a single task by providing type-specific classes that each have different attributes. For example, you may want to annotate detections for the classes `["person", "car", "truck"]` with the attribute `occluded`, while also wanting to tag every sample as either `["sunny", "cloudy", "overcast"]`.  Alternatively, you may want to have the type attribute have values `["suv", "sedan", "hatchback"]` for the `car` class and `["tractor", "garbage", "cement"]` for the `truck` class.

There are a few ways that this could be implemented in the `label_schema` that need to be discussed.

**Comment by brimoor** [comment]
Implemented in https://github.com/voxel51/fiftyone/pull/1305.
