### ISSUE TITLE
[BUG] Large RAM usage when downloading Open Images dataset

### ISSUE THREAD

**Issue by HelloCentaurus** [voxel51/fiftyone#1259]
### System information

-   **OS Platform and Distribution (windows 10):
-   **FiftyOne installed from pip :
-   **FiftyOne version : v0.13.2;
-   **Python version: 3.9:

### Commands to reproduce

# shell commands  
_________________________________________
set HTTP_PROXY=http://127.0.0.1:1081
set HTTPS_PROXY=http://127.0.0.1:1081
python .\PycharmProjects\pythonProject\main.py

#code in main.py
_______________________________________________
import fiftyone.zoo as foz
import os

#dataset = foz.load_zoo_dataset("quickstart")
dataset1 = foz.load_zoo_dataset(
              "open-images-v6",
              split="train",
              label_types=["detections"],
              classes=["Bathtub"],
              max_samples=1000,
              seed=51,
              shuffle=True,
              dataset_name="open-images-Bathtub"
          )

_________________________________________
### Describe the problem
###This is happend after the CSV was parsed and it started to download the images. Crazy increase of memory,as  shown in image below:

![image](https://user-images.githubusercontent.com/15262893/132808119-c4c9ed7d-e997-4a63-9999-e3a9836e05db.png)

**Comment by brimoor** [comment]
Hi @HelloCentaurus 👋 

By default, downloading the images for the Open Images dataset will use `multiprocessing.cpu_count()` processes to do the job, [Here's the code](https://github.com/voxel51/fiftyone/blob/9e492a276edd48f0c0bfed7344dfaa2124973bea/fiftyone/utils/openimages.py#L1580-L1646)). Looks like you're working on a pretty beefy machine with lots of resources. Maybe such a large number of processes is becoming a bit too resource greedy for your liking.

You can pass an optional `num_workers` flag to `load_zoo_dataset()` to specify how many processes can be used. Can you try setting, say `num_workers=4` to see if that resolves it?

Note that you'll have to delete your existing download in order for the images to be actually downloaded again:

```py
import fiftyone.zoo as foz

foz.delete_zoo_dataset("open-images-v6", split="train")
```

**Comment by brimoor** [comment]
One comment is that train labels CSV file is huge (~3 GB if I remember correctly), and we load it into memory order to find some suitable images to download. I wonder if the multiprocessing could be causing copies of that to be shipped to each process? It is not explicitly done, might be a case of lazy garbage collection?

We really should have use multithreading as opposed to multiprocessing for the downloads. It would be interesting to see if making that change in the code I linked above would prevent the memory usage.

**Comment by brimoor** [comment]
I see `C:` and `D:` drives in your screenshot, so I believe you are running Windows. That reminds me that other users have had issues with multiprocessing code on Windows (eg https://github.com/voxel51/fiftyone/issues/1119), for which the recommendation was to use `num_workers=1`, which uses no multiprocessing at all.

Basically I think multiprocessing goes awry on Windows (in your case RAM hungry, in other cases flat out errors) and the best option seems to be to not use it.
