### ISSUE TITLE
AttributeError: module 'fiftyone' has no attribute 'config' [BUG]

### ISSUE THREAD

**Issue by robmarkcole** [voxel51/fiftyone#1267]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Bug Sur 11.5.2 
-   **FiftyOne installed from (pip or source)**:pip into venv
-   **FiftyOne version (run `fiftyone --version`)**:fiftyone v0.13.2
-   **Python version**: Python 3.9.5

### Commands to reproduce
From the quickstart

```
>>> import fiftyone as fo
>>> import fiftyone.zoo as foz
>>> dataset = foz.load_zoo_dataset("quickstart")
Downloading dataset to '/Users/robin/fiftyone/quickstart'
Downloading dataset...
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████|  188.0Mb/188.0Mb [6.9s elapsed, 0s remaining, 23.3Mb/s]      
Extracting dataset...
Parsing dataset metadata
Found 200 samples
Dataset info written to '/Users/robin/fiftyone/quickstart/info.json'
Loading 'quickstart'
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robin/Documents/fiftyone/venv/lib/python3.9/site-packages/fiftyone/zoo/datasets/__init__.py", line 290, in load_zoo_dataset
    dataset.add_importer(dataset_importer, label_field=label_field)
  File "/Users/robin/Documents/fiftyone/venv/lib/python3.9/site-packages/fiftyone/core/dataset.py", line 2759, in add_importer
    return foud.import_samples(
  File "/Users/robin/Documents/fiftyone/venv/lib/python3.9/site-packages/fiftyone/utils/data/importers.py", line 126, in import_samples
    sample_ids = dataset.add_samples(
  File "/Users/robin/Documents/fiftyone/venv/lib/python3.9/site-packages/fiftyone/core/dataset.py", line 1361, in add_samples
    with fou.ProgressBar(total=num_samples) as pb:
  File "/Users/robin/Documents/fiftyone/venv/lib/python3.9/site-packages/fiftyone/core/utils.py", line 771, in __init__
    kwargs["quiet"] = not fo.config.show_progress_bars
AttributeError: module 'fiftyone' has no attribute 'config'
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by robmarkcole** [comment]
Appears to be resolved after following https://voxel51.com/docs/fiftyone/getting_started/install.html#troubleshooting

```
pip install --upgrade pip setuptools wheel
pip install fiftyone
```

**Comment by brimoor** [comment]
Glad that the troubleshooting section in the docs helped! Sounds like you're good to go so I'm going to close this issue.

**Comment by michaelku1** [comment]
I am sorry, but after running the pip install commands no collab, I still got the same error. Does anyone experience the same issue?

**Comment by benjaminpkane** [comment]
Hi @michaelku1. I would refer to troubleshooting to make sure you aren't missing anything:

* https://voxel51.com/docs/fiftyone/getting_started/install.html#troubleshooting

If you're unable to resolve it, you can make an issue detailing your environment, etc. and we can try to help.
