### ISSUE TITLE
[BUG] Video out of sync with label overlay

### ISSUE THREAD

**Issue by doronpor** [voxel51/fiftyone#1270]
### System information

-   Linux Ubuntu 18.04.2 LTS
-   installed from source
-   version 0.13.2
-   python version 3.6.9

### Commands to reproduce

```
1. Create a video with the details bellow
2. Load a database with high amount of labels
3. hover over the Thumbnail or play a video in full screen
```

### Describe the problem

Video occasionally gets out of sync with label overlay, i.e. when hovering on the thumbnail
or when playing video of the sample, the image would start playing in a high rate and 
the labels would catch-up after the video well after the video would stop playing.

### Code to reproduce issue

**Video created with the following parameters**:

_ffmpeg output parameters_:
["-f", "mp4", "-vcodec", "libx264", "-vb",  "4096K",
"-minrate", "4096K", "-maxrate", "4096K", "-bufsize", "250k",                                                                                                                                     "-pix_fmt", "yuv420p", "-vsync", "0"]
_video resolution_: 2688 x 1520
_frame rate_: 4 fps
_Labels_: There are high amount of labels on the video (7 layers including detections and polylines)

**connection information**:

Server is running in linux system. 
Application running on windows remote system (edge or chrome)

### What areas of FiftyOne does this bug affect?

-   [X] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [X] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @doronpor 👋 

Thanks for reporting this. I noticed some occasional frame-label misalignments when doing some in-progress work on video features recently as well. We'll take a look at this and report back ASAP here

**Comment by doronpor** [comment]
Hi Brimoor,
Any success with identifying the issue ?

**Comment by benjaminpkane** [comment]
HI @doronpor. I've made a video per your description and have tested it with a ~200 detections, but am not seeing any issues.

https://github.com/voxel51/fiftyone/pull/1228 has a fix in the video player related to sparse frame labels, but that does not sound like your issue.

Providing reproduction steps would help, i.e. a script that creates a video with some dumby labels. Even just some dumby labels that cause the same issue would help.

**Comment by doronpor** [comment]
Thanks Benjamin, 

I digged around a little and seem pinpoint the issue to the 4 fps video. 
Apparently web browsers are not good with low frame rate video. 
I re-encoded my video from 4 fps to 24 fps which seems to resolve the issue. 
Its only artificial solution, because in order to do that I copied the annotations
to the additional images, but this inflates the data X6 times the data.

**Comment by benjaminpkane** [comment]
Yes, the video player is only as accurate as the web allows. There is a new [API](https://wicg.github.io/video-rvfc/) that we will leverage. Only chromium browsers have it currently, though. We will likely leverage  that, and only use the current method as a fallback.

But the current method should only be off by one frame at most. It should not get progressively worse during playback. And it is always frame accurate when paused. If this is not the case for you, let us know.

Regarding your second issue, each frame is constrained to 16MB of label data (including masks) at the moment. 16MB is MongoDB's document size limit.
