### ISSUE TITLE
[FR] Allow annotations to be loaded into a new label field

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#1291]
When annotating a label field it would be useful to be able to load annotations into a different label field instead of overriding the field that was uploaded. This is workflow currently possible with the `clone_sample_field()` method but for large datasets, cloning the field can take quite some time. 

Being able to upload an existing field immediately and then clone it while annotators are working would allow for these operations to occur concurrently.

This workflow would be equivalent to:
```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
view = dataset.take(10)

view.clone_sample_field("ground_truth", "updated_gt")

results = view.annotate(
    "anno_run",
    label_field="updated_gt",
    launch_editor=True
)

view.load_annotations("anno_run", cleanup=True)
view.delete_annotation_run("anno_run")
```

New more efficient workflow:
```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
view = dataset.take(10)

results = view.annotate(
    "anno_run",
    label_field="ground_truth",
    launch_editor=True
)

# Now cloning occurs at the same time as annotation
view.clone_sample_field("ground_truth", "updated_gt")

view.load_annotations(
    "anno_run",
    destination_label_field="updated_gt",
    cleanup=True,
)
view.delete_annotation_run("anno_run")
```

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/pull/1642
