### ISSUE TITLE
[FR] Guarantee TIFF support in the App

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#1294]
In our FAQ, we recommend adding a [tiff view extension](https://github.com/my-codeworks/tiff-viewer-extension) for chrome and firefox, but the chrome webstore link is dead.

If the extension is able add TIFF support seamlessly, it must be able possible to add TIFF support directly in the App. This would offer support in the desktop App, as well.

**Comment by fcakyon** [comment]
@benjaminpkane how can i visualize tiff images in chrome browser?

**Comment by bisraelsen** [comment]
Any updates on this? I cannot view `.tiff` files in the browser or desktop app... the recommended extension is no longer available.

**Comment by fcakyon** [comment]
@bisraelsen unfortunately they dont care about tiff support and since the extension is no longer available I couldnt a way either.

**Comment by benjaminpkane** [comment]
We are a small team getting requests from all directions. We welcome contributions.

It looks like Safari is the only browser that supports TIFF. See [here](https://stackoverflow.com/questions/2176991/how-would-i-display-a-tiff-images-in-all-web-browsers).

**Comment by benjaminpkane** [comment]
Duplicate of #3717
