### ISSUE TITLE
[FR] Upgrade plotly

### ISSUE THREAD

**Issue by twsl** [voxel51/fiftyone#1319]
### Proposal Summary

Update plotly to the latest major version.

### Motivation

-   What is the use case for this feature? compatibility, reduced technical debt, multiple reasons I use the latest version
-   Why is this use case valuable to support for FiftyOne users in general? yes
-   Why is this use case valuable to support for your project(s) or
    organization? yes
-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient) Couldn't find any reason

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

I checked the release logs and it seems like no feature was depricated. Since v5 plotly requires 3.6 minimum but so does fiftyone.

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [x] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hi @twsl 👋 

When Plotly 5 was released, https://github.com/voxel51/fiftyone/issues/1099 was reported which led us to require `plotly>=4.14,<5` until we could figure out what breaking change Plotly 5 made that is preventing callbacks on our [interactive plots](https://voxel51.com/docs/fiftyone/user_guide/plots.html) from working as expected.

Sounds like you're familiar with Plotly 5; are you able to look into what tweak might be needed to get Plotly 5 to work so we can remove the `plotly<5` requirement?

**Comment by twsl** [comment]
I have just used it a few times, but I can try to find some time to look into it. Do you know, if this repo can participate in hacktoberfest?

**Comment by brimoor** [comment]
I added the `hacktoberfest` topic to the repo, so I believe that means your PR will count towards hacktoberfest!

**Comment by twsl** [comment]
I haven't found any time so far and won't for at least another month, but plotly keeps increasing its version so i'd like to bring this back on the agenda

**Comment by brimoor** [comment]
Good news: https://github.com/voxel51/fiftyone/pull/1981 resolves this issue! As of the next release (`fiftyone>0.16.5`), FiftyOne's plotly requirement will simply be `plotly>=4.14`.

In fact, the current FiftyOne release is actually already fully compatible with `plotly>=5.2.1`, so you can just manually install a newer plotly version and ignore FiftyOne's version complaints.
