### ISSUE TITLE
[BUG] `compute_visualization` does not check for library dependencies until after computing embeddings

### ISSUE THREAD

**Issue by dlangerm** [voxel51/fiftyone#1349]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
-   **FiftyOne installed from (pip or source)**:  pip
-   **FiftyOne version (run `fiftyone --version`)**:  0.13.3
-   **Python version**: 3.9

### Commands to reproduce

Run `compute_visualization` without umap installed, observe embeddings being computed before the check for the dependency, causing the command to fail after a long runtime.

### Describe the problem

`compute_visualization` can take a while to run depending on the size of the dataset. I just had it run for quite a while computing embeddings but was met with this error immediately before it returned:

```
~/xxx/site-packages/fiftyone/brain/internal/core/visualization.py in _ensure_umap()

ImportError: You must install the `umap-learn` package in order to use UMAP-based visualization. This is recommended, as UMAP is awesome! If you do not wish to install UMAP, try `method='tsne'` instead
```

### Code to reproduce issue

N/A, dependency check error not implementation bug

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time. (sorry very busy today)

**Comment by brimoor** [comment]
This is implemented as of `fiftyone==0.14.3`
