### ISSUE TITLE
[BUG] fiftyone.config.dataset_zoo_dir is ignored

### ISSUE THREAD

**Issue by matthewfranglen** [voxel51/fiftyone#1359]
### System information

-   Linux Ubuntu 20.04.3:
-   FiftyOne installed from pip
-   FiftyOne v0.14.0, Voxel51, Inc.
-   Python 3.9.6

### Commands to reproduce

```python
import fiftyone as fo
import fiftyone.zoo as foz

fo.config.dataset_zoo_dir = "/data/fiftyone"
dataset = foz.load_zoo_dataset("quickstart")
print(dataset.first().filepath)
```

This prints `/home/matthew/fiftyone/quickstart/data/000880.jpg`.

### Describe the problem

I don't like sticking things in my home directory.
I want to use a custom directory for the data downloaded by fiftyone.
The configuration modification is documented [here](https://voxel51.com/docs/fiftyone/user_guide/config.html#modifying-your-config-in-code).
The specific field is documented [here](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuration-options).
I have updated the field and the update has applied, yet it is ignored by the dataset.

I've already looked at the code.
The dataset folder is resolved [here](https://github.com/voxel51/fiftyone/blob/56020a239b7db6cfc40958b406487c3514693a78/fiftyone/zoo/datasets/__init__.py#L529).
The dataset should be loaded from the folder I have indicated.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by matthewfranglen** [comment]
What does that even mean? The dataset has been written to disk so of course it's persistent.

**Comment by brimoor** [comment]
You have other datasets' metadata stored in your database too.

```py
import fiftyone as fo

print(fo.list_datasets())

for name in unwanted_datasets():
    fo.delete_dataset(name)
```

Storing metadata in the database allows FiftyOne to support datasets whose metadata exceeds RAM, as well as other features like multiuser collaboration.
