### ISSUE TITLE
[BUG] Trajectory index changes when loading CVAT annotations with multiple class labels in one track

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#1360]
### Problem description

In FiftyOne, when working with video labels, you can modify the class `label` of an object and retain the same `index`. This means that the class of the object can change partway through the trajectory. CVAT does not allow this, so when uploading the trajectory to a CVAT track, it is split into two separate tracks wherever the class `label` changes. When loading the tracks back into FiftyOne, they are each loaded with a different index instead of being loaded back into the same original trajectory.

### Code to reproduce
```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1).select_fields().clone()

sample = dataset.first()
for ind, frame in enumerate(sample.frames.values()):
    if ind > 10:
        label = "l2"
    else:
        label = "l1"

    det = fo.Detection(
        label=label,
        bounding_box=[0.1,0.1,0.3,0.3],
        index=1,
    )

    frame["detections"] = fo.Detections(detections=[det])
sample.save()

anno_key = "multilabel_track"
results = dataset.annotate(
    anno_key,
    label_field="frames.detections",
)

session = fo.launch_app(dataset)

input()

dataset.load_annotations(anno_key, cleanup=True)
session.refresh()
```

### Possible solution 1

One solution is when loading annotations and updating the track indices here:
https://github.com/voxel51/fiftyone/blob/b9abe5618e6d700524d0d0b003aeaead7c8da90f/fiftyone/utils/annotations.py#L1445-L1453

Move the `_seen_indexes = set()` one line down so they are potentially unique per frame. 

There is a problem with this where the indices may not always be unique per frame. Assume you have a track that changes label partway through:
```
---class1_index1---------\------class2_index1--------
```

It would be uploaded to CVAT as two different tracks like this:
```
---class1_index1---------
                         ------class2_index2--------
```
This allows the user to modify the tracks in CVAT to overlap as follows:
```
---class1_index1------------
                         ------class2_index2--------
```

Loading this into FiftyOne would then remap both `index1` and `index2` back to `index1` resulting in the frames in the overlapping section containing multiple objects with the same track index which is not allowed. The way to resolve this would be to delete objects in each frame if their index already exists. It would be better to find a way to prevent this potential issue in the first place.

### Possible solution 2

Let the user specify a `trajectory_label` parameter that will set the label of entire trajectories to a value. This could be something like the label of the `first` frame, the label of the `last` frame, or even some custom lambda function that selects the label based on the entire trajectory.

The issue with this is that it seems like a band-aid over a larger problem which is that maybe we should not allow the class of a trajectory to change in the first place.

**Comment by brimoor** [comment]
This is resolved by https://github.com/voxel51/fiftyone/pull/1382.

If you have a video track in FiftyOne with a single `index` but whose `label` changes, and you wish to load this track into CVAT (which must be split into separate tracks in CVAT due to its data model), then you can pass `annotate(..., allow_index_edits=False)` and then the track won't be split when loading the CVAT shapes back in FiftyOne.
