### ISSUE TITLE
[BUG] Force reencode flag not working

### ISSUE THREAD

**Issue by SiftingSands** [voxel51/fiftyone#1366]
```
from fiftyone.utils import video as fov
<creating the dataset>
fov.reencode_videos(dataset, force_reencode=False)
``` 
does not ignore existing mp4 videos per the documentation, producing unwanted copies of videos.

### System information

-   **Ubuntu 18.04**
-   **source**
-   **0.14**
-   **3.8.11**
-  **ffmpeg version 4.2.4-1ubuntu0.1**

**Comment by brimoor** [comment]
Oops good catch, fixed in https://github.com/voxel51/fiftyone/pull/1367.
