### ISSUE TITLE
[SETUP-BUG] `fiftyone.core.service.DatabaseService failed to bind to port` on Colab with PyTorch-Lightning

### ISSUE THREAD

**Issue by ethanwharris** [voxel51/fiftyone#1376]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab Notebook
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.0
-   **Python version**: 3.7.12

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```
## From colab notebook
!pip install fiftyone pytorch-lightning

# Reset runtime
import fiftyone
```

### Describe the problem

Installing pytorch lightning alongside fiftyone in a colab notebook causes fiftyone to break on import with the error:
```
ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```
This is working fine on my local environment

**Comment by vuvalini** [comment]
`apt install -y libcurl4` work for me.

**Comment by brimoor** [comment]
This is no longer an issue as of `fiftyone==0.18`.

**Comment by titiviking** [comment]
I'm still facing the issue when running CodeProject AI Server 2.5.4

```
13:41:49:TrainingObjectDetectionYOLOv5.py: Subprocess ['/app/modules/TrainingObjectDetectionYOLOv5/bin/linux/python38/venv/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/app/modules/TrainingObjectDetectionYOLOv5/fiftyone', '--logpath', '/app/modules/TrainingObjectDetectionYOLOv5/fiftyone/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error -4:
13:42:43:TrainingObjectDetectionYOLOv5.py: Unable to import and initialise the fiftyone.zoo package: fiftyone.core.service.DatabaseService failed to bind to port
```
