### ISSUE TITLE
Exporting/importing a FiftyOneDataset with an annotation run results in an error

### ISSUE THREAD

**Issue by jnsebgosselin** [voxel51/fiftyone#1385]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.0
-   **Python version**: Python 3.8.10

### Describe the problem

Exporting a dataset with `dataset_type=fo.types.FiftyOneDataset` with at least one annotation run and trying to import it back results in an error.

I am sorry if the issue is caused by not using the interface correctly. We just started using fiftyone in our organization and I am currently working to incorporate it into our workflow.

### Code to reproduce issue
```
import fiftyone as fo
import fiftyone.zoo as foz

dirname = "C:/Users/User/test_dataset_export"

if fo.dataset_exists("quickstart"):
    fo.delete_dataset("quickstart")
dataset = foz.load_zoo_dataset("quickstart")

view = dataset.take(1)
anno_key = "test_export_import_dataset_with_annotation"
view.annotate(
    anno_key,
    label_field="ground_truth",
    url="http://localhost:8080",
    username='********',
    password='********'
    )

dataset.export(
    export_dir=dirname,
    dataset_type=fo.types.FiftyOneDataset,
    export_media=False,
    )

if fo.dataset_exists('another_dataset_name'):
    fo.delete_dataset('another_dataset_name')
new_dataset = fo.Dataset.from_dir(
    dataset_dir=dirname,
    dataset_type=fo.types.FiftyOneDataset,
    name='another_dataset_name',
    )
```

### Other info / logs

```python traceback
Traceback (most recent call last):

  File "C:\Users\User\geostack\ctspec_ai\bug_fiftyone_annotate_export_import.py", line 35, in <module>
    new_dataset = fo.Dataset.from_dir(

  File "C:\Python38\lib\site-packages\fiftyone\core\dataset.py", line 3525, in from_dir
    dataset.add_dir(

  File "C:\Python38\lib\site-packages\fiftyone\core\dataset.py", line 2319, in add_dir
    return self.add_importer(

  File "C:\Python38\lib\site-packages\fiftyone\core\dataset.py", line 2859, in add_importer
    return foud.import_samples(

  File "C:\Python38\lib\site-packages\fiftyone\utils\data\importers.py", line 112, in import_samples
    return dataset_importer.import_samples(dataset, tags=tags)

  File "C:\Python38\lib\site-packages\fiftyone\utils\data\importers.py", line 1458, in import_samples
    return self._import_samples(dataset, dataset_dict, tags=tags)

  File "C:\Python38\lib\site-packages\fiftyone\utils\data\importers.py", line 1570, in _import_samples
    _import_run_results(

  File "C:\Python38\lib\site-packages\fiftyone\utils\data\importers.py", line 1641, in _import_run_results
    results = fors.RunResults.from_json(json_path, dataset)

  File "C:\Python38\lib\site-packages\eta\core\serial.py", line 512, in from_json
    return cls.from_dict(read_json(path), *args, **kwargs)

TypeError: from_dict() missing 1 required positional argument: 'config'
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by jnsebgosselin** [comment]
From my limited understanding of the code at the moment, it seems like this might be resolved by fetching the run config in `fiftyone.utils.data.importers._import_run_results` for each key and pass it to `fors.RunResults.from_json`, such that:

https://github.com/voxel51/fiftyone/blob/0f113175174ec1d4cd2f901a43317bb817847b53/fiftyone/utils/data/importers.py#L1634-L1642

would be instead:

```python
def _import_run_results(dataset, run_dir, run_cls, keys=None):
    if keys is None:
        keys = [os.path.splitext(f)[0] for f in etau.list_files(run_dir)]

    for key in keys:
        json_path = os.path.join(run_dir, key + ".json")
        if os.path.exists(json_path):
            config = run_cls.get_run_info(dataset, key).config
            results = fors.RunResults.from_json(json_path, dataset, config)
            run_cls.save_run_results(dataset, key, results)
```

**Comment by brimoor** [comment]
Hi @jnsebgosselin thanks for reporting this! Your proposed solution was indeed on the right track. I went ahead and implemented it in https://github.com/voxel51/fiftyone/pull/1386 along with a couple other related changes

**Comment by brimoor** [comment]
FYI- one generally doesn't need to export datasets in `FiftyOneDataset` format because you can just [make the dataset persistent](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#dataset-persistence) so that you can load it later like so:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset.name = "my-dataset"
dataset.persistent = True
```

In another session:

```py
import fiftyone as fo

dataset = fo.load_dataset("my-dataset")
```

You may know this already, but since, like you mentioned, you're adopting FiftyOne in your organization (awesome!) you'd like to share datasets with your colleagues. Exporting in `FiftyOneDataset` format is a good "hack" for that, but even better would be to shoot me an email at brian@voxel51.com so I can tell you more about our Teams offering 🤗

**Comment by jnsebgosselin** [comment]
This is excellent, thank you very much for the quick fix and the test :)

And yeah, you are right, I was hoping to use the `FiftyOneDataset` format to share datasets accross our (small) team and also as a mean to do some kind of version control and to backup safely our work.

I'll send you an email to know more about your Teams offering, I am interested to know more.
