### ISSUE TITLE
[FR] Optimize segmentation mask rendering

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1400]
`fiftyone==0.14.0` changed the way that array data such as `Segmentation` and `Heatmap` are rendered. While this enabled the very helpful ability to adjust the transparency/colorscale of these data types, it significantly increased render times.

For example, below we visualize masks whose width/height are > 1024 pixels, which is currently too slow to make using the App desirable:  

```py
import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.utils.labels as foul

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    max_samples=100,
    label_types=["segmentations"],
)

# Defines pixels values for each class in the segmentation masks
mask_targets = {i: label for i, label in enumerate(dataset.default_classes, 1)}
dataset.default_mask_targets = mask_targets

foul.objects_to_segmentations(
    dataset, "segmentations", "masks", mask_targets=mask_targets
)

session = fo.launch_app(dataset)
```

**Comment by benjaminpkane** [comment]
Not a bug
