### ISSUE TITLE
Add support for creating and modifying DatasetViews via the dashboard 

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#142]
Proposed interface after our meeting on June 1st:
- https://docs.google.com/presentation/d/1LcBiyWTviI8EPZh8mAd_C_ekckoePxy0QIN3gE7WMIM/edit#slide=id.g862d95b333_6_0
- https://docs.google.com/presentation/d/1LcBiyWTviI8EPZh8mAd_C_ekckoePxy0QIN3gE7WMIM/edit#slide=id.g862d95b333_6_165

**Comment by benjaminpkane** [comment]
Resolved by #254,  #400, and #413
