### ISSUE TITLE
[FR] convert data format

### ISSUE THREAD

**Issue by alicera** [voxel51/fiftyone#1420]
How to convert the coco format to the info.json, metadata.json, samples.json ?
My custom data have to generate the info.json, metadata.json, samples.json  and  the fiftyone will read the *.json

**Comment by brimoor** [comment]
I think you are asking how to import COCO-formatted data into FiftyOne.

[This page](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#cocodetectiondataset) shows an example of that, and [this section](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#basic-recipe) shows how you can, for example, directly specify the `data_path` where your images are separately from the path to your COCO JSON file.

I'm not sure what you mean by `info.json`, `metadata.json`, and `samples.json`. Perhaps you are asking how to export in [FiftyOneDataset format](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#fiftyonedataset)? This link shows how to do it.

Note however, that there's no need to export in [FiftyOneDataset format](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#fiftyonedataset) unless you specifically want a portable representation of a FiftyOne dataset that you can share with colleagues or load on another machine. If you're just working with a dataset yourself, [make the dataset persistent](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#dataset-persistence) and then you can load it in future sessions w/o having to re-import it.
