### ISSUE TITLE
[BUG] cant see boundinb box from custom database

### ISSUE THREAD

**Issue by an99990** [voxel51/fiftyone#1428]
### System information

-   Linux Ubuntu 20.04:
-   **FiftyOne installed from pip:
-   **FiftyOne version (run `fiftyone --version`)**: **FiftyOne v0.14.1, Voxel51, Inc.**
-   **Python version**: 3.8.10

### Commands to reproduce
```
import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.brain as fob

dataset_dir ='path/to/dataset/i'
name = "person_door_handle_bag"

dataset = fo.Dataset.from_dir(
    dataset_dir=dataset_dir,
    dataset_type=fo.types.YOLOv4Dataset,
    name=name,
)

# View summary info about the dataset
print(dataset)

# Print the first few samples in the dataset
print(dataset.head())

# dataset = foz.load_zoo_dataset("quickstart")
fob.compute_uniqueness(dataset)
session = fo.launch_app(dataset, port=5151)

session.wait()
```
# commands here

### Describe the problem

Loaded my own dataset, and annotations. Images were loaded successfully but not the annotations ? However I can see the label in the chart.

![image](https://user-images.githubusercontent.com/87030365/142268955-68a6bf96-ed77-4cf8-bd0d-0f63eb510fe3.png)
![image](https://user-images.githubusercontent.com/87030365/142269125-ce23d766-25a3-44a3-b9fa-a61c827552a0.png)

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate
the problem.
![0a0e8ceebedf7d18](https://user-images.githubusercontent.com/87030365/142269400-d0401e0b-f7ab-4955-bfce-7179b512e43f.jpg)
[0a0e8ceebedf7d18.txt](https://github.com/voxel51/fiftyone/files/7557471/0a0e8ceebedf7d18.txt)
![0a2e11f1bcd68bf7](https://user-images.githubusercontent.com/87030365/142269403-9004020d-3b23-443a-b518-5f02c7d49fad.jpg)
[0a2e11f1bcd68bf7.txt](https://github.com/voxel51/fiftyone/files/7557472/0a2e11f1bcd68bf7.txt)
![0a4c6b68ca539d0e](https://user-images.githubusercontent.com/87030365/142269405-c11b86a8-7fe7-4571-855a-b4b6bab2365b.jpg)
[0a4c6b68ca539d0e.txt](https://github.com/voxel51/fiftyone/files/7557473/0a4c6b68ca539d0e.txt)
![00a5be32d303e480](https://user-images.githubusercontent.com/87030365/142269407-dad019e0-028e-4ca2-b114-da3b3ab60483.jpg)
[00a5be32d303e480.txt](https://github.com/voxel51/fiftyone/files/7557475/00a5be32d303e480.txt)
![0a6acb71e9635072](https://user-images.githubusercontent.com/87030365/142269413-012cbbf8-5c55-4c94-861d-0dcddc52ba11.jpg)
[0a6acb71e9635072.txt](https://github.com/voxel51/fiftyone/files/7557476/0a6acb71e9635072.txt)
![00a7d31c6cc6b7f3](https://user-images.githubusercontent.com/87030365/142269416-2f4d6f22-ce01-4c38-ac4e-7ab79be9e2f3.jpg)
[00a7d31c6cc6b7f3.txt](https://github.com/voxel51/fiftyone/files/7557477/00a7d31c6cc6b7f3.txt)

sample images and annotation are linked in the issue.

please help

**Comment by benjaminpkane** [comment]
@an99990 I was able to load one of your examples. It looks like some of samples have no detections, i.e. the list is empty.

I would double check that all images do in fact have `detections`, and make sure your data is [formatted](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#yolov4dataset) correctly.

```py
import fiftyone as fo
F = fo.ViewField

# ... load dataset, check for issues
num_detections = F("ground_truth.detections").length()
samples_with_detections = dataset.match(num_detections > 0)
samples_without_detections = dataset.match(num_detections == 0)
```

Note that you can inspect the JSON in the visaulizer, as well.
![Screenshot from 2021-11-17 14-06-47](https://user-images.githubusercontent.com/19821840/142283081-fea3648e-2b1b-4e43-b5c7-c96082691ffd.png)
![Screenshot from 2021-11-17 14-03-49](https://user-images.githubusercontent.com/19821840/142283087-bf11818a-95ae-4dc9-b53a-09fb382bb8ba.png)

**Comment by brimoor** [comment]
I was also able to load with no problem like so:

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset_dir = "/path/to/dataset"

dataset = fo.Dataset.from_dir(
    dataset_dir=dataset_dir,
    dataset_type=fo.types.YOLOv4Dataset,
)

print(dataset)
print(dataset.head())

fob.compute_uniqueness(dataset)
session = fo.launch_app(dataset)
```

with the data on disk as follows:

<img width="404" alt="Screen Shot 2021-11-17 at 4 17 45 PM" src="https://user-images.githubusercontent.com/25985824/142284009-9b677445-8936-4fd1-b1ea-8c151b371c95.png">

`images.txt`:

```
data/0a0e8ceebedf7d18.jpg
data/0a2e11f1bcd68bf7.jpg
data/0a4c6b68ca539d0e.jpg
data/00a5be32d303e480.jpg
data/0a6acb71e9635072.jpg
data/00a7d31c6cc6b7f3.jpg
```

`obj.names`:

```
backpack
door
door_handle
person
```

Even without `images.txt` and `obj.names` in place, the data still loads fine, just without class label strings (like in Ben's screenshot)

**Comment by brimoor** [comment]
Per Ben's comment, I'm guessing among the 6123 images in your dataset, it just so happened that the first 3 printed in `dataset.head()` have no detections. Other samples do have detections though.

You can see the ones with the most detections like this:

```py
from fiftyone import ViewField as F

# Show samples with most 
view = dataset.sort_by(F("ground_truth.detections").length(), reverse=True)
print(view.head())

# Load in App
session.view = view
```

**Comment by an99990** [comment]
thank you so much for the quick answers ! However I am not able to see any bounding box in voxel51.
![image](https://user-images.githubusercontent.com/87030365/142286715-cff0a8ee-504b-4bd2-aa5e-6976a4ae40e5.png)

**Comment by an99990** [comment]
so by adding these lines i was able to see the bouding boxes:
```
view = dataset.sort_by(F("ground_truth.detections").length(), reverse=True)

session = fo.launch_app(dataset, port=5151)
session.view = view
```
![image](https://user-images.githubusercontent.com/87030365/142287231-25b172ef-a433-47a0-9574-00fc436ba863.png)

thank you guys !

**Comment by brimoor** [comment]
Looks like you're already getting value from the tool: now you can see whether your dataset is fully annotated or now :)
