### ISSUE TITLE
[BUG] Load model prediction in custom dataset to fiftyone

### ISSUE THREAD

**Issue by an99990** [voxel51/fiftyone#1435]
### Instructions

This is more of a question than a bug report. But i would like to know how can i export my model prediction/weights to fiftyone. Once i finish training my model, Yolov4, a weight file is generated. Is it possible to load a yolov4 model in fiftyone and predict the classes and display them in fifty one ?
If so, how do I proceed ?

Thank you

**Comment by brimoor** [comment]
FiftyOne doesn't store model weights, but you can certainly update your training loop to add model predictions to a FiftyOne dataset so you can analyze the model with respect to ground truth annotations, per-epoch, etc.

[This recipe](https://voxel51.com/docs/fiftyone/recipes/adding_detections.html) shows an example of adding model predictions to a FiftyOne dataset.

**Comment by an99990** [comment]
what if i have a json file with all the prediction. Is there a way to export the prediciton in fiftyone ? @brimoor thank you

**Comment by brimoor** [comment]
If the predictions are in [a standard format that we support](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html), like [COCO format](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#cocodetectiondataset) for example, then you can load them into FiftyOne in one line of code by following the patterns shown in these links.

If your predictions are stored in a custom format, then you can [write a simple Python loop](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/index.html#custom-formats) to load them into FiftyOne, or if you use a particular format often and want a clean way to load predictions in one line (like COCO format above), then you can [write a custom importer](https://voxel51.com/docs/fiftyone/recipes/custom_importer.html).

**Comment by an99990** [comment]
Tank you. My predictions are stored in a json file with yolov4 format.
Could you pleas provide me the link to load predictions, i was not able to find them.
The one that you link are the links to load dataset with supported format.
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brimoor** [comment]
https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#yolov4dataset
