### ISSUE TITLE
How to change the download location of dataset = fo.zoo.load_zoo_dataset()? 

### ISSUE THREAD

**Issue by Marcus2810** [voxel51/fiftyone#1441]
How do I change the location where zoo datasets are downloaded using `fiftyone.zoo.load_zoo_dataset()`?

**Comment by brimoor** [comment]
By default, all zoo datasets are downloaded to subdirectories of `fiftyone.config.dataset_zoo_dir`, and you can customize this directory [as described here](https://voxel51.com/docs/fiftyone/user_guide/dataset_zoo/api.html#controlling-where-zoo-datasets-are-downloaded).
