### ISSUE TITLE
[BUG] evaluate_detections mAP with classes specify got error

### ISSUE THREAD

**Issue by vuvalini** [voxel51/fiftyone#1453]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Both Ubuntu 18.04.5 /  MacOS 10.14 tested 
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.2
-   **Python version**: Python 3.7

### Describe the problem

Error raised while  evaluate_detections with compute_mAP and classes specify.

### Code to reproduce issue

```python
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

results = dataset.evaluate_detections(
    "predictions",
    gt_field="ground_truth",
    eval_key="eval_predictions",
    classes= ["bottle"],
    compute_mAP=True,
)
```

### Other info / logs

ValueError raised

```bash
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "********************************/scratch.py", line 12, in <module>
    compute_mAP=True,
  File "********************************/fiftyone/fiftyone/core/collections.py", line 1958, in evaluate_detections
    **kwargs,
  File "********************************/fiftyone/fiftyone/utils/eval/detection.py", line 205, in evaluate_detections
    samples, matches, eval_key=eval_key, classes=classes, missing=missing
  File "********************************/fiftyone/fiftyone/utils/eval/coco.py", line 312, in generate_results
    precision[iou_threshs.index(t)][classes.index(c)] = q
ValueError: 'bird' is not in list
python-BaseException
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
@vuvalini thanks for reporting! https://github.com/voxel51/fiftyone/pull/1454 has the patch for this

**Comment by vuvalini** [comment]
Thanks @brimoor , I greatly appreciate your work.
