### ISSUE TITLE
[BUG] The FiftyOne Brain is not actually open source 

### ISSUE THREAD

**Issue by drewm1980** [voxel51/fiftyone#1463]
Fiftyone presents itself online as "The open-source tool for building high-quality datasets and computer vision models", but this is not true due to the dependency on the fiftyone-brain package, which contains the actual implementation of many of the selling points of fiftyone, i.e. image similiarity search, etc...

The package for fiftyone-brain, and possibly others, have been pushed to pypi, but contain code that has been obfuscated by pyarmor.

Please harmonize your marketing copy with the reality of what you are offering, or you're burning trust unnecessarily.

**Comment by brimoor** [comment]
The Brain is the only segment of the tool that's not open source, and this is currently mentioned front and center on its [docs page](https://voxel51.com/docs/fiftyone/user_guide/brain.html):

<img width="783" alt="Screen Shot 2021-12-08 at 8 19 39 AM" src="https://user-images.githubusercontent.com/25985824/145215310-43c5215a-feb9-4495-a506-0f2415d7fff2.png">
