### ISSUE TITLE
[DOCS] Details on image uniqueness calculation

### ISSUE THREAD

**Issue by fcakyon** [voxel51/fiftyone#1464]
Thanks a lot for this awesome project! I am the core maintainer of [sahi](https://github.com/obss/sahi) which includes nice fiftyone integrations such as [coco result visualization via fiftyone](https://github.com/obss/sahi/blob/main/docs/CLI.md#coco-fiftyone-command-usage) or [sliced prediction visualization via fiftyone](https://github.com/obss/sahi/blob/main/docs/CLI.md#coco-fiftyone-command-usage).

I want to utilize custom uniqueness and distance calculation functions in fiftyone but in the docs, there is no detail on the image uniqueness calculation. 

How are the normalized scores calculated from embeddings? Can we provide custom uniqueness and distance calculation functions to fiftyone?

**Comment by brimoor** [comment]
Hi @fcakyon 👋 

First of all, super awesome that you're leveraging FiftyOne in [sahi](https://github.com/obss/sahi)! Just gave it a star 🤗 

Here's a skeleton of how you can add custom uniqueness scores to a dataset:

```py
import numpy as np

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

session = fo.launch_app(dataset)

# Run `fiftyone zoo models list --tags embeddings` to see the available models
model = foz.load_zoo_model("mobilenet-v2-imagenet-torch")

# A `num_samples x num_dims` array of embeddings
embeddings = dataset.compute_embeddings(model)

# Compute your `num_samples` array of uniqueness scores from the embeddings
# EG use a nearest neighbor heuristic
values = np.mean(embeddings, axis=1)  # placeholder data

dataset.set_values("uniqueness", values)
print(dataset)

# Show least unique samples first in the App
session.view = dataset.sort_by("uniqueness")
```

This example uses a model from the [FiftyOne Model Zoo](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/index.html) to compute the embeddings, but you can of course swap that out for your own embedding strategy if desired.

The particular embedding model and uniqueness score function that `compute_uniqueness()` uses is not too important. You can easily substitute your own.

BTW, depending on what you'd like to achieve, you might find it more valuable to use one of these:
- Use [compute_visualization()](https://voxel51.com/docs/fiftyone/user_guide/brain.html#visualizing-embeddings) to directly visualize the embeddings
- Use [compute_similarity()[(https://voxel51.com/docs/fiftyone/user_guide/brain.html#visual-similarity) to index by similarity so you can search for visually similar samples in the App, find near-duplicate samples, etc.

Generally `compute_uniqueness()` is the least valuable of these three.
