### ISSUE TITLE
[BUG] CVAT integration: "Annotation run with key 'cvat_basic_recipe' already exists"

### ISSUE THREAD

**Issue by vii33** [voxel51/fiftyone#1471]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **FiftyOne installed from (pip or source)**: pip 
-   **FiftyOne version (run `fiftyone --version`)**: v0.14.2
-   **Python version**: 3.8

- **CVAT Server version:** 1.3
- **CVAT Core version:** 3.12.0
- **CVAT Canvas version:** 2.4.1
- **CVAT UI version:** 1.18.1

### Commands to reproduce
- Startup CVAT (either locally or web).
- Provide credentials in fiftyone `annotation_config.json`
- Use [Basic Recipe](https://voxel51.com/docs/fiftyone/user_guide/annotation.html#basic-recipe) as code.
- Change `anno_key` to something unique.
- Run the code.
- **Error:**  `Annotation run with key 'cvat_basic_recipe' already exists`

### Describe the problem
I want to link fiftyone to CVAT in order to annotate images. Therefore I tried the Basic Recipe from the documentation but I always get the above described error. It doesn't matter if I change the `anno_key`, each run produces same error result.

I tried both cvat.org and my local server as backend. Credentials do work since I could retrieve images via this [gist](https://gist.github.com/ehofesmann/ec265dee8222b7b8206c8eb1fcfad222).

I appreciate any help since I'm pretty stuck now and both tools would form a very good symbiosis.

### Code to reproduce issue

```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "quickstart", dataset_name="cvat-annotation-example"
)
dataset.persistent = True

anno_key = "cvat_basic_recipe_123"

dataset.annotate(
    anno_key,
    label_field="ground_truth",
    attributes=["iscrowd"],
    launch_editor=True,
)
```

### Other info / logs

```
Dataset already downloaded
Loading existing dataset 'cvat-annotation-example'. To reload from disk, either delete the existing dataset or provide a custom `dataset_name` to use
Uploading samples to CVAT...
Computing image metadata...
Dataset already downloaded
Loading existing dataset 'cvat-annotation-example'. To reload from disk, either delete the existing dataset or provide a custom `dataset_name` to use
[Repeated several times]

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\miniconda3\envs\fifty\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\miniconda3\envs\fifty\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\miniconda3\envs\fifty\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\miniconda3\envs\fifty\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\miniconda3\envs\fifty\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\miniconda3\envs\fifty\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\miniconda3\envs\fifty\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\git\FiftyOne\cvat3.py", line 18, in <module>
    dataset.annotate(
  File "D:\miniconda3\envs\fifty\lib\site-packages\fiftyone\core\collections.py", line 6171, in annotate
    return foua.annotate(
  File "D:\miniconda3\envs\fifty\lib\site-packages\fiftyone\utils\annotations.py", line 209, in annotate
    anno_backend.register_run(samples, anno_key, overwrite=False)
  File "D:\miniconda3\envs\fifty\lib\site-packages\fiftyone\core\runs.py", line 202, in register_run
    self.validate_run(samples, key, overwrite=overwrite)
  File "D:\miniconda3\envs\fifty\lib\site-packages\fiftyone\core\runs.py", line 237, in validate_run
    raise ValueError(
ValueError: Annotation run with key 'cvat_basic_recipe123' already exists
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @vii33 👋 

This error means that your dataset already has an annotation run with key `cvat_basic_receipe123` (because you've run the same code multiple times on the same dataset) and overwriting an existing run is not allowed.

You can have multiple outstanding annotation runs on a dataset as long as you give them different keys; or you can see and delete existing runs like so:

```py
# See the annotation runs on a given dataset
print(dataset.list_annotation_runs())

# Delete an existing annotation run
dataset.delete_annotation_run("cvat_basic_recipe123")
```

See [this page](https://voxel51.com/docs/fiftyone/integrations/cvat.html#managing-annotation-runs) for more information about managing CVAT annotation runs.

**Comment by vii33** [comment]
Hi @brimoor, thank you for the quick reply. 

What bothers me is that this error comes even if I provide a unique key for *the first time*. I can never get past the line `dataset.annotate()` because not matter what key I use it always gives this error (it's also not in the `list_annotation_runs()` result). Therefore I logged this bug.

I found a partial hint, though: After the command `dataset.annotate()` gets executed, then in the terminal is printed 
```
Uploading samples to CVAT...
Computing image metadata...
```
**then the whole code starts to run again from the first line of the file** -> This then leads to the "correct" event that fiftyone is complaining that the key already exists when annotate() is executed a second time.

I have never experienced such a thing, I imagine it is probably a threading issue. I'm running the code as a python file in VS Code. Python Env is a miniconda environment and CVAT is running as a container in WSL2.

I've done a screencast to show that behaviour:
https://user-images.githubusercontent.com/1887246/145689262-9b612c43-b214-48cb-a686-492a1f042422.mp4

 Really weird -_-

**Comment by brimoor** [comment]
Ah okay I see, thanks for the extra information!

This is actually a Windows multiprocessing error. When `dataset.annotate()` is called, this internally invokes `dataset.compute_metadata()` to compute image dimensions etc. The latter method attempts to use `multiprocessing`, but this can fail on Windows in environments like VSCode due to issues [like this](https://stackoverflow.com/questions/20360686).

You should be able to resolve this by manually running `dataset.compute_metadata(num_workers=1)` prior to calling `dataset.annotate()`. Can you check this?

**Comment by vii33** [comment]
It worked! Thanks so much. 🥳🥇
I guess I should really stop using Windows for good 😏

**Comment by vii33** [comment]
Ahh, your tip is stated in one chapter of the [documentation](https://voxel51.com/docs/fiftyone/user_guide/app.html#sessions). I am sorry that I bothered you @brimoor  :-/
