### ISSUE TITLE
[?] How to load YOLOv3 predictions into FiftyOne for analysis

### ISSUE THREAD

**Issue by valentindbdg** [voxel51/fiftyone#1473]
Hello,

I got predictions when testing a Yolo v3 model trained on a custom dataset.
https://drive.google.com/file/d/1fK06fBDGBkBqI0HDb-jPgNRWm25h-SjZ/view?usp=sharing

I would like to know how to input my prediction dataset into Fiftyone, and what format is expected for the prediction (file locations in folders, what the files contain, etc.)

Thank you very much!

**Comment by brimoor** [comment]
Hi @valentindbdg 👋 

Check out [this section](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#yolov4dataset) of our docs for details on creating a FiftyOne dataset from YOLO-formatted TXT files containing model predictions.

If your model doesn't output predictions in that specific format, you can always [write a simple Python loop](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/index.html#custom-formats) to load your model's predictions into a FiftyOne dataset.

**Comment by valentindbdg** [comment]
Thank you for your answer @brimoor 

> If your model doesn't output predictions in that specific format, you can always [write a simple Python loop](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/index.html#custom-formats) to load your model's predictions into a FiftyOne dataset.

My model does not output predictions in Yolo format unfortunately, here is an example of my output file:
https://drive.google.com/file/d/1NGRv0OX8tWmFhh7B-WF9SOCCFFY5_TjL/view?usp=sharing

In the description it is said:
# Bounding box coordinates should be relative values
# in [0, 1] in the following format:
# [top-left-x, top-left-y, width, height]

Are the values relative to the image size (width and height) ? Any idea (formula) to get those values with my output?

Thank you in advance for your answer!
