### ISSUE TITLE
[FR] Return info for unexpected labels

### ISSUE THREAD

**Issue by niclaswue** [voxel51/fiftyone#1477]
At the moment I am using
```
dataset.load_annotations(run, skip_unexpected=True)
```
to load annotations from CVAT into fiftyone. This logs a warning in the console when unexpected labels occur, otherwise it silently ignores the labels. For me, the code is running on a server where no interactive prompt is desired as this would halt the server. Therefore, my only option for `skip_unexpected` is `True`. I think it would be really nice, if there was some return value which indicates whether unexpected labels occured. Or even better, the ability to tag samples with unexpected labels. This way I can exclude them from my dataset later or relabel them afterward.
What do you think?

**Comment by ehofesmann** [comment]
I put together an example PR that returns the sample ids that had unexpected annotations when calling `load_annotations()`. Though, there may be a better way to resolve this.
