### ISSUE TITLE
[BUG] Authentication failed when trying to connect to custom MongoDB deployment

### ISSUE THREAD

**Issue by liucong255** [voxel51/fiftyone#1484]
Fiftyone version: 0.14.2
Configure the custom mongo uri: 
root@test:~/.fiftyone# fiftyone config
{
    "database_dir": "/root/.fiftyone/var/lib/mongo",
    "database_uri": "mongodb://admin:jiangxing123@172.24.121.8:27017",

Use error
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
![image](https://user-images.githubusercontent.com/38726093/147306578-ea948555-733e-4af0-b55a-32d4effb4fcd.png)

**Comment by brimoor** [comment]
Hi @liucong255 👋 

If your MongoDB deployment is running with authentication enabled (the `--auth` flag), FiftyOne must connect with a root user. A root user can be configured with mongo shell:

```
use admin
db.createUser({user: "username", pwd: passwordPrompt(), roles: ["root"]}) 
```

and `?authSource=admin` must be added to database URI:

```
mongodb://[username:password@]host[:port]/?authSource=admin
```

Does this resolve the issue for you?

**Comment by liucong255** [comment]
> 嗨@liucong255 👋
> 
> 如果您的 MongoDB 部署在启用身份验证（`--auth`标志）的情况下运行，FiftyOne 必须与 root 用户连接。可以使用 mongo shell 配置 root 用户：
> 
> ```
> use admin
> db.createUser({user: "username", pwd: passwordPrompt(), roles: ["root"]}) 
> ```
> 
> 并且`?authSource=admin`必须添加到数据库 URI 中：
> 
> ```
> mongodb://[username:password@]host[:port]/?authSource=admin
> ```
> 
> 这是否为您解决了问题？

ok
