### ISSUE TITLE
[BUG] I cannot import a simple YOLOv5 dataset

### ISSUE THREAD

**Issue by moracabanas** [voxel51/fiftyone#1487]
### System information

-   **WSL2 Debian 10**:
-   **FiftyOne installed from pip**:
-   **FiftyOne version (run `fiftyone --version`)**:
-   **Python version**: 3.6.9

### Commands to reproduce

```python
dataset = fo.Dataset.from_dir(
    dataset_type=fo.types.YOLOv5Dataset, 
    data_path="/app/datasets/my-dataset/images",
    dataset_dir="/app/datasets/my-dataset",
    yaml_path="/app/<some-path>/datasets.yaml",
)
```

### Describe the problem
I am trying to import a YOLOv5 dataset following fiftyone utils documentation but I have no luck.

`datasets.yaml` is pointing to the right dataset path and this dataset is correctly loading on YOLOv5 but in this case the dataset loads 0/0 files as shown.

### Other info / logs

This are the output of the python command:

```log
 100% |███████████████████████████████████████████████████| 0/0 [147.3us elapsed, ? remaining, ? samples/s]
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Can you please share what your `datasets.yaml` file contains?

Per [the docs](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#yolov5dataset), it is assumed to look like the example below, where the comment [taken from here](https://docs.ultralytics.com/tutorials/train-custom-datasets/) explains the three options for how a split's images can be specified:

```
# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ./images/train/
val: ./images/val/

# number of classes
nc: 80

# class names
names: ["list", "of", "classes", ...]
```

You can use relative or absolute paths to specify the location of the images, but if you use relative paths, those are interpreted relative to the location of the YAML file itself.

Also note that, per [the docs](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#yolov5dataset), `from_dir()` will only load one split at a time; the default is `split="val"`.

If you want to load multiple splits, the docs show this pattern for that:

```py
import fiftyone as fo

name = "my-dataset"
dataset_dir = "/path/to/yolov5-dataset"

# The splits to load
splits = ["train", "val"]

# Load the dataset, using tags to mark the samples in each split
dataset = fo.Dataset(name)
for split in splits:
    dataset.add_dir(
        dataset_dir=dataset_dir,
        dataset_type=fo.types.YOLOv5Dataset,
        split=split,
        tags=split,
)
```

**Comment by moracabanas** [comment]
> 

This fixed my issue. One thing I am missing is that loading splits by `dataset_dir` is looking for `dataset.yaml` filename by default, so I had to change my `datasets.yaml` to `dataset.yaml` and it loaded correctly.

Thanks you for taking your time!

**Comment by SzaremehrjardiMT** [comment]
Thanks.
I added "test" to the splits set so I'm able to see the test set too.

**Comment by ancri** [comment]
> Can you please share what your `datasets.yaml` file contains?
> 
> Per [the docs](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#yolov5dataset), it is assumed to look like the example below, where the comment [taken from here](https://docs.ultralytics.com/tutorials/train-custom-datasets/) explains the three options for how a split's images can be specified:
> 
> ```
> # train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
> train: ./images/train/
> val: ./images/val/
> 
> # number of classes
> nc: 80
> 
> # class names
> names: ["list", "of", "classes", ...]
> ```
> 
> You can use relative or absolute paths to specify the location of the images, but if you use relative paths, those are interpreted relative to the location of the YAML file itself.
> 
> Also note that, per [the docs](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#yolov5dataset), `from_dir()` will only load one split at a time; the default is `split="val"`.
> 
> If you want to load multiple splits, the docs show this pattern for that:
> 
> ```python
> import fiftyone as fo
> 
> name = "my-dataset"
> dataset_dir = "/path/to/yolov5-dataset"
> 
> # The splits to load
> splits = ["train", "val"]
> 
> # Load the dataset, using tags to mark the samples in each split
> dataset = fo.Dataset(name)
> for split in splits:
>     dataset.add_dir(
>         dataset_dir=dataset_dir,
>         dataset_type=fo.types.YOLOv5Dataset,
>         split=split,
>         tags=split,
> )
> ```

Is there a CLI equivalent to this?
