### ISSUE TITLE
[BUG] fiftyone.core.service.DatabaseService failed to bind to port

### ISSUE THREAD

**Issue by souvik3333** [voxel51/fiftyone#1499]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.6 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 
`fiftyone                    0.14.2
fiftyone-brain              0.7.2
fiftyone-db                 0.3.0` (From `pip list`,  `fiftyone --version` gives the same error mentioned below)
-   **Python version**: 3.7.11 

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue.

```
pip install --upgrade pip setuptools wheel
pip install fiftyone
import fiftyone
```

### Describe the problem
Its getting following error whenever I try to import `fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port`

### Other info / logs
I went through the log file of `mongo.log`. This is the cause of the error I guess.
`
{"t":{"$date":"2022-01-02T18:27:15.553+05:30"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1641128235:553406][19468:0x7fd5375b8ac0], connection: __posix_open_file, 808: /mnt/nfshome2/FRACTAL/souvik.mandal/.fiftyone/var/lib/mongo/WiredTiger.wt: handle-open: open: File exists"}}
{"t":{"$date":"2022-01-02T18:27:15.553+05:30"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.8"}}
{"t":{"$date":"2022-01-02T18:27:15.554+05:30"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1641128235:554332][19468:0x7fd5375b8ac0], connection: __posix_open_file, 808: /mnt/nfshome2/FRACTAL/souvik.mandal/.fiftyone/var/lib/mongo/WiredTiger.wt: handle-open: open: Operation not permitted"}}
{"t":{"$date":"2022-01-02T18:27:15.555+05:30"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
`
Seems like it cannot open the `WiredTiger.wt` file. I checked the permission of the files. They are getting the following permission `-rw-------`.  Any suggestions would be appreciated.

**Comment by benjaminpkane** [comment]
@souvik3333  Are you on a bare metal linux machine? Or are you running a container, VM, etc.?

**Comment by kuntiik** [comment]
I have the same problem, using linux machine connected via ssh. In my case, I am launching fifty-one in conda environment.

**Comment by souvik3333** [comment]
@benjaminpkane It's on a VM. I think I have figured the issue. The files(`WiredTiger.wt`) are created for a different user than my user id. Is there a way I can create those `WiredTiger.wt` files with group read-write permission? Else I will try with docker.

@kuntiik Yes, You might have to install libcurl4 (`sudo apt-get install libcurl4-openssl-dev`) from the issue. I got a similar issue before.

**Comment by brimoor** [comment]
@souvik3333 I think you just need to ensure that any user you plan to use FiftyOne with has read-write permissions for the entire directory in which your `WiredTiger.wt` files live.

**Comment by benjaminpkane** [comment]
You can configure a common directory for the database and give it proper permissions. See [configuration](https://voxel51.com/docs/fiftyone/user_guide/config.html)

```
mkdir /my/path
chmod ...
export FIFTYONE_DATABASE_DIR=/my/path
```

**Comment by souvik3333** [comment]
@benjaminpkane This one worked. 
@brimoor yes I could not give other users permission at my home folder but on a shared folder it worked based on the doc shared by @benjaminpkane 
Thanks. Closing the issue.

**Comment by JefrenAbalos-kumu** [comment]
same issue. cant use fiftyone. I'm using an amazon sagemaker notebook. but i keep getting the
fiftyone.core.service.DatabaseService failed to bind to port

or 

AttributeError: module 'fiftyone' has no attribute 'constants'

after running the import 

`import fiftyone.zoo as foz`

ive tried the other fixes such as removing opencv and only installing one version of it but none of the fixes seem to work.

**Comment by KuenstlicheIntelligenz** [comment]
For me it correlated with #1334

**Comment by zc277584121** [comment]
> sudo apt-get install libcurl4-openssl-dev

**Comment by zc277584121** [comment]
> sudo apt-get install libcurl4-openssl-dev

I got the same problem as @kuntiik , I use this command to solve it, thank you.

**Comment by gorogm** [comment]
This one has solved for me:
https://github.com/voxel51/fiftyone/issues/1988#issuecomment-1221583782

**Comment by stevezkw1998** [comment]
I encountered with same issue when deploying 2 docker containers in one linux machine
both of them are using fiftyone
and both of them has this mount:
-v /opt/.fiftyone/var/lib/mongo:/root/.fiftyone/var/lib/mongo

```
{"t":{"$date":"2023-06-10T07:11:33.768Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"-","msg":"Renamed existing log file","attr":{"oldLogPath":"/root/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/root/.fiftyone/var/lib/mongo/log/mongo.log.2023-06-10T07-11-33"}}
Subprocess ['/opt/conda/lib/python3.10/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/root/.fiftyone/var/lib/mongo', '--logpath', '/root/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Traceback (most recent call last):
... ...
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

**Comment by lukovnikov** [comment]
I'm having the same issue. Everything was working fine so far until today, it didn't.
Changing the database location helped for one run, but rerunning the script results in the same error.
My console says: "Subprocess ['/home/lukovdg1/.conda/envs/control-v11/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/USERSPACE/lukovdg1/fiftyone', '--logpath', '/USERSPACE/lukovdg1/fiftyone/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:" with no more info.
