### ISSUE TITLE
[BUG] TypeError: '<' not supported between instances of 'str' and 'NoneType' when trying to create a dataset

### ISSUE THREAD

**Issue by devrimcavusoglu** [voxel51/fiftyone#1507]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.2, Voxel51, Inc.
-   **Python version**: Python 3.9.9

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```python
import fiftyone as fo

IMAGES_DIR = "/path/to/images"
ANNOTATION_FILE = "/path/to/coco.json"

coco_dataset = fo.Dataset.from_dir(
    dataset_type=fo.types.COCODetectionDataset,
    data_path=IMAGES_DIR,
    labels_path=ANNOTATION_FILE,
    label_field="ground_truth"
)
```

### Describe the problem

I am working in Python venv with latest fiftyone version installed through pip. I have a custom dataset whose annotations are available in coco format. I guarantee that there is nothing wrong with the images paths or coco format because once I got this error, I could be able got it working at 2nd time when I completely uninstall fiftyone packages and then force-reinstall with `--no-cache-dir` option.

```shell
pip uninstall fiftyone fiftyone-brain fiftyone-db -y
pip install fiftyone -I --force-reinstall --no-cache-dir
```

After executing the commands above, I re-tried loading with `fo.Dataset.from_dir()` above with the exact same paths, and it correctly loaded the dataset. After shutting down the notebook kernel however, and re-executing the same code block, I got the same error as before (full traceback is below).

Afterwards the force-reinstalling trick didn't work, and I just got stuck. I couldn't get how it correctly loaded the coco dataset once, but fails on other trials. To hint devs about my env, I use jupyter notebook (`notebook==6.4.6`). I suspect that this problem may be due to fiftyone-db working under the hood collect and leaves some residuals, and when the dataset is loaded (although in a non-persistent way) it crashes.

### Code to reproduce issue

I am not sure if this behaviour can be reproduced.

### Other info / logs

The full traceback is as follows:

```Python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_38892/211814514.py in <module>
----> 1 coco_dataset = fo.Dataset.from_dir(
      2     dataset_type=fo.types.COCODetectionDataset,
      3     data_path=IMAGES_DIR,
      4     labels_path=ANNOTATION_FILE,
      5     label_field="ground_truth"

~/lab/bb/best-subset-selection/venv/lib/python3.9/site-packages/fiftyone/core/dataset.py in from_dir(cls, dataset_dir, dataset_type, data_path, labels_path, name, label_field, tags, **kwargs)
   3533             a :class:`Dataset`
   3534         """
-> 3535         dataset = cls(name)
   3536         dataset.add_dir(
   3537             dataset_dir=dataset_dir,

~/lab/bb/best-subset-selection/venv/lib/python3.9/site-packages/fiftyone/core/singletons.py in __call__(cls, name, _create, *args, **kwargs)
     31         ):
     32             instance = cls.__new__(cls)
---> 33             instance.__init__(name=name, _create=_create, *args, **kwargs)
     34             name = instance.name  # `__init__` may have changed `name`
     35             cls._instances[name] = instance

~/lab/bb/best-subset-selection/venv/lib/python3.9/site-packages/fiftyone/core/dataset.py in __init__(self, name, persistent, overwrite, _create, _virtual, **kwargs)
    226     ):
    227         if name is None and _create:
--> 228             name = get_default_dataset_name()
    229 
    230         if overwrite and dataset_exists(name):

~/lab/bb/best-subset-selection/venv/lib/python3.9/site-packages/fiftyone/core/dataset.py in get_default_dataset_name()
    108     now = datetime.now()
    109     name = now.strftime("%Y.%m.%d.%H.%M.%S")
--> 110     if name in _list_datasets(include_private=True):
    111         name = now.strftime("%Y.%m.%d.%H.%M.%S.%f")
    112 

~/lab/bb/best-subset-selection/venv/lib/python3.9/site-packages/fiftyone/core/dataset.py in _list_datasets(include_private)
   4375 
   4376     if include_private:
-> 4377         return sorted(conn.datasets.distinct("name"))
   4378 
   4379     # Datasets whose sample collections don't start with `samples.` are private

TypeError: '<' not supported between instances of 'str' and 'NoneType'
``` 

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by devrimcavusoglu** [comment]
I found the problem. Indeed it is about fiftyone-db leaving residuals in cache even if the dataset is non-persistent (by default). So, somehow, when I check current datasets with,

```shell
$ fiftyone datasets list
2022.01.04.15.43.59
```
, and when I shut down the kernel and the notebook completely, and re-check the datasets list, the dataset is still there 

```shell
$ fiftyone datasets list
2022.01.04.15.43.59
```

In this case manually deleting dataset, and loading from coco with `from_dir()` works, so currently, I am handling this manually as below:

```python
if fo.dataset_exists("dataset-name"):
     fo.delete_dataset("dataset-name")

coco_dataset = fo.Dataset.from_dir(
    name="dataset-name",
    dataset_type=fo.types.COCODetectionDataset,
    data_path=IMAGES_DIR,
    labels_path=ANNOTATION_FILE,
    label_field="ground_truth"
)
```

**Comment by brimoor** [comment]
The cause of the `TypeError` is that somehow your database got into a state where you have a dataset whose name is `None`, which should never normally be possible and probably means that your kernel happened to be killed at a really inconvenient time when a dataset was being created.

It sounds like you reinstalled FiftyOne completely, which created a fresh database and solved that issue. For future readers, if you get the `TypeError` in this issue and re-installing is not an option, then you should be able to manually delete the corrupted dataset like so:

```py
import fiftyone.core.odm as foo

foo.delete_dataset(None)
```

**Comment by brimoor** [comment]
As for why you see a non-persistent dataset in your database even after restarting your notebook kernel, the reason is that non-persistent datasets are only cleaned up when you go from one to zero database connections.

So, if you for example have another Python shell open with `fiftyone` imported, restarting the notebook won't cause non-persistent dataset deletion, since you still have that connection open. Also, it might be the case that simply restarting a notebook kernel isn't enough to cause the cleanup; you might need to actually kill the notebook server process.

Either way, I think the original `TypeError` you faced was really bad luck; you should be able to revert to omitting the `name=` argument from `from_dir()` if you want to. You shouldn't have to worry about name clashes with datasets whose names are chosen by default; FiftyOne will ensure that they're always unique.

**Comment by vuvalini** [comment]
Encountered same error after interrupting a dataset export execution.
```python
dataset.export(
    dataset_type=fo.types.YOLOv4Dataset,
    labels_path=labels_path,
    label_field=label_field,
)
```

Restarting the notebook server process doesn't help.

**Comment by devrimcavusoglu** [comment]
> The cause of the `TypeError` is that somehow your database got into a state where you have a dataset whose name is `None`, which should never normally be possible and probably means that your kernel happened to be killed at a really inconvenient time when a dataset was being created.
> 
> It sounds like you reinstalled FiftyOne completely, which created a fresh database and solved that issue. For future readers, if you get the `TypeError` in this issue and re-installing is not an option, then you should be able to manually delete the corrupted dataset like so:
> 
> ```python
> import fiftyone.core.odm as foo
> 
> foo.delete_dataset(None)
> ```

@vuvalini have you tried this ? It had solved my problem when I tried (it was for that spesific session though if I remember correctly)

**Comment by brimoor** [comment]
Disabling services prior to running `foo.delete_dataset(None)` will guarantee that you can successfully delete the `None`-named dataset:

```shell
export FIFTYONE_DISABLE_SERVICES=1
```

```py
import fiftyone.core.odm as foo

foo.delete_dataset(None)
```

We're working on a patch to prevent this from happening going forward.

**Comment by vuvalini** [comment]
@brimoor Thanks,that is very helpful.
