### ISSUE TITLE
[FR] Customize colors of semantics segmentation masks in App

### ISSUE THREAD

**Issue by asmith26** [voxel51/fiftyone#1515]
### Proposal Summary

I'm building up a Semantic-Segmentation dataset following https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#semantic-segmentation

I'd love to be able to view the labels with a custom color scheme (e.g. "green" for correct labels, "red" for incorrect labels). Not sure if this is currently possible?

### Willingness to contribute

-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community.

Many thanks for this **_amazing_** lib!! :)

**Comment by brimoor** [comment]
Hi @asmith26 👋 Here's a couple options that currently exist:

### Heatmap labels

The [Heatmap](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#heatmaps) label type allows you to store numeric data that is rendered in the App using the customizable `colorscale` property of your [App config](https://voxel51.com/docs/fiftyone/user_guide/config.html#modifying-your-app-config):

You must switch to `Color by value` mode under the App settings in order for your custom `colorscale` to be used. In the default `Color by field` mode, transparency is used to encode the numeric values of a `Heatmap`.

The example below will render arbitrary green/red mask overlays:

```py
import numpy as np

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart").clone()
dataset.compute_metadata()

for sample in dataset:
    # `mask` contains -1 and 1 values
    h = sample.metadata.height // 4
    w = sample.metadata.width // 4
    mask = np.sign(np.random.randn(h, w)).astype(np.int8)
    sample["mask"] = fo.Heatmap(map=mask, range=[-1, 1])
    sample.save()

session = fo.launch_app(dataset)

# In the App settings menu (gear icon):
#   - Switch to "Color by value" mode
#   - Adjust the label opacity to taste
session.config.colorscale = [
    [0.000, "rgb(255,0,0)"],
    [1.000, "rgb(0,255,0)"],
]
session.refresh()
```

### Segmentation

The colors used by the [Segmentation](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#semantic-segmentation) label type are---like all other non-`Heatmap` fields---chosen from the customizable `color_pool` setting of your [App config](https://voxel51.com/docs/fiftyone/user_guide/config.html#modifying-your-app-config).

This may not be the appropriate option for you if you want to render additional label fields beyond your `Segmentation` masks; but, the example below also renders arbitrary red/green mask overlays: 

```py
import numpy as np

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart").select_fields().clone()
dataset.compute_metadata()

for sample in dataset:
    h = sample.metadata.height // 4
    w = sample.metadata.width // 4
    mask = np.random.randint(3, size=(h, w), dtype=np.uint8)
    sample["mask"] = fo.Segmentation(mask=mask)
    sample.save()

dataset.default_mask_targets = {1: "correct", 2: "incorrect"}

session = fo.launch_app(dataset)

# In the App settings menu (gear icon):
#   - Adjust the label opacity to taste
session.config.color_pool = ["#ff0000", "#00ff00"]
session.refresh()
```

**Comment by asmith26** [comment]
Thanks so much for your help (and very quick response) @brimoor, the code examples are also extremely useful and helpful.

Many thanks again!! :)

**Comment by zimonitrome** [comment]
@brimoor This code indeed is really useful. But I noticed an odd thing. `session.config.color_pool = ["#ff0000", "#00ff00"]` is the reversed order of `dataset.default_mask_targets = {1: "correct", 2: "incorrect"}`.

Does the visualizer draw randomly from the `color_pool`? It would be really useful to be able to set a color map that agrees with class index. Is this currently impossible?

**Comment by brimoor** [comment]
Yeah unfortunately colors are currently chosen in a non-predictable way from `color_pool` (in iteration order I believe, but mask targets are a dict, so this is not deterministic).

Good news though, we are about to implement https://github.com/voxel51/fiftyone/issues/1763, which will bring support for customizing colors on a per-field basis. We'll plan to include per-mask-target as well.

**Comment by brimoor** [comment]
Related: https://github.com/voxel51/fiftyone/issues/1763

**Comment by lanzhenw** [comment]
Customizing 2D semantic segmentation masks and heatmap masks are supported in version 0.23. https://github.com/voxel51/fiftyone/pull/3727 https://github.com/voxel51/fiftyone/pull/3804
