### ISSUE TITLE
[BUG] Export relative paths in COCO `file_name` field

### ISSUE THREAD

**Issue by devrimcavusoglu** [voxel51/fiftyone#1516]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.2, Voxel51, Inc.
-   **Python version**: Python 3.9.7

### Describe the problem

On a custom dataset with COCO format, I want to export COCO annotation file (only this json file), and apparently I can export a COCO dataset or a COCO style annotation file with Fiftyone, however, I couldn't manage to export the `file_name` field as I wanted. I want to export this annotation file with images pointing to relative path (assume the images are contained in a nested directory structure), e.g my images dir is `/home/user/data/`, and annotation file is `/home/user/data/coco.json`, and images are like `/home/user/data/img_set1/a1*.jpg`, `/home/user/data/img_set2/b1*.jpg`, etc.

In this setup, filepaths in my coco.json are relative paths to images (e.g `img_set1/a11.jpg`), and the import is successful without a failure. However, when I want to export a COCO json with relative paths just like in my `coco.json`, I have no success so far. As indicated by doc of `export()`

> **kwargs: optional keyword arguments to pass to the dataset
                   exporter's constructor. If you are exporting image patches,
                   this can also contain keyword arguments for
                   :class:`fiftyone.utils.patches.ImagePatchesExtractor`.

, when I pass `rel_dir` as a keyword argument to `export()`, I expect it to be passed to the dataset exporter's constructor, so that I will get my resulting json file as desired. Yet, I tried this with no luck as `export()` basically ignores `rel_dir`. The code I'm using to export annotation file as below:

```python
my_coco_dataset.export(
    dataset_type=fo.types.COCODetectionDataset,
    labels_path="/path/to/exported_annotation_file.json",
    label_field="labels",
    export_media=False,
    rel_dir=coco_dataset.source_path
)
```
Note that I'm explicitly passing `export_media=False` as instructed to get `rel_dir` working. The output I'm getting is:

```python
Ignoring unsupported parameter 'rel_dir'
 100% |███████████████| 3130/3130 [3.5s elapsed, 0s remaining, 1.1K samples/s]  
```

, and the exported json file, `file_name` fields contain only the filename not the relative path from source images directory.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @devrimcavusoglu 👋 

The docs could (should) be improved, but passing your relative directory to `data_path` should do exactly what you want:

```py
my_coco_dataset.export(
    dataset_type=fo.types.COCODetectionDataset,
    data_path=coco_dataset.source_path,
    labels_path="/path/to/exported_annotation_file.json",
    label_field="labels",
    export_media=False,
)
```

When `export_media != False`, `data_path` specifies where to export the images, but, when `export_media == False`, FiftyOne assumes you are specifying the root directory where your media lives and what you want is to use the relative path to this directory (rather than just filename) for any export formats that support embedding a notion of filename in the labels file.

Here's an example:

```py
import os

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("cifar10", split="test", max_samples=100, shuffle=True)

dataset.export(
    export_dir="/tmp/cifar10",
    dataset_type=fo.types.ImageClassificationDirectoryTree,
)

# Generate a dataset on disk in `root_dir/label/filename.ext` format
dataset2 = fo.Dataset.from_dir(
    dataset_dir="/tmp/cifar10",
    dataset_type=fo.types.ImageClassificationDirectoryTree,
)

dataset2.add_sample_field(
    "detections", fo.EmbeddedDocumentField, embedded_doc_type=fo.Detections
)

# Exports `label/filename.ext` in COCO JSON filenames
rel_dir = os.path.dirname(os.path.dirname(dataset2.first().filepath))
dataset2.export(
    dataset_type=fo.types.COCODetectionDataset,
    data_path=rel_dir,
    labels_path="./coco.json",
    label_field="detections",
    export_media=False,
)
```

**Comment by devrimcavusoglu** [comment]
@brimoor Thank you, that works. As you mentioned, docs for this case could be updated.
