### ISSUE TITLE
[DOCUMENTATION] More elegant COCO bbox format.

### ISSUE THREAD

**Issue by devrimcavusoglu** [voxel51/fiftyone#1517]
### URL(s) with the issue:

[Related doc](https://voxel51.com/docs/fiftyone/api/fiftyone.utils.coco.html#fiftyone.utils.coco.COCOObject).

### Description of proposal (what needs changing):
For COCO bbox, the docstring can be replaced with

> bbox (None) – a bounding box for the object in [xmin, ymin, width, height] format

Convert it to bbox notation alike other dataset formats in the documentation as: 

> bbox (None) – a bounding box for the object in [x-tl, y-tl, width, height] format

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or
another member of your organization be willing to contribute a fix for this
documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently.
-   [ ] Yes. I would be willing to contribute a document fix with guidance from
        the FiftyOne community.
-   [x] No. I cannot contribute a documentation fix at this time.

**Comment by brimoor** [comment]
I think `xmin, ymin` and `x-tl, y-tl` are both pretty common in this library and the CV literature in general
