### ISSUE TITLE
[?] How to run evaluation on subsets of categories and labels

### ISSUE THREAD

**Issue by valentindbdg** [voxel51/fiftyone#1519]
### Summary

I would like to know the best practices (if it is actually possible) to add labels on images (categories) and evaluate the model's performance for a class, but divided into various categories.

Something that could look like this:

 ```
                         precision    recall      f1-score       support

class1      person       0.74        0.40         0.52           952        <-- (overall performance of class1)
category1   low light       -           -           -              -         <-- (performance of class1 for category1)
category2   sea side        -           -           -              -
category3   kid             -           -           -              -         
category4   small object    -           -           -              -
...
```
Thank you in advance for you answer.
### Motivation

-   What is the use case for this feature? 
Improve a dataset iteratively based on a model's performances

-   Why is this use case valuable to support for FiftyOne users in general? 
Cover specific and critical requirements when building an AI solution
Optimize data storage
Guide data collection
Reduce bias and increase fairness

-   Why is this use case valuable to support for your project(s) or organization? 
Improve object detection of a class ('person') by dividing predictions into various: 
environments (forest, urban, sea side, etc.), 
light conditions (day, night), 
classes categorization(gender, age, skin tone, height, etc.), 
picture angles (horizontal, from above), 
etc.

**Comment by brimoor** [comment]
Yeah evaluating subsets of samples and/or objects is easy and very customizable with FiftyOne!

Basically, you'll just want to [construct a view](https://voxel51.com/docs/fiftyone/user_guide/using_views.html) that contains the subset of data of interest and then run `evaluate_detections()` on it.

Related reading:
https://voxel51.com/docs/fiftyone/tutorials/evaluate_detections.html#Filtering-by-bounding-box-area

For example, the code below runs three different evaluations
- Evaluates the full dataset
- Evaluates only on samples with a particular field value, in this case `environment = "urban"`
- Evaluates only on objects with a particular property, in case objects with small bounding boxes. Note that, in this case, you might want to compute recall values by filtering *only* the ground truth field and then compute precision values by filtering *only* the predictions field

Note: use `report()` rather than `print_report()` to get the data in dict format to make your own tables.

```py
import random

import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart").clone()
dataset.compute_metadata()

# Add some fake `environment` data
environments = [random.choice(["forest", "urban", "sea side"]) for _ in range(len(dataset))]
dataset.set_values("environment", environments)

print(dataset)

#
# 1 Evaluate everything
#

results = dataset.evaluate_detections("predictions", gt_field="ground_truth")
results.print_report()

#
# 2 Evaluate only urban scenes 
#

forest_view = dataset.match(F("environment") == "urban")
results = forest_view.evaluate_detections("predictions", gt_field="ground_truth")
results.print_report()

#
# 3. Evaluate only small objects
#

# Expression that matches objects with area less than 32^2 pixels
# https://voxel51.com/docs/fiftyone/tutorials/evaluate_detections.html#Filtering-by-bounding-box-area
bbox_area = (
    F("$metadata.width") * F("bounding_box")[2] *
    F("$metadata.height") * F("bounding_box")[3]
)
small_boxes = bbox_area < 32 ** 2

small_boxes_view = (
    dataset
    .filter_labels("ground_truth", small_boxes)
    .filter_labels("predictions", small_boxes)
)

results = small_boxes_view.evaluate_detections("predictions", gt_field="ground_truth")
results.print_report()
```

**Comment by elonzh** [comment]
@brimoor I have a dataset with 5 categories: 

```json
// categories in coco foramt
"categories":[{"id":1,"name":"text"},{"id":2,"name":"title"},{"id":3,"name":"list"},{"id":4,"name":"table"},{"id":5,"name":"figure"}]
```

Also, I made a prediction only for 2 categories: `table` and `figure`. So I filtered the dataset before calling `evaluate_detections`:

```python
eval_view = dataset.filter_labels(gt_field, F("label").is_in(["figure", "table"]))
results = eval_view.evaluate_detections(
        pred_field, gt_field=gt_field, eval_key=eval_key
    )
```

The results looks good, but the `eval_patches`  view contains other categories as well, for example `text` . Is it possible to make the `eval_patches`  view to contain only specific categories?

**Comment by brimoor** [comment]
`to_evaluation_patches()` will include all patches in the collection to which it is applied, even if they weren't included in the evaluation:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")

gt_labels = ["cat", "dog", "bird", "bear", "rabbit"]
pred_labels = ["cat", "dog"]

eval_view = (
    dataset
    .filter_labels("ground_truth", F("label").is_in(gt_labels))
    .filter_labels("predictions", F("label").is_in(pred_labels))
)

eval_view.evaluate_detections(
    "predictions", gt_field="ground_truth", eval_key="eval"
)

# Contains all objects, even those not involved in the evaluation
all_patches = dataset.to_evaluation_patches("eval")
print(len(all_patches))  # 6825
print(all_patches.count_values("type")) # {None: 6760, 'tp': 27, 'fp': 34, 'fn': 4}
```

Here are two strategies to retrieve only the patches that were involved in the evaluation:

```py
# Option 1: start from `eval_view`, not the entire dataset
eval_patches1 = eval_view.to_evaluation_patches("eval")
print(len(eval_patches1))  # 65

# Option 2: omit samples with no TP/FP/FN type
eval_patches2 = all_patches.exists("type")
print(len(eval_patches2))  # 65
```

You can achieve Option 1 in the App by:
- Loading the evaluation view via Python: `session.view = dataset.load_evaluation_view("eval")`
- Converting to evaluation patches via the action menu above the sample grid

You can achieve Option 2 in the App by:
- Loading the full dataset in the App
- Converting to evaluation patches via the action menu above the sample grid
- Use the sidebar filter to omit samples with `type == None`

<img width="1141" alt="Screen Shot 2023-07-13 at 9 35 55 AM" src="https://github.com/voxel51/fiftyone/assets/25985824/7c5bca2f-9e87-44b3-a77a-912358a6ab0b">

**Comment by elonzh** [comment]
Understood! Operations in UI is inevitable.

Thank you very much !
