### ISSUE TITLE
[BUG] Gracefully handle attempts to load a deleted dataset in the App

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#1521]
Currently, if the dataset on a `Session` is deleted, an error is raised by the App when loading the page and the user cannot escape the error page without modifying the session via python.

**Comment by brimoor** [comment]
I think a good option here would be for the error page to include a couple additional buttons for common actions that may be needed to escape the issue.

One reason these buttons are necessary is when an error occurs in an "App-only" workflow where the user of the App doesn't have access to the `session` object to programmatically take the right action.

```
# Refresh (currently the only option)
session.refresh()

# Clear the view (will fix things if the view is broken)
session.view = None

# Clear the dataset (only solution for cases like when the dataset is deleted)
session.dataset = None
```
