### ISSUE TITLE
[BUG] Exception raised when finding duplicates on dataset view

### ISSUE THREAD

**Issue by FGeri** [voxel51/fiftyone#1527]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.2 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: v0.14.2
-   **Python version**: 3.8
-   **FiftyOne brain version: 0.7.2

### Commands to reproduce

-

### Describe the problem

An exception is raised when computing similarity on a dataset view and finding duplicates with extrem values or values which results in no duplicates. It works correctly on the whole dataset, though.

### Code to reproduce issue

```
dataset = load_dataset("some_dataset")
view = dataset.limit(100)
result = fob.compute_similarity(view)
result.find_duplicates(thresh=None,fraction=0.0)
```
or
```
dataset = load_dataset("some_dataset")
view = dataset.limit(100)
result = fob.compute_similarity(view)
result.find_duplicates(thresh=0.0,fraction=None)
```

### Other info / logs

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_3650650/1293562871.py in <module>
      1 result = fob.compute_similarity(view, embeddings=f"embeddings_imagenet_inception_v3")
----> 2 result.find_duplicates(thresh=None,fraction=0.0)

~/venvs/datalake/lib/python3.8/site-packages/fiftyone/brain/similarity.py in find_duplicates(***failed resolving arguments***)

~/venvs/datalake/lib/python3.8/site-packages/fiftyone/brain/internal/core/similarity.py in find_duplicates(***failed resolving arguments***)

IndexError: arrays used as indices must be of integer (or boolean) type

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by FGeri** [comment]
BTW, with fraction over one, it seems to get into an infinite loop.
E.g.:
```
dataset = load_dataset("some_dataset")
view = dataset.limit(100)
result = fob.compute_similarity(view)
result.find_duplicates(thresh=None,fraction=1.2)
```

**Comment by brimoor** [comment]
Thanks for reporting, a patch for this will be in `fiftyone==0.14.3`.

Specifically, all of the following extreme cases will now work (although the results are not interesting):

```py
import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.brain as fob

dataset = foz.load_zoo_dataset("quickstart")
results = fob.compute_similarity(dataset, brain_key="img_sim")

results.find_duplicates(fraction=-1)
results.find_duplicates(fraction=0)
results.find_duplicates(fraction=1)
results.find_duplicates(fraction=2)
results.find_duplicates(thresh=0)
results.find_duplicates(thresh=-1)
```
