### ISSUE TITLE
[FR] Display similarity score in the App

### ISSUE THREAD

**Issue by Rusteam** [voxel51/fiftyone#1545]
### Proposal Summary

Show similarity score the App when sorted by similarity.
Possible, add a view for similarity search.

### Motivation

-   What is the use case for this feature?

> When sorting images by similarity we are only able to see the order of images but not their scores.
That's quite an important step in exploring a feature extractor/embeddings.

-   Why is this use case valuable to support for FiftyOne users in general?

> Similarity search is a usual case when we're dealing with large number of classes 
and few images per class, or even without class labels. Now, users have to switch another
tool like python plotting libs or custom frontend to visualize similarities/matches and scores.
If fiftyone could have sim.score displayed in the least, or a dedicated view 
for similarity search that would make it very useful for this task.

-   Why is this use case valuable to support for your project(s) or
    organization?

> We deal with cases where there's large number of classes (few thousand) and 
few images per class (1-5).

-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)

> `sortBySimiliarty` does not display a score and it's hard to tell if there's any difference
between rank 1 or rank 2 or rank 3.

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [ ] Core: Core `fiftyone` Python library
-   [x] Server: FiftyOne server

### Details

Need guidance.

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [x] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hey @Rusteam, good idea 💪 I implemented this in https://github.com/voxel51/fiftyone/pull/1548 and it will be included in the next release.

In the meantime, check out [this example](https://voxel51.com/docs/fiftyone/user_guide/brain.html#cifar-10-example) for some ways that you can access embedding distances in the context of unique/duplicate detection.

**Comment by Rusteam** [comment]
> In the meantime, check out [this example](https://voxel51.com/docs/fiftyone/user_guide/brain.html#cifar-10-example) for some ways that you can access embedding distances in the context of unique/duplicate detection.

Indeed that's a clever workaround. Thanks
