### ISSUE TITLE
[FR] Grid Zoom: Smallest images still too large

### ISSUE THREAD

**Issue by r0f1** [voxel51/fiftyone#1561]
Hi, I am using fiftyone via Python in its Jupyter environment to display images that are 64x64 pixels in size. Setting the grid zoom slider to its leftmost value, renders images that are still too large for me. 

Is there a possibility to make the grid of images even smaller?

I saw that I can pass `grid_zoom=0` to the app, but this does not really help me as this only programmatically sets the slider to its leftmost position.

Thank you.

**Comment by benjaminpkane** [comment]
Hi @r0f1. I hear you. I will try increase the limit a little. There are practical limits, of course. We don't want to offer a lower bound that leads to a poor experience.

Generally speaking, App optimization is an ongoing effort and the limit will be increased accordingly.

**Comment by benjaminpkane** [comment]
Range increased by #4281 in `0.25.0`
