### ISSUE TITLE
[FR] Add support for storing and rendering skeletons for keypoint fields

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1563]
When working with keypoint models, one often has an associated skeleton defining connectivity between the keypoints that should be rendered as edges (see screenshot below).

Currently, to achieve this, one must store two copies of the data: one in a `Keypoints` field and another in a `Polylines` field. The issues with this approach are:
- Data is duplicated
- Performing filtering operations (eg to see only specific objects) is cumbersome, because both fields must be individually filtered.

Instead, it would be ideal to have `default_skeleton` and `skeleton` fields analogous to `default_classes/classes` and `default_mask_targets/mask_targets` that allow users to attach skeletons to their dataset and/or specific fields, which would then be used by the App to dynamically render connections between points. The simplest data structure for this would be:

```
skeleton = {
    "labels": ["nose", "left eye", "right eye", ...],
    "edges": [[0, 1], [1, 2], ...],
}
```

which assigns semantic labels to each point and then draws edges `points[0] -> points[1]`, `points[1] -> points[2]`, etc.

Although, perhaps we may want to also allow for the possibility of per-`Keypoint.label` skeleton definitions?

In the example code below, [KeypointDetectorOutputProcessor](https://github.com/voxel51/fiftyone/blob/50c8fc08a57b049cdbb34406249c86f7249ceac1/fiftyone/utils/torch.py#L802) manually performs the `Polylines` population so that the desired visualization is achieved (albeit clunky for the reasons described above):

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("coco-2017", split="validation")

view = dataset.take(20)

model = foz.load_zoo_model("keypoint-rcnn-resnet50-fpn-coco-torch")
view.apply_model(model, label_field="predictions")

session = fo.launch_app(view)
```

<img width="1151" alt="Screen Shot 2022-01-24 at 11 31 49 AM" src="https://user-images.githubusercontent.com/25985824/150824031-8f301790-e156-4ec0-a356-2f8c691e406a.png">

**Comment by benjaminpkane** [comment]
Stale. Resolved
