### ISSUE TITLE
[SETUP-BUG] Installation of developer build fails on Apple Silicon Mac

### ISSUE THREAD

**Issue by stbdang** [voxel51/fiftyone#1584]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
-   **FiftyOne installed from (pip or source)**: source
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.3 (develop 7c389522ab2122887e69d994214ecc4440bc371f)
-   **Python version**: Python 3.9.10

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue.

```
source /Users/daniel/miniforge3/bin/activate
conda create -n pytorch python=3.9

// Install fifty and other things using pip until it's able to import and do things

cd <fiftyone dir>
bash install.bash -d

```

### Describe the problem

Provide the exact sequence of commands / steps that you executed before running
into the problem.

I think I have seen similar problem with other projects where installation is attempting to build numpy from source.

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.
[fiftyone-build-error.log](https://github.com/voxel51/fiftyone/files/7999106/fiftyone-build-error.log)

**Comment by swheaton** [comment]
OBE, no longer bug
