### ISSUE TITLE
[BUG]  Not Found for url: https://cvat.org/api/v1/auth/login

### ISSUE THREAD

**Issue by mabravo641** [voxel51/fiftyone#1599]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
-   **FiftyOne installed from (pip or source)**:
-   **FiftyOne version (run `fiftyone --version`)**:
-   **Python version**:

### Commands to reproduce
python3.7
fifty-one 0.14.4

### Code to reproduce issue

```
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

# Step 1: Load your data into FiftyOne

dataset = foz.load_zoo_dataset(
    "quickstart", dataset_name="cvat-annotation-example"
)
dataset.persistent = True

dataset.evaluate_detections(
    "predictions", gt_field="ground_truth", eval_key="eval"
)

# Step 2: Locate a subset of your data requiring annotation

# Create a view that contains only high confidence false positive model
# predictions, with samples containing the most false positives first
most_fp_view = (
    dataset
    .filter_labels("predictions", (F("confidence") > 0.8) & (F("eval") == "fp"))
    .sort_by(F("predictions.detections").length(), reverse=True)
)

# Let's edit the ground truth annotations for the sample with the most
# high confidence false positives
sample_id = most_fp_view.first().id
view = dataset.select(sample_id)

# Step 3: Send samples to CVAT

# A unique identifier for this run
anno_key = "cvat_basic_recipe"

view.annotate(
    anno_key,
    label_field="ground_truth",
    attributes=["iscrowd"],
    launch_editor=True,
)
```

### Describe the problem
It seems the API of cvat is not working
HTTPError: 404 Client Error: Not Found for url: https://cvat.org/api/v1/auth/login

### Other info / logs
```
Found existing field 'ground_truth' with multiple types ['detections', 'instances']. Only the 'detections' will be annotated
Please enter your login credentials.
You can avoid this in the future by setting your `FIFTYONE_CVAT_USERNAME` and `FIFTYONE_CVAT_PASSWORD` environment variables
Username: <USERNAME>
Password: 
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-12-2e810e51b1f5> in <module>
      3     label_field="ground_truth",
      4     attributes=["iscrowd"],
----> 5     launch_editor=True,
      6 )

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/fiftyone/core/collections.py in annotate(self, anno_key, label_schema, label_field, label_type, classes, attributes, mask_targets, allow_additions, allow_deletions, allow_label_edits, allow_index_edits, allow_spatial_edits, media_field, backend, launch_editor, **kwargs)
   6287             backend=backend,
   6288             launch_editor=launch_editor,
-> 6289             **kwargs,
   6290         )
   6291 

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/fiftyone/utils/annotations.py in annotate(samples, anno_key, label_schema, label_field, label_type, classes, attributes, mask_targets, allow_additions, allow_deletions, allow_label_edits, allow_index_edits, allow_spatial_edits, media_field, backend, launch_editor, **kwargs)
    211 
    212     results = anno_backend.upload_annotations(
--> 213         samples, launch_editor=launch_editor
    214     )
    215 

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/fiftyone/utils/cvat.py in upload_annotations(self, samples, launch_editor)
   3150 
   3151     def upload_annotations(self, samples, launch_editor=False):
-> 3152         api = self.connect_to_api()
   3153 
   3154         logger.info("Uploading samples to CVAT...")

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/fiftyone/utils/cvat.py in connect_to_api(self)
   3146             username=self.config.username,
   3147             password=self.config.password,
-> 3148             headers=self.config.headers,
   3149         )
   3150 

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/fiftyone/utils/cvat.py in __init__(self, name, url, username, password, headers)
   3431         self._project_id_map = {}
   3432 
-> 3433         self._setup()
   3434 
   3435     @property

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/fiftyone/utils/cvat.py in _setup(self)
   3543             self.login_url,
   3544             print_error_info=False,
-> 3545             data={"username": username, "password": password},
   3546         )
   3547 

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/fiftyone/utils/cvat.py in _make_request(self, request_method, url, print_error_info, **kwargs)
   3558             self._validate(response, kwargs)
   3559         else:
-> 3560             response.raise_for_status()
   3561         return response
   3562 

~/anaconda3/envs/env_py37_fifty_one/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    958 
    959         if http_error_msg:
--> 960             raise HTTPError(http_error_msg, response=self)
    961 
    962     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://cvat.org/api/v1/auth/login

```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [x] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

### Comments
I would like to know if there is anyway to upload data to CVAT from fiftyone. I need to annotate some data and would like to use this app

**Comment by ehofesmann** [comment]
The integration between FiftyOne and CVAT is built for CVAT v1 servers. Version 2 of CVAT is being developed and is beginning to roll out. [cvat.org](https://cvat.org) has recently been updated to v2 which is why you are seeing this error. [We have made a PR](https://github.com/voxel51/fiftyone#installing-from-source) to introduce basic functionality with CVATv2 servers, however, this is a major update and will take some time to fully integrate.

For now, there are 2 choices:

1) Set up a local CVAT v1 server following these instructions: https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/

Then under the section where you clone CVAT from GitHub, you can select the specific release branch:
```
sudo apt-get --no-install-recommends install -y git
git clone https://github.com/opencv/cvat
cd cvat
git checkout release-1.7.0
```
v1.7.0 is the most recent official release and is still CVAT v1.0


2) Install FiftyOne from source to access the CVATv2 patch before it is officially released: https://github.com/voxel51/fiftyone/pull/1595
https://github.com/voxel51/fiftyone#installing-from-source

**Comment by nsriniva03** [comment]
@ehofesmann , 

I installed FiftyOne from source to access the CVATv2 patch. However, when I try to launch the app over port 5151, I get "Not Found" msg and the same happens when I run session.show(). Any suggestions or thoughts?

Thanks

**Comment by ariyapour** [comment]
I had the same issue but following this link solved the problem:
https://github.com/voxel51/fiftyone/issues/3424#issuecomment-1683191657
