### ISSUE TITLE
[BUG] import fiftyone.brain fails on Apple Silicon Mac

### ISSUE THREAD

**Issue by stbdang** [voxel51/fiftyone#1600]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Darwin Kernel Version 21.3.0: Wed Jan 5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
-   **FiftyOne installed from (pip or source)**: Fails in both cases 
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.4
-   **Python version**: 3.9.10

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```
conda create -n fiftyone python=3.9
conda activate fiftyone
pip install fiftyone

python -c "import fiftyone.brain as fob"                                                                                                
```

### Describe the problem

Import fails with python instance getting killed
[1]    33631 killed     python -c "import fiftyone.brain as fob"

### Code to reproduce issue

Provided above

### Other info / logs

There's no log printed from the import failure.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by stbdang** [comment]
Tried your rc and it's still giving me the same issue. Let me know if you have any updates!

**Comment by swheaton** [comment]
OBE
