### ISSUE TITLE
[BUG] Cannot find the database file

### ISSUE THREAD

**Issue by alen-smajic** [voxel51/fiftyone#1603]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.4
-   **Python version**: 3.8.10

### Commands to reproduce

```
import fiftyone as fo

fo.config.default_dataset_dir = 'data/alen/FiftyOne_DB'

dataset = fo.Dataset('Test')
dataset.persistent = True

print(fo.list_datasets())  # Returns ['Test']
print(fo.core.dataset.get_default_dataset_dir('Test'))  # Returns '/data/alen/FiftyOne_DB/Test'
```

### Describe the problem

I am trying to verify that the database is being written on my custom path, since I do not want to blow up my SSD (where the library is stored). However when I look into the folder 'data/alen/FiftyOne_DB', it is completely empty (even no hidden files). Can anybody help me to clarify this? :)

### Code to reproduce issue

provided above

### Other info / logs

/

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [X ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [X ] No. I cannot contribute a bug fix at this time.

**Comment by benjaminpkane** [comment]
Hi @alen-smajic. `database_dir` (not `default_dataset_dir`) is the option you are looking for. See [configuring FiftyOne](https://voxel51.com/docs/fiftyone/user_guide/config.html) for more details.

**Comment by brimoor** [comment]
Pro tip: run `fiftyone config` from your shell to see the current value of `database_dir` for your deployment.

FYI- `database_dir` is not something you can change at runtime in Python, because the database connection is established immediately when `import fiftyone` occurs.

You can definitely customize `database_dir`, but you must do it either by setting this environment variable:

```shell
export FIFTYONE_DATABASE_DIR=/path/for/db
```

or by adding it to your FiftyOne config at `~/.fiftyone/config.json` (create one if you haven't used this feature yet):

```
{
    "database_dir": "/path/for/db",
    ...
}
```

See [this page](https://voxel51.com/docs/fiftyone/user_guide/config.html) for more information about configuring FiftyOne.

**Comment by alen-smajic** [comment]
> FYI- `database_dir` is not something you can change at runtime in Python, because the database connection is established immediately when `import fiftyone` occurs.

I think this is something that is not mentioned in the docs :). Before posting my issue I also tried to set  
fo.config.database_dir = "/data/alen/Master_Thesis/FiftyOne_DB"
inside of my python script, but obviously it did not work.
So I went with the option of creating a FiftyOne config file at ~/.fiftyone/config.json.  Everything is working fine, unless I try to change the database_dir then I always get this error:

{"t":{"$date":"2022-02-17T07:47:37.536Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/data/FiftyOne_data/log/mongo.log","newLogPath":"/data/FiftyOne_data/log/mongo.log.2022-02-17T07-47-37"}}
Subprocess ['/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/data/FiftyOne_data', '--logpath', '/data/FiftyOne_data/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 14:

I also deleted the folder ~/.fiftyone/var as I have seen in previous issues that this often helped. However the error message is still the same.

**Comment by brimoor** [comment]
Are you saying there's a problem when you set `database_dir` before importing Python? Or are you just pointing out that if you change `fo.config.database_dir` within in Python session then you start getting errors?

You are not allowed to change `database_dir` within a session, period.

**Comment by alen-smajic** [comment]
I was just pointing out that I was trying to change fo.config.database_dir within a Python session before you clarified that, it is not allowed to do so. That's why I pointed out, that it would be maybe helpful to add that information in the docs :).

However right now I am having problems when trying to import fiftyone with my config file at ~/.fiftyone/config.json. As soon as I edit the fo.config.database_dir property, the import of fiftyone will fail with the error message posted above.

**Comment by alen-smajic** [comment]
I have tried out a few things and I think I found the core of the problem. 

So the server I am using has a SSD where the fiftyone library has been installed and where my home folder is ('/home/alen'). The server has also an additional external hard drive mounted at '/data', which I want to use to store the database.
I have made sure to set the permission on '/data/FiftyOne_db' (the folder which I want to use for storing the database), but I always keep getting the same error and the log files have many 'Operation not permitted' messages, which means that there is some kind of permission error. However, when I set the database path to be anywhere inside the SSD for example '/home/fiftyOne_db', it works without any problems.

For me it seems like its kinda related to the usage of a different hard drive and mongodb. Any ideas or suggestions :)?

**Comment by brimoor** [comment]
You haven't set the permissions on `/data/FiftyOne_db` correctly yet. `/data` is probably owned by root whereas your home directory is owned by your user.

`chmod 777 /data/FiftyOne_db` would definitely work, but you should probably `chown` the `/data` drive to your current user. Or better create a group, and yourself to it, make the group the owner of `/data`, and then use something like `chmod 774` to set the permissions.
