### ISSUE TITLE
[FR] Add a report_dict return in case of reuse 

### ISSUE THREAD

**Issue by vuvalini** [voxel51/fiftyone#1608]
### Proposal Summary

Add a skm.classification_report(output_dict = True) return to the func
https://github.com/voxel51/fiftyone/blob/41bd4e5cc27c81fcd514549e6466ddf86d34e9ef/fiftyone/utils/eval/base.py#L160-L183

### Motivation

- Extend reuse the report in any integration scenario.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [x] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
That's what `report()` does :)

https://github.com/voxel51/fiftyone/blob/41bd4e5cc27c81fcd514549e6466ddf86d34e9ef/fiftyone/utils/eval/base.py#L76-L114

**Comment by vuvalini** [comment]
Oh no! My bad,thx.
