### ISSUE TITLE
[FR]Chinese users cannot download demo data

### ISSUE THREAD

**Issue by monkeycc** [voxel51/fiftyone#1613]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature
request)

### Motivation

-   What is the use case for this feature?
Chinese users cannot use

-   Why is this use case valuable to support for FiftyOne users in general?
Chinese users

-   Why is this use case valuable to support for your project(s) or
    organization?

-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)
```

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

session = fo.launch_app(dataset)
```

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1UWTlFmdq8H-wdJHxVsAKpXBilY1CWwm_ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACA86372C8>: Failed to establish a new connection: [WinError 10060]`

Chinese users  cannot access Google

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [ ] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

(Use this section to include any additional information about the feature. If
you have a proposal for how to implement this feature, please include it here.)

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hi @monkeycc:

Certain zoo datasets are only available via Google Drive, so you'll need to install a proxy in order to access them.

All web downloads in FiftyOne should be happening via the `requests` module in some form or another, so per the [requests package docs](https://2.python-requests.org/en/latest/user/advanced/#proxies), you can the environment variables per below and then your proxies will be used by default by `requests` everywhere:

Linux [(source)](https://github.com/voxel51/fiftyone/issues/1163#issuecomment-894933905):

```shell
export HTTP_PROXY=http://127.0.0.1:10809
export HTTPS_PROXY=https://127.0.0.1:10809

# If you need username/password to access your proxies
export HTTP_PROXY_USER=username
export HTTP_PROXY_PASS=password
export HTTPS_PROXY_USER=username
export HTTPS_PROXY_PASS=password
```

Windows [(source)](https://github.com/voxel51/fiftyone/issues/1163#issuecomment-894959627):

```shell
set HTTP_PROXY=http://127.0.0.1:12333
set HTTPS_PROXY=http://127.0.0.1:12333

# If you need username/password to access your proxies
set HTTP_PROXY_USER=username
set HTTP_PROXY_PASS=password
set HTTPS_PROXY_USER=username
set HTTPS_PROXY_PASS=password
```

Now this should work:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")  # should work now
session = fo.launch_app(dataset)
```

**Comment by monkeycc** [comment]
Thank you for your help. The problem has been solved

However, in China, the use of agents by individual users is illegal and criminal

**Comment by shaojun** [comment]
Hi @brimoor 

your `export`:

> ```shell
> export HTTP_PROXY=http://127.0.0.1:10809
> export HTTPS_PROXY=https://127.0.0.1:10809

works for load the dataset (I've started a proxy in system at port **7890**).

But noticed an prior error when importing:

```
(fiftyone) xxx@pcpc:~$ export HTTP_PROXY=http://127.0.0.1:7890
(fiftyone) xxx@pcpc:~$ export HTTPS_PROXY=https://127.0.0.1:7890
(fiftyone) xxx@pcpc:~$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiftyone as fo
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/shao/.local/lib/python3.8/site-packages/fiftyone/core/uid.py", line 86, in send_import_event
    with ua.HTTPRequest() as http:
  File "/home/shao/.local/lib/python3.8/site-packages/universal_analytics/requests.py", line 27, in __init__
    self.session = session or self.http_client_cls(headers=self.headers)
  File "/home/shao/.local/lib/python3.8/site-packages/httpx/_client.py", line 658, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "/home/shao/.local/lib/python3.8/site-packages/httpx/_client.py", line 209, in _get_proxy_map
    return {
  File "/home/shao/.local/lib/python3.8/site-packages/httpx/_client.py", line 210, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/shao/.local/lib/python3.8/site-packages/httpx/_config.py", line 329, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://localhost:7890/')
```
I have every time to kill the proxy application to let the `import` go through, and later start it again to make the load dataset work.

**Comment by brimoor** [comment]
This proxy stuff is out of scope for the FiftyOne project. The `requests` package documentation or other web searches on the topic are probably the best bet.

I do apologize that the `quickstart` and `quickstart-video` datasets are currently hosted in Google Drive. Migrating these to a public S3/GCP bucket is in our backlog.

**Comment by wcw1998** [comment]
An easy method:run the example in Colab Notebook, and download the demo dataset File to local disk.
