### ISSUE TITLE
Can't see annotation in CVAT after view.annotate(...)

### ISSUE THREAD

**Issue by shaojun** [voxel51/fiftyone#1622]
Hi,
I'm trying to download a very small subset of `Open Images` data of class `Bicycle`, and then upload the images and annotations to `CVAT`.
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04.3 LTS, x64
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.4, Voxel51, Inc.
-   **Python version**: Python 3.8.10 (default, Nov 26 2021, 20:14:08)

### Commands to reproduce

this is what I've done:
```
dataset = foz.load_zoo_dataset("open-images-v6", split="validation", label_types=["detections"], classes=["Bicycle"], max_samples=20, seed=51, shuffle=True, dataset_name="open-images-bicycle-mini-set-upload-to-cvat",)
session = fo.launch_app(dataset)
#can see the preview in below picture 1.
view = dataset.view()
anno_key="cvat_existing_field"
view.annotate(anno_key, label_field="ground_truth",label_type="detections",classes=["Bicycle","Person"])
#can see below info indicates the upload is successful, and open CVAT can see a new task is created with upload images, in picture 2
Uploading samples to CVAT...
Computing image metadata...
 100% |█████████████████████████████████████████████████████████████████| 20/20 [78.8ms elapsed, 0s remaining, 253.7 samples/s] 
Upload complete
```
picture 1:
![image](https://user-images.githubusercontent.com/3241829/156119845-dffb2bba-898c-4881-bdee-57ac1056dd58.png)

picture 2:
![image](https://user-images.githubusercontent.com/3241829/156119451-65d3c72e-41ba-401b-83c3-6e07b174acb0.png)

### Describe the problem

In `CVAT`, all upload images can be seen, but none of it has the annotation rectangles.

> The [tutorial](https://voxel51.com/docs/fiftyone/integrations/cvat.html#editing-existing-labels) works good.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
In your dataset, your existing labels are in a field called “detections”, not “ground_truth”.

Your current annotate() call is requesting bboxes in a new field called “ground_truth”

**Comment by shaojun** [comment]
thanks @brimoor
could you explain a bit more for `label_field` in `view.annotate(...)`

**Comment by brimoor** [comment]
These pages contain tons of info:
- https://voxel51.com/docs/fiftyone/integrations/cvat.html#requesting-annotations
- https://voxel51.com/docs/fiftyone/integrations/cvat.html#adding-new-label-fields
- https://voxel51.com/docs/fiftyone/integrations/cvat.html#editing-existing-labels
