### ISSUE TITLE
[BUG] Coco Object Detection Data Loader fails to read annotation json files if it contains "info":  NULL

### ISSUE THREAD

**Issue by Bukkster** [voxel51/fiftyone#1629]
### System information

-  **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Windows 11 PRO 64-bit, Version: 10.0.22000 , Build 22000,
-   **FiftyOne installed from:** pip in conda environment
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.3, Voxel51, Inc.
-   **Python version**: 3.7.12

### Commands to reproduce

```
import fiftyone as fo

# Define dataset name & paths 
val_name = "Objects365Val"
val_data_path = "C:/Users/UserName/Coding/Datasets/Objects365/Images/val"
val_labels_path = "C:/Users/UserName/Coding/Datasets/Objects365/Annotations/val.json"

# Load the dataset
obj365ValDataset = fo.Dataset.from_dir(
    name = val_name,
    dataset_type=fo.types.COCODetectionDataset,
    data_path=val_data_path,
    labels_path=val_labels_path,
)
```

### Describe the problem

Categories fail to load when when I try to use the coco object detection data loader with the Objects 365 dataset which has a coco formatting (except without supercatagorey field).  I get the following Type Error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_26932\4192680555.py in <module>
      8     dataset_type=fo.types.COCODetectionDataset,
      9     data_path=val_data_path,
---> 10     labels_path=val_labels_path,
     11 ) 
     12 #label_map_path=label_map_path, class_path=class_path,

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\core\dataset.py in from_dir(cls, dataset_dir, dataset_type, data_path, labels_path, name, label_field, tags, **kwargs)
   3553             label_field=label_field,
   3554             tags=tags,
-> 3555             **kwargs,
   3556         )
   3557         return dataset

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\core\dataset.py in add_dir(self, dataset_dir, dataset_type, data_path, labels_path, label_field, tags, expand_schema, add_info, **kwargs)
   2341             tags=tags,
   2342             expand_schema=expand_schema,
-> 2343             add_info=add_info,
   2344         )
   2345 

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\core\dataset.py in add_importer(self, dataset_importer, label_field, tags, expand_schema, add_info)
   2885             tags=tags,
   2886             expand_schema=expand_schema,
-> 2887             add_info=add_info,
   2888         )
   2889 

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\utils\data\importers.py in import_samples(dataset, dataset_importer, label_field, tags, expand_schema, add_info)
    116     #
    117 
--> 118     with dataset_importer:
    119         parse_sample, expand_schema = _build_parse_sample_fcn(
    120             dataset, dataset_importer, label_field, tags, expand_schema

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\utils\data\importers.py in __enter__(self)
    718 
    719     def __enter__(self):
--> 720         self.setup()
    721         return self
    722 

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\utils\coco.py in setup(self)
    530                 annotations,
    531             ) = load_coco_detection_annotations(
--> 532                 self.labels_path, extra_attrs=self.extra_attrs
    533             )
    534 

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\utils\coco.py in load_coco_detection_annotations(json_path, extra_attrs)
   1266     """
   1267     d = etas.load_json(json_path)
-> 1268     return _parse_coco_detection_annotations(d, extra_attrs=extra_attrs)
   1269 
   1270 

C:\Programs\Anaconda3\envs\fiftyone\lib\site-packages\fiftyone\utils\coco.py in _parse_coco_detection_annotations(d, extra_attrs)
   1282 
   1283     if categories is not None:
-> 1284         info["categories"] = categories
   1285 
   1286     # Load classes

TypeError: 'NoneType' object does not support item assignment
```
### Code to reproduce issue

At first I thought they dataset creators messed something up with the label mappings data type, but actually the problem lies with the way fiftyone uses the annotation "info" key. Object365's annotation json files defines this key as ```"info": null,```, and this trips up the  _parse_coco_detection_annotations function. 

When we navigated to  fiftyone\utils\coco.py and inspect lines 1271-1280, we see the origin of the problem is in line 1273:

```
1271    def _parse_coco_detection_annotations(d, extra_attrs=True):
1272        # Load info
->1273    info = d.get("info", {}) <-
1274        licenses = d.get("licenses", None)
1275        categories = d.get("categories", None)
1276        if licenses is not None:
1277            info["licenses"] = licenses
1278
1279        if categories is not None:
1280          info["categories"] = categories
```

If info is defined as null in the json file then then the info in line 1273 becomes a NoneType variable in coco.py

The ```if``` statement in line 1276 gets skipped because the licences field in Objects365 is also NoneType. We get stuck on line 1280 because we are trying to assign the categories variable (ListType) to a NoneType variable being treated as a Dictionary Type variable. 

### Potential Fix

I found a work around by replacing line 1273 in coco.py with the following:

```
1273    info = {}
1274        if d.get("info", {}) is not None:
1275            info = d.get("info", {})
```

I'm not sure if this the right way to fix it but it works for me. I'd be willing to make a commit and fix this but I'm still fairly new to github and git in general so not sure how to do that or a pull request to fix this. If someone can tell me how or if this is a valid bug fix, then I'd love to get the feedback.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [x] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/pull/1639.
