### ISSUE TITLE
[BUG] 404: Not Found when launching the app

### ISSUE THREAD

**Issue by EdwardYGLi** [voxel51/fiftyone#1633]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX Catalina 10.15.7
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.4, Voxel51, Inc.
-   **Python version**: python 3.8

### Commands to reproduce

Ran the tutorial but when launching the app in a browser I get 404 : Not Found
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)


session.wait()
```

### Describe the problem

Ran the tutorial but when launching the app in a browser I get 404 : Not Found

### Code to reproduce issue

same as above. 

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

![image](https://user-images.githubusercontent.com/44178551/157135409-8ffec97b-05db-48b0-9abe-163b29d22d4b.png)

**Comment by EdwardYGLi** [comment]
MongoDB 4.4 was installed and running on my system as well

**Comment by benjaminpkane** [comment]
5151 is the default port for sessions. It would only be running on 8000 if you explicitly provided it. I'm not sure that is FiftyOne returning a 404

**Comment by EdwardYGLi** [comment]
@benjaminpkane I've setup a config to use 8000 instead of the default 5151, I get the same error though with port 5151.

**Comment by EdwardYGLi** [comment]
@benjaminpkane Any ideas what can be causing this ?

**Comment by benjaminpkane** [comment]
Well the server can't find the `index.html`. I would force reinstall. `path/to/env/fiftyone/server/static` should have web assets if you want to check.

**Comment by benjaminpkane** [comment]
Some users have had issues with 0.0.0.0. I recommend just using `localhost`

**Comment by EdwardYGLi** [comment]
> Some users have had issues with 0.0.0.0. I recommend just using `localhost`

I tried with localhost as well.  I can try reinstalling, but I've done that as well. 

How do I force reinstall ? Any examples of commands I should run ?

**Comment by EdwardYGLi** [comment]
> Force reinstall is pip command.
> 
> Are you installing from source? You wrote that you installed from `pip`, but we have never seen this issue before...

I tried reinstalling, and using a new environment, but same issue. I check that the files are available in that path in the environment. Any other ideas on how to fix this ?

**Comment by benjaminpkane** [comment]
You can debug with server logs if you start the server directly from your shell:

```
python /path/to/env/fiftyone/server/main.py --port PORT
```

**Comment by EdwardYGLi** [comment]
> 

ok so calling `main.py` directly worked,  and I can see the ui now. But from the script it doesn't work

**Comment by benjaminpkane** [comment]
Please read the documentation. Datasets can be made persistent.

I recommend using IPython, and not scripts to start. If your scripts are exiting, that means the server is no longer running. `session.wait(-1)` will serve forever.
