### ISSUE TITLE
[BUG] missing annotations when using import_annotations with CVAT video task and exporting to CVAT video format

### ISSUE THREAD

**Issue by MathieuHaller** [voxel51/fiftyone#1634]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 21.04  
-   **FiftyOne installed from (pip or source)**: FiftyOne installed from pip  
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.15.0, Voxel51, Inc.  
-   **Python version**: 3.6.9  

### Commands to reproduce

```
import fiftyone as fo
import fiftyone.utils.cvat as fouc

dataset = fo.Dataset()
fouc.import_annotations(
        dataset,
        task_ids=[cvat_task_id],
        download_media=False,
        data_path=path_to_video_being_annotated
    )
dataset.export(export_dir="./output/",
                       dataset_type=fo.types.CVATVideoDataset)
```
Replace cvat_task_id with your CVAT task's id.    
Replace path_to_video_being_annotated with the folder containing the video being annotated at the task id.  

### Describe the problem

When downloading a video CVAT task's annotations, and the task has many overlapping short tracks of different types (bounding boxes, polylines, polygons...) and of the same class/label, sometimes a track may be missing when using the code above to export said task to CVAT video format.   

I would expect for all tracks to be downloaded and exported without any missing in the final .xml. No track is missing when using the manual CVAT download on the same CVAT task.

### How to reproduce

It's hard to describe how to reproduce this bug without being able to share the data or precise (self hosted) CVAT task.   
And I don't know exactly what triggers the missing tracks.

However, to have high chances of reproducing it, I would recommend what I described earlier: make a CVAT video task and annotate it with multiple short overlapping tracks of the same label and of different types (bounding boxes, polylines, polygons...).  

Then run the "Commands to reproduce" python script and examine the exported .xml file to check for any missing annotation.

### Other info / logs
Full log:  
 100% |████████████████████████████████████████████████████████████████████████| 1/1 [2.8ms elapsed, 0s remaining, 368.6 samples/s] 
Computing video metadata...
 100% |████████████████████████████████████████████████████████████████████████| 1/1 [65.4ms elapsed, 0s remaining, 15.3 samples/s] 
Downloading labels from CVAT...
Download complete
Loading labels for field 'frames.detections'...
 100% |████████████████████████████████████████████████████████████████████████| 1/1 [163.8ms elapsed, 0s remaining, 6.1 samples/s] 
Loading labels for field 'frames.polylines'...
 100% |████████████████████████████████████████████████████████████████████████| 1/1 [153.4ms elapsed, 0s remaining, 6.5 samples/s] 
 100% |████████████████████████████████████████████████████████████████████████| 1/1 [126.2ms elapsed, 0s remaining, 7.9 samples/s] 
   0% ||-----------------------------------------------------------------------| 0/1 [16.7ms elapsed, ? remaining, ? samples/s] /home/mhaller/miniconda3/envs/US_Hydra/lib/python3.6/site-packages/fiftyone/utils/cvat.py:6592: UserWarning:

Found polyline with more than one shape; only the first shape will be stored in CVAT format

 100% |████████████████████████████████████████████████████████████████████████| 1/1 [110.7ms elapsed, 0s remaining, 9.0 samples/s] 

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by ehofesmann** [comment]
Thanks @MathieuHaller, I will try to reproduce.

**Comment by MathieuHaller** [comment]
Sometimes instead of missing tracks, some tracks are simply fused into a single one.  
For example I sometimes have a track containing both a bounding box and a polyline, which are really 2 different tracks that have been fused in the xml by mistake during the export.

**Comment by MathieuHaller** [comment]
PS: after more testing, 1 polyline track and 1 bounding box track overlapping seem to be enough for there to be issues

**Comment by ehofesmann** [comment]
I was able to replicate the issue of tracks fusing. Just to clarify, after importing the data into FiftyOne, are you able to see all of the annotations correctly from the App? Do these issues only arise after exporting to XML?

**Comment by MathieuHaller** [comment]
Cheers !
