### ISSUE TITLE
[?] When and where are images on disk read into memory by FiftyOne?

### ISSUE THREAD

**Issue by Neighbor-Mr-Wang** [voxel51/fiftyone#1636]
### Instructions
Hi~Now i’m using FiftyOne to visualize datasets.I know FiftyOne datasets must make their images available as individual files on disk.But now I have some datasets stored in Hub(a dataset database on disk), I can read images from Hub to memory, I want visualize these images without save them to disk.The key problem is that I do not know when and where the images on disk will be readed to memory by FiftyOne?After launch app, Python backend read images or TypeScript app read?I could not find the interface that read images from disk.Could you help me?Thank you!

**Comment by brimoor** [comment]
When you [construct a FiftyOne dataset](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/index.html#custom-formats), you must provide a `filepath` for each sample on disk. So the storing of the media on disk happens by you before/during FiftyOne dataset creation time. All subsequent actions in FiftyOne (viewing a dataset in the App, applying a model using `Dataset.apply_model()`, etc) will use each filepaths to retrieve the media as necessary.

You can write a [DatasetImporter](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#basic-recipe) that takes in-memory or batched binary data as input (eg [TFImageClassificationDataset](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#tfimageclassificationdataset)), but the interface will require you to unpack the media and provide a `filepath` for each one to support FiftyOne's data model

**Comment by Neighbor-Mr-Wang** [comment]
ok, thank you !
