### ISSUE TITLE
[BUG] mongodb connection issues when merging several datasets

### ISSUE THREAD

**Issue by Nkusi-Richard** [voxel51/fiftyone#1645]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 19.1 Tessa
-   **FiftyOne installed from (pip or source)**: pip 
-   **FiftyOne version (run `fiftyone --version`)**:FiftyOne v0.14.4, Voxel51, Inc.
-   **Python version**: 3.7.4
### Code to reproduce issue

```
for pid in pid_test:
    dataset_test_temp = fo.Dataset.from_dir(data_path= expo_dir+"/"+pid+"/data/",
            labels_path=expo_dir+"/"+pid+"/labels/output.xml",
            dataset_type=fo.types.CVATImageDataset)
    dataset_test.merge_samples(dataset_test_temp)
```

### Describe the problem

The code above iterate over many folders and merge them together. Depending on the number of folders to iterate through (over 500 folders no matter the number of images, for my case), the codes throw ```pymongo.errors.AutoReconnect: connection closed ``` error at some point.  

### Other info / logs
![Screenshot from 2022-03-17 10-26-20](https://user-images.githubusercontent.com/61280024/158768362-4ba64447-9978-460d-946a-bddbda0fd138.png)

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [x] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by Nkusi-Richard** [comment]
Hi @benjaminpkane 
Here is the log file 
[mongo.log](https://github.com/voxel51/fiftyone/files/8287435/mongo.log)

**Comment by benjaminpkane** [comment]
> Hi @benjaminpkane
> Here is the log file
> [mongo.log](https://github.com/voxel51/fiftyone/files/8287435/mongo.log)

That link isn't working for me.

**Comment by Nkusi-Richard** [comment]
> > Hi @benjaminpkane
> > Here is the log file
> > [mongo.log](https://github.com/voxel51/fiftyone/files/8287435/mongo.log)
> 
> That link isn't working for me.

The above screenshot is the end part of the log file

**Comment by Nkusi-Richard** [comment]
> > Hi @benjaminpkane
> > Here is the log file
> > [mongo.log](https://github.com/voxel51/fiftyone/files/8287435/mongo.log)
> 
> That link isn't working for me.

I put the screenshot instead

**Comment by benjaminpkane** [comment]
You need to adjust your ulimit settings. MongoDB documentation on the issue can be found [here](https://docs.mongodb.com/manual/reference/ulimit/).

`ulimit -n 64000` should fix the issue. 64000 is MongoDB's recommended open file limit. We will be adding documentation for the issue.

Please prefer code snippets over screenshots. Screenshots are hard to read, and they can't be indexed by search engines.

**Comment by Nkusi-Richard** [comment]
> You need to adjust your ulimit settings. MongoDB documentation on the issue can be found [here](https://docs.mongodb.com/manual/reference/ulimit/).
> 
> `ulimit -n 64000` should fix the issue. 64000 is MongoDB's recommended open file limit. We will be adding documentation for this.
> 
> Please prefer code snippets over screenshots. Screenshots are hard to read, and they can't be indexed by search engines.
> 
> Issue appreciated! Let us know if you're still having issues.

Thank you, the issue have been solved.
