### ISSUE TITLE
[BUG] wrong download size of zoo models

### ISSUE THREAD

**Issue by Rusteam** [voxel51/fiftyone#1694]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Catalina
-   **FiftyOne installed from (pip or source)**: source
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.15.0.1, Voxel51, Inc.
-   **Python version**: 3.9.7

### Commands to reproduce

For instance: [Model card](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/models.html#deeplabv3-resnet101-coco-torch) stated size is 232MB, but the progress bar shows 1.8Gb:
```
model = foz.load_zoo_model("deeplabv3-resnet101-coco-torch")

### outputs:
Downloading model from 'https://download.pytorch.org/models/deeplabv3_resnet101_coco-586e9e4e.pth'...
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|    1.8Gb/1.8Gb [14.3s elapsed, 0s remaining, 185.3Mb/s]   
```

### Describe the problem

When downloading a model from the model zoo, progress bar shows a wrong download file size.
Different from model zoo model card. Apprently it has to be divided by 8.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [x] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Looks like the model card uses megabyte but the progress bar uses megabits (`1MB = 8Mb`)
