### ISSUE TITLE
[FR] Add progress bar in CVAT upload

### ISSUE THREAD

**Issue by ioangatop** [voxel51/fiftyone#1695]
To upload big datasets to CVAT, or datasets with where each sample size is large (4k images), I set the `task_size` and `segment_size` low enough, for example around `100`.  However, during the uploading process, we have no indication of the process, rather than a simple log `Uploading samples to CVAT...` and `Upload complete` in the end.

Simple enough, we can add `ProgressBar` here https://github.com/voxel51/fiftyone/blob/cf0a75d9ec5352db8027a105bcd300c54fab0d53/fiftyone/utils/cvat.py#L4134

as follows:
```
with fo.ProgressBar(total= num_samples, iters_str="batches") as pb:
    for idx, offset in enumerate(range(0, num_samples, batch_size)):
        ...
        pb.update(batch_size)
```
and probably remove [this](https://github.com/voxel51/fiftyone/blob/cf0a75d9ec5352db8027a105bcd300c54fab0d53/fiftyone/utils/cvat.py#L3171) and [this](https://github.com/voxel51/fiftyone/blob/cf0a75d9ec5352db8027a105bcd300c54fab0d53/fiftyone/utils/cvat.py#L3173) log.

**Comment by ehofesmann** [comment]
@ioangatop I think this would be a nice improvement! Your suggestions look pretty spot on, if you are willing to contribute, I'd be happy to review a PR for this :hugs:

**Comment by ioangatop** [comment]
@ehofesmann I'll be happy too! Can you please add me as a collaborator, because I can not create a branch? Or is there a different way to contribute?

**Comment by ehofesmann** [comment]
Amazing! The way to go about it is to create your own fork of the repository, create a custom branch in that fork with your changes, then open a pull request from your fork/branch to the `develop` branch in this voxel51 repository. Here is an example of a PR from a community member: https://github.com/voxel51/fiftyone/pull/1691

**Comment by ioangatop** [comment]
@ehofesmann great, thank you! And thank you very much for the comments and for contributing to this great tool! 
I hope I can contribute more as we move forward!
