### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by RoiNachmani** [voxel51/fiftyone#1706]
Hi,
I get the following error when I'm trying to lunch the app:

session = fiftyone.launch_app(dataset)
session.wait()

Server version (0.15.0.1) does not match client version (0.15.0.2)
Server Error

An exception has been raised by the server. Your session has been reverted to its previous state.

Traceback (most recent call last):
  File "main.py", line 313, in wrapper
    result = await func(self, *args, **kwargs)
  File "main.py", line 556, in on_message
    await event(self, **message)
  File "main.py", line 634, in on_update
    StateHandler.state = fos.StateDescription.from_dict(state).serialize()
  File "/home/miniconda3/envs/semantic_segmentation/lib/python3.7/site-packages/fiftyone/core/state.py", line 128, in from_dict
    dataset = fod.load_dataset(dataset.get("name"))
  File "/home/miniconda3/envs/semantic_segmentation/lib/python3.7/site-packages/fiftyone/core/dataset.py", line 100, in load_dataset
    return Dataset(name, _create=False)
  File "/home/miniconda3/envs/semantic_segmentation/lib/python3.7/site-packages/fiftyone/core/singletons.py", line 33, in __call__
    instance.__init__(name=name, _create=_create, *args, **kwargs)
  File "/home/miniconda3/envs/semantic_segmentation/lib/python3.7/site-packages/fiftyone/core/dataset.py", line 240, in __init__
    name, virtual=_virtual
  File "/home/miniconda3/envs/semantic_segmentation/lib/python3.7/site-packages/fiftyone/core/dataset.py", line 4707, in _load_dataset
    fomi.migrate_dataset_if_necessary(name)
  File "/home/miniconda3/envs/semantic_segmentation/lib/python3.7/site-packages/fiftyone/migrations/runner.py", line 175, in migrate_dataset_if_necessary
    runner = MigrationRunner(head=head, destination=destination)
  File "/home/miniconda3/envs/semantic_segmentation/lib/python3.7/site-packages/fiftyone/migrations/runner.py", line 220, in __init__
    % (max(head_ver, dest_ver), head_ver, dest_ver, pkg_ver)
OSError: You must have fiftyone>=0.15.0.2 installed in order to migrate from v0.15.0.2 to v0.15.0.1, but you are currently running fiftyone==0.15.0.1.

See https://voxel51.com/docs/fiftyone/getting_started/install.html#downgrading-fiftyone for information about downgrading FiftyOne.

App launched. Point your web browser to http://localhost:5151

fiftyone==0.15.0.2 
fiftyone-brain==0.8.1            
fiftyone-db==0.3.0                
mongoengine==0.20.0

**Comment by brimoor** [comment]
This means that you upgraded your Python client to `fiftyone==0.15.0.2` but you still have an App instance running using `fiftyone==0.15.0.1`.

Try to track down all places where you have FiftyOne imported, close them all, and then try again.

**Comment by RoiNachmani** [comment]
Solved! 
Thanks!

**Comment by barzan-hayati** [comment]
I build from source version` 0.24.0` and it did not work properly and I uninstalled it and I build from source `0.23.3`.
But by running 

`import fiftyone as fo`

I encounter this problem:

```
File ~/Downloads/fiftyone-0.23.3/fiftyone/__init__.py:33
     30 _fol.init_logging()
     32 if _os.environ.get("FIFTYONE_DISABLE_SERVICES", "0") != "1":
---> 33     _fom.migrate_database_if_necessary()

File ~/Downloads/fiftyone-0.23.3/fiftyone/migrations/runner.py:147, in migrate_database_if_necessary(destination, verbose)
    139         raise EnvironmentError(
    140             "Cannot migrate database from v%s to v%s when database_admin=%s. "
    141             "See https://docs.voxel51.com/user_guide/config.html#database-migrations "
    142             "for more information"
    143             % (head, destination, fo.config.database_admin)
    144         )
    146 if _database_exists():
--> 147     runner = MigrationRunner(head, destination)
    148     if runner.has_admin_revisions:
    149         logger.info("Migrating database to v%s", destination)

File ~/Downloads/fiftyone-0.23.3/fiftyone/migrations/runner.py:300, in MigrationRunner.__init__(self, head, destination, _revisions, _admin_revisions)
    298 dest_ver = Version(destination)
    299 if head_ver > pkg_ver or dest_ver > pkg_ver:
--> 300     raise EnvironmentError(
    301         "You must have fiftyone>=%s installed in order to migrate "
    302         "from v%s to v%s, but you are currently running fiftyone==%s."
    303         "\n\nSee https://docs.voxel51.com/getting_started/install.html#downgrading-fiftyone "
    304         "for information about downgrading FiftyOne."
    305         % (max(head_ver, dest_ver), head_ver, dest_ver, pkg_ver)
    306     )
    308 if _revisions is None:
    309     _revisions = _get_all_revisions()

OSError: You must have fiftyone>=0.24.0 installed in order to migrate from v0.24.0 to v0.23.3, but you are currently running fiftyone==0.23.3.

See https://docs.voxel51.com/getting_started/install.html#downgrading-fiftyone for information about downgrading FiftyOne.


```

**Comment by sergiev** [comment]
same as above on version 0.23.8
![image](https://github.com/voxel51/fiftyone/assets/27900857/670b32ef-0b92-465a-b4ab-0b99279895d0)
@brimoor how to solve it?

**Comment by benjaminpkane** [comment]
Hi @sergiev, if you have FiftyOne installed from source, you can fix this by migrating down before switching branches (or installing a different version from pip)
```shell
# in repository root on 'develop'
fiftyone migrate --all --version 0.23.8
```
