### ISSUE TITLE
[BUG] ChunkedEncodingError: Connection reset by peer

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1720]
When performing a partial download of the [COCO-2017 dataset](https://voxel51.com/docs/fiftyone/user_guide/dataset_zoo/datasets.html#coco-2017) from the [FiftyOne Dataset Zoo](https://voxel51.com/docs/fiftyone/user_guide/dataset_zoo/datasets.html) like so:

```py
dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    max_samples=1000,
    shuffle=True,
)
```

users have reported seeing the following error:

```
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by brimoor** [comment]
The underlying issue here is that the [COCO download method](https://github.com/voxel51/fiftyone/blob/e9adcd04023572f559290a490da84a132c0914db/fiftyone/utils/coco.py#L1825-L1847) uses multiple threads when downloading individual images, and this can result in a rate limit error from AWS (the COCO dataset images are hosted at http://images.cocodataset.org, which is an S3 bucket).

There are two solutions here:

(1) Pass the optional [num_workers parameter](https://voxel51.com/docs/fiftyone/user_guide/dataset_zoo/datasets.html#coco-2017) to choose a smaller number of threads to download the images. The default is `multiprocessing.cpu_count()` which could be quite large if your machine has many cores. A smaller value like `num_workers=4` or `num_workers=8` might avoid the rate limit:

```py
dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    max_samples=1000,
    shuffle=True,
    num_workers=4,  # only use 4 threads to download images
)
```

(2) Download the entire split(s) of interest:

```py
dataset = foz.load_zoo_dataset("coco-2017", split="train")
```

In this case, rather than the individual images being downloaded (partial download mode), a single tarball containing all of the images will be downloaded.

Henceforward, you can load partial splits like normal w/o needing to download individual images:

```py
# Images are already downloaded, just create the dataset
dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    max_samples=1000,
    shuffle=True,
)
```

**Comment by stwerner97** [comment]
This does not work for me, as even a single thread (i.e., ``num_workers=1``) crashes the download for me 🤒 

Are there any other options to limit the download rate with fiftyone?
