### ISSUE TITLE
[FR] Add a database save context

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1724]
## Background

A common FiftyOne workflow is to iterate over a collection, modify the sample, and save the result.

This is currently achieved via code like this:

```py
# collection may be a Dataset or a DatasetView

for sample in collection:
    sample["somefield"] = f(sample)
    sample.save()
```

The `for` loop reads samples from the database using a single cursor (resuming from the last read sample if the iteration takes so long that the cursor times out), which means that the read operation is relatively efficient.

However, each `sample.save()` call results in a new database connection, which presents a performance bottleneck.

For large datasets, minimizing the runtime of the above pattern is a high priority.

Currently, the **read operation** can be optimized by using `select_fields()` to limit which fields of the dataset are read from the database:

```py
# Suppose f() only needs `required_field`  
for sample in collection.select_fields("required_field"):
    sample["somefield"] = f(sample)
    sample.save()
```

Currently, the only way to optimize the **write operations** is to leverage `values()` and `set_values()` to "vectorize" the code:

```py
# One db connection
inputs = collection.values("required_field")

outputs = [f(value) for value in inputs]

# One db connection
collection.set_values("somefield", outputs)
```

with the limitation that `inputs` and `outputs` must fit in memory.

## Feature request

An alternative to the above for optimizing the **write operations** would be to introduce what we might call a database "save context" that would defer save operations until a sufficiently large batch is accumulated and then execute the write using bulk operations:

```py
with collection.save_context(batch_size=100):
    for sample in collection:
        sample["somefield"] = f(sample)
        sample.save()
```

The above would decrease the number of database connections by 100x, for example. Some benchmarking would need to be done, but I suspect this will significantly decrease the runtime of the loop.

Syntactic sugar could be added to merge the above with the for loop:

```py
for sample in collection.save_context(batch_size=100):
    sample["somefield"] = f(sample)
    sample.save()
```

Or the save context could be added to the existing `iter_samples()` method:

```py
# Render a progress bar and batch save operations!
for sample in collection.iter_samples(progress=True, batch_size=100):
    sample["somefield"] = f(sample)
    sample.save()
```

## Discussion points

Should we allow `sample.save()` to be omitted, with the understanding that the save context implicitly implies that all changes will be saved?

```py
for sample in collection.save_context(batch_size=100):
    sample["somefield"] = f(sample)
```

One concern I have with the above is that users could encounter problems if they decide to remove the save context (thinking of it only as an optimization):

```py
# everything's fine here
for sample in dataset.save_context(batch_size=100):
    sample["somefield"] = f(sample)

# big problems: nothing is saved!
for sample in dataset:
    sample["somefield"] = f(sample)
```

**Comment by brimoor** [comment]
Side notes:

There is a fancy `DynamicBatcher` class that could be used to dynamically size the write batches to achieve a desired save rate (eg one save per second):

https://github.com/voxel51/fiftyone/blob/2957ccc4d07ac94f140da1acb03d4fdacf322f89/fiftyone/core/dataset.py#L1446-L1451

Atomicity should also be acknowledged here: what guarantees do we want to make if `f(sample)` returns an error for the 51st sample? With the vanilla for loop, updates for samples 1-50 will be saved. Depending on how the save context is implemented and configured, failures could result in various save states.

There are various places in the codebase where batching is performed, and nothing too fancy has been done yet to provide any globally consistent atomicity. Generally batches are executed on synchronously, with failures being critical and each batch being atomic (no changes saved if any part of a batch fails)

**Comment by j053y** [comment]
My initial thought was to save based on `batch_size` and not to batch around time. Using the context manager would save whenever a `batch_size` is reached or if there are any items left in the batch on exit. So the same updates would be saved as the vanilla for loop.

**Comment by ehofesmann** [comment]
I definitely agree that we don't want to have two ways of iterating, where one requires `sample.save()` and one does not.

That being said, I do like the syntax of:
```python
for sample in collection.iter_samples(progress=True, batch_size=100):
    sample["somefield"] = f(sample)
```

One alternative could be to update the `__iter__()` method to also automatically save and batch even when you just iterate over the dataset:
```python
for sample in dataset:
    sample["somefield"] = f(sample)
```

At that point, the confusion would come when you load and modify a sample outside of a loop, you would still need to manually save it in that case. Unless we can somehow automatically save every change made to a sample outside of a loop.

Given all of that, it's probably best to just keep `sample.save()` everything imo.

**Comment by j053y** [comment]
@ehofesmann Thanks for the input. I agree keeping `sample.save()` seems the safest.
