### ISSUE TITLE
[FR] Segmentation paths and reference fields

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1729]
[Segmenation](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#semantic-segmentation) and [Heatmap](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#heatmaps) label types are currently stored as [binary blobs](https://github.com/voxel51/fiftyone/blob/4035cf729e01ab76d9cf84df616055a4fc971a34/fiftyone/core/fields.py#L507-L530) directly in the main `Sample` document in the database.

An important problem with this approach is that `Segmentation` and `Heatmap` arrays can easily be as large as the sample's image itself, which means that:
- Users can easily run into MongoDB's [16MB limit](https://www.mongodb.com/docs/manual/reference/limits/#:~:text=The%20maximum%20BSON%20document%20size,MongoDB%20provides%20the%20GridFS%20API.) when trying to store multiple segmentation/heatmap fields on a single sample (eg multiple sets of predictions from semantic segmentation models)
- View stages such as [shuffle()](https://github.com/voxel51/fiftyone/blob/4035cf729e01ab76d9cf84df616055a4fc971a34/fiftyone/core/stages.py#L5098) that sort collections by unindexed fields can be quite slow because large documents are involved

Here's two ideas to improve this situation:
- Add new `Segmentation.mask_path` and `Heatmap.map_path` fields that allow users to optionally store their segmenation/heatmap data externally and simply provide a path to them on disk (like `Sample.filepath`)
- Refactor the existing `Segmentation.mask` and `Heatmap.map` fields to be implemented as reference fields, so that large array data is stored in a separate collection and lazily loaded only when accessed

When making a data model change like this, all public segmentation/heatmap-related workflows will need to be updated to support either array-in-document or path-based data format.

Some places where segmentation/heatmap data is used:
- App-side rendering (@benjaminpkane can assist here as needed)
- Importing and exporting in [FiftyOneDataset](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#fiftyonedataset) format. Array data could be stored in an `arrays/` folder or something
- Importing and exporting in [ImageSegmentationDirectory](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#imagesegmentationdirectory) format
- [Evaluating semantic segmentation models](https://voxel51.com/docs/fiftyone/user_guide/evaluation.html#semantic-segmentations)
- [fod.Dataset.delete()](https://github.com/voxel51/fiftyone/blob/40c0012b9755d4678f12842d3d809f78dcc56921/fiftyone/core/dataset.py#L2396) and [foo.delete_dataset()](https://github.com/voxel51/fiftyone/blob/40c0012b9755d4678f12842d3d809f78dcc56921/fiftyone/core/odm/database.py#L631) will need to properly cleanup reference collections

An idea to implement this would be to refactor array access into `get_mask()`/`get_map()` methods that would pull data from whichever source is available.

**Comment by benjaminpkane** [comment]
Hmmm, my schemas work is going to inform this work a lot. Or change it when it becomes ready. Feel free to work on this, but there will be changes.

**Comment by brimoor** [comment]
^hopefully not too many changes, just that the implementation of any `ReferenceField` class used to implement lookups will just need to be swapped out for a different one.

**Comment by DanTaranis** [comment]
@brimoor any update on when we should expect this to be WIP?

**Comment by brimoor** [comment]
Getting close, planning for us to work on this in the next couple weeks

**Comment by Mikael-Spotscale** [comment]
For what it's worth, I'd advocate a solution that doesn't necessarily store the data (from e.g. a Segmentation) in the database.

In my experience, the amount of data quickly becomes very big when we save segmentation mask results from different CNN models to the FiftyOne/Mongo database, since there is no compression performed.

In contrast, saving the masks directly to file and storing the path to the database as suggested by @brimoor enables us to save the masks in e.g. PNG format (compressed) which drastically reduces the total file size on disk for the data.

**Comment by brimoor** [comment]
Yep storing paths to segmentations on disk is the new option we're building 👍

**Comment by DanTaranis** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉
