### ISSUE TITLE
[BUG] Keypoint skeleton not showing in the App for videos

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#1731]
When viewing a video in the App that has keypoints, the skeleton is not drawn when specified through `dataset.skeletons`, only if it is provided through `dataset.default_skeleton`.

## Example
```python
import fiftyone as fo
import fiftyone.zoo as foz

img_dataset = foz.load_zoo_dataset("quickstart", max_samples=1).select_fields().clone()
vid_dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1).select_fields().clone()

skeleton = fo.KeypointSkeleton(
    labels=["point1", "point2"],
    edges=[[0,1]],
)

img_dataset.skeletons["kps"] = skeleton
vid_dataset.skeletons["kps"] = skeleton

kps = fo.Keypoints(
    keypoints=[
        fo.Keypoint(label="test", points=[[0.5,0.5], [0.7,0.7]])
    ],
)

sample = img_dataset.first()
sample["kps"] = kps
sample.save()

sample = vid_dataset.first()
sample.frames[1]["kps"] = kps
sample.save()

session = fo.launch_app(img_dataset)
# Skeleton is drawn for image dataset

session.dataset = vid_dataset
# No skeleton for video dataset

vid_dataset.default_skeleton = skeleton
session.refresh()
# Skeleton is drawn for video dataset
```

**Comment by benjaminpkane** [comment]
@brimoor  @ehofesmann  The desired behavior is that the named skeleton for a `frames.kps` field should be `kps`? Not `frames.kps`? In other words, these mappings use field names for keys and not field paths?

**Comment by brimoor** [comment]
No I think `frames.kps` should be provided if a skeleton is to be used for a specific frame field.

**Comment by ehofesmann** [comment]
Yeah, that's generally how other things work in FiftyOne. But at the moment it seems that `frames.kps` also has this issue, and seemingly results in `vid_dataset.skeletons={}` after launching the app in the above example.

**Comment by benjaminpkane** [comment]
Yes, there was certainly a bug. Fixing it now in the new release.
