### ISSUE TITLE
[BUG] open-images-v6 dataset exported as COCODetection  missing annotations

### ISSUE THREAD

**Issue by Bassie1** [voxel51/fiftyone#1734]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.4
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 15.1
-   **Python version**: python 3.8.10

### Describe the problem

I am using a dataset from open-images v6. I loaded the dataset and checked that it loaded with all annotations. I need that dataset if COCO format for the model I am running, so I exported the dataset. When I tried running the model, I got an error. I went back to the labels.json file and saw that the annotations were completely empty.
### Code to reproduce issue

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    classes = ["Raccoon", "Cat"],
    max_samples =2000,
    label_types = ['segmentations'],
    seed=51,
    shuffle=True,
    dataset_name="cat-raccoon",
    overwrite=True
)
dataset.persistent = True
dataset.save()

dataset.export(
    export_dir="/home/User/cat-raccoon/",
    dataset_type=fo.types.COCODetectionDataset,
     classes=["cat", "raccoon"],
)
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Per the first half of your example code, Open Images uses capitalized label names: `Cat`, `Raccoon`. So, in your export you need to use `label_types=["Cat", "Raccoon"]` to match.

In your code as written, since there are no objects with labels `cat` and `raccoon`, the exported labels are empty.

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    classes=["Raccoon", "Cat"],
    max_samples=20,
    label_types=["segmentations"],
)

# See what labels exist in the dataset
print(dataset.count_values("segmentations.detections.label"))

dataset.export(
    export_dir="/tmp/test1",
    dataset_type=fo.types.COCODetectionDataset,
    classes=["Cat", "Raccoon"],
)

dataset1 = fo.Dataset.from_dir(
    dataset_dir="/tmp/test1",
    dataset_type=fo.types.COCODetectionDataset,
    label_field="segmentations",
)

print(dataset1.count_values("segmentations.detections.label"))
# all labels present
```

**Comment by Bassie1** [comment]
Amazing, thanks!
