### ISSUE TITLE
[BUG] Cannot open CocoDataset in after upgrade from 0.14.4 to 0.15.1 

### ISSUE THREAD

**Issue by hovnatan** [voxel51/fiftyone#1741]
### System information

-   **OS Platform and Distribution MacOS M1**:
-   **FiftyOne installed from pip**:
-   **FiftyOne version FiftyOne v0.15.1, Voxel51, Inc.**:
-   **Python version 3.9.12**:

### Describe the problem

I get `fiftyone.core.odm.dataset.DoesNotExist: Document does not exist` on the exact same code after upgrading from 0.14.4 to 0.15.1

```
    coco_dataset = fo.Dataset.from_dir(
        dataset_type=fo.types.COCODetectionDataset,
        dataset_dir="./images_path",
        data_path="images/",
        labels_path="labels.json",
        label_types="segmentations",
   )
   session = fo.launch_app(coco_dataset)
```

### Other info / logs
```
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [9.7ms elapsed, 0s remaining, 307.8 samples/s]
Uncaught exception
Traceback (most recent call last):
  File "/Users/hovnatan/run_fifty_one.py", line 10, in <module>
    session = fo.launch_app(coco_dataset)
  File "/Users/hovnatan/fiftyone/fiftyone/core/session.py", line 142, in launch_app
    _session = Session(
  File "/Users/hovnatan/fiftyone/fiftyone/core/session.py", line 339, in __init__
    state.dataset._reload()
  File "/Users/hovnatan/fiftyone/fiftyone/core/dataset.py", line 4558, in _reload
    self._doc.reload()
  File "/Users/hovnatan/venv_mmseg/lib/python3.9/site-packages/mongoengine/document.py", line 746, in reload
    raise self.DoesNotExist("Document does not exist")
fiftyone.core.odm.dataset.DoesNotExist: Document does not exist
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @hovnatan looks like there's a bug here that is causing [non-persistent datasets](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#dataset-persistence) to be erroneously deleted when `launch_app()` is called. I believe this was introduced by #1697.

We'll patch this right away, but, in the meantime, a workaround is to make all datasets persistent before doing anything with them so that they won't ever be deleted unless you do it:

```py
coco_dataset = fo.Dataset.from_dir(
    dataset_type=fo.types.COCODetectionDataset,
    dataset_dir="./images_path",
    data_path="images/",
    labels_path="labels.json",
    label_types="segmentations",
)

# Mark dataset as persistent so it will never be automatically deleted
coco_dataset.persistent = True

session = fo.launch_app(coco_dataset)
```

**Comment by hovnatan** [comment]
That worked. Thanks!
