### ISSUE TITLE
[BUG] Thumbnail view of images does not render all images

### ISSUE THREAD

**Issue by Robotatron** [voxel51/fiftyone#1750]
Several images are not rendered for some reason in the FiftyOne App:
![image](https://user-images.githubusercontent.com/95919873/168483867-290611a9-4455-4302-bba5-0b0615c62733.png)

Clicking on the image it seems the file exists and the property (image size) was read by Fifty One successfully:

![image](https://user-images.githubusercontent.com/95919873/168483891-1c076436-df53-4abf-a4d8-f17f9f77b214.png)

I can also double check the image exists and can be displayed in Python:

![image](https://user-images.githubusercontent.com/95919873/168483911-014130ef-f545-41e8-b04d-d8378c9b9114.png)

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

**Comment by benjaminpkane** [comment]
If any are still seeing this issue, sharing the browser and any errors from the browser console will help resolution

**Comment by fatemeh-mohseni-AI** [comment]
I also have this problem . 

```
import fiftyone as fo

# A name for the dataset
name = "check4"

# The directory containing the dataset to import
dataset_dir = "/home/fatemeh/Documents/training_datasets/newly_added"
dataset_type = fo.types.ImageSegmentationDirectory  # for example


dataset = fo.Dataset.from_dir(
    dataset_dir=dataset_dir,
    dataset_type=dataset_type,
    name=name,
    overwrite=True
    # tags=["ground_truth"],
    )

session = fo.launch_app(dataset, address="0.0.0.0", port=4545)
session.wait()
```

with both firefox and chrome on ubuntu 22.04 , python 3.10, fiftyone v0.22.0, all images size : 640*640

![Screenshot from 2024-09-15 16-56-02](https://github.com/user-attachments/assets/9076ac40-f5e8-4b40-8171-991bd5d0f9d2)
