### ISSUE TITLE
[FR] Add support for any starting frame number to transform_videos()

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1757]
FiftyOne provides methods like [transform_videos()](https://github.com/voxel51/fiftyone/blob/22e34e91deb1d2e2fe6316ec81714e0c55015523/fiftyone/utils/video.py#L139) that accept patterns like `/path/to/frames/%06d.jpg` and output encoded video files.

Currently, if you have images like this:

```
/path/to/frames/
    000010.jpg
    000011.jpg
    ....
```

and you try to run:

```py
import fiftyone.utils.video as fouv

frames_patt = "/path/to/frames/%06d.jpg"
video_path = "/path/for/video.mp4"

fouv.transform_video(frames_patt, video_path)
```

you'll get an error like this:

```
Could find no file with with path ... and index in the range 0-4
```

It looks like a `-start_number 10` option can be added to ffmpeg to enable the frames to start from any index:
https://superuser.com/questions/666860/clarification-for-ffmpeg-input-option-with-image-files-as-input

So, it would be nice if `transform_video()` and `transform_videos()` would automatically sniff out the appropriate start number and use it, without requiring the user to (a) manually specify the starting frame numbers, or (b) have to renumber their frames to start in 0-4.

[parse_pattern()[(https://github.com/voxel51/eta/blob/61fa0760bb205aa85238046c53fe6377a2da2077/eta/core/utils.py#L3744) seems helpful here.

**Comment by neuralsyn** [comment]
Resolved by [eta #562](https://github.com/voxel51/eta/pull/562)
