### ISSUE TITLE
[FR] Add keyboard shortcut to temporarily hide all labels in the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1761]
Often one needs a quick way to hide all labels in the expanded modal so that the image beneath them can be inspected. Currently the only way to achieve this is to uncheck all label fields, but there could be many, and maybe I forget which ones I had selected.

Having the option to hold `SPACE` (for example) to temporarily hide all labels would be super convenient.

**Update**: `SPACE` controls play/pause for videos, so something else may be needed here.

Note that all keyboard shortcuts should be documented under the `?` menu in the HUD.

<img width="1141" alt="Screen Shot 2022-05-20 at 6 29 10 PM" src="https://user-images.githubusercontent.com/25985824/169620531-008afc06-cd9d-4e78-90b7-63a124ed9c15.png">

**Comment by benjaminpkane** [comment]
Resolved by #1779
