### ISSUE TITLE
[FR] Render URLs in string fields as clickable links in the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1762]
When a field contains a URL, it should be displayed as a clickable link in the App:

```py
import fiftyone as fo

sample = fo.Sample(
    filepath="/path/to/image.png",
    link="https://voxel51.com",
)

dataset = fo.Dataset()
dataset.add_sample(sample)

session = fo.launch_app(dataset)
```

<img width="1141" alt="Screen Shot 2022-05-20 at 6 35 48 PM" src="https://user-images.githubusercontent.com/25985824/169621003-3a326a23-58bb-4d1a-a212-0082e529851f.png">

**Comment by ErfanTagh** [comment]
This issue appears to have been resolved in the current version of the app
