### ISSUE TITLE
[BUG] When fo.Dataset.from_dir() fails it prevents any new dataset with that name from being created

### ISSUE THREAD

**Issue by jim-meyer** [voxel51/fiftyone#1780]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.15.7
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.15.1, Voxel51, Inc.
-   **Python version**: Python 3.6.8

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```
import fiftyone as fo
dataset_images_path = '/data/scraped_jan_2022/images'
dataset_labels_path = '/data/scraped_jan_2022/labels'
dataset_name = 'scraped_jan_2022'
dataset = fo.Dataset.from_dir(dataset_type=fo.types.VOCDetectionDataset, data_path=dataset_path, labels_path=dataset_path, name=dataset_name)
```

### Describe the problem

When `fo.Dataset.from_dir()` fails for some reason it evidently leaves a `Dataset` lying around thus preventing using the dataset name again until I manually delete the `Dataset`. This is completely unexpected. The call to `from_dir()` failed. If it fails I expect it to leave no lingering side effects like a `Dataset` lying around.
This makes it annoying to use fiftyone to import new datasets that cause `from_dir()` to fail since I have to constantly keep changing dataset names, or deleting the dataset that was created when `from_dir()` failed.

### Code to reproduce issue

Ensure that there is a .txt file in /data/scraped_jan_2022/labels. This causes an exception to occur (see https://github.com/voxel51/fiftyone/issues/1778) thus `from_dir()` doesn't complete successfully using the code above.
Now run the same code again. An exception gets thrown indicate that the dataset has already been created. But it wasn't created (shouldn't have been created) since `from_dir()` failed.

```
ValueError: Dataset 'scraped_jan_2022' already exists; use `fiftyone.load_dataset()` to load an existing dataset
```

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached. Please do not use screenshots for sharing text. Code
snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
This one is a feature, not a bug 😄

Maybe the import failed on the very last sample, but you'd like to load the dataset and use the other samples or inspect the contents that *were* loaded to help you diagnose what the problem might have been:

```py
import fiftyone as fo

name = "..."

# Oops, this failed
dataset = fo.Dataset.from_dir(..., dataset_name=name)

# Let's try loading it and see what actually got loaded
dataset = fo.load_dataset(name)
print(dataset)

# Now we delete it
fo.delete_dataset(name)
```

Note that datasets are [non-persistent by default](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#dataset-persistence), so if you just restart Python, the failed dataset (even if you gave it a specific name) will be automatically cleaned up and you can try again.

Alternatively, you can take advantage of the fact that, if you don't specify a name at creation time, datasets are given unique names and thus a failed dataset creation will not affect your ability to re-run the code (eg if you killed it yourself or fixed something "live"):

```py
import fiftyone as fo

# Suppose something goes wrong here
dataset = fo.Dataset.from_dir(...)

# No worries, you can run it again because a new name will be used
dataset = fo.Dataset.from_dir(...)

# Now that it worked, give the dataset a name of choice and make it persistent
dataset.name = "..."
dataset.persistent = True
```

**Comment by cipri-tom** [comment]
@brimoor but what about the `overwrite` parameter ? If this is True, then shouldn't it be able to reuse that name ?
