### ISSUE TITLE
[BUG] FiftyOne import fails, Ubuntu 22.02 LTS

### ISSUE THREAD

**Issue by Nils-ChristianIseke** [voxel51/fiftyone#1803]
### System information

-   **OS Platform and Distribution**: Ubuntu 22.04 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: Not applicable, due to failing import:
-   **Python version**: Python 3.10.4

### Commands to reproduce

```
conda create -n PDSM pip
conda activate PDSM
pip install --upgrade pip setuptools wheel
pip install fiftyone
python3
import fiftyone

```

### Describe the problem

```
python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiftyone
Subprocess ['/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/nils/.fiftyone/var/lib/mongo', '--logpath', '/home/nils/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 127:
/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/db/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/__public__.py", line 15, in <module>
    _foo.establish_db_conn(config)
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/core/odm/database.py", line 155, in establish_db_conn
    port = _db_service.port
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/core/service.py", line 276, in port
    return self._wait_for_child_port()
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/core/service.py", line 170, in _wait_for_child_port
    return find_port()
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/nils/anaconda3/envs/PDSM/lib/python3.10/site-packages/fiftyone/core/service.py", line 168, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

### Code to reproduce issue

see above

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by tadejsv** [comment]
This is related to libcrypto1.1 not being availible on Ubuntu 22.04
https://askubuntu.com/a/1403961/1102180

**Comment by Nils-ChristianIseke** [comment]
@tadejsv Thank you very much!
The provided solution resolves the import error:
1. Download libssl1.1 from https://packages.debian.org/stretch/libssl1.1
2. In the directory where you dowloaded libssl1.1 to :`sudo dpkg -i libssl1.1*.deb`

**Comment by tadejsv** [comment]
My solution was to create a new machine with ubuntu 20.04 😄

**Comment by vii33** [comment]
@Nils-ChristianIseke Unfortunately not for me. I installed the newest `libssl1.1` package, then tried to `import fiftyone as fo`.

Resulting error: 
```
Subprocess ['/home/vii33/.virtualenvs/test2-mlao/lib/python3.10/site-packages/fiftyone/db/bin/mongod', 
'--dbpath', '/home/vii/.fiftyone/var/lib/mongo', '--logpath', '/home/vii33/.fiftyone/var/lib/mongo/log/mongo.log', 
'--port', '0', '--nounixsocket'] exited with error 1:

/home/vii33/.virtualenvs/test2-mlao/lib/python3.10/site-packages/fiftyone/db/bin/mongod: 
/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/vii33/.virtualenvs/test2-mlao/lib/python3.10/site-packages/fiftyone/db/bin/mongod)
```

Ubuntu 22.04 should be adopted by a lot of people now. Really frustrating to have to deal with such issues.

**Comment by benjaminpkane** [comment]
It is true that the current MongoDB that is distributed by default (4.4). We will look into upgrading to 6.0 as the default binary or an optional upgrade

Regardless, MongoDB 6.0 is available now for [Ubuntu 22.04](https://askubuntu.com/questions/1403619/mongodb-install-fails-on-ubuntu-22-04-depends-on-libssl1-1-but-it-is-not-insta) and can be used instead via your own database URI. We have instructions for configuring your own MongoDB connection [here](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-mongodb-connection)

**Comment by barney2074** [comment]
> Ubuntu 22.04 should be adopted by a lot of people now. Really frustrating to have to deal with such issues.

I'd agree with this. It seems that the easiest workaround is a virtual machine running 20.04 ??

**Comment by vii33** [comment]
> It is true that the current MongoDB that is distributed by default (5.0) will not work on 22.04. We will look into upgrading to 6.0 as the default binary or at least offer an optional upgrade
> 
> Regardless, MongoDB 6.0 is available now for [Ubuntu 22.04](https://askubuntu.com/questions/1403619/mongodb-install-fails-on-ubuntu-22-04-depends-on-libssl1-1-but-it-is-not-insta) and can be used instead via your own database URI. We have instructions for configuring your own MongoDB connection [here](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-mongodb-connection)

Yes, this worked, thank you.

**Comment by mitjanikolaus** [comment]
> @tadejsv Thank you very much! The provided solution resolves the import error:
> 
>     1. Download libssl1.1 from https://packages.debian.org/stretch/libssl1.1
> 
>     2. In the directory where you dowloaded libssl1.1 to :`sudo dpkg -i libssl1.1*.deb`

That didn't work for me, I needed to download and install a more recent version of libssl (ibssl1.1_1.1.1) from here: https://packages.debian.org/buster/amd64/libssl1.1/download

**Comment by iraadit** [comment]
Workaround I'm using is to provide the path through an installed libssl1.1 (in an Anaconda environment by example) with LD_LIBRARY_PATH

**Comment by FrancescoSaverioZuppichini** [comment]
I don't think you want to install `libssl1.1` in your os, since it's old

see [here](https://askubuntu.com/questions/1408000/unable-to-locate-package-libssl1-1)

So please don't do it, to my understanding that will create big security issues in your system

**Comment by heyitsguay** [comment]
I'm hitting this issue too. It's a shame! I was trying to evaluate voxel51 for my team at work. Looks nice, but I'll see if any alternatives work on my (very common by now) OS.

**Comment by brimoor** [comment]
Ubuntu 22.04 users should now be able to install FiftyOne as follows:

```py
pip install fiftyone
pip install fiftyone-db-ubuntu2204
```

Note: manually installing `fiftyone-db-ubuntu2204` will be necessary until we update the MongoDB version [here](https://github.com/voxel51/fiftyone/blob/e62d0a21aa70d0a05749d7d5324557a9b07d832f/package/db/setup.py#L29) to 6.0.4 or greater, at which point the `fiftyone` package will ship with MongoDB 6.0.4 by default on all Linux systems.

**Comment by NicoJorgensen1** [comment]
I ran
`python -m pip uninstall fiftyone
python -m pip install fiftyone-db-ubuntu2204`
However, now I cannot use the fiftyone zoo anymore.
When I try:
`import fiftyone as fo 
 import fiftyone.zoo as foz `
I get an "ModuleNotFoundError: No module named 'fiftyone.zoo'"

**Comment by NicoJorgensen1** [comment]
@Nils-ChristianIseke let me know if these posts are annoying, I don't want to hijack your thread.

@brimoor, thats what I did. I can see from my earlier post that I forgot to write that `pip install fiftyone` line...
As you can see in the attached screenshot here you the import of fiftyone fails.
![fiftyone_not_workign](https://github.com/voxel51/fiftyone/assets/70665230/5da86155-bedc-4430-baa9-64ec72b8fc37)


Bonus info: I am running this in a docker container (more specifically, a devcontainer in vscode). I run with [this nvidia/cuda baseimage](https://hub.docker.com/layers/nvidia/cuda/12.1.0-runtime-ubuntu20.04/images/sha256-3fafc3b0872ce6a4b6121f51d1c3728eec3e680b4df31421cc1d9b6fadf81bb8?context=explore) . It has an ubuntu 20.04 OS, as seen here:
![ubuntu_base](https://github.com/voxel51/fiftyone/assets/70665230/dd6c4db4-b8cd-4aae-9b95-293b5ef0e28d)
The host machine is also running ubuntu 20.04. 
I run the devcontainer using these runArgs if that matters:
```
`"runArgs": [
    "-v", "/tmp/.X11-unix:/tmp/.X11-unix",
    "-e", "DISPLAY",
    "--privileged",
    "-v", "/dev/bus/usb:/dev/bus/usb",
    "--gpus", "all",
    "-p", "5151:5151",
    "--network", "host",
    "--rm"
]`

```


I have tried both reinstalling fiftyone over and over, restarting the docker container and the host machine, but nothing works. I just keep getting the same ImportError over and over.

**Comment by brimoor** [comment]
See also: #3321, #3236, #2961, #2900, #2737, #1988

**Comment by sriram-dsl** [comment]
refr this https://github.com/voxel51/fiftyone/issues/2900#issuecomment-1960666337
