### ISSUE TITLE
[FR] Reduce FiftyOne import time

### ISSUE THREAD

**Issue by nmichlo** [voxel51/fiftyone#1804]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Macos 12.0.1
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: v0.15.1
-   **Python version**: 3.10.4

### Commands to reproduce

`fiftyone`
or
`fiftyone --version`
or
`python -c "import fiftyone"`

### Describe the problem

Importing fiftyone in general is VERY slow often 4-6 seconds.
`import fiftyone`

This is not desirable if fiftyone is needed for command line applications.

The main culprits seem to be:
- submodules in fiftyone reference back to the public api which means importing submodules imports everything. Eg. `fiftyone.core.dataset` contains `import fiftyone`
- In `fiftyone/__public__.py` the following files seem to be the culprits:
    + **core.config**: 548.17ms
    + **core.odm**: 1019.60ms
    + **core.plots**: 620.60ms
    + core.session: 54.95ms
    + load_config(): 214.52ms
    + **establish_db_conn()**: 3761.12ms

### Code to reproduce issue

`import fiftyone`

`from fiftyone.core.dataset import Dataset`
- Should be noted that this seems to have back references to `fiftyone.__public__`. This should bot be the case across the library. Imports in submodules should make direct references to the components they need to speed up importing. Importing this should be expected to be faster than importing the entire public interface.

### Other info / logs

Output of running: `python3 -c "import fiftyone"` (With modifications given below)

Custom logs for each import from `fiftyone/__public__.py`
```bash
N/A: 0.00ms
core.config: 548.17ms
core.odm: 1019.60ms
load_config(): 214.52ms
load_annotation_config(): 0.19ms
load_app_config(): 0.07ms
N/A: 0.00ms
core.config: 278.28ms
core.odm: 582.77ms
load_config(): 58.93ms
load_annotation_config(): 0.11ms
load_app_config(): 0.04ms
establish_db_conn(): 0.01ms
core.aggregations: 2.35ms
core.config: 0.00ms
core.dataset: 122.92ms
core.expressions: 0.01ms
core.fields: 0.01ms
core.frame: 0.00ms
core.labels: 0.01ms
core.metadata: 0.00ms
core.models: 0.00ms
core.odm: 0.00ms
core.plots: 620.60ms
core.sample: 0.00ms
core.stages: 2.01ms
core.session: 54.95ms
core.utils: 0.01ms
core.view: 0.00ms
utils.eval.classification: 12.39ms
utils.eval.detection: 0.00ms
utils.eval.segmentation: 0.00ms
utils.eval.quickstart: 25.54ms
establish_db_conn(): 3761.12ms
core.aggregations: 2.75ms
core.config: 0.01ms
core.dataset: 68.54ms
core.expressions: 0.01ms
core.fields: 0.01ms
core.frame: 0.00ms
core.labels: 0.01ms
core.metadata: 0.00ms
core.models: 0.00ms
core.odm: 0.01ms
core.plots: 344.27ms
core.sample: 0.00ms
core.stages: 1.26ms
core.session: 31.29ms
core.utils: 0.01ms
core.view: 0.00ms
utils.eval.classification: 6.16ms
utils.eval.detection: 0.00ms
utils.eval.segmentation: 0.00ms
utils.eval.quickstart: 13.43ms
```

<details>
<summary>Code Modification of `__public__.py` Used To Generate the Above</summary>
<br>
<p>
import time

_t = time.time()
def print_elapsed(msg: str = None):
    global _t
    t = time.time() - _t
    print(f'{msg}: {t*1000:.2f}ms' if msg else f'{t*1000:.2f}ms')
    _t = time.time()

print_elapsed('N/A')
import fiftyone.core.config as _foc
print_elapsed('core.config')
import fiftyone.core.odm as _foo
print_elapsed('core.odm')

config = _foc.load_config()
print_elapsed('load_config()')
annotation_config = _foc.load_annotation_config()
print_elapsed('load_annotation_config()')
app_config = _foc.load_app_config()
print_elapsed('load_app_config()')

_foo.establish_db_conn(config)
print_elapsed('establish_db_conn()')

from .core.aggregations import (
    Bounds,
    Count,
    CountValues,
    Distinct,
    HistogramValues,
    Mean,
    Std,
    Sum,
    Values,
)
print_elapsed('core.aggregations')
from .core.config import AppConfig
print_elapsed('core.config')
from .core.dataset import (
    Dataset,
    list_datasets,
    dataset_exists,
    load_dataset,
    delete_dataset,
    delete_datasets,
    delete_non_persistent_datasets,
    get_default_dataset_name,
    make_unique_dataset_name,
    get_default_dataset_dir,
)
print_elapsed('core.dataset')
from .core.expressions import (
    ViewField,
    ViewExpression,
    VALUE,
)
print_elapsed('core.expressions')
from .core.fields import (
    ArrayField,
    BooleanField,
    ClassesField,
    DateField,
    DateTimeField,
    DictField,
    EmbeddedDocumentField,
    EmbeddedDocumentListField,
    Field,
    FrameNumberField,
    FrameSupportField,
    FloatField,
    GeoPointField,
    GeoLineStringField,
    GeoPolygonField,
    GeoMultiPointField,
    GeoMultiLineStringField,
    GeoMultiPolygonField,
    IntField,
    IntDictField,
    KeypointsField,
    ListField,
    ObjectIdField,
    PolylinePointsField,
    StringField,
    TargetsField,
    VectorField,
)
print_elapsed('core.fields')
from .core.frame import Frame
print_elapsed('core.frame')
from .core.labels import (
    Label,
    Attribute,
    BooleanAttribute,
    CategoricalAttribute,
    NumericAttribute,
    ListAttribute,
    Regression,
    Classification,
    Classifications,
    Detection,
    Detections,
    Polyline,
    Polylines,
    Keypoint,
    Keypoints,
    Segmentation,
    Heatmap,
    TemporalDetection,
    TemporalDetections,
    GeoLocation,
    GeoLocations,
)
print_elapsed('core.labels')
from .core.metadata import (
    Metadata,
    ImageMetadata,
    VideoMetadata,
)
print_elapsed('core.metadata')
from .core.models import (
    apply_model,
    compute_embeddings,
    compute_patch_embeddings,
    load_model,
    Model,
    ModelConfig,
    EmbeddingsMixin,
    TorchModelMixin,
    ModelManagerConfig,
    ModelManager,
)
print_elapsed('core.models')
from .core.odm import KeypointSkeleton
print_elapsed('core.odm')
from .core.plots import (
    plot_confusion_matrix,
    plot_pr_curve,
    plot_pr_curves,
    plot_roc_curve,
    lines,
    scatterplot,
    location_scatterplot,
    Plot,
    ResponsivePlot,
    InteractivePlot,
    ViewPlot,
    ViewGrid,
    CategoricalHistogram,
    NumericalHistogram,
)
print_elapsed('core.plots')
from .core.sample import Sample
print_elapsed('core.sample')
from .core.stages import (
    Concat,
    Exclude,
    ExcludeBy,
    ExcludeFields,
    ExcludeFrames,
    ExcludeLabels,
    Exists,
    FilterField,
    FilterLabels,
    FilterKeypoints,
    Limit,
    LimitLabels,
    GeoNear,
    GeoWithin,
    GroupBy,
    MapLabels,
    Match,
    MatchFrames,
    MatchLabels,
    MatchTags,
    Mongo,
    Shuffle,
    Select,
    SelectBy,
    SelectFields,
    SelectFrames,
    SelectLabels,
    SetField,
    Skip,
    SortBy,
    SortBySimilarity,
    Take,
    ToPatches,
    ToEvaluationPatches,
    ToClips,
    ToFrames,
)
print_elapsed('core.stages')
from .core.session import (
    close_app,
    launch_app,
    Session,
)
print_elapsed('core.session')
from .core.utils import (
    pprint,
    pformat,
    ProgressBar,
)
print_elapsed('core.utils')
from .core.view import DatasetView
print_elapsed('core.view')
from .utils.eval.classification import (
    evaluate_classifications,
    ClassificationResults,
    BinaryClassificationResults,
)
print_elapsed('utils.eval.classification')
from .utils.eval.detection import (
    evaluate_detections,
    DetectionResults,
)
print_elapsed('utils.eval.detection')
from .utils.eval.segmentation import (
    evaluate_segmentations,
    SegmentationResults,
)
print_elapsed('utils.eval.segmentation')
from .utils.quickstart import quickstart
print_elapsed('utils.eval.quickstart')
</p>
</details>

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @nmichlo, per your benchmarking, most of the import time (~4 seconds) is due to establishing a MongoDB connection, which is mandatory for using FiftyOne (that's where all metadata is stored).

By default, importing FiftyOne spins up a MongoDB instance in a background process. This process is a singleton on the machine, however, so, if you import FiftyOne in multiple processes, imports after the first one will be faster.

One option to speed up imports is to [run MongoDB outside of FiftyOne](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-a-mongodb-connection), in which case you'll avoid the 4 seconds of MongoDB-related setup at import.

**Comment by nmichlo** [comment]
I am not entirely sure about the architecture of FiftyOne, but some of the APIs that fiftyone provides are extremely useful on their own, but I do not see any reason why they should require that MongoDB is initialised to use them?

Could fiftyone be configured to use an alternative more lightweight backend?
- Maybe something like `tinydb`?

With regards to Mongo DB
- Could initialisation be lazily run, only when required?
- Could initialisation be done in a background process?

**Comment by brimoor** [comment]
Everything in FiftyOne requires MongoDB, because that's where all `Dataset` object's contents are stored. So deferring MongoDB startup is not an option, nor is swapping it out for another backend, because FiftyOne's API is tightly coupled with MongoDB-specific features.

**Comment by nmichlo** [comment]
That is unfortunate.

I hope in future there might be workarounds for this, especially with regards to dataset conversion and uploading to CVAT. Which are useful APIs but are limited by the startup times.
