### ISSUE TITLE
[FR] Add support for rotated bounding boxes

### ISSUE THREAD

**Issue by HamLam** [voxel51/fiftyone#1821]
### Proposal Summary

Could you please provide support for the visualization of rotated bounding boxes for coco dataset? 
The bounding box parameters for rotated boxes would include a fifth entry (rotated angle in radian) instead of the usual four for coco formatted dataset. Thank you! 

### Motivation

-   What is the use case for this feature?
Rotated bounding boxes are commonly bound on coco dataset in object detection. 

-   Why is this use case valuable to support for FiftyOne users in general?
It is a valuable feature because it expands the capability of FiftyOne

### What areas of FiftyOne does this feature affect?

-   [ *] App: FiftyOne application
-   [* ] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

(Use this section to include any additional information about the feature. If
you have a proposal for how to implement this feature, please include it here.)

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ *] No. I cannot contribute this feature at this time.

**Comment by ehofesmann** [comment]
I definitely agree that rotated bounding boxes would be valuable to have in FiftyOne. While it shouldn't be too much of a lift to add, it will require updates to the App to support rotated bbox visualization, and we also need to decide on how the rotation angle will be stored in the dataset. It seems like the best options would be either:
1) add the rotation angle into the `bounding_box` list allowing it to either be 4 or 5 elements in length
2) add a new dedicated attribute `rotation_angle` to the `Detection`

**Comment by radao** [comment]
Any plans to add rotated boxes in the near term?

**Comment by robmarkcole** [comment]
This is an increasingly common format for aerial datasets and its inclusion would benefit this entire domain

**Comment by brimoor** [comment]
Note that one can already visualize this data by storing it as [polylines](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#polylines-and-polygons).

Perhaps it would be sufficient to just add a `Polyline.from_rotated_box()` factory method?


```py
import cv2
import numpy as np

import fiftyone as fo
import fiftyone.core.labels as fol


def from_rotated_box(xc, yc, w, h, theta, **kwargs):
    R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
    x = 0.5 * w * np.array([1, -1, -1, 1])
    y = 0.5 * h * np.array([1, 1, -1, -1])
    points = R.dot(np.stack((x, y))).T + np.array((xc, yc))
    return fol.Polyline(points=[points.tolist()], closed=True, **kwargs)


polylines = []
for _ in range(10):
    xc, yc = 0.2 + 0.6 * np.random.rand(2)
    w, h = 1.5 * (min(xc, yc, 1 - xc, 1 - yc)) * np.random.rand(2)
    theta = 2 * np.pi * np.random.rand()
    polyline = from_rotated_box(xc, yc, w, h, theta, label="rotated box")
    polylines.append(polyline)


cv2.imwrite("/tmp/image.png", np.full((128, 128, 3), 255, dtype=np.uint8))

sample = fo.Sample(
    filepath="/tmp/image.png",
    boxes=fo.Polylines(polylines=polylines),
)

dataset = fo.Dataset()
dataset.add_sample(sample)

session = fo.launch_app(dataset)
```

<img width="788" alt="Screen Shot 2022-10-24 at 9 44 33 AM" src="https://user-images.githubusercontent.com/25985824/197540585-0ffae0e3-c7e5-44a2-97fd-a824c5ded2a8.png">

**Comment by adriantre** [comment]
My first instinct is that we don't need a dedicated type for this. Add a 'rotation' field to the Detection (which could default to 0). If it is present, then rotate around the provided coordinate.

One thing to note is that [Detectron2](https://detectron2.readthedocs.io/en/latest/modules/structures.html?highlight=rotated_boxes#detectron2.structures.RotatedBoxes) specifies RotatedBoxes as `(x_center, y_center, width, height, angle)`, and Detections in Fiftyone are stored as `[<top-left-x>, <top-left-y>, <width>, <height>]`. It does not matter for applying the rotation, but for evaluation (e.g. iou) and exporting to other formats this needs to be adapted.

**Comment by huynguyenxuan212** [comment]
it should be integrated with cvat backend too

**Comment by jamesljlster** [comment]
Hi,

I'm a Machine Learning Engineer, looking forward to rotated bounding box support from FiftyOne.
I stand for a dedicated rotated bounding box type for the following reasons:
- Rotated bounding box is not just bounding box adding with theta.  
  When theta of a rotated bounding box is changed, box size should be adjusted too, unless they are really correct.
  ![image](https://user-images.githubusercontent.com/28639476/208691728-ff0cddcf-8078-4f33-bf32-421951055b1a.png)

- Sometimes rotated bounding box cannot be translated to ideal bounding box directly.
  The following two objects share the same rotated bounding box, but having different bounding boxes:
  ![image](https://user-images.githubusercontent.com/28639476/208689114-dfcbc342-5817-4573-a3b0-0658d47831ea.png)  
  Personally, I always treat rotated bounding box and bounding box as different annotations, because they cannot reinterpret to each other.

- It's always more convenient to check what it is through its type, rather than contents.

**Comment by brimoor** [comment]
@Rephil2 good call, our `from_rotated_box()` method definitely needs to know the width/height of the image in order to correctly apply the rotation *and then* convert to normalized coordinates 👍
