### ISSUE TITLE
[FR] Make results lists scrollabe in the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1831]
On `fiftyone>=0.16`, the dataset list dropdown now behaves like other "long list" elements: they are limited to 10 results and never scrollable, and the user must start typing in order to limit their results to <10 in order to find certain datasets.

I propose that, to increase usability:
- The default results count is increased
- These lists are scrollable, to ensure that users that don't want to (or don't realize they can) start typing to narrow results can still find the element of interest to them

<img width="295" alt="Screen Shot 2022-06-07 at 11 51 49 AM" src="https://user-images.githubusercontent.com/25985824/172425713-245180cf-4453-467b-b306-13c616fc07bf.png">

<img width="821" alt="Screen Shot 2022-06-07 at 11 49 48 AM" src="https://user-images.githubusercontent.com/25985824/172425706-6a35215e-f7f8-4706-bbc0-7a1ffd9d0057.png">

**Comment by benjaminpkane** [comment]
Not a bug, but I will increase the number of returned results to 200 with scrolling.

**Comment by brimoor** [comment]
Ah I see, the user is supposed to know they have to start typing to narrow down the results.

I think we should take the hint from naive users like me and others that making any list fully scrollable is probably the safest bet to ensure users don't get stuck/confused.

I can honestly say I thought it was impossible to load certain datasets that didn't appear in the dataset dropdown in this design.
