### ISSUE TITLE
[FR] Add support for 3D point clouds, 3D detections, and birds eye view

### ISSUE THREAD

**Issue by TroyeFun** [voxel51/fiftyone#1846]
### Proposal Summary

Currently, Fiftyone supports image and video. And I find it a bit troublesome to support new media types (like point cloud), especially when trying not to modify the source code (so that I can directly install Fiftyone using pip instead of building it locally).
In my work, I want to read point cloud files and visualize them in bird-eye-view (BEV). A possible way can be still recognizing the point-cloud files as images, and processing them to BEV images in function draw_label. But I'm still wondering if there can be any better way.

### Motivation

-   What is the use case for this feature?
In 3D vision tasks, which is common in autonomous driving.

-   Why is this use case valuable to support for your project(s) or
    organization?
I'm doing some work about 3D detection in autonomous driving, and hoping to visualize the detection results in bird-eye-view or even in 3D point-cloud.

-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)
I'm trying to add new media_type without modifying the source code of Fiftyone, by adding wrapper to fo.Sample and fo.Dataset. But I find it hard as too many modules in the library rely on fom.MEDIA_TYPE. It will be appreciated if customized media_type can be supported, or simply supporting point cloud.

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [x] Server: FiftyOne server

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [x] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by TroyeFun** [comment]
Hi @brimoor ~

Thanks for your reply. I'm grad to hear that the development of support for 3D point cloud datasets is in the progress. 

> Example point cloud data. I assume .pcd format?
> Example 3D detections, so we can see the format you're working with

About the point cloud data and 3D detection, I think [KITTI 3D Object Detection Benchmark](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) is a valuable reference. You can find the point cloud data and the development kit in the website.

I don't know whether there is a standard point cloud file format. Anyway, I think a general function to read point cloud data is hard to satisfy the all kinds of need and it could be better if we can customize our point cloud file reader. For example, in  autonomous driving, we usually have more than one lidar (e.g. one master lidar and two side lidar), and we usually concatenate the point cloud at several successive timestamps together before pushing it into the DNN. We may need to read the point cloud from multiple data files and preprocess the data before getting the final point cloud.

> Any tools you are using to render the point cloud data today?
I'm not quite familiar with the 3d rendering tools. And to my knowledge, [pcl](https://pointclouds.org/), matplotlib, [open3d](http://www.open3d.org/), and [pharos](https://tensorbay-python-sdk.graviti.com/en/latest/features/visualization.html) seem to be good tools for 3d visualization, especially the last two, which support Jupyter(open3d) and web gui(pharos).

**Comment by benjaminpkane** [comment]
[Supported](https://docs.voxel51.com/user_guide/using_datasets.html#d-datasets)!
