### ISSUE TITLE
[BUG] tfrecord shard enumeration starting from 1 instead of 0

### ISSUE THREAD

**Issue by laserK3000** [voxel51/fiftyone#1847]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: v0.16.2
-   **Python version**: 3.10.4

### Commands to reproduce

export a view or dataset using the `export(...)` method with `num_shards >1`

### Describe the problem

Currently tfrecord shards are exported with filenames of the format `filename.tfrecord-xxxxx-of-yyyyy` with `x` ranging from `1` to `y`. This works in general if imported using the `tf.data` api but it seems that the range should be `0` to `y-1`.
We are trying to convert our exported tfrecord shards to a `tfds`. This fails as [`tfds.folder_dataset.compute_split_info`](https://www.tensorflow.org/datasets/api_docs/python/tfds/folder_dataset/compute_split_info)
expects enumeration starting from `0`.
We also looked through a couple of tensorflow datasets and enumeration from one looks like the common case.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [x] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
@laserK3000 feel free to make a PR to resolve this 🤗
