### ISSUE TITLE
[BUG] Quickstart fails in Colab "module 'cv2' has no attribute '_registerMatType'"

### ISSUE THREAD

**Issue by darknoon** [voxel51/fiftyone#1868]
### Instructions

Just clicked the "Try FiftyOne" button on the home page.

When it gets to importing the module it says:

```
AttributeError: module 'cv2' has no attribute '_registerMatType'
```

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
-   **FiftyOne installed from (pip or source)**:  pip
-   **FiftyOne version (run `fiftyone --version`)**:
-   **Python version**:

### Commands to reproduce

Click button on homepage, run notebook

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hey this is a quirk of Google Colab's default environment and a solution is available at https://github.com/voxel51/fiftyone/issues/1494#issuecomment-1003148448!
