### ISSUE TITLE
Make Take() deterministic

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#187]
This detail has come to my attention a few times, so I thought I'd start a discussion.

Take will return different results each time its view pipeline is executed. I'll note that `$sample`, which `take` uses, does not offer seeding.

The main point is that this behavior conflicts with the notion that what you see in the GUI, is what you have in python. Things get even worse when the view requires multiple page requests, i.e. `take(1000)`.

Perhaps this is an inconsequential detail, perhaps not.

**Comment by tylerganter** [comment]
resolved by #362
