### ISSUE TITLE
[?] How to create a new Dataset from a DatasetView?

### ISSUE THREAD

**Issue by flystarhe** [voxel51/fiftyone#1870]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature
request)

### Motivation

-   What is the use case for this feature?
-   Why is this use case valuable to support for FiftyOne users in general?
-   Why is this use case valuable to support for your project(s) or
    organization?
-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [ ] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

(Use this section to include any additional information about the feature. If
you have a proposal for how to implement this feature, please include it here.)

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
You're looking for [DatasetView.clone()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.view.html#fiftyone.core.view.DatasetView.clone) 🤗 

[Additional docs here](https://voxel51.com/docs/fiftyone/user_guide/using_views.html#saving-and-cloning).

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")

view = (
    dataset
    .select_fields("ground_truth")
    .filter_labels("ground_truth", F("label").is_in(["cat", "dog"]))
)

new_dataset = view.clone()

print(new_dataset.count_values("ground_truth.detections.label"))
# {'cat': 16, 'dog': 15}
```
