### ISSUE TITLE
[BUG] Renaming a cloned detection label prevents the web app from displaying the dataset

### ISSUE THREAD

**Issue by geoffrp** [voxel51/fiftyone#1887]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.16.2
-   **Python version**: 3.9.10

### Commands to reproduce
When trying to clone a sample field and then change labels of detections, the dataset becomes corrupted and the web application will no longer serve the dataset.  Below is a snippet that can reproduce the error (just set up a folder with a single image in it next to the script called `images`):

```
from pathlib import Path

import fiftyone as fo

# Make a 1 image dataset and make it persistent
dataset = fo.Dataset.from_images_dir(Path(__file__).parent.joinpath("images"))
dataset.name = "Bug"
dataset.persistent = True
dataset.compute_metadata()

# Open it up and add a detection
sample = dataset.first()
sample["dog_boxes"] = fo.Detections(
    detections=[fo.Detection(label="dog", bounding_box=[0.1, 0.1, 0.1, 0.1])]
)
sample.save()
# Remove the sample (close the connection...?),
del sample

dataset.clone_sample_field('dog_boxes', 'another_one')
# Open the sample again to add classifications to the detection
sample = dataset.first()
det = sample.another_one.detections[0]
det.label = 'ohno'
sample.save()

session = fo.launch_app(dataset, port=5000)
```

### Describe the problem

Describe the problem clearly here. Include descriptions of the expected
behavior and the actual behavior.

When duplicating a sample field, detection labels seem to be impossible to modify.  These labels should be readily modifiable.  When editing the original sample field's detections in-place, no errors occur.

### Code to reproduce issue

See above.

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached. Please do not use screenshots for sharing text. Code
snippets should be used instead when providing tracebacks, logs, etc.

The app launches successfully, but the webpage shows the following error:
```
get/<@http://localhost:5001/assets/index.0750e387.js:191:12025
a@http://localhost:5001/assets/vendor.b0739682.js:52:494206
w@http://localhost:5001/assets/vendor.b0739682.js:52:483152
B@http://localhost:5001/assets/vendor.b0739682.js:52:484364
F/<@http://localhost:5001/assets/vendor.b0739682.js:52:485658
F/<@http://localhost:5001/assets/vendor.b0739682.js:52:485629
F@http://localhost:5001/assets/vendor.b0739682.js:52:485651
getNodeLoadable@http://localhost:5001/assets/vendor.b0739682.js:52:442147
getRecoilValueAsLoadable@http://localhost:5001/assets/vendor.b0739682.js:52:445726
L0/r<@http://localhost:5001/assets/vendor.b0739682.js:52:463085
L0/i</<@http://localhost:5001/assets/vendor.b0739682.js:52:463158
useSyncExternalStore@http://localhost:5001/assets/vendor.b0739682.js:43:69664
h.useSyncExternalStore@http://localhost:5001/assets/vendor.b0739682.js:1:7602
L0@http://localhost:5001/assets/vendor.b0739682.js:52:463383
z0@http://localhost:5001/assets/vendor.b0739682.js:52:465253
j0@http://localhost:5001/assets/vendor.b0739682.js:52:465295
dm@http://localhost:5001/assets/index.0750e387.js:258:1066
ef@http://localhost:5001/assets/vendor.b0739682.js:43:62613
th@http://localhost:5001/assets/vendor.b0739682.js:43:120137
Zh@http://localhost:5001/assets/vendor.b0739682.js:43:109070
Jh@http://localhost:5001/assets/vendor.b0739682.js:43:108998
Yh@http://localhost:5001/assets/vendor.b0739682.js:43:108858
Kh@http://localhost:5001/assets/vendor.b0739682.js:43:106003
_A@http://localhost:5001/assets/vendor.b0739682.js:43:46860
Ph/<@http://localhost:5001/assets/vendor.b0739682.js:43:103571
```

### What areas of FiftyOne does this bug affect?

-   [X] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [X] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by benjaminpkane** [comment]
Hi @geoffrp. I believe this issue has been fixed in `v0.16.4`. Schema changes were fixed in the App, and I can no longer reproduce.

Let us know if you still have issues. Thanks!
