### ISSUE TITLE
Make tags look different from other bubbles

### ISSUE THREAD

**Issue by tylerganter** [voxel51/fiftyone#189]
I think it would be really cool to go with the "Best Buy" look. It would also help a bit with overly similar colors which we've gotten feedback on.

<img width="158" alt="Screen Shot 2020-06-11 at 10 53 23 AM" src="https://user-images.githubusercontent.com/9789052/84401878-ca5f9e00-abd1-11ea-9fe6-f9fd340fa078.png">

**Comment by benjaminpkane** [comment]
Noted in V1 design.
