### ISSUE TITLE
[FR] Add support for rendering 2D cuboids on images/videos

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1947]
We should add support for rendering 2D cuboids on images and videos, IE projected 3D detections defined by their 8 corners in 2D image coordinates.

[Example 2D cuboid data format](https://scale.com/blog/3d-cuboids-annotations).

This is distinct from https://github.com/voxel51/fiftyone/issues/1946, which is about true 3D detections/polylines.

**Comment by LJL0511** [comment]
<bndbox>
			<point0>660.30,857.79</point0>
			<point1>660.30,532.86</point1>
			<point2>958.94,740.93</point2>
			<point3>406.78,857.79</point3>
			<point4>406.78,532.86</point4>
			<point5>795.86,740.93</point5>
			<point6>958.94,531.91</point6>
			<point7>795.86,531.91</point7>
		</bndbox>
VOC format if mixed with 3D type bndbox, will there be support for this aspect in the future

**Comment by brimoor** [comment]
Note that one can already visualize this data by storing it as [polylines](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#polylines-and-polygons).

Perhaps it would be sufficient to just add a `Polyline.from_cuboid()` factory method?

```py
import cv2
import numpy as np

import fiftyone as fo
import fiftyone.core.labels as fol


def from_cuboid(vertices, **kwargs):
    """Contructs a cuboid from its 8 vertices in the format depicted below.

           7--------6
          /|       /|
         / |      / |
        3--------2  |
        |  4-----|--5
        | /      | /
        |/       |/
        0--------1

    Args:
        vertices: a list of 8 ``(x, y)`` vertices in the order depicted above
        **kwargs: additional arguments for the :class:`Polyline` constructor

    Returns:
        a :class:`Polyline`
    """
    vertices = np.asarray(vertices)
    front = vertices[:4]
    back = vertices[4:]
    top = vertices[[3, 2, 6, 7], :]
    bottom = vertices[[0, 1, 5, 4], :]
    faces = [front.tolist(), back.tolist(), top.tolist(), bottom.tolist()]
    return fol.Polyline(points=faces, closed=True, **kwargs)


polylines = []
for _ in range(3):
    x0, y0 = [0, 0.2] + 0.8 * np.random.rand(2)
    dx, dy = (min(0.8 - x0, y0 - 0.2)) * np.random.rand(2)
    x1, y1 = x0 + dx, y0 - dy
    w, h = (min(1 - x1, y1)) * np.random.rand(2)
    front = [(x0, y0), (x0 + w, y0), (x0 + w, y0 - h), (x0, y0 - h)]
    back = [(x1, y1), (x1 + w, y1), (x1 + w, y1 - h), (x1, y1 - h)]
    vertices = front + back

    polyline = from_cuboid(vertices, label="cuboid")
    polylines.append(polyline)


cv2.imwrite("/tmp/image.png", np.full((128, 128, 3), 255, dtype=np.uint8))

sample = fo.Sample(
    filepath="/tmp/image.png",
    boxes=fo.Polylines(polylines=polylines),
)

dataset = fo.Dataset()
dataset.add_sample(sample)

session = fo.launch_app(dataset)
```

<img width="786" alt="Screen Shot 2022-10-25 at 12 54 20 PM" src="https://user-images.githubusercontent.com/25985824/197835649-ffe676d6-424f-462c-8433-6f37e7c65d31.png">
