### ISSUE TITLE
[FR] Add support for exporting absolute paths in COCO format

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1974]
When performing labels-only exports in COCO format, the `file_name` field of the exported JSON contains literally the filename (`os.path.basename(filepath)`), however, in some workflows, since the corresponding media is not actually being exported into a parallel folder, it would be desirable to include the full `filepath` in the JSON.

A good syntax for this may be an optional `abs_paths=True` argument:

```py
dataset.export(
    labels_path="/tmp/coco.json",
    dataset_type=fo.types.COCODetectionDataset,
    abs_paths=True,
)
```

Such an option could make sense in other contexts too:
1. Even when media is also being exported (user choice)
2. Likely this option would make sense for other builtin export formats too

Current behavior:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

dataset.export(
    labels_path="/tmp/coco.json",
    dataset_type=fo.types.COCODetectionDataset,
)
```

```shell
python -m json.tool /tmp/coco.json
```

```
        ...
        {
            "id": 66,
            "file_name": "003713.jpg",
            "height": 640,
            "width": 439,
            "license": null,
            "coco_url": null
        },
        ...
```

**Comment by kalpit-S** [comment]
I believe this has been addressed by https://github.com/voxel51/fiftyone/pull/2060.

**Comment by brimoor** [comment]
Correct! This syntax is now supported:

```py
dataset.export(
    labels_path="/tmp/coco.json",
    dataset_type=fo.types.COCODetectionDataset,
    abs_paths=True,
)
```
