### ISSUE TITLE
[BUG] App does not use custom AppConfig

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1986]
On `fiftyone==0.16.5`, the App ignores the custom AppConfig provided in the example below:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

app_config = fo.AppConfig()
app_config.color_pool = ["#FF0000", "#00FF00", "#0000FF"]

session = fo.launch_app(dataset, config=app_config)

# The custom color pool is there, but the App doesn't use it
print(session.config)
```

On `fiftyone==0.15.1`, the custom color pool is used as expected.

**Comment by aniasusual** [comment]
@brimoor hey, I want to work on this issue can you please help me getting started?

**Comment by brimoor** [comment]
@aniasusual that's awesome! @benjaminpkane would be able to point you in the right direction here

**Comment by brimoor** [comment]
This is working again as of `fiftyone==0.18.0`.
