### ISSUE TITLE
[FR] Document how to install FiftyOne on Ubuntu 22.04

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1988]
MongoDB has issues on Ubuntu 22.04: https://askubuntu.com/q/1403619

We need to document a recommend approach(es) for installing FiftyOne on Ubuntu 22.04, which may include:
- Workarounds to install MongoDB manually
- Run MongoDB in a Docker 
- Run all of FiftyOne in a Docker

Here are a variety of relevant places in the existing documentation:

- Troubleshooting section of the install page. Our recommended solution for installing on Ubuntu 22.04 should be directly listed (or linked to) from here:
https://voxel51.com/docs/fiftyone/getting_started/install.html#troubleshooting

- Spillover page where more complex install troubleshooting descriptions live:
https://voxel51.com/docs/fiftyone/getting_started/troubleshooting.html#troubleshooting

- Some install environments (eg Apple Silicon) require installing and running MongoDB manually; this is currently documented here:
https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-a-mongodb-connection

- Instructions from the README regarding running (all of) FiftyOne inside Docker:
https://github.com/voxel51/fiftyone#docker-installs

- Docs page discussing how to work with FiftyOne in different environments. It may make sense to add a Docker section here:
https://voxel51.com/docs/fiftyone/environments/index.html

**Comment by brimoor** [comment]
Users have reported success getting MongoDB (and hence FiftyOne) running on Ubuntu 22.04 as follows:

```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb -O libsll.deb \
&& dpkg -i libsll.deb
```

For reference, the actual error observed when trying to import FiftyOne on Ubuntu 22.04 is the following:

```
>> import fiftyone
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

**Comment by ctorres-actuate** [comment]
I was getting the same error.

Here is what worked for me when installing on ubuntu and pop.os 22.04 with miniconda and python 3.10 (inside a conda virtual env). 

Note: paraphrasing the steps. Adjust to your system and preferences.

> You need to install libssl

The package [website](https://packages.ubuntu.com/bionic/amd64/libssl1.1/download) -- the one above is `no longer active/working`. You can manually download it to a local directory (e.g., Install/) or use the following commands:

```bash
cd ~/Install
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.21_amd64.deb
sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.21_amd64.deb
```
Follow the prompt to install... and now you can complete the setup and run the fiftyone [quickstart](https://docs.voxel51.com/getting_started/install.html#quickstart)

**Comment by ksaaskil** [comment]
For reference, here's how to run MongoDB 6.0 in a Docker container:

```sh
docker run --name mongo --rm -v $HOME/.fiftyone/var/lib/mongo:/data/db -d -p 27017:27017 mongo:6.0.4-jammy
```
and configure FiftyOne to use the custom database:
```sh
cat <<EOF > $HOME/.fiftyone/config.json
{
  "database_uri": "mongodb://localhost:27017"
}
EOF
```

**Comment by kikislater** [comment]
> I was getting the same error.
> 
> Here is what worked for me when installing on ubuntu and pop.os 22.04 with miniconda and python 3.10 (inside a conda virtual env).
> 
> Note: paraphrasing the steps. Adjust to your system and preferences.
> 
> > You need to install libssl
> 
> Get the package from the **current** [website](https://packages.ubuntu.com/bionic/amd64/libssl1.1/download) -- the one above is `no longer active/working`. You can manually download it to a local directory (e.g., Install/) or use the following commands:
> 
> ```shell
> cd ~/Install
> wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.21_amd64.deb
> sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.21_amd64.deb
> ```
> 
> Follow the prompt to install... and now you can complete the setup and run the fiftyone [quickstart](https://docs.voxel51.com/getting_started/install.html#quickstart)

So you are installing an ubuntu's 18.04 lib inside ubuntu 22.04 and you have no problem with that. It's totally dirty with security considerations !
Does the firtyone not able to build a newer version of mongod binary inside their pip package ? A better option is not to embedded this mongod binary and let user install in prerequisites ...

**Comment by kikislater** [comment]
Culprit is here : 
https://github.com/voxel51/fiftyone/blob/develop/package/db/setup.py#L29

Hardlink instead of dynamic from `sys` module

Btw, mongod 5 is not available through these links for ubuntu 22.04. It starts since version 6

**Comment by kikislater** [comment]
These lines are useless : https://github.com/voxel51/fiftyone/blob/develop/package/db/setup.py#L40-L41

They are used in other part of the script

**Comment by kikislater** [comment]
May be a CI/CD would be welcome ... last updates from these dockerfiles : 2 years ago. Looks like an abandonned project whereas some company and public institutions pay for it  !
https://github.com/voxel51/fiftyone/tree/develop/package/test-envs/dockerfiles

**Comment by kikislater** [comment]
Well no comment anymore ... lol  => https://github.com/voxel51/fiftyone/commit/bb271d5853eb637c393c180b35a3e3be23c49483
Weird package that'all. I'll leave this repo now

**Comment by stevezkw1998** [comment]
I encountered with same issue when deploying 2 docker containers in one linux machine
both of them are using fiftyone
and both of them has this mount:
-v /opt/.fiftyone/var/lib/mongo:/root/.fiftyone/var/lib/mongo

```
{"t":{"$date":"2023-06-10T07:11:33.768Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"-","msg":"Renamed existing log file","attr":{"oldLogPath":"/root/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/root/.fiftyone/var/lib/mongo/log/mongo.log.2023-06-10T07-11-33"}}
Subprocess ['/opt/conda/lib/python3.10/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/root/.fiftyone/var/lib/mongo', '--logpath', '/root/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Traceback (most recent call last):
... ...
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

**Comment by benjaminpkane** [comment]
Pardon the silence. Current solution for Ubuntu 22.04 installs is documented [here](https://docs.voxel51.com/getting_started/troubleshooting.html#alternative-linux-builds). 

A general solution I propose to remove `fiftyone-db` and related packages can be tracked [here](https://github.com/voxel51/fiftyone/issues/1988)

**Comment by brimoor** [comment]
For clarity, the current solution is to install FiftyOne like so:

```
pip install fiftyone
pip install fiftyone-db-ubuntu2204
```

**Comment by brimoor** [comment]
See also: #3321, #3236, #2961, #2900, #2737, #1803

**Comment by ClementPinard** [comment]
> Pardon the silence. Current solution for Ubuntu 22.04 installs is documented [here](https://docs.voxel51.com/getting_started/troubleshooting.html#alternative-linux-builds).
> 
> A general solution I propose to remove `fiftyone-db` and related packages can be tracked [here](https://github.com/voxel51/fiftyone/issues/1988).

I believe the second link is incorrect (it redirects to here actually). The right link, discussing the dynamic installation of fiftyone-db is here : https://github.com/voxel51/fiftyone/issues/3236
