### ISSUE TITLE
[BUG] Add validation to dataset names

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#1996]
Dataset names should be validated for unsupported characters before being saved. Many non-alphanumeric characters result in issues when attempting to load the dataset in the App. 

```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart").clone()
dataset.name = "test/1"

session = fo.launch_app(dataset)
```

```
404: /datasets/test%2F1 not found
```

**Comment by brimoor** [comment]
More generally, we'll need to introduce notions of "human-readable" vs "URL-friendly" dataset names.

IE a dataset with name `ErIc's CrAzY DaTaSeT` will be reachable at `/datasets/erics-crazy-dataset`.

We could still add validation to the human-readable name, but I do think spaces should be allowed in the dataset name, but they can't be allowed in the URL.

**Comment by swheaton** [comment]
URL safe slugs are used now.
