### ISSUE TITLE
[FR] Offline Serving

### ISSUE THREAD

**Issue by eladrich** [voxel51/fiftyone#2014]
### Proposal Summary

Unless I'm just experiencing a bug, it looks like fiftyone sessions require an internet connection. Would it be able to allow serving sessions locally with no internet connection?

### Motivation
When working locally users don't always have a stable internet connection and being able to serve locally / on-premise as in Jupyter Notebooks could be useful

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [ ] Core: Core `fiftyone` Python library
-   [x] Server: FiftyOne server

**Comment by benjaminpkane** [comment]
Hi @eladrich. FiftyOne does not require an internet connection. Can you describe the issue(s) you are encountering?

**Comment by eladrich** [comment]
My bad, I encountered a white screen on the served web page. But turns out I had a really old chrome version on that machine (69) and that caused the problem
