### ISSUE TITLE
[BUG] fiftyone.utils.splits pacakge is removed from 0.16.6 version, but the 0.16.5 version still has.

### ISSUE THREAD

**Issue by YaoQ** [voxel51/fiftyone#2033]
Why  fiftyone.utils.splits is removed from 0.16.6 version, and is there any new packaged replacing with it ?

Thank you very much.

**Comment by YaoQ** [comment]
Now I find fiftyone.utils.random replacing the splits function for 0.16.6 version.

**Comment by brimoor** [comment]
Yes `fiftyone.utils.splits` was renamed to `fiftyone.utils.random` in v0.16.6 because it now has more utilities in it 🤗 

https://voxel51.com/docs/fiftyone/api/fiftyone.utils.random.html
