### ISSUE TITLE
[BUG] SyntaxError: Unexpected token 'U', "Unsupporte"... is not valid JSON

### ISSUE THREAD

**Issue by flystarhe** [voxel51/fiftyone#2064]
### Instructions
![image](https://user-images.githubusercontent.com/5718508/188659555-7cd246b5-5ea0-454d-afa1-344913e113d6.png)

### System information

-   **Win11**:
-   **FiftyOne installed from pip**:
-   **FiftyOne v0.16.6, Voxel51, Inc.**:
-   **Python 3.9.12**:

### Commands to reproduce

```
session = fo.launch_app(dataset)
```

**Comment by KuenstlicheIntelligenz** [comment]
I also get a Syntax Error without an error msg, both in Jupyter Notebook and in Firefox on 
- Ubuntu 20.04
- pip
- v0.16.5
- python 3.9.5

**Comment by brimoor** [comment]
Are you upgrading from an older version of FiftyOne? Can you try uninstalling first and then reinstalling?

```shell
pip uninstall fiftyone fiftyone-brain fiftyone-db
pip install --upgrade fiftyone
```

Alternatively, can you trying creating a fresh virtual environment?

I'm unable to reproduce this from a fresh virtual environment, eg:

```shell
conda create -n tmp python=3.9
conda activate tmp
pip install --upgrade fiftyone ipython
ipython
```

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

**Comment by KuenstlicheIntelligenz** [comment]
Ive upgraded, yes. Reinstalling didnt help.

Fresh environment worked. 
A little bit unsatisfying, because if i install my old env again, it could be the same?
But at least for now this solves my problem.

**Comment by KuenstlicheIntelligenz** [comment]
Unfortunately i dont know from which version i upgraded.
I tried a few other minor versions e.g. 0.16.1 but they all had the same error.

0.15.1 is just stuck in "Pixelating" so is 0.14.4.

**Comment by Rusteam** [comment]
hi there, also stuck at `pixelating` after starting up the app: `fiftyone app launch`. No logs in a terminal.

system info:
- MacOS Monterrey (M1 chip)
- fiftyone=0.16.6 (pip installed)
- python=3.10.4

**Comment by benjaminpkane** [comment]
I am trying to reproduce yet. Still investigating.

For any upgrade/downgrade issues when using the App, I always recommend clearing the browser cache.

**Comment by Rusteam** [comment]
Surprisingly, the home page loaded after some idle time.  It's working now for me :).

**Comment by brimoor** [comment]
If you encounter this again, I think the solution may just be to do a hard reload (`ctrl + shift + R` in Chrome, for example), or just to be extra safe, an `Empty Cache and Hard Reload` (open dev tools when right-click the refresh icon, in Chrome):

![download](https://user-images.githubusercontent.com/25985824/189738944-a36ab092-700b-41ec-a5b2-91f443a727c2.png)

**Comment by Rusteam** [comment]
Thanks I'll try clearing cache if it happens again. (I've tried with ctrl + shift + R, it didn't work)

**Comment by benjaminpkane** [comment]
@KuenstlicheIntelligenz It looks like this error is coming from a network request. If you can share the response data from the network tab in dev tools, I can probably find the issue.

**Comment by KuenstlicheIntelligenz** [comment]
@benjaminpkane 

Not sure exactly what you need. I'll just guess.
![network_fiftyone](https://user-images.githubusercontent.com/17128163/190111515-9bf46ede-bdfd-457d-9c4d-d0afea0716b4.png)
![headers](https://user-images.githubusercontent.com/17128163/190111504-a1203668-7071-4fc1-a72d-a9023ecbfc46.png)
![payload](https://user-images.githubusercontent.com/17128163/190111518-e387551c-3aa4-4108-ba48-d23db84cff66.png)
![unsup_media](https://user-images.githubusercontent.com/17128163/190111519-73de124b-d05b-4c73-852e-32dd1dc5ae3e.png)

**Comment by benjaminpkane** [comment]
Perfect, thanks. The server is returning a 415 from `/graphql`, which I haven't seen before.

Can you share your versions of `hypercorn`, `starlette` and `strawberry-graphql`?

```
pip list | grep "hypercorn"
pip list | grep "starlette"
pip list | grep "strawberry-graphql"
```

**Comment by KuenstlicheIntelligenz** [comment]
Hey, sorry for the late reply, was ill...
```
hypercorn                      0.14.2
sse-starlette                  0.10.3
starlette                      0.16.0
strawberry-graphql             0.96.0
```

**Comment by phuvinhnguyen** [comment]
It seems like Im having a similar problem

console:
![image](https://user-images.githubusercontent.com/81418873/196414348-ed81dbb9-aeb7-4abc-9904-3ea796f0a22e.png)

**Comment by phuvinhnguyen** [comment]
change to version 0.15.1 works for me

**Comment by swheaton** [comment]
old issue. please reopen a new one if this is a problem in the lates FO version
