### ISSUE TITLE
Downgrade from 0.16.6 to e.g. 0.16.5 not working as expected

### ISSUE THREAD

**Issue by KuenstlicheIntelligenz** [voxel51/fiftyone#2065]
### System information

-   Ubuntu 20.04
-   installed from pip
-   **FiftyOne version** : FiftyOne v0.16.6, Voxel51, Inc.
-   **Python version**: Python 3.9.5

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```python
# Version 0.16.6
# Download
import fiftyone.zoo as foz
dataset = foz.load_zoo_dataset("quickstart")
dataset.persistent = True
# Restart kernel
```
```python
# More or less just a check
# Version 0.16.6
import fiftyone as fo
dataset = fo.load_dataset("quickstart")
# Stop the kernel
```
```bash
#!/bin/bash
# The version that you wish to downgrade to
VERSION=0.16.5

# Migrate the database
fiftyone migrate --all -v $VERSION

# Optional: verify that your datasets were migrated
fiftyone migrate --info

# Now install the older version of `fiftyone`
pip install fiftyone==$VERSION
```

```
# Start the kernel
# Error
import fiftyone as fo
```

### Describe the problem

Can't downgrade as expected 

### Other info / logs
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_16495/1310548987.py in <module>
      1 # Start the kernel
----> 2 import fiftyone as fo

~/miniconda3/envs/bab/lib/python3.9/site-packages/fiftyone/__init__.py in <module>
     29 
     30 if _os.environ.get("FIFTYONE_DISABLE_SERVICES", "0") != "1":
---> 31     _fom.migrate_database_if_necessary()
     32     _fou.log_import_if_allowed()

~/miniconda3/envs/bab/lib/python3.9/site-packages/fiftyone/migrations/runner.py in migrate_database_if_necessary(destination, verbose)
    122 
    123     if _database_exists():
--> 124         runner = MigrationRunner(head=head, destination=destination)
    125         if runner.has_admin_revisions:
    126             logger.info("Migrating database to v%s", destination)

~/miniconda3/envs/bab/lib/python3.9/site-packages/fiftyone/migrations/runner.py in __init__(self, head, destination, _revisions, _admin_revisions)
    236         dest_ver = Version(destination)
    237         if head_ver > pkg_ver or dest_ver > pkg_ver:
--> 238             raise EnvironmentError(
    239                 "You must have fiftyone>=%s installed in order to migrate "
    240                 "from v%s to v%s, but you are currently running fiftyone==%s."

OSError: You must have fiftyone>=0.16.6 installed in order to migrate from v0.16.6 to v0.16.5, but you are currently running fiftyone==0.16.5.

See https://voxel51.com/docs/fiftyone/getting_started/install.html#downgrading-fiftyone for information about downgrading FiftyOne.
```

Output of migration info:
```
Client version: 0.16.6
Compatible versions: >=0.16.3,<0.17

Database version: 0.16.6

dataset         version
--------------  ---------
quickstart      0.16.5
``` 

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time. (Probably way to deep for me to solve?)

**Comment by brimoor** [comment]
Hi @KuenstlicheIntelligenz 👋 

Apologies, the order of the commands in the docs should be switched:

```shell
# The version that you wish to downgrade to
VERSION=0.16.5

# Migrate the database
fiftyone migrate --all -v $VERSION

# Install the older version of `fiftyone`
pip install fiftyone==$VERSION

# NOW verify that your datasets were migrated
fiftyone migrate --info
```

Running `fiftyone migrate --info` directly after `fiftyone migrate --all -v $VERSION` will cause the database to be migrated back up to the current client version before you change your client version.

**Comment by KuenstlicheIntelligenz** [comment]
Thanks a lot!
I dont know how you proceed with changing that in the docs, so close this for now.

**Comment by barzan-hayati** [comment]
> ```shell
> # The version that you wish to downgrade to
> VERSION=0.16.5
> 
> # Migrate the database
> fiftyone migrate --all -v $VERSION
> 
> # Install the older version of `fiftyone`
> pip install fiftyone==$VERSION
> 
> # NOW verify that your datasets were migrated
> fiftyone migrate --info
> ```

This does not work for me :

`OSError: You must have fiftyone>=0.24.0 installed in order to migrate from v0.24.0 to v0.23.3, but you are currently running fiftyone==0.23.3.
`
