### ISSUE TITLE
Quotation marks needed for fiftyone[desktop]

### ISSUE THREAD

**Issue by GeorgePearse** [voxel51/fiftyone#2067]
### URL(s) with the issue:

https://voxel51.com/docs/fiftyone/getting_started/install.html#installing-fiftyone-desktop

### Description of proposal (what needs changing):
```
pip install fiftyone[desktop]
```
does not work, it needs quotation marks

e.g.
```
pip install "fiftyone[desktop]"
```

### Willingness to contribute

-   [X] Yes. I can contribute a documentation fix independently.
-   [ ] Yes. I would be willing to contribute a document fix with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute a documentation fix at this time.

**Comment by brimoor** [comment]
Ah good catch, feel free to make a PR to patch it 🤗

**Comment by brimoor** [comment]
Closed by https://github.com/voxel51/fiftyone/pull/2068.
