### ISSUE TITLE
How to add custom labels which can be accessible in UI?

### ISSUE THREAD

**Issue by ankxyz** [voxel51/fiftyone#2077]
I want to add to each sample of my dataset some label with several field:

```python
for sample in dataset:
    sample['my_label'] = {
        'field_1': [<list-of-values],
        'field_2': [<list-of-values]
    }

    sample.save()
````

Field values - lists [<list-of-values] - can be of different lengths (it's important!) from sample to sample.

I would like to see `my_label` in the `LABELS`  list in UI, as drop-down list, that I can filter by `field_1`, `field_2` values.

I tried to do it with dictionaries, but:
- `my_label` is displayed just in `OTHERS`, but not in `LABELS`
- it's not drop-down list, but it's just line in `OTHER` group

---

The closest what I want is `Detections` example: https://voxel51.com/docs/fiftyone/tutorials/evaluate_detections.html#Add-predictions-to-dataset. But with custom field names:

```python
for sample in dataset:
    
    my_labels = []
    for field_1_v,  field_2_v in values_list:
        my_labels.append(
            MyLabel(field_1=field_1_v, field_2=field_2_v)
        )
    sample['my_label'] = MyLabels(labels=my_labels)
    sample.save()
```

Is it possible with dictionaries or I should to define custom classes like `Classification` and `Classifications` or like `Detection` and `Detections`?

Thanks for advace.

**Comment by swheaton** [comment]
I do not think it's possible with just a dictionary, you can add a label class or use one of the existing ones.
