### ISSUE TITLE
[FR] Add keypoint evaluation

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2092]
Similar to `evaluate_detections()` and `evaluate_classifications()`, it would be useful to add a built-in method to evaluate keypoint labels. A good place to start is likely replicating the COCO method for keypoint evaluation defined here: https://cocodataset.org/#keypoints-eval

**Comment by smidm** [comment]
https://github.com/voxel51/fiftyone/pull/2928 closes this issue
