### ISSUE TITLE
[FR] YOLOv5DatasetExporter : Add optional to add path to dataset.yaml

### ISSUE THREAD

**Issue by karsil** [voxel51/fiftyone#2106]
### Proposal Summary
Add option for the YOLOv5 dataset export to add the value for `path` to the `dataset.yaml`.

### Motivation
A problem occured when working with the pip package of YOLOv5.
YOLOv5 will try before training to resolve the relative `train` / `val` inside the `dataset.yaml`.
Without any reference to the absolute path of the data, it will end up resolving it inside the pip package, not in any project. This will end up in an exception and stopping the training process.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [X] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

By adding the absolute path as value to the key `path`, this problem can be fixed. (I modified the `dataset.yaml` after the export to verify this). The already existing variable `export_dir` could be used for this.

As far as I understood it until now, my proposed changes would be quite small:
- **YOLOv5DatasetExporter.init(...)**: Recieves another optional, boolean parameter: `export_dir_as_path`, default `False`
- **YOLOv5DatasetExporter.close(...)**:  If flag has been set, export_dir is added as value to key `path`

Open for any improvements!

### Willingness to contribute
-   [ ] Yes. I can contribute this feature independently.
-   [X] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hi @karsil 👋 makes sense! I might recommend `include_path=True` as the name of the new optional parameter for this case. 

If you submit a PR I'd be happy to approve it! 🤗

**Comment by brimoor** [comment]
cc @victor1cea @alexk-ede from https://github.com/voxel51/fiftyone/pull/2016

**Comment by karsil** [comment]
Fix #2114
