### ISSUE TITLE
[BUG] missing embeddings when trying to load embeddings directly per sample

### ISSUE THREAD

**Issue by eladrich** [voxel51/fiftyone#2130]
### System information

-   **OS Platform and Distribution - Linux Ubuntu 16.04**:
-   **FiftyOne installed from pip**:
-   **FiftyOne version - v0.16.5**:
-   **Python version - 3.9.5**:

### Commands to reproduce

```python
for find,path in paths:
    dataset[path]['embedding'] = np.random.randn(512) # originally with real vectors, but has same effect
results = fob.compute_visualization(dataset,embeddings='embedding',brain_key='data_vis')
```

### Describe the problem

When trying to load existing embeddings into a dataset, the embeddings seem to be loaded correctly, but when I try to compute a visualization based on these embeddings I get the following warning
"Using zeros for X missing embeddings", where X is the my dataset's length, so it looks like none of the embeddings were parsed correctly.

I assumed that the option of using the embeddings parameter of `fob.compute_visualization` as "the name of a dataset field containing the embeddings to use" means an embedding field per sample. If not, what's the right way to use it?

### Code to reproduce issue

Above

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by eladrich** [comment]
A related question, is there a tutorial on using custom models as a `fiftyone.core.models.Model`?

**Comment by brimoor** [comment]
Hi @eladrich, you need to include `sample.save()` in order to persist edits to samples:

```py
for find,path in paths:
    sample = dataset[path]
    sample['embedding'] = np.random.randn(512)
    sample.save()
```

Here's some relevant docs on the topic: https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#editing-sample-fields

**Comment by brimoor** [comment]
> A related question, is there a tutorial on using a custom PyTorch model as a `fiftyone.core.models.Model`?

Answered this one over here: https://github.com/voxel51/fiftyone/issues/2134
