### ISSUE TITLE
[FR] Change the index and names of classes in .txt and .yaml files

### ISSUE THREAD

**Issue by Mahmood-Hussain** [voxel51/fiftyone#2133]
### Motivation

-   What is the use case for this feature?
When trained Yolo(x) models on a different dataset and when we want to test those on another dataset but that dataset happens to have different class indices as compared to a dataset on which method was trained it would be useful to have a feature in conversion tool to modify the class indexes and class names. 

-   Why is this use case valuable to support for FiftyOne users in general?
It would save a lot of time and I think it would be easy to implement.

-   Why is this use case valuable to support for your project(s) or
    organization?
For example, I converted PascalVOC format to yolov5 format using this library but I couldn't alter the classes indexes and class names which would have been useful for my case. 

-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)
I am not sure even if it already exists within FiftyOne but I was not able to find it in either documentation or issues of this tool

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

here is an example in the training set I have the following labels in this sequence
```
- Car
- Person
- Motorcycle
- Bus
- Bicycle
```
but in the testing set, I have
```
- person
- bus
- car
- motorbike
- bicycle
```
I would like the FifityOne conversion feature to have the ability to unify classes and their indexes across both training and the testing dataset.

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [x] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hi @Mahmood-Hussain 👋 you can control the ordering of the classes in the exported YOLO files by passing the `classes` argument to `export()`, as demonstrated (and required, when exporting multiple splits) here:

https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#yolov5dataset
