### ISSUE TITLE
[BUG] View bar stops responding after session refresh

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2142]
On `fiftyone==0.17.2`, the view bar stops responding after the following sequence of operations are done via copy + paste (not run in a script):
- Launch App
- Load view via `session.view = ...`
- Refresh session

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

session = fo.launch_app(dataset)

# Do this manually, after the App loads
session.view = dataset.limit(10)

# After this, view bar stops responding
session.refresh()
```

**Comment by benjaminpkane** [comment]
Is this still an issue? I cannot reproduce.

**Comment by brimoor** [comment]
Yes this is still an issue. I watched @manivoxel51 experience this issue on a recent screen share too.

**Comment by brimoor** [comment]
I am no longer observing this on `develop`.
