### ISSUE TITLE
[FR] Store and visualize custom field-level information

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2163]
Similar to `dataset.info` it would be useful to be able to store some form of `dataset.field_name.info` that can contain a dictionary (or other structure) of any arbitrary information that the user may be interested in keeping in FiftyOne that corresponds to the same field of all samples in a dataset. 

It is important for this to be visualizable in the App as well.

Some example use cases are if you are training models, you will end up with multiple label fields containing model predictions. It would be useful to have a text description that users can see in the App to know what the goal/process of each training run was.

Similarly, when integrating with an experiment tracker like weights and biases, it is useful to store a link to the corresponding WandB run in FiftyOne, but the only way to be able to visualize a clickable link in the App is to duplicate it into a new field in every sample.

**Comment by brimoor** [comment]
This can be achieved by adding (say) `description` and `info` fields to [SampleFieldDocument](https://github.com/voxel51/fiftyone/blob/c5c3269c0bc000c02848f071554089f1d79569ae/fiftyone/core/odm/dataset.py#L139).

Here's how this could work through the SDK:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

schema = dataset.get_field_schema()
field = schema["ground_truth"]
print(field.description)

field.description = "Updated description"
field.save()

new_dataset = fo.Dataset()

new_dataset.add_sample_field(
    "ground_truth",
    fo.EmbeddedDocumentField,
    embedded_doc_type=fo.Detections,
    description="Annotations from project XXXX",
)
```
