### ISSUE TITLE
[FR] Add horizontal scroll bar to JSON viewer

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2167]
When a field has a value that is many characters long, the JSON viewer becomes unusable. It would be useful to have a scroll bar in the JSON viewer.

```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart", max_samples=1).clone()
sample = dataset.first()
sample["new_field"] = "51"*300
sample.save()

session = fo.launch_app(dataset)
```

![image](https://user-images.githubusercontent.com/21222883/195948261-29b4604d-8325-425f-a784-544c46401d15.png)

**Comment by ShawnOakley** [comment]
Cross-posting question here:

Do we want a scroll-bar or do we want the overflow to wrap?

See attached image for example of a wrap in the filepath field:

<img width="917" alt="Screen Shot 2022-12-19 at 3 29 44 PM" src="https://user-images.githubusercontent.com/1494369/208516114-1f4344b7-c342-4c01-b4ed-ab2bb1f7b60c.png">

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/pull/2677
