### ISSUE TITLE
[DOCUMENTATION] Add a guide mapping common pandas dataframe operations to FiftyOne view expressions

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2168]
Pandas provides a lot of similar capabilities to filtering and slicing dataframes that FiftyOne provides to create views of datasets. For new users that are familiar with pandas, it would be useful to have a chart mapping pandas operations to the matching FiftyOne operations.

**Comment by NeoKish** [comment]
@ehofesmann, was interested in this. Would like to contribute if it is open to new contributors.

**Comment by brimoor** [comment]
https://docs.voxel51.com/tutorials/pandas_comparison.html
https://docs.voxel51.com/cheat_sheets/pandas_vs_fiftyone.html
