### ISSUE TITLE
[DOCUMENTATION] How to have a developer installation in windows ? 

### ISSUE THREAD

**Issue by syedjafer** [voxel51/fiftyone#2184]
I would like to contribute to voxel51, but not sure about the process of having a developer mode of installation . Can you please provide instructions to do the same. 

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or
another member of your organization be willing to contribute a fix for this
documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently.
-   [ ] Yes. I would be willing to contribute a document fix with guidance from
        the FiftyOne community.
-   [x] No. I cannot contribute a documentation fix at this time.

**Comment by brimoor** [comment]
Here's the instructions! https://github.com/voxel51/fiftyone#contributing-to-fiftyone

**Comment by brimoor** [comment]
Ah I see now that you're asking specifically about Windows; you'll basically just need to:
- Run the install script: https://github.com/voxel51/fiftyone/blob/develop/install.bash
- Install MongoDB yourself (install script won't do it automatically on Windows)
- Configure your MongoDB connection: https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-a-mongodb-connection
