### ISSUE TITLE
Databricks notebook visualization is no longer working

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2197]
_Originally posted by @jpkoponen in https://github.com/voxel51/fiftyone/issues/1343#issuecomment-1292000330_

I think this issue should be re-opened. Apparently there has been some refactoring after merging the branch and Databricks integration doesn't work anymore. One clear issue is that in [`fiftyone/core/session/notebooks.py`](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/session/notebooks.py#L52), the function for displaying Databricks has been omitted, causing the following KeyError:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<command-3730664978028155> in <cell line: 1>()
----> 1 fo.launch_app()

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in launch_app(dataset, view, port, address, remote, desktop, height, auto, config)
    154     close_app()
    155 
--> 156     _session = Session(
    157         dataset=dataset,
    158         view=view,

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in __init__(self, dataset, view, plots, port, address, remote, desktop, height, auto, config)
    351 
    352         if self.auto and focx.is_notebook_context():
--> 353             self.show(height=config.notebook_height)
    354 
    355         if self.remote:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in wrapper(session, *args, **kwargs)
    208             if auto_show and session.auto and focx.is_notebook_context():
    209                 session.freeze()
--> 210             result = func(session, *args, **kwargs)
    211             session._client.send_event(StateUpdate(state=session._state))
    212             if auto_show and session.auto and focx.is_notebook_context():

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in show(self, height)
    888         )
    889 
--> 890         fosn.display(self._client, self._notebook_cells[uuid])
    891 
    892     def no_show(self) -> fou.SetAttributes:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/notebooks.py in display(client, cell, reactivate)
     54         focx._IPYTHON: display_ipython,
     55     }
---> 56     fn = funcs[focx._get_context()]
     57     fn(client, cell, reactivate)
     58 

KeyError: 'DATABRICKS'

```

I tried to fix the issue by re-introducing [`_display_databricks()`](https://github.com/voxel51/fiftyone/pull/1343/files#diff-20487b959e9116a305a132d18998a4341410897edc5695d53d3f7e0580f911bdR1129) from the branch and using it in [`display()`](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/session/notebooks.py#L48). I got no errors in Notebook but there was an empty page in place of the FiftyOne UI. There were also some 404 errors in the browser Javascript console. I'm not sure if it is due to some mismatch in the FiftyOne front-end paths or connectivity issues on our Databricks side. That's where I stopped exploring because I don't have strong web dev skills and it would take too much time.

Hopefully, these findings could help someone with more expertise and time to get the Databricks integration to work.

**Comment by paultreadel** [comment]
I found [v0.15.1](https://github.com/voxel51/fiftyone/releases/tag/v0.15.1) the last working release that supports Databricks. 

In addition I looked into fixing myself but couldn't understand some of the refactoring and got stuck.  What I did discover is that these [functions](https://github.com/twsl/fiftyone/blob/513ce64aae4d119b6dfa34ff07b990df194bb057/fiftyone/core/session.py#L1129-L1183) did not get migrated into the [notebooks.py](fiftyone/core/session/notebooks.py) when the original [session.py](https://github.com/twsl/fiftyone/blob/513ce64aae4d119b6dfa34ff07b990df194bb057/fiftyone/core/session.py) was refactored into multiple smaller elements in the now [session module](https://github.com/voxel51/fiftyone/tree/develop/fiftyone/core/session).

I'm very interested in running in databricks but don't have the skills to correct the issue.  I can, however offer my services in any tests that may be required within databricks.  Let me know how I can help.
