### ISSUE TITLE
[BUG] Prevent password suggester from appearing in dataset selector

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2245]
Recently Chrome's password suggester has been popping up when I click into the dataset selector in the App 😞 

I am unsure if this started happening due to a browser update or if some metadata was changed on the component in FiftyOne, but can something be done to tell Chrome to stop doing this???

<img width="602" alt="Screen Shot 2022-11-04 at 10 10 56 PM" src="https://user-images.githubusercontent.com/25985824/200096848-305c75dc-0610-446b-bf6e-567436efe482.png">

**Comment by lanzhenw** [comment]
@brimoor I am using Chrome (Version 107.0.5304.110 (Official Build) (arm64)) and had the chrome password manager turned on for all settings. Cannot duplicate this bug. Could you provide more info about the environment?

<img width="534" alt="Screenshot 2022-11-16 at 11 24 21 AM" src="https://user-images.githubusercontent.com/17770824/202263226-b3930815-67ae-468d-963d-6390cb70610b.png">

**Comment by brimoor** [comment]
No longer seeing this.
