### ISSUE TITLE
[DOCUMENTATION] Environments page still mentions Teams is for early adopters

### ISSUE THREAD

**Issue by cupcakesprinkle3** [voxel51/fiftyone#2246]
### Description of proposal (what needs changing):

Content reads "[Contact us](https://voxel51.com/#teams-form) about becoming an early adopter of FiftyOne Teams, an open source-compatible enterprise deployment of FiftyOne with multiuser collaboration features, native cloud dataset support, and much more!"

Content should be something along the lines of: "[Contact us](https://voxel51.com/#teams-form) about FiftyOne Teams, an open source-compatible enterprise deployment of FiftyOne that adds collaborative features built specifically for teams, including cloud-backed media, dataset permissions, versioning, sharing, and more."

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or
another member of your organization be willing to contribute a fix for this
documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently.
-   [X] Yes. I would be willing to contribute a document fix with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute a documentation fix at this time.

**Comment by brimoor** [comment]
Good point! This was updated [here](https://github.com/voxel51/fiftyone/commit/098aec949e27ade6ba7344ba599e04d75a6a215f) and will be live when we release Monday morning
