### ISSUE TITLE
[DOCUMENTATION] [QUESTION] Exporting fiftyone dataset as fiftyone dataset

### ISSUE THREAD

**Issue by senovr** [voxel51/fiftyone#2260]
Hi, 
Let's assume the following scenario:
I started to work on unlabeled dataset on one machine and applied some calculations on the top of it (such as- calculate image uniqueness, applying predictions from pre-trained model).
What is the best way to export existing fiftyone dataset not in yolo/coco/voc format, but in original fiftyone format?

The goal is to keep all of the metadata that has been generated (such as predictions confidence, for example) and continue to visualize/analyze the results on another laptop/desktop.

I was unable to find such kind of how-to in tutorials.

**Comment by brimoor** [comment]
You're looking for [FiftyOneDataset format](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#fiftyonedataset) 🎉 

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

dataset.export(
    export="/tmp/test",
    dataset_type=fo.types.FiftyOneDataset,
)

dataset2 = fo.Dataset.from_dir(
    dataset_dir="/tmp/test",
    dataset_type=fo.types.FiftyOneDataset,
)
```
