### ISSUE TITLE
[BUG] Only include supported eval keys in App's patches UI

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2275]
The patches menu in the App currently includes all evaluation keys, but only evaluations on `Detections` and `Polylines` support patch views. Evaluation keys for unsupported task types should not appear in the dropdown.

```py
import random

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("cifar10", split="test", max_samples=1000, shuffle=True)
classes = dataset.distinct("ground_truth.label")

def jitter(val):
    if random.random() < 0.10:
        return random.choice(classes)

    return val

predictions = [
    fo.Classification(label=jitter(gt.label), confidence=random.random())
    for gt in dataset.values("ground_truth")
]

dataset.set_values("predictions", predictions)
dataset.evaluate_classifications("predictions", gt_field="ground_truth", eval_key="eval_class")

dataset.to_evaluation_patches("eval_class")
# ValueError: Invalid label field type <class 'fiftyone.core.labels.Classification'>. Extracting patches is only supported for the following types: (<class 'fiftyone.core.labels.Detections'>, <class 'fiftyone.core.labels.Polylines'>)

# Here's how to deduce whether the evaluation has a supported type
info = dataset.get_evaluation_info("eval_class")
label_type = dataset._get_label_field_type(info.config.gt_field)
is_supported = label_type in (fo.Detections, fo.Polylines)

session = fo.launch_app(dataset)
```

<img width="572" alt="Screen Shot 2022-11-09 at 3 16 42 PM" src="https://user-images.githubusercontent.com/25985824/200933401-1137ec1e-28ca-47e0-8c50-c9e0f992e4ba.png">

**Comment by jwertherUM** [comment]
Hey is this still up for grabs? I'm pretty new to open source but I'd love to give it a shot

**Comment by brimoor** [comment]
Absolutely!

**Comment by jwertherUM** [comment]
Hi @lanzhenw I'm still trying to work through this, any chance you could give me another day or two?

**Comment by jwertherUM** [comment]
I apologize I had to table it for a while

**Comment by jwertherUM** [comment]
@brimoor I see that the dropdown is populated by the evaluationKeys constant in patcher.tsx on line 69. It maps fos.dataset (an Evaluation Typescript object containing gt_field) to its key. I know on the backend you can use _get_label_field_type() on the gt_field as shown to determine type, but is there any way to replicate this behavior on the frontend with a utility function so this process can be completed in the patcher file?

**Comment by jwertherUM** [comment]
Or should I be manipulating the backend so only the appropriate keys are sent to the frontend in the first place?

**Comment by brimoor** [comment]
cc @benjaminpkane who is the right person to answer this from an App perspective.

You'll need to get access to the `info.config` for the evaluation run so you can retrieve the names of the label fields involved; then you'll need to consult the dataset's schema to grab the types of the fields.

Or maybe this should be refactored to server-side logic. Ben will have thoughts!

**Comment by jwertherUM** [comment]
Sounds good, looking forward to hearing your thoughts @benjaminpkane . And if there's an internal API route to solve this that I'm missing please let me know, I'm still pretty new to the codebase

**Comment by jwertherUM** [comment]
I just made a PR addressing this issue. This is my first contribution to the repo, so please feel free to make edits or point out if I missed anything from the style guide. I believe the logic I used mirrors exactly what you laid out @brimoor, but I'm not sure if there's a testing approach you'd like me to take that I'm missing. @lanzhenw I know you expressed some interest in this issue, so if you have any time to check out the PR as well let me know. Thanks!
