### ISSUE TITLE
[BUG] Improve None-handling when filtering list fields in the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2277]
Here I'm creating a `ListField` field in my dataset for which some samples have `[]` or `None` values:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset.untag_samples("validation")

for tag in "abc":
    dataset.take(25).tag_samples(tag)

dataset.clone_sample_field("tags", "list_field")

session = fo.launch_app(dataset)
```

On initial load, the filter widget exposes counts of `None` values:

<img width="378" alt="Screen Shot 2022-11-09 at 5 09 34 PM" src="https://user-images.githubusercontent.com/25985824/200952899-1beeabae-a9e6-4b8b-ad4c-ebbb588e0890.png">

which makes me think I can filter based on the `None` value.

However, the results are nonsensical:

1. Here I've taken the bait and selected `None`, but instead of (presumably) seeing all samples with no values in `list_field`, I see nothing:
<img width="412" alt="Screen Shot 2022-11-09 at 5 09 29 PM" src="https://user-images.githubusercontent.com/25985824/200952995-3d82a604-3209-4c60-984f-4f4a70e475c9.png">

2. Here I've filtered by another value and the `None` count is negative:
<img width="341" alt="Screen Shot 2022-11-09 at 5 09 21 PM" src="https://user-images.githubusercontent.com/25985824/200952997-6e61257d-382e-48b5-af79-f49894a6a55d.png">

`None` values are handled separately from non-None in other contexts. For example with this view:

```py
from fiftyone import ViewField as F

# Some confidences are numbers, some are None
some_nones = (F("confidence") < 0.5).if_else(None, F("confidence"))
view = dataset.set_field("predictions.detections.confidence", some_nones)

session.view = view
```

the widget lets you independently select (a) what valid data to include/exclude and then (b) whether to include or exclude `None`-valued data:

<img width="282" alt="Screen Shot 2022-11-09 at 5 18 09 PM" src="https://user-images.githubusercontent.com/25985824/200954187-d7735f27-f2c6-4bce-8bd2-28bac38956de.png">

List fields need similar consideration.

**Comment by wesley7502** [comment]
Hello, I want to try looking into this issue! I'm an University of Michigan Student and I'm new to contributing to open-source code.

**Comment by benjaminpkane** [comment]
Hi @wesley7502! Great! I was just doing some cleaning where this code is. If you work from the branch `bugfix/none-counts` it might be easier to read the code.

Here is a [link](https://github.com/voxel51/fiftyone/blob/3b183fea551286ab81c8a568bda92f5084ba3f8f/app/packages/state/src/recoil/aggregations.ts#L84) to the Recoil selector that is incorrect. It produces `None` (or `null`) counts. If you're able to set up your dev environment, you should be able to debug and fix the selector with just the code above.

The instructions for setting up your environment for App development can be found [here](https://github.com/voxel51/fiftyone/tree/bugfix/none-counts/app). Cheers

**Comment by wesley7502** [comment]
If I am developing on just the app, would I still need follow the developer installation instructions on fiftyone?

eg: run `bash install.bash -d`

Or would the instructions you linked above be good enough?

**Comment by benjaminpkane** [comment]
`bash install.bash` should be enough just so you have the python package installed from source and can load datasets and run the server

**Comment by wesley7502** [comment]
When I try to run `yarn dev`, I got this issue

`Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)`

I'm not sure what's causing this as I ran `yarn install` beforehand. For context, I'm working on an ubuntu AWS EC2 Instance.

**Comment by brimoor** [comment]
To clarify, we decided offline that what we should do to resolve this issue is to:
1. Remove the `None` item that is currently being added for list fields to track the number of samples with empty lists
2. Add support for negative matches more holistically as described in https://github.com/voxel51/fiftyone/issues/2405

**Comment by brimoor** [comment]
Here's a dataset to test with:

```py
import random

import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")

for tag in "abc":
    dataset.take(100).tag_samples(tag)

dataset.clone_sample_field("tags", "list_field")

dataset.set_values("bool_field", [u > 0.5 for u in dataset.values("uniqueness")])
dataset.set_values("str_field", [random.choice("abc") for _ in range(len(dataset))])

some_nones = lambda field: (F(field) < 0.5).if_else(None, F(field))
view = (
    dataset
    .set_field("predictions.detections.confidence", some_nones("confidence"))
    .set_field("uniqueness", some_nones("uniqueness"))
)
view.save()

session = fo.launch_app(dataset)
```
