### ISSUE TITLE
[BUG] Use same default expansion logic when sidebar groups are defined

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2284]
As of `fiftyone==0.18`, the sidebar has some nice default logic, such as automatically collapsing the `OTHER` group for the dataset below, since it contains all unsupported field types:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

dataset.set_values("dict_field", [{}] * len(dataset))

dataset.add_sample_field("list_field", fo.ListField)
dataset.set_values("list_field", dataset.values("tags"))

session = fo.launch_app(dataset)
```

Or collapsing the sample/label tags sections by default in fast mode.

However, this default expansion logic only applies when the dataset does not have an `app_config` explicitly defined. Once an app config is defined, the collapsed-by-default logic no longer works.

To see this, make a trivial edit to the sidebar groups in the App and then refresh the page.

```py
# Edit sidebar groups in the App

dataset.reload()
print(dataset.app_config)
```

```
<DatasetAppConfig: {
    'media_fields': ['filepath'],
    'grid_media_field': 'filepath',
    'modal_media_field': 'filepath',
    'sidebar_mode': None,
    'sidebar_groups': [
        <SidebarGroupDocument: {'name': 'tags', 'paths': [], 'expanded': None}>,
        <SidebarGroupDocument: {'name': 'label tags', 'paths': [], 'expanded': None}>,
        <SidebarGroupDocument: {
            'name': 'metadata',
            'paths': [
                'metadata.size_bytes',
                'metadata.mime_type',
                'metadata.width',
                'metadata.height',
                'metadata.num_channels',
            ],
            'expanded': None,
        }>,
        <SidebarGroupDocument: {'name': 'labels', 'paths': ['predictions', 'ground_truth'], 'expanded': None}>,
        <SidebarGroupDocument: {'name': 'primitives', 'paths': ['id', 'uniqueness', 'filepath'], 'expanded': None}>,
        <SidebarGroupDocument: {'name': 'other', 'paths': ['dict_field', 'list_field'], 'expanded': None}>,
    ],
    'plugins': {},
}>
```

In the above `sidebar_groups`, all `expanded` states are `None`, so the default logic should be applied to determine whether they are collapsed or not.

**Comment by lanzhenw** [comment]
Looks like `dataset.appConfig` is not in sync with the backend setting. 
![Screenshot 2022-12-06 at 11 59 23 PM](https://user-images.githubusercontent.com/17770824/206100379-d5054a62-7b91-49e9-95fe-3fc2788d4621.png)
![Screenshot 2022-12-06 at 11 59 14 PM](https://user-images.githubusercontent.com/17770824/206100382-7f7bf6ca-49f1-4ffa-b4df-4b2bd4db3407.png)

**Comment by brimoor** [comment]
There is some logic in-place that will populate default values clientside using the `dataset.app_config` from the server for defaults. May need to discuss offline to explain that.
