### ISSUE TITLE
[BUG] Remove excluded media fields from App selector 

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2286]
The App supports configuring [multiple media fields](https://voxel51.com/docs/fiftyone/user_guide/app.html#multiple-media-fields). However, the user can exclude non-default fields from their schema in various ways.

The App currently includes excluded media fields in the `Media field` selector under the settings menu. However, it would be more friendly if it would omit entries from that list that have been excluded from the current view's schema:

```py
import fiftyone as fo
import fiftyone.utils.image as foui
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

foui.transform_images(
    dataset,
    size=(-1, 64),
    output_field="thumbnail_path",
    output_dir="/tmp/thumbnails",
)

dataset.app_config.media_fields = ["filepath", "thumbnail_path"]
dataset.app_config.grid_media_field = "thumbnail_path"
dataset.save()

session = fo.launch_app(dataset)

# Both of these views try and fail to access thumbnail_path
session.view = dataset.select_fields()
session.view = dataset.to_patches("ground_truth")
```

<img width="920" alt="Screen Shot 2022-11-10 at 1 11 50 AM" src="https://user-images.githubusercontent.com/25985824/201017437-9bdbe67e-7a7c-4563-a3c0-1c9ed2d21f83.png">

**Comment by lanzhenw** [comment]
@brimoor Took a look at the issue, it looks like recoil is not getting the updated `mediaFields` from appConfig after the view changes. 

```
const datasetAppConfig = selector<State.DatasetAppConfig>({
  key: "datasetAppConfig",
  get: ({ get }) => get(dataset).appConfig,
});
```

I can overwrite the default mediaFields based on the view's field. Are `to-patches` and `select_fields` the only methods that can cause the view to exclude default media fields? 
Is it okay to assume the conditions are when the view has `select_field` or `field_names` in `kwargs` ?

These are the console of the view for the two bug cases:
<img width="417" alt="Screen Shot 2022-11-14 at 1 10 37 AM" src="https://user-images.githubusercontent.com/17770824/201599840-573ec6d3-5821-4c2a-a0d2-522e61b50127.png">
<img width="312" alt="Screen Shot 2022-11-14 at 9 02 07 AM" src="https://user-images.githubusercontent.com/17770824/201693195-218b85bd-85f4-4c66-a337-192c791038f8.png">

**Comment by lanzhenw** [comment]
Ben suggested including a filter that removes media fields that don’t exist through the field selector.

**Comment by brimoor** [comment]
There's one more aspect of this issue that #2303 doesn't address: if `app_config. grid_media_field` or `app_config.modal_media_field` are excluded from the current view, then the App should default to `filepath`, which is a default field that can never be deselected.

The reason this is important is that, in `develop` currently, when I run the code below, none of the media loads in the grid because it is still trying to use `thumbnail_path`, but the media fields selector also does not appear under the settings menu, because it was filtered down to one option (`filepath`). So I have no way to see valid media now...

```py
import fiftyone as fo
import fiftyone.utils.image as foui
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

foui.transform_images(
    dataset,
    size=(-1, 64),
    output_field="thumbnail_path",
    output_dir="/tmp/thumbnails",
)

dataset.app_config.media_fields = ["filepath", "thumbnail_path"]
dataset.app_config.grid_media_field = "thumbnail_path"
dataset.save()

view = dataset.to_patches("ground_truth")

session = fo.launch_app(view)
```

**Comment by lanzhenw** [comment]
if `grid_media_field` or `modal_media_field` is set to a field that’s not in the current view’s schema, the App needs to override to filepath (which must always exist), so that the grid always default render on the right path. 
PR #2378 fixes this issue.
