### ISSUE TITLE
[FR] Support for using lmdb format files in fiftyone

### ISSUE THREAD

**Issue by swatideshpande2228** [voxel51/fiftyone#2293]
I am trying to use fiftyone with a dataset in lmdb format (.mdb) and I want to know which class I should extend to add support for it?
This database is binary and does not have individual file path entries.

**Comment by brimoor** [comment]
Hi @swatideshpande2228 👋 

FiftyOne is fundamentally designed to have all data stored in MongoDB, which filepaths on disk to media files. It would be a ton of work to write a `Dataset` subclass that instead pulls data from an lmdb, as the public interface of the `SampleCollection` class is quite extensive.

You can certainly, however, write an importer that will load your data into FiftyOne. Here's some advice on doing that: https://github.com/voxel51/fiftyone/issues/1636#issuecomment-1064303172

**Comment by swatideshpande2228** [comment]
Thanks

**Comment by swheaton** [comment]
closing as won't do, it should be done with a custom importer
