### ISSUE TITLE
[BUG] Module 'fiftyone' has no attribute 'BooleanField' on mac m1

### ISSUE THREAD

**Issue by lanzhenw** [voxel51/fiftyone#2305]
### Instructions

When I run the fiftyone in development mode, using `python fiftyone/server/main.py` has an **AttributeError: module 'fiftyone' has no attribute 'BooleanField'**.

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): max OS m1
-   **Python version** (`python --version`): 3.9 | 3.10
-   **FiftyOne version** (`fiftyone --version`): 18
-   **FiftyOne installed from** (pip or source): source

### Commands to reproduce

follow the instruction here:
https://github.com/voxel51/fiftyone/tree/develop/app

run the virtual env (tried python 3.9 and python 3.10)
```
cd app
yarn install
yarn dev
-------
cd ..
python fiftyone/server/main.py
```

### Describe the problem

Cannot run the fiftyone backend from source on mac m1 machine. I run the same process on an Mac OS intel machine and had no issues. 

### Other info/logs

```
(virtual51) [develop][~/voxel/fiftyone]$ python fiftyone/server/main.py
Traceback (most recent call last):
  File "/Users/lanny/voxel/fiftyone/fiftyone/server/main.py", line 23, in <module>
    from fiftyone.server.app import app
  File "/Users/lanny/voxel/fiftyone/fiftyone/server/app.py", line 29, in <module>
    from fiftyone.server.mutation import Mutation
  File "/Users/lanny/voxel/fiftyone/fiftyone/server/mutation.py", line 22, in <module>
    from fiftyone.server.events import get_state, dispatch_event
  File "/Users/lanny/voxel/fiftyone/fiftyone/server/events.py", line 30, in <module>
    from fiftyone.server.query import serialize_dataset
  File "/Users/lanny/voxel/fiftyone/fiftyone/server/query.py", line 30, in <module>
    import fiftyone.server.aggregate as fosa
  File "/Users/lanny/voxel/fiftyone/fiftyone/server/aggregate.py", line 56, in <module>
    COUNT_VALUES_TYPES = {fo.BooleanField, fo.IntField, fo.StringField}
AttributeError: module 'fiftyone' has no attribute 'BooleanField'
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [?] `Server`: FiftyOne server issue

**Comment by lanzhenw** [comment]
Tried python 3.9 and python 3.10 in virtual env setting. 
Run `pip install -e .`
Add fiftyone to $PYTHONPATH (eg `export PYTHONPATH=$PYTHONPATH:~/Dev/voxel51/fiftyone)
The issue persists.

**Comment by lanzhenw** [comment]
Did the same thing on a Mac OS intel chip laptop, and it works.

**Comment by brimoor** [comment]
This seems like a MongoDB connection issue. We can take it offline.

**Comment by lanzhenw** [comment]
Mac OS M1 should use MongoDB 6.0, while I was using MongoDB Community@4.4 installed through brew

**Fix to this issue:**
1. [Uninstall MongoDB completely ](https://www.mongodb.com/basics/uninstall-mongodb)
2. Change this setting from `SCRATCH_MONGODB_INSTALL` from `false` to `true`
3. Check the `~/.fiftyone/config.json` file. If you see the`"database_admin": false,`, remove it or turn it to `true` 
4. Install and run the bash command to build again

**Comment by sashankaryal** [comment]
For me it was setting `PYTHONPATH`. See https://github.com/voxel51/fiftyone/issues/2154#issuecomment-1277788070
