### ISSUE TITLE
[FR] Never show expanded list for ID fields

### ISSUE THREAD

**Issue by oguz-hanoglu** [voxel51/fiftyone#2308]
### Proposal Summary

Ids are listed when they are few. They do not convey much information while holding a large space. I propose "never show expanded list" feature. Ids can always be shown in the same manner (with a drop down menu, as in the case for large sample counts).

![image (2)](https://user-images.githubusercontent.com/99868596/201936331-fb17de88-889c-4f5d-a716-d71ea457f1fa.png)

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [ ] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

**Comment by brimoor** [comment]
I agree!
