### ISSUE TITLE
[BUG] Lasso tool not syncing selected samples into app

### ISSUE THREAD

**Issue by TushnaE** [voxel51/fiftyone#2319]
### System information

-   **OS Platform and Distribution**: Ubuntu 20.04.2 LTS
-   **Python version**: Python 3.8.10
-   **FiftyOne version**: FiftyOne v0.17.2
-   **FiftyOne installed from**: pip

Versioning:
- fiftyone                      0.17.2              
- fiftyone-brain                0.9.2               
- fiftyone-db                   0.3.0 
- ipywidgets                    7.7.2
- ipykernel                     6.15.2
- notebook                      6.5.2
- plotly                        5.11.0

### Describe the problem

I have created 2d embeddings for my dataset using `fob.compute_visualization()` and am able to use `.visualize()` to render the scatterplot inline within my jupyter notebook. I'm even able to utilize the lasso tool to select object clusters. Separately, I'm able to render the FOB app within my notebook, and navigate to filter by different ground truth labels. But using the lasso tool to populate the app with the particular samples that were lassoed does not work for me. I have followed seemingly every instruction but to no avail. I do know that the lasso selection portion is working because I'm able to print the ids of the selected samples using `plot.selected_ids`. I even tried taking these sample ids and passing it into the session as a "view", like so: `view = dataset.select(plot.selected_ids)` and `session = fo.launch_app(view=view, address="0.0.0.0")` but that didn't work either (session still renders entire original dataset). FWIW, this problem still persists when using the example code to lasso points from the mnist scatterplot and view those samples.

### Code to reproduce issue

Note: This problem persists for me even when using the sample mnist code (and malaria .ipynb), so that can also be used to reproduce.

```
results_v5_image_embeddings = fob.compute_visualization(
    dataset,
    num_dims=2,
    method="umap",
    brain_key="v5_image_embeddings",
    verbose=True,
    seed=51,
)

plot = results_v5_image_embeddings.visualize(labels="source")
session.plots.attach(plot)
plot.show(height=800)

## this is where I would use the lasso tool to select
view = dataset.select(plot.selected_ids)

session = fo.launch_app(view=view, address="0.0.0.0")

## I also experience this issue when using `launch_app` first, and then refreshing the app to register any update
```
### Other info/logs

I am running this jupyter notebook on a remote machine (no docker container), and viewing the app both inline as well as in browser locally. The images being rendering in app are all located on the same remote machine as the one running the notebook. I have specified the jupyter address in config to be "0.0.0.0" (as specified in the FOB instructions). And I'm running the notebook using the following command: `jupyter notebook --no-browser --port=8888 /home/my_user/Voxel51_Experimentation.ipynb` along with the appropriate port forwarding commands (one for the notebook and one for the app).

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [X] No. I cannot contribute a bug fix at this time

**Comment by TushnaE** [comment]
Hi, thanks for your reply! So I just upgraded to `fiftyone==0.18` and I have the versions below:
```
fiftyone==0.18.0
fiftyone-brain==0.9.2
fiftyone-db==0.4.0
ipywidgets==7.5.0
plotly==5.11.0
```

But whenever I upgrade to version 18, I have this problem in my jupyter notebook where I am no longer able to view plots. This is the error that comes along with it:
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'FigureModel' from module 'jupyterlab-plotly'
Error: Script error for "jupyterlab-plotly"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (http://localhost:8090/static/components/requirejs/require.js?v=f0cc8bbb2fcef87fc194fecbb632fcfa:168:17)
    at HTMLScriptElement.onScriptError (http://localhost:8090/static/components/requirejs/require.js?v=f0cc8bbb2fcef87fc194fecbb632fcfa:1738:36)
```

I tried `! jupyter --v` to see what version of jupyterlab-plotly I could have, and it actually tells me `jupyter lab      : not installed
`. Just trying everything at this point but I tried specifically installing jupyterlab and it caused some issues loading the zoo dataset so I uninstalled and that's where I'm at right now. So I have all the versions that you outlined, but now the scatterplots themselves aren't being rendered in my notebook. Any ideas?

**Comment by brimoor** [comment]
Have you tried restarting your notebook?

Also, are you sure that you installed jupyter lab in your virtual environment? Sometimes it is possible to be running in a Python virtual environment without jupyter lab installed but the `jupyter lab` command works and secretly starts a Python session outside of your virtual environment that doesn't have the right packages available.

**Comment by TushnaE** [comment]
Update! So I did the following installs that plotly suggests `! pip install "jupyterlab>=3" "ipywidgets>=7.6"`
and this code to generate a basic plot works, but the plot that's generated from results.visualize still won't render

```
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()
```

**Comment by TushnaE** [comment]
Hm so I have restarted the notebook^ and when I do a `!pip list` I do see jupyter lab now (just installed it w/ the command above). Is that sufficient to check whether it was installed in my virtual env?

**Comment by brimoor** [comment]
Apologies for the delay, updating the following package versions should resolve this issue:

```shell
# If using Jupyter notebooks
pip install "notebook>=6" "ipywidgets>=8,<9"
  
# If using JupyterLab
pip install "jupyterlab>=4" "ipywidgets>=8,<9"
```
