### ISSUE TITLE
[BUG] Page not loading

### ISSUE THREAD

**Issue by Sa-Schmi** [voxel51/fiftyone#2326]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Windows 12
-   **Python version** (`python --version`): Python 3.9.12
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.18.0, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce
```
python -m venv venv

.\venv\Scripts\activate

pip install fiftyone

fiftyone app launch
```

### Describe the problem

When I try to open fiftyone with Firefox or Chrome, it does not work, as you can see in the screenshots below:

![grafik](https://user-images.githubusercontent.com/39338429/202731654-e19e4cc3-6663-4004-95ce-97708489d12b.png)
![grafik](https://user-images.githubusercontent.com/39338429/202731767-99b51f1a-4e06-4d32-8a66-6c5aad091192.png)

I'm pretty sure the problem is with my PC, but I thought I should post it anyway.
I already had to change the mime type in my registry (HKEY_CLASSES_ROOT\.js) from `text/plain` to `application/javascript`. But it did not solve the problem.

Fiftyone works with Jupyter and the desktop application, so I can still work with it.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @Sa-Schmi looks like an issue with SSE (Server Sent Events). Adding `polling` to the URL may fix things, as that enables the HTTP polling fallback.
```
http://localhost:5151/?polling
```

**Comment by Sa-Schmi** [comment]
Hi @benjaminpkane thank you very much, it really was that simple. 
Can you help me solve this problem, or should I just use `polling` all the time?

**Comment by benjaminpkane** [comment]
Hi @Sa-Schmi. Apologies. I recommend using polling. We will likely transition to polling only approach in the future

**Comment by Sa-Schmi** [comment]
Ok thank you for your help!
