### ISSUE TITLE
[BUG] (App development) React Spring error

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#2330]
An unhandled error from React Spring, which breaks some development modes, is being thrown by one or more components with an incorrect animation value.

```
Unhandled Runtime Error
Error: Cannot animate between AnimatedValue and AnimatedString, as the "to" prop suggests
````

**Comment by ShawnOakley** [comment]
Perhaps related: https://github.com/pmndrs/react-spring/issues/867#issuecomment-600304475
