### ISSUE TITLE
[?] A way to plug in my pytorch model in fiftyone?

### ISSUE THREAD

**Issue by Ayumu-J-S** [voxel51/fiftyone#2343]
Is there a way to load my PyTorch model (not from the model zoo) as [fiftyone.utils.torch.TorchImageModel](https://github.com/voxel51/fiftyone/blob/aa97933ba6f7454d2b428f7a7958adc0f5116d05/fiftyone/utils/torch.py#L197) and get the embeddings with that wrapped model to compute the uniqueness?

**Comment by brimoor** [comment]
Hi @Ayumu-J-S 👋 

Absolutely! Here's how you can load and use a custom Torch model via the `TorchImageModel` class:

```py
import os
import eta

import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.utils.torch as fout

labels_path = os.path.join(
    eta.constants.RESOURCES_DIR, "imagenet-labels-no-background.txt"
)

config = fout.TorchImageModelConfig(
    {
        "entrypoint_fcn": "torchvision.models.mobilenet.mobilenet_v2",
        "entrypoint_args": {"pretrained": True},
        "output_processor_cls": "fiftyone.utils.torch.ClassifierOutputProcessor",
        "labels_path": labels_path,
        "image_min_dim": 224,
        "image_max_dim": 2048,
        "image_mean": [0.485, 0.456, 0.406],
        "image_std": [0.229, 0.224, 0.225],
        "embeddings_layer": "<classifier.1",
    }
)
model = fout.TorchImageModel(config)

dataset = foz.load_zoo_dataset("quickstart")
embeddings = dataset.compute_embeddings(model)
```

Under the hood, the torch model is loaded via:

```
model = entrypoint_fcn(**entrypoint_args)
```

and the other parameters in the `config` allow you to specify any required preprocessing, post-processing, and, in the case of generating embeddings, the name of the layer to extract and use as embeddings.

**Comment by Ayumu-J-S** [comment]
Thank you for your quick reply. This seems like it is still using one of the torch vision pre-trained models. Is there a way to use a customized model (nn.module) that I created, which would have a unique CNN architecture trained with a unique dataset for extracting the embeddings? I was wondering if I could do this since I wanted to calculate the uniqueness from the distribution of the dataset that I am using.

**Comment by brimoor** [comment]
I used a torchvision model for illustrative purposes, but:

```
model = entrypoint_fcn(**entrypoint_args)
```

can be any `nn.module`. [This PR](https://github.com/voxel51/fiftyone/pull/2348) contains more documentation on this. Check it out!

**Comment by Ayumu-J-S** [comment]
Thank you for your reply. Sorry, this is such a back and forth, but I didn't get this very well.
From what I understand (and I also looked at the `TorchImageModelConfig`), the `entrypoint_fcn` has to be a string which specifies one of the models in `manifest_torch.json`, which if I am using something like PyTorch lightning, I am not able to use this.

How do I use my custom unique model implemented with nn.module (which has a unique architecture) that is not registered in `manifest_torch.json` but rather stored in a python file locally?

If this is not a functionality then that is fine, but I just wanted to know if that is possible.

**Comment by brimoor** [comment]
entrypoint_fcn can be any function. Like the name of a function in a module or package that you wrote. It just needs to return a nn.module.

**Comment by Ayumu-J-S** [comment]
Ah, I see. This does make sense and it seems to be working with my model. Thank you:)
