### ISSUE TITLE
[?] How to choose which labels are exported

### ISSUE THREAD

**Issue by WHBSmith** [voxel51/fiftyone#2345]
I have loaded a subset of the open images dataset. I've used the class filter and exported the dataset to a COCO format. So far so good, but the image labels still contain labels for other classes, how do I remove them? I'm sure this must be documented somewhere but I've spent half a day looking and I can't find what I'm after, any help appreciated.

**Comment by brimoor** [comment]
## Option 1: only import the desired labels in the first place

This is possible by providing the optional `only_matching=True` option to `load_zoo_dataset()`:

Relevant docs: https://voxel51.com/docs/fiftyone/user_guide/dataset_zoo/datasets.html#open-images-v6

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    max_samples=5,
    label_types=["detections"],
    classes=["Cat", "Dog"],
    only_matching=True,
    dataset_name=fo.get_default_dataset_name(),
)

print(dataset.count_values("detections.detections.label"))
# {'Cat': 2, 'Dog': 5}

dataset.export(
    export_dir="/tmp/coco",
    dataset_type=fo.types.COCODetectionDataset,
    label_field="detections",
)
```

## Option 2: load everything and filter before exporting

Relevant docs:
https://voxel51.com/docs/fiftyone/user_guide/using_views.html#filtering

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="validation",
    max_samples=5,
    label_types=["detections"],
    classes=["Cat", "Dog"],
    dataset_name=fo.get_default_dataset_name(),
)

view = dataset.filter_labels("detections", F("label").is_in(["Cat", "Dog"]))

print(dataset.count_values("detections.detections.label"))
# {'Human hand': 1, 'Human arm': 2, 'Cat': 2, 'Dog': 5, ...}

print(view.count_values("detections.detections.label"))
# {'Dog': 5, 'Cat': 2}

view.export(
    export_dir="/tmp/coco",
    dataset_type=fo.types.COCODetectionDataset,
    label_field="detections",
    overwrite=True,
)
```

**Comment by WHBSmith** [comment]
Thank you so much!!!
