### ISSUE TITLE
[BUG] [SOLVED] Error connection refused when launching the App

### ISSUE THREAD

**Issue by SauceCat** [voxel51/fiftyone#2350]
### Describe the problem

I've been using fiftyone for a long time. I always launch the app from jupyterlab because I can easily do some data processing before I send the data for visualization. :100: 
I tried to upgrade from `0.14.4` to `0.18.0`, but keep failing launch_app, always get **err_connection_refused**. Then I tried to downgrade to `0.15.1` (I found `starlette` was introduced since `0.16.0`, so I downgraded to the latest version before that) and it worked again. However, I don't want to give up using the latest version.

### Solution

After a few hours of struggle, upgrading all kinds of stuffs including jupyterlab, ipython, blablabla, it just didn't work. :crying_cat_face: 
Finally, it works like this!!! (Just don't want anyone waste the time that I did

```python
session = fo.launch_app(dataset, port=2221, auto=False, address="0.0.0.0")
```
The only change is to manually [set the App address](https://voxel51.com/docs/fiftyone/environments/index.html#restricting-app-address) to `0.0.0.0`.  Well, it's still weird, because I don't need to do this if I am staying with <=`0.15.1`. :thinking: Maybe somebody can tell me the reason behind.

**Comment by brimoor** [comment]
Hi @SauceCat 👋 

As per [the documentation](https://voxel51.com/docs/fiftyone/environments/index.html#restricting-app-address) that you linked, we made a change awhile back where the App will only accept connections from `localhost` by default:

> Using the default of localhost means the App can only be accessed from the local machine or a machine that was able to setup ssh port forwarding as described in the previous section.
>
> An alternative is to set the App address to "0.0.0.0" so that the App can be accessed from a remote host or from the local machine itself. Using "0.0.0.0" will bind the App to all available interfaces and will allow access to the App from any remote resource with access to your network.

This was done for security reasons, as it was deemed bad practice to allow connections from non-localhost machines by default.

**Comment by brimoor** [comment]
@benjaminpkane @findtopher would it make sense to change the default behavior here to reduce user pain? For example, can we default to `0.0.0.0` in jupyter environments?

https://github.com/voxel51/fiftyone/blob/9f7295a3a7db9d658b201f80540d13f66831b02d/fiftyone/core/session/session.py#L309-L313

**Comment by SauceCat** [comment]
@brimoor thanks for the explanation! Yep it sounds very similar to the scenario where we need to set ip as 0.0.0.0 if we want to access Jupyter started on a remote server.
