### ISSUE TITLE
[?] Is there any simple way to adopt custom metadata?

### ISSUE THREAD

**Issue by huangzehao** [voxel51/fiftyone#2351]
I write a custom LabeledImageSampleParser and custom ImageMetadata. However, the app does not show the newly added meta information.
![image](https://user-images.githubusercontent.com/13661914/204088762-440fcea3-7416-4f98-9a6e-ff55141186e2.png)
![image](https://user-images.githubusercontent.com/13661914/204088815-dafd067d-f931-4b9a-aee6-a35a75cf0775.png)

Is there any simple way to adopt custom metadata, and achieve the result like the following:
![image](https://user-images.githubusercontent.com/13661914/204088995-fc7708cb-756f-4b4e-9df7-9ba980e01262.png)

Thanks!

**Comment by huangzehao** [comment]
I add a new sample_field named custom_metadata to the dataset to show my custom metadata. Is there any way to overwrite the default metadata field?
![image](https://user-images.githubusercontent.com/13661914/204097198-0fadab4c-ff02-460f-b1e6-d76575f3252d.png)

**Comment by brimoor** [comment]
Hi @huangzehao 👋 

It is not recommend to store custom data in the `metadata` field of your datasets, as certain builtin methods (eg exporting in formats like COCO that require absolute pixel coordinates, not relative coordinates) will expect that they can find image dimensions in the `metadata` field, or, if this field is null, automatically populate it by calling `compute_metadata()`.

Instead, just modify your `LabeledImageSampleParser` to return your custom fields from the `get_label()` method. This method can return a dict of values:

```py

    def get_label(self):
        return {
            "task_id": task_id,
            "bad_id": bag_id,
            "ground_truth": fo.Detections(...),
            ...
        }
```

**Comment by brimoor** [comment]
Side note, as [per the docs](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/samples.html#using-sample-parsers), we recommend using dataset importers rather than sample parsers. The latter are more flexible.

<img width="658" alt="Screen Shot 2022-11-26 at 11 35 14 AM" src="https://user-images.githubusercontent.com/25985824/204099151-45dba300-b199-48a9-ad6c-0264824a678f.png">

**Comment by huangzehao** [comment]
Hi @brimoor 
Thank you for your prompt response. I will follow your advice.
