### ISSUE TITLE
[FR] Configure dynamic attributes shown in App sidebar

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2374]
The ability to add custom dynamic attributes to the dataset schema making them available for filtering in the App sidebar with v0.18 is great! But, oftentimes there are a LOT of attributes that get stored on labels, many of which are not always necessary to show in the sidebar for filtering aside from specific situations.
![image (2)](https://user-images.githubusercontent.com/21222883/204821481-e7b0574e-fab6-4f02-81fe-8e9f03d42d77.png)

Two times when this comes up are:
1) If users want to be able to declare these attributes on their schema to enforce types, but don't actually want to filter by the attributes
2) If users want to remove default attributes from the sidebar that are not interesting (like the 'filled' attribute of polylines if every polyline in your dataset is empty)

I'm thinking that there should be additional app config parameters allowing you to specify which attributes are displayed in the sidebar. Ideally, there would also be a way to do this in the UI. Potentially some kind of menu you can access for each field that lets you select the attributes that are displayed or hidden.

An open question is if this should be at the dataset-level or the user-level.

**Comment by benjaminpkane** [comment]
Resolve with schema settings
