### ISSUE TITLE
[FR] Be able to exclude samples based on tags

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2404]
Similar to https://github.com/voxel51/fiftyone/issues/1161, it would be useful to add another state to the tag filtering icon in the App to exclude any samples of a certain tag.

For example, the third click results in a line crossing out the eye icon.

![image](https://user-images.githubusercontent.com/21222883/205977571-16db6c15-dbef-4cb7-8dfa-ed42d7dad33f.png)

**Comment by brimoor** [comment]
See also: https://github.com/voxel51/fiftyone/issues/2405

**Comment by swheaton** [comment]
completed via https://github.com/voxel51/fiftyone/pull/2466 I think
