### ISSUE TITLE
[BUG] Non-persistent datasets are erroneously deleted

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2424]
On `fiftyone==0.18`, in one Python session I run:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = fo.zoo.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

Then in another shell, I run:

```shell
fiftyone datasets list
```

I see `quickstart` listed, but if I refresh my browser, I find that the `quickstart` dataset has been deleted, presumably due to the automatic non-persistent dataset cleanup method erroneously running when the second CLI method exits.

**Comment by brimoor** [comment]
To clarify, datasets will never be erroneously deleted if you mark them as persistent. So mark anything important as persistent as soon as you create the dataset to avoid this error:

```py
dataset.persistent = True
```

**Comment by swheaton** [comment]
has since been fixed
