### ISSUE TITLE
[BUG] App histograms are tied to view, not extended view

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2425]
The histogram tabs in the App are tied to the view, but they should update to reflect the extended view like all other components. For example, below I have filtered to show only a single sample, but the histograms show stats for the entire dataset:

<img width="1271" alt="Screen Shot 2022-12-09 at 4 12 41 PM" src="https://user-images.githubusercontent.com/25985824/206797069-04a4dea8-0bce-4208-bd80-83934034b42a.png">

**Comment by imanjra** [comment]
Fixed by https://github.com/voxel51/fiftyone/pull/2460. Closing.
