### ISSUE TITLE
[?] output_processor_cls for TorchImageModelConfig

### ISSUE THREAD

**Issue by Ayumu-J-S** [voxel51/fiftyone#2426]
This is a question I have but I was not able to add a question label for some reason I just added a documentation label.

 The question I had was something to do with TorchImageModelConfig. I am trying to use my own model, which has 1 output node, which outputs a value from 0 to 1. For this case, what should I use for `output_processor_cls`?

```python
config = fout.TorchImageModelConfig(
    {
        "entrypoint_fcn": "src.load_model",
        "entrypoint_args": {"model_name": "custom_model"},
        "output_processor_cls": "?????",
        "labels_string": "?????",
        "image_size": [64, 64],
        "image_mean": [0.485, 0.456, 0.406],
        "image_std": [0.229, 0.224, 0.225],
        "embeddings_layer": "avgpool",
    }
)
model2 = fout.TorchImageModel(config)
```

I just tried 
```
"output_processor_cls": "fiftyone.utils.torch.ClassifierOutputProcessor",
"labels_string": "something",
```
to see what happens and I get the following error
`ValueError: Found array with dim 4. check_pairwise_arrays expected <= 2.`
so I am guessing this is not the correct way to do this.

**Comment by brimoor** [comment]
Hi @Ayumu-J-S apologies for the delay here.

The `output_processor_cls` argument expects the fully-qualified name of a class that implements the [OutputProcessor](https://github.com/voxel51/fiftyone/blob/de89c6d45669bf31489b17a4dd3b6bb59b4e5757/fiftyone/utils/torch.py#L631) interface.

In your case, if you could add one of these classes to your `src` module:

```py
import fiftyone.core.labels as fol
import fiftyone.utils.torch as fout


class NoOutputProcessor(fout.OutputProcessor):
    """Output processor that returns the raw output."""

    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, output, *args, **kwargs):
        return output


class RegressionOutputProcessor(fout.OutputProcessor):
    """Output processor that emits :class:`fiftyone.core.labels.Regression`
    instances.
    """

    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, output, *args, **kwargs):
        return output

        return fol.Regression(value=output)
```

**Comment by brimoor** [comment]
FYI with https://github.com/voxel51/fiftyone/pull/2949 merged you'll be able to omit `output_processor_cls` altogether, which will have the same effect as using `NoOutputProcessor` as defined above.

**Comment by Ayumu-J-S** [comment]
Thank you!
