### ISSUE TITLE
[?] Tips and Advice for Custom Dataset Training to Predict Polylines

### ISSUE THREAD

**Issue by jasonchanhku** [voxel51/fiftyone#2449]
I have a use case which is to train a model and predict the polylines of the cables. I already have all the polyline labels. Below is an example:

![image](https://user-images.githubusercontent.com/20807220/208661756-eb991dea-793b-44d2-bac0-4fb520fb5463.png)

Was wondering if anyone has ever tried a similar use case? My questions are as follows:

- For predicting polylines in this use case, is it considered a segmentation task?
- Can I use fiftyone to directly train a model after loading in the dataset and labels?

I understand that I can load the images and labels using ![this](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#polylines-and-polygons). I have seen some cases where Detectron2 was used on a custom dataset ![here](https://voxel51.com/docs/fiftyone/tutorials/detectron2.html) but it is more geared towards segmentation. Would appreciate it if anyone can provide any advise or direction. Thanks!

**Comment by brimoor** [comment]
Hi @jasonchanhku 👋 

I bet you'll find some good tips and discussion about this use case in the [FiftyOne Slack community!](https://join.slack.com/t/fiftyone-users/shared_invite/zt-s6936w7b-2R5eVPJoUw008wP7miJmPQ)

**Comment by jasonchanhku** [comment]
Thanks will join it ! Cheers

**Comment by brimoor** [comment]
If you're reading this, there was indeed some good discussion about this use case in the  [FiftyOne Slack community](https://join.slack.com/t/fiftyone-users/shared_invite/zt-s6936w7b-2R5eVPJoUw008wP7miJmPQ). Come join the fun!
