### ISSUE TITLE
[BUG] CSV Exporter has too many double quotes in list fields

### ISSUE THREAD

**Issue by swheaton** [voxel51/fiftyone#2493]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Mac OSX A1 chip
-   **Python version** (`python --version`): 3.10.8
-   **FiftyOne version** (`fiftyone --version`): develop
-   **FiftyOne installed from** (pip or source): source

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
view = dataset.limit(2)
view.export(
  dataset_type=fo.types.CSVDataset,
  export_dir="/tmp/csv_export_test",
  fields=[
    "filepath",
    "tags",
    "ground_truth.detections.tags",
    "ground_truth.detections.label"
  ]
)
```

### Describe the problem

CSV Exporter quotes list fields one too many times so that if read in by a CSV reader, the whole list will be surrounded by double quotes.

Above code generates this:
```
filepath,tags,ground_truth.detections.tags,ground_truth.detections.label
000880.jpg,"""validation""","""[],[],[]""","""bird,bird,bird"""
```
Vs. expected:
```
filepath,tags,ground_truth.detections.tags,ground_truth.detections.label
000880.jpg,"validation","[],[],[]","bird,bird,bird"
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [x] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
k I'll let you take a look when able
