### ISSUE TITLE
[BUG] Filter keypoints by label if no skeleton is provided

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2507]
If loading a `Keypoints` field where each `Keypoint` only corresponds to a single point, you should be able to filter by the `Keypoint` labels in the sidebar, but currently, that is not an option.

It makes sense that if a keypoint skeleton is provided, you can't filter both by skeleton labels and keypoint labels, but that should be determined by the existence of a skeleton.

Ex:
```python
sample["points"] = fo.Keypoints(keypoints=[fo.Keypoint(label="dog", points=[[0.5, 0.1]], no_votes=0, unsure_votes=0, yes_votes=3)])
# Can't filter by "dog" in the App
```

![image](https://user-images.githubusercontent.com/21222883/211691169-79d18046-f443-4bd7-b127-990e3bef9c2c.png)

This is important for #2446 which adds point labels where each point is stored as a single `Keypoint` label.

**Comment by benjaminpkane** [comment]
Resolved by #3280
