### ISSUE TITLE
[BUG] The MatchTag stage in the App automatically removes spaces

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2509]
Spaces are allowed in a sample or label tag, but when you try to use the `MatchTags` view stage in the app, any tags written in the `list,of,tags` automatically have spaces removed. This means it is impossible to filter by a tag using this stage. You have to use the sidebar to filter by that specific tag.

![image](https://user-images.githubusercontent.com/21222883/211922110-a292e5d7-6933-436b-b487-3959c845fbed.png)

**Comment by manivoxel51** [comment]
fix is merged to develop. safe to close this?
