### ISSUE TITLE
[BUG] Switching to patches view should not reset space layout

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2531]
In the example below, I configure my spaces to show `Samples | Embeddings`:

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
fob.compute_visualization(dataset, patches_field="ground_truth", brain_key="gt_viz")

session = fo.launch_app(dataset)

samples_panel = fo.Panel(type="Samples", pinned=True)
embeddings_panel = fo.Panel(
    type="Embeddings",
    state=dict(
        brainResult="gt_viz",
        colorByField="ground_truth.detections.label",
    ),
)

session.spaces = fo.Space(
    children=[
        fo.Space(children=[samples_panel]),
        fo.Space(children=[embeddings_panel]),
    ],
    orientation="horizontal",
)
```

If I then switch to `ground_truth` patches view using the App, my spaces layout resets to `Samples` panel only, while `session.spaces` still reports the previous layout.

If I remove the patches view by clearing the view bar, my spaces layout then resets to `Samples | Embeddings` as it previously was configured.

The expected behavior is that switching between patches and non-patches views does not reset my spaces layout. The space layout for a dataset should be independent of the current view.

**Comment by brimoor** [comment]
Some additional context on this issue: I found that this issue only occurs when setting `session.spaces`. If I instead just launch the App and then configure the spaces layout manually; I am able to convert to patches view without my spaces layout resetting.

**Comment by imanjra** [comment]
@brimoor I am unable to re-create this bug. Are you still seeing the issue?
