### ISSUE TITLE
[DOCS] CVAT Annotation Tutorial: CVAT v2.4 API breaking change

### ISSUE THREAD

**Issue by allenleetc** [voxel51/fiftyone#2572]
### URL(s) with the issue
https://docs.voxel51.com/tutorials/cvat_annotation.html

### Description of proposal (what needs changing)
CVAT v2.4 has a breaking API change that causes the annotation code in this tutorial to error out if using the CVAT server on cvat.ai.

Proposed workaround is to downgrade to CVAT v2.3 if possible.

**Comment by ehofesmann** [comment]
Related: https://github.com/voxel51/fiftyone/issues/2565
