### ISSUE TITLE
[BUG] Error Launching 0.19 In Databricks: KeyError: 'DATABRICKS'

### ISSUE THREAD

**Issue by paultreadel** [voxel51/fiftyone#2648]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04):  `Databricks  11.3 LTS`
-   **Python version** (`python --version`):  `3.9`
-   **FiftyOne version** (`fiftyone --version`):  `0.19.0`
-   **FiftyOne installed from** (pip or source):  `pip`

### Commands to reproduce

```
pip install fiftyone==0.19.0

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

### Describe the problem

`KeyError: 'DATABRICKS'` thrown when trying to launch the app in DataBricks on the quickstart dataset.

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

#### Traceback
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<command-3645939023465003> in <cell line: 5>()
      3 
      4 dataset = foz.load_zoo_dataset("quickstart")
----> 5 session = fo.launch_app(dataset)

/local_disk0/.ephemeral_nfs/envs/pythonEnv-d4292355-58f7-447f-b1f9-116a43d6871d/lib/python3.9/site-packages/fiftyone/core/session/session.py in launch_app(dataset, view, spaces, plots, port, address, remote, desktop, height, auto, config)
    161     close_app()
    162 
--> 163     _session = Session(
    164         dataset=dataset,
    165         view=view,

/local_disk0/.ephemeral_nfs/envs/pythonEnv-d4292355-58f7-447f-b1f9-116a43d6871d/lib/python3.9/site-packages/fiftyone/core/session/session.py in __init__(self, dataset, view, view_name, spaces, plots, port, address, remote, desktop, height, auto, config)
    387 
    388         if self.auto and focx.is_notebook_context():
--> 389             self.show(height=config.notebook_height)
    390 
    391         if self.remote:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-d4292355-58f7-447f-b1f9-116a43d6871d/lib/python3.9/site-packages/fiftyone/core/session/session.py in wrapper(session, *args, **kwargs)
    217             if auto_show and session.auto and focx.is_notebook_context():
    218                 session.freeze()
--> 219             result = func(session, *args, **kwargs)
    220             session._client.send_event(StateUpdate(state=session._state))
    221             if auto_show and session.auto and focx.is_notebook_context():

/local_disk0/.ephemeral_nfs/envs/pythonEnv-d4292355-58f7-447f-b1f9-116a43d6871d/lib/python3.9/site-packages/fiftyone/core/session/session.py in show(self, height)
    952 
    953         self._notebook_cells[uuid] = cell
--> 954         fosn.display(self._client, cell)
    955 
    956     def no_show(self) -> fou.SetAttributes:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-d4292355-58f7-447f-b1f9-116a43d6871d/lib/python3.9/site-packages/fiftyone/core/session/notebooks.py in display(client, cell, reactivate)
     56         # focx._DATABRICKS: display_databricks,
     57     }
---> 58     fn = funcs[focx._get_context()]
     59     fn(client, cell, reactivate)
     60 

KeyError: 'DATABRICKS'
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by paultreadel** [comment]
Saw that v0.19.1 has been tagged recently and gave it a test drive.  Everything is looking good in a databricks for the quickstart dataset!  Nice work and thanks for the quick turnaround!
![databricks_fiftyone_quickstart_v19](https://user-images.githubusercontent.com/60437545/219480627-bd3e4204-2293-4309-8169-37b271508f51.gif)

**Comment by yuanhao-li** [comment]
> Saw that v0.19.1 has been tagged recently and gave it a test drive. Everything is looking good in a databricks for the quickstart dataset! Nice work and thanks for the quick turnaround! ![databricks_fiftyone_quickstart_v19](https://user-images.githubusercontent.com/60437545/219480627-bd3e4204-2293-4309-8169-37b271508f51.gif) [ ![databricks_fiftyone_quickstart_v19](https://user-images.githubusercontent.com/60437545/219480627-bd3e4204-2293-4309-8169-37b271508f51.gif) ](https://user-images.githubusercontent.com/60437545/219480627-bd3e4204-2293-4309-8169-37b271508f51.gif) [ ](https://user-images.githubusercontent.com/60437545/219480627-bd3e4204-2293-4309-8169-37b271508f51.gif)

Very impressive. What is your databricks settings to make it showed in notebooks?

**Comment by paultreadel** [comment]
@yuanhao-li As far as I know as long as one uses `fiftyone==v0.19.1` then it should happily work in databricks without any special setup on the databricks end.

I'm a user of an enterprise managed version of databricks though, so I don't know all our config details (but would happily check for something specific if you could be more precise).  In general I am running `DataBricks Runtime LTS 11.3` on a single node cluster of instance type `r5d.4xlarge`

**Comment by yuanhao-li** [comment]
@paultreadel thanks for the info. I thought you have customised your workspace settings. 

I have created an issue here: https://github.com/voxel51/fiftyone/issues/2668
