### ISSUE TITLE
[FR] Support segmentation masks as filepaths

### ISSUE THREAD

**Issue by charlielito** [voxel51/fiftyone#2664]
### Proposal Summary

It could be very useful for very simple segmentation masks, to support saving in the db just the paths to the segmentation masks as png one-channel files, instead of encoding the raw mask as base64 and storing it directly in the db.

### Motivation
This is useful where this can be supported because the space taken in the db will decrease significatively. When using high-resolution images, the db starts to grow considerably when using segmentation masks the way it is currently implemented.

### What areas of FiftyOne does this feature affect?
I am not sure where this should be implemented

-   [ ] App: FiftyOne application
-   [ ] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [X] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by brimoor** [comment]
Hi @charlielito 👋 

Good news: we just added support for this!

Upgrade to `fiftyone>=0.19` and you can provide paths on disk rather than storing segmentations/heatmaps in the database:
https://docs.voxel51.com/user_guide/using_datasets.html#semantic-segmentation
