### ISSUE TITLE
[BUG] DatasetView.save() after Dataset.sort_by() has no effect after v0.14.4

### ISSUE THREAD

**Issue by duanyao** [voxel51/fiftyone#2666]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Deepin 20.8 (debian 10 based)
-   **Python version** (`python --version`): Python 3.9.2
-   **FiftyOne version** (`fiftyone --version`):FiftyOne v0.19.1, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source):pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

Downgrade fiftyone to 0.14.2\~0.14.4:
```
VERSION=0.14.4 # 0.14.3 or 0.14.2
fiftyone migrate --all -v $VERSION
pip install fiftyone==$VERSION

python3
```

### Describe the problem

I sort a dataset by `filepath` and save the returned view, and expect the sorted result is saved in the dataset. This works with fiftyone 0.14.2\~0.14.3, but not with 0.14.4\~0.19.1 (the dataset is not changed by `save()`). 

I'm not sure fiftyone 0.14.4 changed this behavior by intention or it is a bug. If this is not a bug, how do I save a  sorted dataset?

### Code to reproduce issue

```
import fiftyone as fo
ds2=fo.Dataset('ds2')
ds2.add_samples( 
     [
         fo.Sample(filepath="/path/to/image1.jpg"), 
         fo.Sample(filepath="/path/to/image2.jpg"),
     ]
 )
v=ds2.sort_by('filepath', reverse=True)
v.save()
assert v.first().filepath == "/path/to/image2.jpg"
assert ds2.first().filepath == "/path/to/image2.jpg" # passes with fiftyone 0.14.2~0.14.3; AssertionError with 0.14.4~0.19.1 
```

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Please do not use screenshots for sharing text. Code snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @duanyao 👋 

The current behavior is intended. `view.save()` is intended to save updates to any documents in the view, but it's not intended to, for example, modify any documents that are *not* in the view. So in general it doesn't make any promises about the order of the documents it updates.

If you want to reorder the documents, you can use this approach:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

view = dataset.sort_by("uniqueness", reverse=True)

# Retains order of view
new_dataset = view.clone()

# Delete old dataset if desired
dataset.delete()
new_dataset.name = "quickstart"
```

**Comment by duanyao** [comment]
Hi, @brimoor , I see, thank you very much!
