### ISSUE TITLE
[BUG] Network Error trying to load video dataset in the App

### ISSUE THREAD

**Issue by peiliu0408** [voxel51/fiftyone#2673]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
-   **Python version** (`python --version`): 3.8.5
-   **FiftyOne version** (`fiftyone --version`): 19.1
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
fiftyone app view --videos-dir /data1/videos
```

### Describe the problem

Work fine for images dir, (Dataset.from_images_dir), but fails for videos. No showing in website browser.  Local Network, No Internet connection.

### Code to reproduce issue

Also start the FiftyOne App using Python:

```py
import fiftyone as fo

dataset = fo.Dataset.from_videos_dir("/data1/videos")
session = fo.launch_app(dataset, remote=True)
session.wait()
```

Same with starts command line, tell Network Error.

### Other info/logs

![042E8C6F-7387-4A46-A171-4D25C3B0D2C7](https://user-images.githubusercontent.com/18061950/220044147-991f7c3e-4ccd-4440-a3f6-625d84bab836.jpeg)

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [* ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
I was able to reproduce this error by uninstalling `ffmpeg`, so I think this is indeed the issue.

**Comment by brimoor** [comment]
@benjaminpkane I believe the intention was for the user to see a nice error:

https://github.com/voxel51/fiftyone/blob/dfb81b6fffb8ef9bb36bcb0d534f357e664ccfc8/fiftyone/server/metadata.py#L160-L163

when they don't have ffmpeg installed, but this

https://github.com/voxel51/fiftyone/blob/dfb81b6fffb8ef9bb36bcb0d534f357e664ccfc8/fiftyone/server/metadata.py#L87-L89

doesn't seem to be getting it into the App's error handler (anymore?)

Can we get the intended error message to show in the App?

**Comment by peiliu0408** [comment]
> Hmm I'm not able to reproduce. This works for me, for example:
> 
> ```shell
> fiftyone zoo datasets download quickstart-video
> 
> VIDEOS_DIR="$(fiftyone zoo datasets find quickstart-video)/data"
> fiftyone app view --videos-dir ~/fiftyone/quickstart-video/data
> ```
> 
> Do you have `ffmpeg` installed? That is required in order to work with video datasets: https://docs.voxel51.com/getting_started/install.html#installing-fiftyone

Thanks for your kindly reply. Unfortunately, I can not download that QuickStart-video directly for server is deployed in a local network. 

What interesting is, the image dataset (load_images_dir) works perfect, so I guess there is no connection error. 

I will try to download quick-start video data in an Internet access PC, and then copy part of video into a temporary directory to see whether the problems is cased by video format.

**Comment by peiliu0408** [comment]
> @benjaminpkane I believe the intention was for the user to see a nice error:
> 
> https://github.com/voxel51/fiftyone/blob/dfb81b6fffb8ef9bb36bcb0d534f357e664ccfc8/fiftyone/server/metadata.py#L160-L163
> 
> when they don't have ffmpeg installed, but this
> 
> https://github.com/voxel51/fiftyone/blob/dfb81b6fffb8ef9bb36bcb0d534f357e664ccfc8/fiftyone/server/metadata.py#L87-L89
> 
> doesn't seem to be getting it into the App's error handler (anymore?)
> 
> Can we get the intended error message to show in the App?

Thanks for your reply. I start the fiftyone in a remote server, in methods of python script and command line, both got the same errors. I am a new for fiftyone family, and I installed fiftyone yesterday, version is 19.1.

FFmpeg is installed, I checked that several times.

The video is also process using fiftyone.utility.videos.reencode_video func provided by fiftyone lib. All video could be opened correctly using a media player.

Strongly, there is no intended error message showing in server, but fails in PC’s website browser. whether there is a way to print the error message? Just like verbose mode?

**Comment by peiliu0408** [comment]
I doubt this is not error about video format (of course no connection problem, works fine for image folders). I start the process (videos-dir) using an empty dir or putting quick-start video, the errors stills appears.

**Comment by peiliu0408** [comment]
Problems solved. Updater the website browser in PC, and fiftyone on server updated to 0.19.1rc1 version. Works fine!
