### ISSUE TITLE
[BUG] How is the COCO17 dataset 144GB?

### ISSUE THREAD

**Issue by Telephos** [voxel51/fiftyone#2699]
### System information

-   **Windows 10.0 Enterprise** 
-   **Python 3.9.13** 
-   **FiftyOne 0.19.1** 
-   **FiftyOne installed from pip** 

### Commands to reproduce

```
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset(
    "coco-2017",
    splits=("train", "validation"),
    label_types=["detections"],
    drop_existing_dataset==True
)

dataset.persistent = True

one_view = (
    dataset
    .select_fields("ground_truth")
    .match(F("ground_truth.detections").length() == 1)
)
# dataset.save_view("one-view", one_view)

session = fo.launch_app(one_view, desktop=True)
session.wait()
```

### Describe the problem

COCO17 is ~26GB for the entire detection dataset, but FiftyOne is attempting to download 144GB. I was going to reduce the dataset down to images with only a single object instance, but I was trying to do that in the view. 

Any help is appreciated!

**Comment by brimoor** [comment]
The progress bar shows bits, not bytes. Does 25.20GB = 201.6Gb for the test + train splits sound more reasonable 😄 

Related: the [zoo docs](https://docs.voxel51.com/user_guide/dataset_zoo/datasets.html#coco-2017) explain how you can specifically download (only) a subset of COCO if you'd like.

**Comment by Telephos** [comment]
Oh, shoot! Well, thank you!
