### ISSUE TITLE
Problem with CSVDataset export

### ISSUE THREAD

**Issue by barney2074** [voxel51/fiftyone#2704]
Hi

I'm having a problem with exporting to a CSV dataset.
For example, running the below, I get this error. Other exports work fine
`
AttributeError: module 'fiftyone.types' has no attribute 'CSVDataset'`

`import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
view = dataset.limit(2)
view.export(
  dataset_type=fo.types.CSVDataset,
  export_dir="/tmp/csv_export_test",
  fields=[
    "filepath",
    "tags",
    "ground_truth.detections.tags",
    "ground_truth.detections.label"
  ]
)`

Any help would be greatly appreciated.
thank you

Andrew

**Comment by brimoor** [comment]
CSV export support was released in [fiftyone==0.19](https://docs.voxel51.com/release-notes.html#fiftyone-0-19-0). Can you try upgrading?

**Comment by barney2074** [comment]
thanks for the very quick reply.
Yes, that has fixed it

thanks again
Andrew
