### ISSUE TITLE
[DOCS] What is the best practice for working with a local fiftyone?

### ISSUE THREAD

**Issue by ramanova** [voxel51/fiftyone#2708]
Hello, what is the best practice for working with a local fiftyone?

Use Case:
1. Run ingest/ visualization script that brings up fiftyone instance (runs local mongo), stays on session.wait()
2. Work iteratively in another script or a notebook: updating labels, calculating metrics.

### Description of proposal (what needs changing)
A simple way to start an instance locally, so other processes can connect to it

I understand that I can run a local mongo instance via
~/.local/lib/python3.8/site-packages/fiftyone/db/bin/mongod     --dbpath ~/.fiftyone/var/lib/mongo --logpath /home/sz68zj/.fiftyone/var/lib/mongo/log/mongo.log --port 27017 --nounixsocket

And then connect to it in my processing script like so:
os.environ["FEATURESTORE_URI"] = "mongodb://localhost:27017"
os.environ["FEATURESTORE_NAME"] = "fiftyone"

But currently I see that the mongod process created on the custom port 27017 jumps back to port 0 and then dies.

Thanks in advance

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ X] Yes. I can contribute a documentation fix independently
-   [ X] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a documentation fix at this time

**Comment by swheaton** [comment]
There is not a best practice around this I think, we have users that do both ways or others.
In general, our "best practices" are contained in the user guides and tutorials in the docs. Other than that, it's all up to how you prefer to work. https://docs.voxel51.com/user_guide/index.html
