### ISSUE TITLE
Make docs.voxel51.com and voxel51.com/docs redirect to sensible locations

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#277]
We currently have the following docs pages:

**FiftyOne**
- https://voxel51.com/docs/fiftyone

**Platform**
- API: https://voxel51.com/docs/api
- Analytics: https://voxel51.com/docs/analytics
- Applications: https://voxel51.com/docs/applications
- Python client lib: https://voxel51.com/docs/api-py
- JS client lib: https://voxel51.com/docs/api-js

Two common places for docs are https://docs.voxel51.com and https://voxel51.com/docs, neither of which we currently support. We should choose an appropriate home for these links.

Given that FiftyOne is our sole focus, and that clicking on the `Docs` link on voxel51.com directs to https://voxel51.com/docs/fiftyone, it seems that we should have https://docs.voxel51.com and https://voxel51.com/docs redirect to https://voxel51.com/docs/fiftyone.

Thoughts?

A possible alternative is to develop a landing page at https://voxel51.com/docs that links to the relevant product docs. But, would `Docs` link on voxel51.com and https://docs.voxel51.com then also link to this?

**Comment by swheaton** [comment]
OBE, docs.voxel51.com and voxel51.com/docs exist
