### ISSUE TITLE
[FR] Is there solutions to upload both dataset and its existed labels to CVAT in fiftyone right now?

### ISSUE THREAD

**Issue by stevezkw1998** [voxel51/fiftyone#2802]
### Proposal Summary

I try to upload a validation coco dataset with existed labels 'ground  truth'  to CVAT, but in CVAT I can only see the images, can not see the existed labels that displayed in Fiftyone App 

### Motivation

-   What is the use case for this feature?  
Wrong Labels corrections 
-   Why is this use case valuable to support for FiftyOne users in general? 
It should be able to correct/modified existed labels rather than labeling a new one
-   Why is this use case valuable to support for your project(s) or organization? 
When we auto-labeled a dataset using models, there might be 10% bad labels, we want to correct them rather than re-labels them.
-   Why is it currently difficult to achieve this use case?
I find out all of the documents it seems we can only upload samples and labels separately, which is very inconvenient to use

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

Load and dataset
```python
import fiftyone as fo

dataset = fo.zoo.load_zoo_dataset(
    name='coco-2017',
    split="validation",
    dataset_name='test2',
    max_samples=50,
    shuffle=False,
)
dataset.persistent = True
```
![image](https://user-images.githubusercontent.com/53121066/225763856-3c8c9c7e-120f-496e-9008-32062cfc765a.png)
From the screen shot we can see this dataset has labels filed 'ground_truth'

Then I upload dataset to CVAT

```python
dataset = fo.load_dataset('test2')

dataset.annotate(anno_key, project_name='ZOO', label_field='ground_truth', label_type='detections',
                    username=*******, password=********, launch_editor=True)
```
![image](https://user-images.githubusercontent.com/53121066/225764277-c9aabb0b-ecd6-4ccd-bd6e-83b7d544933f.png)

But from the screen shot we can see there is no labels on CVAT's site.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by jasoncorso** [comment]
This is already standard functionality.  Documentation is here: https://docs.voxel51.com/integrations/cvat.html#editing-existing-labels
