### ISSUE TITLE
[BUG] View bar doesn't update correctly when loading a schema-changing view

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2833]
In this setup:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

adding a `SelectFields("ground_truth")` stage to my view works in the sense that the grid updates, but the parameters disappear from the view stage `SelectFields(list,of,fields)`:

https://user-images.githubusercontent.com/25985824/226948145-d7178172-d484-45a7-9667-515a51e94646.mov

**Comment by benjaminpkane** [comment]
Resolved
