### ISSUE TITLE
[BUG] stats() is inaccurate on a DatasetView with a SelectFieldsStage

### ISSUE THREAD

**Issue by swheaton** [voxel51/fiftyone#2836]
### Commands to reproduce

When you exclude fields the document size does not contain those fields but for some reason when you select fields the document size includes all fields.

I have verified that simply adding a "$project" stage with the given fields before the "$bsonSize" stage generated in `SampleCollection._get_samples_bytes()` gives the expected result, but that should be exactly what the `SelectFieldsStage` is doing. So it needs to be looked into more.

As a workaround if one needed it, one could exclude all but the wanted (and default) fields and it seemingly works.
```python
import fiftyone.zoo as foz
dataset=foz.load_zoo_dataset('quickstart')

# Fails, sizes are equal
select_view = dataset.select_fields()
assert select_view.stats()["total_bytes"] < dataset.stats()["total_bytes"]

# Works as expected
exclude_view = dataset.exclude_fields(["ground_truth", "predictions"])
assert exclude_view.stats()["total_bytes"] < dataset.stats()["total_bytes"]
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Mac
-   **Python version** (`python --version`): 3.10.9
-   **FiftyOne version** (`fiftyone --version`): 0.20.0
-   **FiftyOne installed from** (pip or source): pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [x] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
I can't reproduce the bug you're reporting here, at least on `develop`. This succeeds:

```py
import fiftyone.zoo as foz

dataset=foz.load_zoo_dataset('quickstart')
select_view = dataset.select_fields()
assert select_view.stats()["total_bytes"] < dataset.stats()["total_bytes"]
```

**Comment by brimoor** [comment]
The `mongo()` stage can be leveraged to avoid inclusion of default fields that `select_fields()` performs:

```py
def force_select_fields(sample_collection, fields):
    if isinstance(fields, str):
        fields = [fields]

    project = {"_id": False}
    project.update({f: True for f in fields})
    return sample_collection.mongo([{"$project": project}])
```

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

view1 = dataset.select_fields("uniqueness")
view2 = force_select_fields(dataset, "uniqueness")

fo.pprint(view1._pipeline())
fo.pprint(view2._pipeline())

print(dataset.stats()["samples_bytes"])  # 1271362
print(view1.stats()["samples_bytes"]) # 39400
print(view2.stats()["samples_bytes"])  # 5000
```

In general, this is dangerous because the resulting view is invalid (missing required fields like `filepath` to be used by the rest of the SDK), but for the particular purpose of computing `stats()` *without* `include_media=True` it works like a charm.

**Comment by swheaton** [comment]
Interesting - it also fails for me in develop. Mongo version 6.0.1. What version do you have locally?
I have previously confirmed it also doesn't work in Teams API with dev DB which is 6.0.4.

Further, your `force_select_fields` doesn't work either!
Nor does a direct aggregation. I swear I tried this before and it was working, but it's not now... I must've been mistaken.
```python
# Single projected document size is correct!
>>> pipeline1=[{'$project': {'id': 1}}, {'$project': {'byte_size': {"$bsonSize": "$$ROOT"}}}]
>>> next(dataset._aggregate(pipeline1))
{'_id': ObjectId('6320b079b5b940abbfeddeb3'), 'byte_size': 22}

# Grouped projected document size is incorrect! Should be 200 * 22 = 4400
>>> pipeline=[
    {'$project': {'_id': 1}},
    {'$group': {'_id': None, 'size_bytes': {'$sum': {'$bsonSize': '$$ROOT'}}}},
]
>>> next(dataset._aggregate(pipeline))["size_bytes"]
1293987
```

**Comment by swheaton** [comment]
Workaround merged in but [MongoDB bug ticket has been filed](https://jira.mongodb.org/browse/SERVER-75267)
