### ISSUE TITLE
[DOCS] What is the signature and input/output of the _radius_neighbors() method

### ISSUE THREAD

**Issue by captainfffsama** [voxel51/fiftyone#2856]
### Instructions

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md) for information on what types of issues we address.

1. Please fill in this template to ensure a timely and thorough response
2. Place an "x" between the brackets next to an option if it applies. For example:
    -   [x] Selected option
3. **Please delete everything above this line before submitting the issue**

### URL(s) with the issue

<https://docs.voxel51.com/api/fiftyone.brain.similarity.html#fiftyone.brain.similarity.DuplicatesMixin>

### Description of proposal (what needs changing)
What is the signature and input/output of the `_radius_neighbors()` method mentioned in the documentation for implementing duplicate detection in the similarity backend?

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently
-   [x] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a documentation fix at this time

**Comment by brimoor** [comment]
You can find the definition of the entire similarity interface on your machine as follows:

```py
import fiftyone.brain.similarity as fbs
print(fbs.__file__)
```

Here's the `_radius_neighbors()` method:

```py
    def _radius_neighbors(self, query=None, thresh=None, return_dists=False):
        """Returns the neighbors within the given distance threshold for the
        given query.

        This method should only return results from the current :meth:`view`.

        Args:
            query (None): the query, which can be any of the following:

                -   an ID or list of IDs for which to return neighbors
                -   an embedding or ``num_queries x num_dim`` array of
                    embeddings for which to return neighbors
                -   ``None``, in which case the neighbors for all points in the
                    current :meth:`view are returned

            thresh (None): the distance threshold to use
            return_dists (False): whether to return query-neighbor distances

        Returns:
            the query result, in one of the following formats:

                -   an ``(ids, dists)`` tuple, when ``return_dists`` is True
                -   ``ids``, when ``return_dists`` is False

            In the above, ``ids`` contains the IDs of the nearest neighbors, in
            one of the following formats:

                -   a list of nearest neighbor IDs, when a single query ID or
                    vector is provided
                -   a list of lists of nearest neighbor IDs, when multiple
                    query IDs/vectors is provided
                -   a list of arrays of the **integer indexes** (not IDs) of
                    nearest neighbor points for every vector in the index, when
                    no query is provided

            and ``dists`` contains the corresponding query-neighbor distances
            for each result in ``ids``
        """
```
