### ISSUE TITLE
[BUG] Next/previous navigation doesn't match view order after switching to/from patches

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2889]
On `fiftyone==0.20.1` (and previous versions likely), next/previous navigation doesn't match view order after switching to/from patches. Refreshing the grid solves the issue.

https://user-images.githubusercontent.com/25985824/230734272-0f97e825-5635-4b25-8827-e02445f10988.mov

**Comment by benjaminpkane** [comment]
I'm unable to reproduce on `develop` or `v0.20.1`. It looks like an unwanted re-render/flicker is occurring in the recording you shared which is likely related. I do not see that when testing in my environment.

**Comment by lanzhenw** [comment]
Tested again with quickstart, bdd and grouped dataset, could not reproduce it.

**Comment by brimoor** [comment]
Okay, must've been resolved at some point ✔️
