### ISSUE TITLE
[DOCS] Github changelog for 0.20.1 is not showing correct commits?

### ISSUE THREAD

**Issue by NeoKish** [voxel51/fiftyone#2892]
### Instructions

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md) for information on what types of issues we address

### Description of proposal (what needs changing)

The changelog for latest release [v0.20.1 ](https://github.com/voxel51/fiftyone/releases/tag/v0.20.1) doesn't seem right. Shouldn't it be showing changes on top of the previous release which in this case is v0.20.0. Same issue is present with the [v0.19.0](https://github.com/voxel51/fiftyone/releases/tag/v0.19.0) release as well.

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently
-   [x] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a documentation fix at this time

**Comment by swheaton** [comment]
Our release change logs are on our documentation site now: https://docs.voxel51.com/release-notes.html
