### ISSUE TITLE
Error loading libcrypto.so.1.1 on Ubuntu 22.04

### ISSUE THREAD

**Issue by ufosoftwarellc** [voxel51/fiftyone#2900]
import fiftyone as fo causes the following errors when loading MongoDB:

```
/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 127:
lib/python3.10/site-packages/fiftyone/db/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

This is due to the fact that fiftyone has installed and is trying to load a version of MongoDB that is not compatible with Ubuntu 22.04.

A newer version of MongoDB exists that is compatible with Ubuntu 22.04 that should be added to the MONGODB_DOWNLOAD_URLS section of the fiftyone/blob/develop/package/db/setup.py

**Comment by benjaminpkane** [comment]
Hi @ufosoftwarellc. I am working on a fix for this. In the meantime, using a[ configured MongoDB database ](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection) is a viable workaround.

**Comment by franfcunha** [comment]
You can follow this tutorial on how to download and build from source, then just make sure your LD_LIBRARY_PATH points to the location where the required lib was built (https://askubuntu.com/questions/1126893/how-to-install-openssl-1-1-1-and-libssl-package)

**Comment by ufosoftwarellc** [comment]
> Hi @ufosoftwarellc. I am working on a fix for this. In the meantime, using a[ configured MongoDB database ](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection) is a viable workaround.

Hi @benjaminpkane I tried using MongoDB 6.0.5 Community and I receive a Failed to validate 'mongod' version error even after setting "database validation":false in the .fiftyone/config.json

**Comment by ufosoftwarellc** [comment]
> You can follow this tutorial on how to download and build from source, then just make sure your LD_LIBRARY_PATH points to the location where the required lib was built (https://askubuntu.com/questions/1126893/how-to-install-openssl-1-1-1-and-libssl-package)

@franfcunha Since we want to recommend Voxel51 to clients for an annotation solution having them rebuild your software is not an option.  I need a generic solution that will work on whatever hardware / operating system the client is using.

**Comment by benjaminpkane** [comment]
Hi All. The current fix for this is to install [`fiftyone-db-ubuntu-2204`](https://pypi.org/project/fiftyone-db-ubuntu2204/) alongside `fiftyone`

```
pip install fiftyone fiftyone-db-2204
```

**Comment by brimoor** [comment]
See also: #3321, #3236, #2900, #2737, #2480, #1988, #1803

**Comment by sriram-dsl** [comment]
this eroor is because of compatibility issues of libcrypto.so.1.1 
not a mongodb issue
just try to create a dummy directory and install openssl-1.1.1o
direct  the LD_LIBRARY_PATH to the openssl-1.1.1o path
```
mkdir $HOME/dummy && cd $HOME/dummy && mkdir openssl_1.1 && cd $HOME/dummy/openssl_1.1
wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
tar -zxvf openssl-1.1.1o.tar.gz
cd openssl-1.1.1o
./config && make && make test
```
```
export LD_LIBRARY_PATH=$HOME/dummy/openssl_1.1/openssl-1.1.1o
```

make sure the path to the openssl-1.1.1o is correct

**Comment by yszansx** [comment]
/data/mongodb/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
