### ISSUE TITLE
AttributeError: 'COCODetectionResults' object has no attribute 'eval_key'

### ISSUE THREAD

**Issue by CexyNature** [voxel51/fiftyone#2902]
### System information

-   Linux Ubuntu 18.04
-   Python 3.8.0
-   FiftyOne version 0.20.1
-   FiftyOne installed from pip

### Commands to reproduce

```python
import fiftyone as fo
import fiftyone.utils.yolo as fouy
import fiftyone.utils.coco as fouc
from fiftyone import ViewField as F

dataset = fo.Dataset.from_dir(
    dataset_dir=DATASET_DIR,
    yaml_path=DATASET_YAML_PATH,
    dataset_type=fo.types.YOLOv5Dataset,
    split="test",
    label_field="ground_truth",
)

classes = dataset.default_classes

fouy.add_yolo_labels(
    dataset,
    "predictions",
    DATASET_INFERENCE_RESULTS,
    classes,
)

results = dataset.evaluate_detections(
    "predictions",
    gt_field="ground_truth",
    method="coco",
    eval_key="test",
    use_boxes=True,
    compute_mAP=True,
    iou_threshs=[0.5,0.6,0.7,0.8,0.9]
)

results.eval_key
```

### Describe the problem

The above commands returns AttributeError

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[32], line 1
----> 1 results.eval_key

AttributeError: 'COCODetectionResults' object has no attribute 'eval_key'
```

### Other info/logs

I have noticed that some refactoring was done previously-to and at 075e309 commit particularly on [coco.py](fiftyone/utils/eval/coco.py) and [base.py](fiftyone/utils/eval/base.py), could this be the cause of the problem? 

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
We did some refactoring to standardize evaluations, annotation runs, and brain runs in `fiftyone==0.20.1`. The key is now available via a `results.key` property in all cases:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
results = dataset.evaluate_detections("predictions", eval_key="eval")

print(results.key)
# 'eval'
```

Can you just update to use that instead?

Out of curiosity, were you following along with a tutorial or documentation somewhere that suggested to use `results.eval_key`? I don't believe we formally documented that `results.eval_key` should be available.

**Comment by CexyNature** [comment]
Thanks for the prompt response.
Yes, that will work. Appreciate the suggestion.

I am using the `results.eval_key` for creating a custom plot, in this case getting the `eval_key` name defined during `dataset.evaluate_detections()` step. It is similar to this [example](https://github.com/voxel51/fiftyone/issues/1635#issuecomment-1191653847). The `eval_key` key is referenced in the documentation [here](https://docs.voxel51.com/api/fiftyone.utils.eval.coco.html#fiftyone.utils.eval.coco.COCODetectionResults).

Thanks again!
