### ISSUE TITLE
Images showing up twice in App

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#292]
I'm working off of the `det-blog` branch that was updated with `develop` a few days ago. I'm not sure if this happens when just loading the dataset into a session but it is easy to spot when sorting by a field since the same images will show up close together. 

The images are not actually duplicated in the dataset and when clicking on them they have the same ID. Clicking on one selects them both.

I'll play around with it to see how easy it is to replicate.

![Screenshot from 2020-07-22 20-44-23](https://user-images.githubusercontent.com/21222883/88243095-492e0900-cc5d-11ea-82ab-35d607c96711.png)
![Screenshot from 2020-07-22 20-46-22](https://user-images.githubusercontent.com/21222883/88243098-4af7cc80-cc5d-11ea-9786-ece6d6832391.png)
![Screenshot from 2020-07-22 20-46-33](https://user-images.githubusercontent.com/21222883/88243099-4af7cc80-cc5d-11ea-9c7e-eca90f954372.png)

**Comment by benjaminpkane** [comment]
Happy to dig into this if this can still be reproduced. It may not be an issue anymore, though. A fundamental error in pagination has been fixed.
