### ISSUE TITLE
[BUG] Cannot visualise/show RGB semantic segmentations masks

### ISSUE THREAD

**Issue by cyberkostas1984** [voxel51/fiftyone#2920]
### Instructions

Hi,
I'm trying to visualise imported RGB masks (.png) on 51, but while the masks looks like they are loaded, for some reason the image doesn't show up at all.

### System information

-   **OS Platform and Distribution**: `Windows 11, 22H2`, Build: `22621.1555`) using WSL2: `Ubuntu-20.04`
-   **Python version** (`python --version`): `3.10.9`
-   **FiftyOne version** (`fiftyone --version`): 
-   **FiftyOne installed from** (pip or source): `pip`, version: `22.3.1`
-   **Virtual Env Conda**:  `22.9.0`
-   **Chrome Version**: `112.0.5615.138`

### Commands to reproduce

Steps:
1. Create a new virtual env with the specks above
2. Update the dataset paths to point to where the image and mask is stored on your local env.
3. Run the code below on a Jupyter env on VS Code
4. Open 51 on browser using Chrome on `http://localhost:5151`

### Describe the problem

Fiftyone doesn't display correctly RGB masks stored as png image files.
The only way this can work is by first converting the mask to greyscale, save it, and then load that mask.

### Code to reproduce issue
RGB code:
```python
import fiftyone  as fo
import fiftyone.utils.labels as foul

dataset_rgb = fo.Dataset.from_dir(
    data_path="path/to/images",
    labels_path="path/to/masks_rgb",
    dataset_type=fo.types.ImageSegmentationDirectory,
    label_field="segmentations",
)

foul.segmentations_to_detections(
    dataset,
    "segmentations",
    "instances",
    mask_targets={
        "#000000": "__background__",
        "#32ff32": "big_dog",
        "#ff3232": "small_dog"
    },
    mask_types="thing"
)
dataset.save()
session = fo.launch_app(dataset)
```
Greyscale mask code:
```python
import fiftyone  as fo
import fiftyone.utils.labels as foul

dataset = fo.Dataset.from_dir(
    data_path="path/to/images",
    labels_path="path/tomasks",
    dataset_type=fo.types.ImageSegmentationDirectory,
    label_field="segmentations",
)

foul.segmentations_to_detections(
    dataset,
    "segmentations",
    "instances",
    mask_targets={111: "big_dog", 170: "small_dog"},
    mask_types="thing"
)
dataset.save()

session = fo.launch_app(dataset)
```

### Other info/logs
While converted masks to detections seem to have happenned correctly, the image doesn't load:
![image](https://user-images.githubusercontent.com/86245526/234018397-460e6a23-e3a8-46c7-b3a3-65795d4c5e39.png)
Example of detection:
![image](https://user-images.githubusercontent.com/86245526/234018492-05978ba3-a692-41df-afdc-89e8dcdea3a1.png)

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

### Data used for this use case/but.
![dogs](https://user-images.githubusercontent.com/86245526/234016681-10d7a21c-a93d-40ba-847d-2724aff47c12.jpg)
![dogs](https://user-images.githubusercontent.com/86245526/234016733-6e9a7ffa-d6c9-4ba5-bec9-af1874116265.png)
![dogs](https://user-images.githubusercontent.com/86245526/234019764-df827a31-ba7e-4946-a4ff-054444a4e022.png)

Any suggestions, advice, or guidance on how to tackle this is welcomed :).
Thanks

**Comment by brimoor** [comment]
Hmm, thanks for reporting this. I am able to produce the issue. The images fail to render specifically when working with the RGB masks.

I placed the original image and RGB masks here:

```
/tmp/dogs/images/dogs.jpg
/tmp/dogs/masks-rgb/dogs.png
```

and then ran this:

```py
import fiftyone  as fo
import fiftyone.utils.labels as foul\

mask_targets = {
    "#000000": "__background__",
    "#32ff32": "big_dog",
    "#ff3232": "small_dog"
}

dataset = fo.Dataset.from_dir(
    data_path="/tmp/dogs/images",
    labels_path="/tmp/dogs/masks-rgb",
    dataset_type=fo.types.ImageSegmentationDirectory,
    label_field="segmentations",
)

dataset.default_mask_targets = mask_targets

foul.segmentations_to_detections(
    dataset,
    "segmentations",
    "instances",
    mask_targets=mask_targets,
    mask_types="thing",
)

# Looker fails to render
session = fo.launch_app(dataset)

# Everything works
session.view = dataset.exclude_fields("segmentations")
```

**Comment by brimoor** [comment]
@benjaminpkane @sashankaryal can one of you track down why Looker doesn't like the RGB dog mask?
