### ISSUE TITLE
[FR] Add DINOv2 model to model zoo

### ISSUE THREAD

**Issue by ilyanelken** [voxel51/fiftyone#2944]
### Proposal Summary

**Hi, is it possible to add DINOv2 model to pytorch model zoo?**

### Motivation

-   What is the use case for this feature?
-   Why is this use case valuable to support for FiftyOne users in general?
-   Why is this use case valuable to support for your project(s) or organization?
-   Why is it currently difficult to achieve this use case?

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

Having **DINOv2** in model zoo will bring more attention to this library, and might significantly
increase the number of new users.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by brimoor** [comment]
Hi @ilyanelken, I'm working on this in https://github.com/voxel51/fiftyone/pull/2951 🙌

**Comment by ilyanelken** [comment]
@brimoor Great, thanks!  Do you have an estimation when it is expected to be integrated?

**Comment by swheaton** [comment]
Closed by #2951
