### ISSUE TITLE
[BUG] No plot result for plot_confusion_matrix and plot_pr_curves

### ISSUE THREAD

**Issue by snkrbhr** [voxel51/fiftyone#2950]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04):
-   **Python version** (`python 3.9.7`):
-   **FiftyOne version** (`fiftyone 0.20.1`):
-   **FiftyOne installed from** (pip):

### Describe the problem

I successfully call the evaluate_detections and got the evaluation result, but when I and calling plot_confusion_matrix  and plot_pr_curves there is no result. Note I and able to print the result using print_report() method.

### Code to reproduce issue

```
#Evaluate the predictions in the `faster_rcnn`
results_yolo = dataset.evaluate_detections(
    "yolo_predictions",
    gt_field="ground_truth_detections",
    eval_key="eval_yolo",
    compute_mAP=True,
)
#got nice result
results_yolo.print_report() 

#error 1
plot = results_yolo.plot_pr_curves(classes=classes)
plot.show() # no output
plot.save('res'.png) # this is working

#error 2 
plot = results_yolo.plot_confusion_matrix(classes=classes)
plot.show() # no output

plot = results_yolo.plot_confusion_matrix(classes=classes, backend='matplotlib')
plot.show() # working

```
### Other info/logs

Please note the I have checked the plotly versions and ploted a graph using plotly whicich is working. I guess there is some issue in the fiftyone methods.

![Screenshot 2023-05-03 at 12-14-50 New_2023_ICIP_unlabel_data - Jupyter Notebook](https://user-images.githubusercontent.com/10548519/235847946-a5bf8956-b19e-4541-b185-812446a78224.png)

![Screenshot 2023-05-03 at 12-13-53 New_2023_ICIP_unlabel_data - Jupyter Notebook](https://user-images.githubusercontent.com/10548519/235847991-56fb60e4-79fd-4f10-bf63-cec3f8ac507b.png)
![Screenshot 2023-05-03 at 12-14-16 New_2023_ICIP_unlabel_data - Jupyter Notebook](https://user-images.githubusercontent.com/10548519/235848443-eb4d3bc8-6637-432f-886a-20e564654b91.png)

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by snkrbhr** [comment]
@brimoor, my installation already has those requirements. Unfortunately sill I cannot produce the plots.

![image](https://user-images.githubusercontent.com/10548519/236386864-252549b4-08fc-4ec2-aa7e-358187adf22c.png)

**Comment by brimoor** [comment]
I believe that updating the following package versions should resolve this issue:

```shell
# If using Jupyter notebooks
pip install "notebook>=6" "ipywidgets>=8,<9"
  
# If using JupyterLab
pip install "jupyterlab>=4" "ipywidgets>=8,<9"
```
