### ISSUE TITLE
[BUG] Default Kitty download takes 93.7 GB

### ISSUE THREAD

**Issue by rusmux** [voxel51/fiftyone#3006]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22.04
-   **Python version** (`python --version`): Python 3.10.11
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.20.1, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
fiftyone zoo datasets load kitti --split train
```

### Describe the problem

Loading KITTI [dataset](https://docs.voxel51.com/user_guide/dataset_zoo/datasets.html#kitti) leads to downloading 93.7 GB, however, default train/test detection set of left images should take only ~12 GB.

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
fiftyone zoo datasets load kitti --split train
```

### Other info/logs

```Bash
Downloading split 'train' to '/Users/rusmux/fiftyone/kitti/train'
Downloading labels to '/Users/rusmux/fiftyone/kitti/tmp-download/data_object_label_2.zip'
 100% |████████████████████████████████████████████████████████████████████████████████████████████|   42.7Mb/42.7Mb [17.2s elapsed, 0s remaining, 8.2Mb/s]        
Extracting '/Users/rusmux/fiftyone/kitti/tmp-download/data_object_label_2.zip'
Downloading data to '/Users/rusmux/fiftyone/kitti/tmp-download/data_object_image_2.zip'
   0% |/-------------------------------------------------------------------------------------------|    7.5Mb/93.7Gb [1.8s elapsed, 6.5h remaining, 4.4Mb/s]
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
93.7Gb / 8  = 11.7GB. Does that explain the discrepancy?

Here's the download sources being used for the various media types: https://github.com/voxel51/fiftyone/blob/82b256322549de3e17870b332af70e1eeabc225e/fiftyone/utils/kitti.py#L610

**Comment by rusmux** [comment]
@brimoor Thank you, but I don't quite understand. Is there a way to download only `image_2` and `label_2` for train split and `image_2` for test split? It should be ~12 GB

**Comment by brimoor** [comment]
The progress bar says 93.7Gb, which is 11.7GB. So I think it is doing exactly what you want.

**Comment by rusmux** [comment]
Oh, you mean gigabit, I got it, thank you
