### ISSUE TITLE
[BUG] ValueError: Dataset name 'dataset' is not available

### ISSUE THREAD

**Issue by NevilleMthw** [voxel51/fiftyone#3016]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux Ubuntu
-   **Python version** (`python --version`): 3.10.0
-   **FiftyOne version** (`fiftyone --version`): 0.20.1
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
None
```

### Describe the problem

The problem I am facing is quite strange, I get an error which says ```ValueError: Dataset name 'dataset' is not available```. But the dataset name is already available. However, it gets fixed when I edit the name a second time and then run the code, no errors pop up again.

### Code to reproduce issue

```python
dataset_dir = "/file/path/"
name = "dataset"

# Create the dataset
dataset = fo.Dataset.from_dir(
    dataset_dir=dataset_dir,
    dataset_type=fo.types.ImageClassificationDirectoryTree, # Or ImageClassificationDirectoryTree for classification dataset
    name=name,
)

print(dataset)
```
### Other info/logs

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 2
      1 # Create the dataset
----> 2 dataset = fo.Dataset.from_dir(
      3     dataset_dir=dataset_dir,
      4     dataset_type=fo.types.ImageClassificationDirectoryTree, # Or ImageClassificationDirectoryTree for classification dataset
      5     name=name,
      6 )
      8 print(dataset)

File [~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/fiftyone/core/dataset.py:5199](https://file+.vscode-resource.vscode-cdn.net/home/intern/Desktop/fiftyone-scripts/~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/fiftyone/core/dataset.py:5199), in Dataset.from_dir(cls, dataset_dir, dataset_type, data_path, labels_path, name, label_field, tags, dynamic, **kwargs)
   5097 @classmethod
   5098 def from_dir(
   5099     cls,
   (...)
   5108     **kwargs,
   5109 ):
   5110     """Creates a :class:`Dataset` from the contents of the given directory.
   5111 
   5112     You can create datasets with this method via the following basic
   (...)
   5197         a :class:`Dataset`
   5198     """
-> 5199     dataset = cls(name)
...
    105 if bool(list(conn.datasets.find(query, {"_id": 1}).limit(1))):
--> 106     raise ValueError("Dataset name '%s' is not available" % name)
    108 return slug

ValueError: Dataset name 'dataset' is not available
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by swheaton** [comment]
Hi Neville, this means that there is a dataset called "dataset" already existing.
What do you mean by:
> But the dataset name is already available.

If you run `fo.load_dataset('dataset')` what happens?

**Comment by OlegBEZb** [comment]
> Hi Neville, this means that there is a dataset called "dataset" already existing. What do you mean by:
> 
> > But the dataset name is already available.
> 
> If you run `fo.load_dataset('dataset')` what happens?

I also have this issue. The command returns:
ValueError: Dataset 'dataset' not found

**Comment by swheaton** [comment]
@OlegBEZb can't reproduce on my side. You must have a dataset called 'dataset' that already exists.
What's the result of running 
```python
fo.load_dataset('dataset')
```

**Comment by NevilleMthw** [comment]
> Hi Neville, this means that there is a dataset called "dataset" already existing. What do you mean by:
> 
> > But the dataset name is already available.
> 
> If you run `fo.load_dataset('dataset')` what happens?

I get the result as shown:

```python
Name:        dataset
Media type:  image
Num samples: 3503
Persistent:  False
Tags:        []
Sample fields:
    id:           fiftyone.core.fields.ObjectIdField
    filepath:     fiftyone.core.fields.StringField
    tags:         fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    ground_truth: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Classification)
```

However, when I try to run the above function which is ```fo.Dataset.from_dir()```, it shows me errors but if I change the ```name``` variable to something else, it works. But if I restart my kernel in jupyter notebook and run the cell again, I get the same error back again.

For example, the ```name``` variable does not work with the same value twice until I keep changing it after the first run of the notebook.

```python
ValueError                                Traceback (most recent call last)
Cell In[8], line 3
      1 # Create the dataset
      2 # fo.load_dataset(name)
----> 3 dataset = fo.Dataset.from_dir(
      4     dataset_dir=dataset_dir,
      5     dataset_type=fo.types.ImageClassificationDirectoryTree, # Or ImageClassificationDirectoryTree for classification dataset
      6     name=name,
      7 )
      9 print(dataset)

File [~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/fiftyone/core/dataset.py:5199](https://file+.vscode-resource.vscode-cdn.net/home/intern/Desktop/fiftyone-scripts/~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/fiftyone/core/dataset.py:5199), in Dataset.from_dir(cls, dataset_dir, dataset_type, data_path, labels_path, name, label_field, tags, dynamic, **kwargs)
   5097 @classmethod
   5098 def from_dir(
   5099     cls,
   (...)
   5108     **kwargs,
   5109 ):
   5110     """Creates a :class:`Dataset` from the contents of the given directory.
   5111 
   5112     You can create datasets with this method via the following basic
   (...)
   5197         a :class:`Dataset`
   5198     """
...
    105 if bool(list(conn.datasets.find(query, {"_id": 1}).limit(1))):
--> 106     raise ValueError("Dataset name '%s' is not available" % name)
    108 return slug

ValueError: Dataset name 'dataset1' is not available
```
I have changed to ```name=dataset1```, it will show up the same error even after I restart the kernel and run the cell until I change the name to something else.

Hope it's clear. If not, I can send a screen recording to show how it works.

Thanks,
Neville

**Comment by NevilleMthw** [comment]
Hi, @swheaton thanks for the quick response. I have tried out the second option and it seems to work out just fine. Thanks a lot. 👍🏼

**Comment by MatoFD** [comment]
Hi, I have noticed this happens to me when debugging on Pycharm, if I have a `dataset = fo.Dataset(
        name="Example",
        persistent=False,
    )` in my scripts, everything behaves as expected when running normally. But if I try debugging the code, find a bug, and stop the execution, then next time I try to execute the code it will throw the ValueError of the name not being available. Simply rerunning things without debugging mode clears this error. 
I suspect this happens because when stopping the debugging run, no time is given to the fiftyone library to clear the reserved "Example" name from its internal data, so not commenting this here expecting a fix from fiftyone, just leaving the info in case it helps anyone having this problem.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04.3 LTS
Python version (python --version): Python 3.10.12
FiftyOne version (fiftyone --version): FiftyOne v0.23.2, Voxel51, Inc.
FiftyOne installed from (pip or source): pip
Pycharm Community version: 2023.3.3 installed from ubuntu software snap store
