### ISSUE TITLE
[BUG] ValueError:  Invalid property path 'selections' for layout

### ISSUE THREAD

**Issue by NevilleMthw** [voxel51/fiftyone#3017]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux Ubuntu
-   **Python version** (`python --version`): 3.10.0
-   **FiftyOne version** (`fiftyone --version`): 0.20.1
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
None
```

### Describe the problem

I am trying to use interactive plots which is featured in the documentation: https://docs.voxel51.com/user_guide/plots.htm. I have executed the code, however when I try to use the lasso feature in the visualization, it throws an error. Although, it gets updated in the fiftyone application with the selected images according to which the lasso has selected in the visualization. Could the error be directly linked with plotly or umap or should not be bothered to much about it?

### Code to reproduce issue

```python
results = fob.compute_visualization(
    dataset,
    num_dims=2,
    brain_key="image_embeddings",
    verbose=True,
    seed=51,
)
session = fo.launch_app(dataset)

# Plot embeddings colored by ground truth label
plot = results.visualize(labels="ground_truth.label")
plot.show(height=720)

# Attach plot to session
session.plots.attach(plot)
```

### Other info/logs

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File [~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:674](https://file+.vscode-resource.vscode-cdn.net/home/intern/Desktop/fiftyone-scripts/~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:674), in Widget._handle_msg(self, msg)
    672         if 'buffer_paths' in data:
    673             _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 674         self.set_state(state)
    676 # Handle a state request.
    677 elif method == 'request_state':

File [~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:538](https://file+.vscode-resource.vscode-cdn.net/home/intern/Desktop/fiftyone-scripts/~/anaconda3/envs/fiftyone/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:538), in Widget.set_state(self, sync_data)
    534 """Called when a state is received from the front-end."""
    535 # The order of these context managers is important. Properties must
    536 # be locked when the hold_trait_notification context manager is
    537 # released and notifications are fired.
--> 538 with self._lock_property(**sync_data), self.hold_trait_notifications():
    539     for name in sync_data:
    540         if name in self.keys:

File [~/anaconda3/envs/fiftyone/lib/python3.10/contextlib.py:142](https://file+.vscode-resource.vscode-cdn.net/home/intern/Desktop/fiftyone-scripts/~/anaconda3/envs/fiftyone/lib/python3.10/contextlib.py:142), in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    140 if typ is None:
    141     try:
--> 142         next(self.gen)
    143     except StopIteration:
    144         return False
...
   2650             val_changed = BaseFigure._set_in(self._layout, key_path_str, v)

ValueError: 
Invalid property path 'selections' for layout
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @NevilleMthw 👋 can you share the versions of `plotly` and `ipywidgets` that you're running?

```
pip show plotly
pip show ipywidgets
```

And are you running these examples in a Jupyter notebook? Juptyer lab? Something else?

FYI- I would definitely recommend working directly in the App via the [Embeddings panel](https://docs.voxel51.com/user_guide/app.html#embeddings-panel) rather than using `session.plots.attach()`, which is mostly deprecated now that embeddings visualizations are natively supported in the App.

**Comment by NevilleMthw** [comment]
Hi @brimoor plotly version is 5.9.0 and ipywidgets is 7.5.0. Yes, I am using Jupyter notebook. Maybe I should just transition to the embeddings panel instead.

**Comment by brimoor** [comment]
Hmm, I'm running `plotly==5.9.0` and `ipywidgets==7.7.2`. Can you try upgrading `ipywidgets` to the [latest supported version](https://docs.voxel51.com/user_guide/plots.html#working-in-notebooks)?

```
pip install --upgrade 'ipywidgets<8'
```

**Comment by NevilleMthw** [comment]
Hi @brimoor, I am running plotly version 5.9.0 with ipywidgets version 8.0.6. Anyways, I have followed your recommendation and now using the embeddings tab in your application which works well with no errors.
