### ISSUE TITLE
[BUG] Square aspect in tiling for grouped datasets

### ISSUE THREAD

**Issue by clane9** [voxel51/fiftyone#3070]
### System information

-   **OS Platform and Distribution** (CentOS Linux 8):
-   **Python version** (Python 3.10.11):
-   **FiftyOne version** (0.20.1):
-   **FiftyOne installed from** (pip):

### Describe the problem

I'm creating a [grouped dataset](https://docs.voxel51.com/user_guide/groups.html) containing images and videos with wide aspects. I noticed that for grouped datasets, the aspect in the tiling view is fixed to be square. Whereas in standard datasets, the native image aspect is used for each tile. Ideally, I would like to see the native aspect used by default for all images and groups.

Thanks in advance! Fiftyone is a great tool btw I love it.

### Code to reproduce issue

```python
from pathlib import Path

import fiftyone as fo
import numpy as np
from PIL import Image

dataset = fo.Dataset("aspect_test", persistent=True, overwrite=True)
# Remove group to see correct images
dataset.add_group_field("group", default="img")

img_dir = Path("aspect_test_images")
img_dir.mkdir(exist_ok=True)

samples = []
for ii in range(10):
    group = fo.Group()
    img = Image.fromarray((np.ones((50, 200, 3)) * [255, 0, 0]).astype("uint8"))
    img_path = img_dir / f"img_{ii:02d}.png"
    img.save(img_path)
    sample = fo.Sample(filepath=img_path, group=group.element("img"))
    samples.append(sample)

dataset.add_samples(samples)
```

### Other info/logs

Example with group:

<img width="920" alt="Screen Shot 2023-05-17 at 3 38 50 PM" src="https://github.com/voxel51/fiftyone/assets/11963692/42854552-659a-4a84-a7fe-bd7aab2add39">

Example without group:

<img width="922" alt="Screen Shot 2023-05-17 at 3 39 36 PM" src="https://github.com/voxel51/fiftyone/assets/11963692/9092902f-ca1d-434b-8167-b9e10b6473f2">

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
This will be fixed in the next release. Stay tuned!

**Comment by clane9** [comment]
That's great! Will be looking out for it. Closing the issue.
