### ISSUE TITLE
[FR] scale.py label import "open" line type

### ISSUE THREAD

**Issue by fnobis** [voxel51/fiftyone#3119]
### Proposal Summary

We import "line" type labels from scale. These lines are not meant to describe a "closed" outline for the downstream task.
The current scale.py file in `_parse_objects()` imports them as `closed=True` which I manually set to False in a local version of the file.

I am not familar if there is also a way to label closed lines in scale and if the difference can be infered from their json format. In our file, I just find the "line" type and its vertices, representing an "open" line. If there is a way to distinguish the two types, it would be good to implement this decision in the code.

Otherwise the closed=True/False decision could also be passed as a parameter to the import function, depending on what the design choices fiftyone has in mind for the parametrization there.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by brimoor** [comment]
Actually I'd just call this a bug in our implementation: very likely `"line"` annotation are implicitly not closed. If it was a closed shape, you'd probably have used `"polygon"` annotations instead!
