### ISSUE TITLE
Unable to access app from remote machine

### ISSUE THREAD

**Issue by vidit98** [voxel51/fiftyone#3121]
### System information

-   **OS Platform and Distribution**:  Linux Ubuntu 16.04
-   **Python version**: 3.9.13
-   **FiftyOne version**: FiftyOne v0.20.1, Voxel51, Inc.
-   **FiftyOne installed from**: pip

### Commands to reproduce

I used the script below on a remote server and tried to access the app using `ssh -N -L 5151:127.0.0.1:5151 [<username>@]<hostname>`.  However, when I open the link 127.0.0.1:5151 on the local machine I was not able to access it.
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset, remote=True)
```

### Other info/logs

I was getting this message on terminal

`channel 3: open failed: connect failed: Connection refused`

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [x] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by vidit98** [comment]
need to add `session.wait()`

**Comment by pathikg** [comment]
Thanks @vidit98 
I added that and it worked but the session automatically closes after certain amount of time
How can I resolve this?
