### ISSUE TITLE
[FR] Adjustable padding when coercing detections to image classification

### ISSUE THREAD

**Issue by Interpause** [voxel51/fiftyone#3126]
### Proposal Summary

<https://docs.voxel51.com/user_guide/export_datasets.html#object-patches>

Add a new kwarg `padding: float = 0.0` to `dataset.export()` that adds padding to object patches when coercing detection labels to classification labels.

### Motivation

Padding around the subject of an image is needed for augmentations that adjust cropping and rotation. Such augmentations are useful for training model resilience against poor crops. The current way to do this would involve adjusting labels for all samples, which is inconvenient.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

I am new to using `fiftyone` and am not sure about the internal workings. However, I think the above could be done by:

- Read user-specified field (e.g. `ground_truth`) for detection.
- Add padding relative to the detection size.
- Save new label to temporary field.
- Export the temporary field as image classification.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by brimoor** [comment]
Actually this is already supported! The `export()` documentation mentions that you can pass extra `**kwargs` for patches:
https://github.com/voxel51/fiftyone/blob/660545dcbc4ad3883cc9bb59f53c212b5e85e628/fiftyone/core/collections.py#L8063-L8066

Specifically, you can pass the `alpha` parameter defined here:
https://github.com/voxel51/fiftyone/blob/660545dcbc4ad3883cc9bb59f53c212b5e85e628/fiftyone/utils/patches.py#L38-L43

**Comment by Interpause** [comment]
oh darn, I am already done coding it...
