### ISSUE TITLE
[BUG] Detections do not match label files

### ISSUE THREAD

**Issue by rusmux** [voxel51/fiftyone#3128]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22.04
-   **Python version** (`python --version`): 3.10.11
-   **FiftyOne version** (`fiftyone --version`): v0.20.1
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

```Python
from pathlib import Path

import cv2
import fiftyone as fo
import numpy as np


def create_example_dataset(dataset_dir: Path, label: np.ndarray) -> None:
    dataset_dir.mkdir(exist_ok=True)
    (dataset_dir / "images").mkdir(exist_ok=True)
    (dataset_dir / "labels").mkdir(exist_ok=True)

    image = np.zeros((256, 256, 3))
    cv2.imwrite(str(dataset_dir / "images/0.jpg"), image)

    np.savetxt(dataset_dir / "labels/0.txt", label)

    dataset_yaml = f"""names:\n- object\nnc: 1\npath: {dataset_dir}\nval: ./images"""
    with open(dataset_dir / "dataset.yaml", "w") as yaml_file:
        yaml_file.write(dataset_yaml)


def main() -> None:
    dataset_dir = Path("fiftyone_bug_example").resolve()
    label = np.array([
        [0., 0.9965897, 0.7488701, 0.00680916, 0.01683898],
        [0., 0.96171546, 0.02009826, 0.01950754, 0.02677685],
        [0., 0.28373685, 0.7186426, 0.02245206, 0.02208399]
    ])
    create_example_dataset(dataset_dir, label)

    dataset = fo.Dataset.from_dir(
        dataset_dir=dataset_dir,
        dataset_type=fo.types.YOLOv5Dataset,
    )
    sample = dataset.first()
    boxes = np.array([detection["bounding_box"] for detection in sample["ground_truth"]["detections"]])

    print("Fiftyone label:")
    print(boxes)
    print()
    print("Raw label:")
    print(label[:, 1:])


if __name__ == "__main__":
    main()
```

This prints:

```Bash
Fiftyone label:
[[0.99318512 0.74045061 0.00680916 0.01683898]
 [0.95196169 0.00670983 0.01950754 0.02677685]
 [0.27251082 0.7076006  0.02245206 0.02208399]]

Raw label:
[[0.9965897  0.7488701  0.00680916 0.01683898]
 [0.96171546 0.02009826 0.01950754 0.02677685]
 [0.28373685 0.7186426  0.02245206 0.02208399]]
```

### Describe the problem

Fiftyone detection points and raw label points are different.

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Please do not use screenshots for sharing text. Code snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @rusmux 

[YOLO bounding boxes](https://github.com/voxel51/fiftyone/blob/a53b9019002e57e7ebabf9f2dc357b95e3c0567b/fiftyone/utils/yolo.py#L1010C13-L1010C13) are formatted as `<x-center> <y-center> <width> <height>`. FiftyOne uses `<x-top-left> <y-top-left> <width> <height>`. So a difference in values is expected. The height and width remain the same.
