### ISSUE TITLE
[FR] Do not create a database connection during import

### ISSUE THREAD

**Issue by pietermarsman** [voxel51/fiftyone#3189]
### Proposal Summary

Do not setup a database connection during import. 

### Motivation

Setting up a database connection can be time consuming and error prone. Doing it implicitly during an import is unexpected (for me). It leads to errors and creates global state (that we all hate). This is a bad code smell. 

There is a very good alternative: having a client object that represents the connection. 

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

We including FiftyOne in our multi-gpu training code and it crashed because of it. Multiple processes tried to connect to the same port. This is an unwanted side-effect of doing an import in a file that is not used during the training. 

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [ ] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [x] No. I cannot contribute this feature at this time

**Comment by pietermarsman** [comment]
To reproduce

```python
from multiprocessing import Process


def main():
    import fiftyone


if __name__ == "__main__":
    processes = [Process(target=main) for i in range(2)]
    for p in processes:
        p.start()
    for p in processes:
        p.join()
```

Works with 1 process. Does not with 2. 

```
Subprocess ['.../.venv/lib/python3.10/site-packages/fiftyone/db/bin/mongod', '--dbpath', '.../.fiftyone/var/lib/mongo', '--logpath', '.../.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
{"t":{"$date":"2023-06-12T15:49:34.228Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"-","msg":"Renamed existing log file","attr":{"oldLogPath":".../.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":".../.fiftyone/var/lib/mongo/log/mongo.log.2023-06-12T15-49-34"}}
```

**Comment by swheaton** [comment]
Hi @pietermarsman this is something we definitely agree with having! I can't give an estimate of when this might be done though because it's not a quick fix unfortunately.

In your particular case, you could try spinning up your own mongodb instance and [pointing fiftyone to it before importing.](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection) I tested this and it worked for me locally with your script above.

e.g.,
```
# No
python pieter.py
# Yes
FIFTYONE_DATABASE_URI=mongodb://localhost:27017 python pieter.py
```

**Comment by brimoor** [comment]
As an aside, even without configuring a database URI as @swheaton described, FiftyOne *is* designed to support concurrent usage in multiple separate processes. EG if you import FiftyOne in multiple shells, a single child process will run the database and shut it down only when all processes are finished.

The specific problem that this issue has identified is that FiftyOne does not seem to support `multiprocessing` when no custom database URI is configured.

**Comment by swheaton** [comment]
Actually I think it works with `multiprocessing` but the problem here is that the two processes both try to start a mongod at the exact same time. The toy script works if I add a 4s delay, for example.

```python
from multiprocessing import Process
import time

def main(i):
    time.sleep(i)
    import fiftyone


if __name__ == "__main__":
    processes = [Process(target=main, args=(i*4,)) for i in range(2)]
    for p in processes:
        p.start()
    for p in processes:
        p.join()
```

**Comment by brimoor** [comment]
Yeah that makes sense. The problem only arises when two processes simultaneously decide they need to be the one that spawns the `mongod` subprocess.

Either way, just confirming that using a custom `database_uri` is the most robust approach to multiple connections.

**Comment by YuseqYaseq** [comment]
Same problem here. In my case I have a huge pipeline with a yaml config that defines how an experiment should be configured (I would like to configure a mongo connection in this file). The pipeline has some top level imports (one of which contains `import fiftyone` itself). All in all this means that I have to read the yaml and execute some code before importing files which is a huge pain, because I can't have top level imports.
