### ISSUE TITLE
Add support for storing label maps (and other custom data) at the dataset level

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#320]
> @ehofesmann When trying to add model predictions and only using FiftyOne, there is no way to access the mapping of class names to id. I updated the ImageDetectionSampleParser so that when a Detections is returned, it has a new field for classes.

> @brimoor I do agree that there's an underlying thing to address here. I've been thinking about requesting the ability to store information at the Dataset-level. So you could, for example, store your class list for a particular model or model(s) and then access that when working with your dataset.
> 
> I've also thought about adding an int-valued target field to Classification and Detection so that users can store information in int format (which is more of a native type for model training) rather than string labels (which does also waste space, for example). In such cases, the user would then be forced to provide class label lists at the dataset-level so that the App could lookup the appropriate string values to render. But this could be introduced separately from the dataset-level class list storage idea.

**Comment by tylerganter** [comment]
resolved by #358
