### ISSUE TITLE
[BUG] App throws a ``HTTP 500 Internal Server Error`` when connecting to it via a forwarded port

### ISSUE THREAD

**Issue by stwerner97** [voxel51/fiftyone#3206]
### System information

-   **OS Platform and Distribution**: ``Linux Ubuntu 20.04``
-   **Python version**: ``Python 3.9.16``
-   **FiftyOne version**: ``FiftyOne v0.21.0, Voxel51, Inc.``
-   **FiftyOne installed from**: ``pip``

### Describe the problem

The ``fiftyone app`` throws an ``HTTP 500 Internal Server Error`` once I launch it on a remote kubernetes pod and connect to it via a port forwarding. 

### Commands to reproduce

I launch the fiftyone app in my kubernetes pod with ``fiftyone app launch`` (I also tried the ``--remote`` flag).
On my local machine, I set up a port forwarding as ``kubectl port-forward <my-pod-name> 5151:5151``.

### Other info/logs
The browser displays ``Error: 500 http://127.0.0.1:5151/events`` with the following trace
```
Error: 500 http://127.0.0.1:5151/events
    at fetch (http://127.0.0.1:5151/assets/index.9e36d8f3.js:338:1390)
    at async A (http://127.0.0.1:5151/assets/index.9e36d8f3.js:337:1369)
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @stwerner97. The network request should have a stack trace in the response (in the developer tools network tab). Or if you start the server directly on the pod with `python /path/to/fiftyone/server/main.py` we can see all server output.
