### ISSUE TITLE
[BUG] compute_uniqueness does not create any field.

### ISSUE THREAD

**Issue by FrankwaP** [voxel51/fiftyone#3208]
### System information

-   **Ubuntu 22.04** (e.g., Linux Ubuntu 16.04):
-   **Python 3.9.16** (`python --version`):
-   **FiftyOne 0.21.0** (`fiftyone --version`):
-   **FiftyOne installed pip** (pip or source):

### Describe the problem

The [documentation](https://docs.voxel51.com/tutorials/uniqueness.html) says it will create a "uniqueness" field, but it's not the case.  
As a side note, the [documentation](https://docs.voxel51.com/api/fiftyone.brain.html#fiftyone.brain.compute_uniqueness) does not mention that an object is returned.

### Code to reproduce issue
```python
import fiftyone.zoo as foz
import fiftyone.brain as fob

dataset = foz.load_zoo_dataset(
    "coco-2014",
    split="validation",
    label_types=["segmentations"],
    max_samples=5,
)

res = fob.compute_similarity(dataset)

print('dataset:\n', dataset)  # no "uniqueness" field as suggested in the doc 
print('res:\n',res)  # has an undocumented return
```

### Other info/logs

Here's the log:

> /.../python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since  0.13 and may be removed in the future, please use 'weights' instead.
>  warnings.warn(
> /.../python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
>   warnings.warn(msg)
> Computing embeddings...
>  100% |█████████████████████| 5/5 [281.0ms elapsed, 0s remaining, 17.8 samples/s]     

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @FrankwaP The code snippet you shared is calling `fob.compute_similarity()`. `fob.compute_uniqueness()` should behave as expected.
```py
import fiftyone.zoo as foz
import fiftyone.brain as fob

dataset = foz.load_zoo_dataset(
    "coco-2014",
    split="validation",
    label_types=["segmentations"],
    max_samples=5,
)

res = fob.compute_similarity(dataset)

print('dataset:\n', dataset)  # `uniqueness` should be present
print('res:\n',res)  # None
```

If there is another issue, please feel free to reopen
