### ISSUE TITLE
[BUG] Adding classifications recipe CIFAR10 model

### ISSUE THREAD

**Issue by Sejal1506** [voxel51/fiftyone#3221]
### System information

-   **Windows 10 ** (e.g., Linux Ubuntu 16.04):
-   **Python 3.11.4** (`python --version`):
-   **FiftyOne version** (`fiftyone --version`):
-   **FiftyOne installed from pip** :

### Commands to reproduce

```py
import sys

import numpy as np
import torch
import torchvision
from torch.utils.data import DataLoader

import fiftyone.utils.torch as fout

sys.path.insert(1, "PyTorch_CIFAR10")
from cifar10_models import resnet50


def make_cifar10_data_loader(image_paths, sample_ids, batch_size):
    mean = [0.4914, 0.4822, 0.4465]
    std = [0.2023, 0.1994, 0.2010]
    transforms = torchvision.transforms.Compose(
        [
            torchvision.transforms.ToTensor(),
            torchvision.transforms.Normalize(mean, std),
        ]
    )
    dataset = fout.TorchImageDataset(
        image_paths, sample_ids=sample_ids, transform=transforms
    )
    return DataLoader(dataset, batch_size=batch_size, num_workers=4)


def predict(model, imgs):
    logits = model(imgs).detach().cpu().numpy()
    predictions = np.argmax(logits, axis=1)
    odds = np.exp(logits)
    confidences = np.max(odds, axis=1) / np.sum(odds, axis=1)
    return predictions, confidences, logits


model = resnet50(pretrained=True)
model_name = "resnet50"

num_samples = 1000
batch_size = 20
view = dataset.take(num_samples)
image_paths, sample_ids = zip(*[(s.filepath, s.id) for s in view.iter_samples()])
data_loader = make_cifar10_data_loader(image_paths, sample_ids, batch_size)


with fo.ProgressBar() as pb:
    for imgs, sample_ids in pb(data_loader):
        predictions, _, logits_ = predict(model, imgs)

       
        for sample_id, prediction, logits in zip(sample_ids, predictions, logits_):
            sample = dataset[sample_id]
            sample.tags.append("processed")
            sample[model_name] = fo.Classification(
                label=classes[prediction], logits=logits,
            )
            sample.save()
```

### Describe the problem

After running this code which is there in fiftyone documentation under dinfing classification mistakes. This is the code for adding predictions to the dataset while running this code i am not able to install ResNet50 from cifar_10 model. This is the snippet of error i am recieving after running this code;

![image](https://github.com/voxel51/fiftyone/assets/106472809/57cb4305-3b8c-434e-ac54-b6a4a2db0607)

### Code to reproduce issue

sys.path.insert(1, "PyTorch_CIFAR10")
from cifar10_models import resnet50

### Other info/logs
This is the link from the documentation which i have exactly copied: https://docs.voxel51.com/tutorials/classification_mistakes.html

### What areas of FiftyOne does this bug affect?

-    `Core`: Core Python library issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-    No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @Sejal1506. Confirming the below snippet from the [recipe](https://docs.voxel51.com/recipes/adding_classifications.html) was run first?
```py
!git clone --depth 1 --branch v2.1 https://github.com/huyvnphan/PyTorch_CIFAR10.git

# Download the pretrained model (90MB)
!eta gdrive download --public \
    1dGfpeFK_QG0kV-U6QDHMX2EOGXPqaNzu \
    PyTorch_CIFAR10/cifar10_models/state_dicts/resnet50.pt
```

**Comment by Sejal1506** [comment]
Yes I ran this code first.

**Comment by benjaminpkane** [comment]
There are migration logs in the error screenshot indicating that `fiftyone` had not yet been imported. Ensuring the `PyTorch_CIFAR10` clone will resolve the issue. I'm not sure this is a FiftyOne specific bug
