### ISSUE TITLE
[BUG] Yolov5 export creates invalid dataset.yaml file.

### ISSUE THREAD

**Issue by matthewDDennis** [voxel51/fiftyone#3235]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Windows 11
-   **Python version** (`python --version`): 3.9.13
-   **FiftyOne version** (`fiftyone --version`): 0.21.0
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce
I am using a Notebook to flesh out automating the creation of Yolov5 models.
The dataset.yaml file has incorrect values for training using the YoloV5 6.2.3 pip package train.py.

### Describe the problem

I am using a Notebook to flesh out automating the creation of Yolov5 models.
The dataset.yaml file has incorrect values for training. I am getting 'validation:' instead of 'val:'

Is there a way of renaming the ' validation' split to 'val'?

I am expecting 
``` json
names:
- Raccoon
- Cat
- Dog
- Squirrel
- Skunk
nc: 5
path: c:\Dev\Ultralytics\Training\datasets\critters2
test: .\images\test\
train: .\images\train\
val: .\images\validation\
```
but I am getting
``` json
names:
- Raccoon
- Cat
- Dog
- Squirrel
- Skunk
nc: 5
path: c:\Dev\Ultralytics\Training\datasets\critters2
test: .\images\test\
train: .\images\train\
validation: .\images\validation\
```

### Code to reproduce issue
I create a dataset from the Open Images V7 repo.
``` python
import fiftyone as fo
import fiftyone.zoo as foz

splits = ['train', 'validation', 'test']
numSamples = 100
seed = 42
classes = ['Raccoon', 'Cat', 'Dog', 'Squirrel', 'Skunk']

# Get 100 images (maybe in total, maybe of each split) from fiftyone. We'll ask FiftyOne to
# use images from the open-images-v7 dataset and store information of this download in the
# dataset named 'open-images-critters'. 

# The data that's downloaded will include the images, annotations, and a summary of what's
# been downloaded. That summary will be stored /Users/<username>/.FiftyOne in a mongoDB. 
# The images / annoations will be un /Users/<username>/FiftyOne.

if fo.dataset_exists('open-images-critters'):
    fo.delete_dataset('open-images-critters')

dataset = fo.Dataset('open-images-critters')

for thing in classes:
    print(f'getting {thing}s from Open Image V7')
    sub_dataset = foz.load_zoo_dataset(
        'open-images-v7',
        # Don't specify a split, so we get all of them
        #splits=splits,
        label_types=['detections'],
        classes = thing,
        max_samples=numSamples,
        seed=seed,
        shuffle=True,
        dataset_name=f'open-images-{thing}')

    # Merge the sub_dataset into the main dataset
    dataset.merge_samples(sub_dataset) 
    print('------------------')

# Take a quick peek to see what's there
print(dataset)

# For whenever you want to see what's been loaded.
#print(fo.list_datasets())
```

I then export the train, validation, and test splits to a YoloV5 dataset
``` python
import fiftyone as fo

export_dir = 'datasets/critters2'
label_field = 'detections'  # for example

# The splits to export
splits = ['train', 'validation', 'test']

# All splits must use the same classes list
classes = ['Raccoon', 'Cat', 'Dog', 'Squirrel', 'Skunk']

# The dataset or view to export
# We assume the dataset uses sample tags to encode the splits to export
dataset_or_view = fo.load_dataset('open-images-critters')

# Export the splits
for split in splits:
    split_view = dataset_or_view.match_tags(split)
    split_view.export(
        export_dir=export_dir,
        dataset_type=fo.types.YOLOv5Dataset,
        #label_field=label_field,
        split=split,
        classes=classes,
    )
```

I attempt to train with the following in my notebook
``` python
!python ./venv/Lib/site-packages/yolov5/train.py --batch 16 --weights models/yolov5s.pt --data datasets/critters2/dataset.yaml --project train/critters2 --name 100ep --epochs 100 --device 0 --freeze 0
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ X] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [X ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
You can rename the `validation` tag to `val` on your dataset before exporting:

```py
view = dataset.match_tags("validation")
view.tag_samples("val")
view.untag_samples("validation")
```

**Comment by matthewDDennis** [comment]
Thank you very much.

The documentation, while being technically correct, really didn't help trying to figure this out.

**Comment by matthewDDennis** [comment]
Worked like magic. Thanks again.
