### ISSUE TITLE
[FR] Dynamically install default MongoDB distribution

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#3236]
Currently, when installing `fiftyone` on Ubuntu 22.04, `fiftyone-db-ubuntu2204` must be installed alongside it for compatibility issues (see https://github.com/voxel51/fiftyone/issues/1988).

```
pip install fiftyone
pip install fiftyone-db-ubuntu2204
```

A general solution to ensure MongoDB compatibility is dynamically resolve and download the correct default db on first import (when a database URI is not set). This approach would remove the need to distribute distribution specific `fiftyone-db` packages.

**Comment by brimoor** [comment]
For context, sadly pypi does not support uploading different `fiftyone-db` wheels for different Linux distributions:
https://github.com/pypa/packaging-problems/issues/69

So @benjaminpkane's dynamic resolution proposal does indeed seem necessary.

**Comment by brimoor** [comment]
See also: #3321, #2961, #2900, #2737, #2480, #1988, #1803
