### ISSUE TITLE
how to load large dataset in streaming way

### ISSUE THREAD

**Issue by winnechan** [voxel51/fiftyone#3241]
I am trying to load large dataset like openimages-v6 with `fo.zoo.load_zoo_dataset`. however, when I have downloaded the dataset before, it still takes long time to load the whole dataset one by one. I have checked the API docs and not found a solution to load the dataset in streaming way, which enables me to loop over the dataset with fast dataset initialization and less memory.

can someone help? thx!

**Comment by benjaminpkane** [comment]
Hi @winnechan. I recommend marking your datasets as [persistent](https://docs.voxel51.com/user_guide/using_datasets.html#dataset-persistence) after creation so they remain in the database across processes and do not have to imported from disk again.
```
dataset.persistent = True
```
