### ISSUE TITLE
[BUG] Thumbnails don't match full image when filters are used.

### ISSUE THREAD

**Issue by tfriedel** [voxel51/fiftyone#3247]
### System information

-   **OS Platform and Distribution** Ubuntu 22.04.2 LTS
-   **Python version** 3.10.6
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.21.1
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

### Describe the problem

We have a dataset containing crop images. Some images where prediction differs from ground truth were marked with the tag "mistake". We apply a filter for tag "mistake" by selecting "mistake" in sample_tags. We also filter for a crop by selecting labels / ground_truth, label: CAULIFLOWER. When clicking on images in the gallery we see the full image popping up, however in some cases it looks different from the thumbnail. It also shows different labels, ids etc. 
This does not happen if we don't apply filters. 

We found the following workaround, where we basically switch from "show samples with tags" to "omit samples with tags" and back again:
first select sample_tags: mistake
then: labels / ground_truth, label: CAULIFLOWER
then: in sample tags click "Show samples with tags". 
Then: "omit samples with tags". 
Then: "show samples with tags"

We then also found the bug is not in version 0.20.1 and we downgraded now. 

### Code to reproduce issue
edit: see simpler MNIST example below in thread
We create an image classification dataset like this:
```py
from tqdm import tqdm
sub_df = df_ffint3
dataset_name = 'ffint3_2'
try:
    dataset_ffint3 = fo.load_dataset(dataset_name)
    dataset_ffint3.delete()
except:
    pass
dataset = fo.Dataset(name=dataset_name)
samples = []
dataset.add_sample_field(
    "meerkat_id", fo.StringField, description="meerkat _id"
)
dataset.add_sample_field(
    "feedforward_integer", fo.IntField, description="feedforward_integer"
)
for _, row in tqdm(sub_df.iterrows(), total=len(sub_df)):
    filepath = row['path']
    if not filepath.startswith('/'):
        filepath = '/mnt/shared/plantixdata-resized/1920/' + filepath
    sample = fo.Sample(filepath=filepath)
    sample["ground_truth"] = fo.Classification(label=row['variety'])
    sample["prediction"] = fo.Classification(label=row['pred_crop'], confidence=row['pred_crop_score'])
    tags = []
    if row['stage'] >= 4:
        tags.append('labeled')
    elif row['feedforward_integer'] == 3:
        tags.append('ffint3')
    if sample['ground_truth']['label'] != sample['prediction']['label']:
        tags.append('mistake')
    sample['tags'] = tags
    sample['meerkat_id'] = str(row['id'])
    if row['feedforward_integer']:
        sample['feedforward_integer'] = row['feedforward_integer']
    
    dataset.add_sample(sample)
    samples.append(sample)
```

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Please do not use screenshots for sharing text. Code snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [x] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @tfriedel. This is a bug we'd like to fix as we want the App to be accurate in its filtering. Is this is an issue for you on `0.21.0`, as well?

If you're able to share reproduction code using a zoo dataset, or something that can run without file system setup it would expedite things.

**Comment by tfriedel** [comment]
@benjaminpkane I don't find the issue in 0.21.0. Going to try a zoo dataset now.

**Comment by tfriedel** [comment]
I managed to reproduce it with MNIST:

```py
import fiftyone as fo
import fiftyone.zoo as foz
dataset = foz.load_zoo_dataset("mnist", split="test")
session = fo.launch_app(dataset, port=5001, remote=False)
```
Select ground truth -> label -> "4 - four".  Click on right most image in 4th row (assuming each row shows 6 images). The first few images seem ok. Every image below fourth row doesn't match the thumbnail.

**Comment by benjaminpkane** [comment]
Thanks @tfriedel! I'm able to reproduce and have a [fix](https://github.com/voxel51/fiftyone/pull/3249). I will post `0.21.2rc1` later today so it's available (will confirm).

Thank you for making this known! 👍

**Comment by benjaminpkane** [comment]
Hi @tfriedel. We went ahead with a full patch release ([0.21.2](https://pypi.org/project/fiftyone/0.21.2/). Thanks again
