### ISSUE TITLE
[DOCS]

### ISSUE THREAD

**Issue by Sejal1506** [voxel51/fiftyone#3264]
### URL(s) with the issue

https://voxel51.com/computer-vision-use-cases/automotive/

### Description of proposal (what needs changing)

Can you demonstrate like how exactly fiftyone can be used in automotives.
Developers of automotive applications can benefit from FiftyOne’s ability to visualize large-scale multimodal data including images, videos, and point clouds related to road scenes. The model evaluation capabilities of FiftyOne are also instrumental in ensuring the quality of models prior to deploying them in vehicles on the road.
I am not able to understand it's application like what does it exactly mean when it says model evaluation capabilities.

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently
-   [ ] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [X] No. I cannot contribute a documentation fix at this time

**Comment by benjaminpkane** [comment]
Hi @Sejal1506. This is a business related comment out of scope for [docs.voxel51.com](https://docs.voxel51.com). Feel free to schedule a [workshop](https://voxel51.com/schedule-teams-workshop/) if you and your company are interested Teams and business applications of FiftyOne.
