### ISSUE TITLE
[BUG] SKlearnSimilarityIndex._kneighbors including self-distance for small datasets

### ISSUE THREAD

**Issue by allenleetc** [voxel51/fiftyone#3305]
### System information

-   **OS Platform and Distribution** ubuntu 20.04
-   **Python version** 3.10
-   **FiftyOne version** 0.13.3
-   **FiftyOne installed from** pip

### Commands to reproduce

SKlearnSimiliartyIndex._kneighbors (used by plot_distances()) appears to include the 0.0 self-distance when the dataset size is small. 

The shape returned also differs which is potentially an issue

```
import fiftyone 
import fiftyone.brain as fob

# ds is a dataset with 50k samples

si = fob.compute_similarity(ds,backend='sklearn',embeddings=np.random.rand(len(ds),128))
_,dists0 = si._kneighbors(k=1,return_dists=True)
print(dists0.shape,dists0[:10])
si = fob.compute_similarity(ds.limit(100),backend='sklearn',embeddings=np.random.rand(100,128))
_,dists1 = si._kneighbors(k=1,return_dists=True)
print(dists1.shape,dists1[:10])
```

This returns
```
Generating neighbors graph for 50000 embeddings...
Index complete
(50000, 1) [[1.0636905 ]
 [1.14580266]
 [1.06965531]
 [1.09768375]
 [1.1370769 ]
 [1.12103635]
 [1.11061701]
 [1.13043187]
 [1.12858513]
 [1.1433385 ]]
Generating index for 100 embeddings...
Index complete
(100,) [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```
### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

**Comment by brimoor** [comment]
This has been patched and will be available in `fiftyone>0.21.4`.
