### ISSUE TITLE
[FR] Visualise 3D bounding box in the images

### ISSUE THREAD

**Issue by FrankCAN** [voxel51/fiftyone#3311]
### Instructions

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md) for information on what types of issues we address.

1. Please fill in this template to ensure a timely and thorough response
2. Place an "x" between the brackets next to an option if it applies. For example:
    -   [x] Selected option
3. **Please delete everything above this line before submitting the issue**

### Proposal Summary

In a few sentences, provide a clear, high-level description of the feature request.

### Motivation

-   What is the use case for this feature?
Visualize the 3D bounding boxes in both image and point cloud datasets.

-   Why is this use case valuable to support for FiftyOne users in general?
It makes us easier to view the position of 3D bounding box in the point cloud, and in the images. It is supposed to be useful in the point cloud and image sensor fusion research, such as autonomous driving.

-   Why is this use case valuable to support for your project(s) or organization?
My work is for 3D object detection model development in the company, and we mainly use both lidar and camera sensors.

-   Why is it currently difficult to achieve this use case?
Currently, our Fiftyone only supports to view the 2D bounding box in the image, which is difficult to precisely see the bounding box position in the 3D world.

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [ ] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [x] No. I cannot contribute this feature at this time

**Comment by swheaton** [comment]
We now support 3D bounding boxes in the form of cuboids. Please see documentation or here's a writeup of how we imported the nuScenes dataset into try.fiftyone.ai 
https://voxel51.com/blog/nuscenes-dataset-navigating-the-road-ahead/
