### ISSUE TITLE
[BUG] Google Colab: ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#3321]
Recently, in Google Colab, Installing FiftyOne like this:

```shell
!pip install fiftyone
```

```py
import fiftyone as fo
```

leads to the following error:

```
ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

**Comment by brimoor** [comment]
The root cause is that Colab seems to have recently upgraded its default machines to Ubuntu 22.04.

The solution is to install FiftyOne like this:

```
!pip install fiftyone
!pip install fiftyone-db-ubuntu2204
```

**Comment by brimoor** [comment]
See also: https://github.com/voxel51/fiftyone/issues/2900, https://github.com/voxel51/fiftyone/issues/2737, https://github.com/voxel51/fiftyone/issues/1988, https://github.com/voxel51/fiftyone/issues/1803

**Comment by zshn25** [comment]
> The root cause is that Colab seems to have recently upgraded its default machines to Ubuntu 22.04.
> 
> The solution is to install FiftyOne like this:
> 
> ```
> !pip install fiftyone
> !pip install fiftyone-db-ubuntu2204
> ```

I had this error on Ubuntu 20.04. I resolved by installing 

```
!pip install fiftyone
!pip install fiftyone-db-ubuntu204
```

**Comment by sriram-dsl** [comment]
refer this https://github.com/voxel51/fiftyone/issues/2900#issuecomment-1960666337
