### ISSUE TITLE
Generalize usage of ID on Label classes

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#334]
https://github.com/voxel51/fiftyone/pull/305 introduces `id` fields for `Classification` and `Detection`, which are used so that changes to documents in filtered lists in `SampleView` can be reliably updated.

The above is currently a strictly internal use case for `id`, but the concept of labels having UUIDs makes sense more generally. For example, it would provide a reliable mechanism for referring to individual labels that may be, e.g., used to identify bad labels that should be removed, or sent for human annotation/review, etc.

Some discussion points come to mind:
- should `Detections` and `Classifications` object have IDs, or not because they are simply containers of more atomic labels
- should `Attribute`s have IDs?
- how to assign IDs to `ImageLabels`? Presumably every sub `eta.core.objects.DetectedObject` and `eta.core.data.Attribute` should have an ID, for consistency of the notion that all "atomic" annotations can be referenced by ID

**Comment by swheaton** [comment]
I don't believe there are labels that don't have an ID. eta is an old module
