### ISSUE TITLE
[BUG] Visualizer Plugins: Overwriting and activator not working as expected

### ISSUE THREAD

**Issue by Sa-Schmi** [voxel51/fiftyone#3356]
### System information

-   **OS Platform and Distribution** : Manjaro Linux 23.0.0
-   **Python version**: 3.10
-   **FiftyOne version**: 0.21.4
-   **FiftyOne installed from**: source

### Describe the problem

`myActivator` is never used, as `usePlugin` is called [here](https://github.com/voxel51/fiftyone/blob/3c0cd9d9ab596ad18506bfeb02a3328638eb8832/app/packages/core/src/components/Modal/Sample3d.tsx#L12).
`useActivePlugins` should be used.

Further, a custom visualizer can never overwrite the built-in Looker3d as [here](https://github.com/voxel51/fiftyone/blob/3c0cd9d9ab596ad18506bfeb02a3328638eb8832/app/packages/core/src/components/Modal/Sample3d.tsx#L12) the array gets destructured to the first element which is Looker3d. `.pop()` would fix it.

There are also some typos in the docs. I will address them in my PR.

### Code to reproduce issue

None of these two `log` commands will print something.

```python
import { PluginComponentType, registerComponent } from "@fiftyone/plugins";

function CustomVisualizer({ api }) {
    console.log(api)
}

function myActivator({ dataset }) {
    console.log(dataset);
    return true;
}

registerComponent({
    name: "minimal",
    component: CustomVisualizer,
    type: PluginComponentType.Visualizer,
    activator: myActivator,
});
```

### What areas of FiftyOne does this bug affect?

-   [ x ] `App`: FiftyOne application issue

### Willingness to contribute

-   [ x ] Yes. I can contribute a fix for this bug independently

I will do a PR

**Comment by benjaminpkane** [comment]
Resolved by #3357
