### ISSUE TITLE
[FR] Add OCR task support

### ISSUE THREAD

**Issue by rusmux** [voxel51/fiftyone#3361]
### Proposal Summary

Add support for Optical Character Recognition (OCR) task.

### Motivation

OCR is one of the computer vision tasks.

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by swheaton** [comment]
We have support for OCR via FiftyOne plugin now!
Please see Week 5 of the 10 weeks of plugins! https://github.com/jacobmarks/pytesseract-ocr-plugin
