### ISSUE TITLE
[BUG] CVAT v2.5 text and checkbox attributes require values

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#3372]
CVAT v2.5 introduced a breaking change where text and checkbox attributes now require a `values` attribute to be provided. For other attribute types like radio and select, these values are the options to choose from, for text attributes, this just needs to be an empty list, for checkbox attributes it needs to be `[True, False]`

This error currently raises:
```
Exception: 400 error for request <PreparedRequest [POST]> to url http://10.2xx.2xx.2xx:8080/api/tasks with the reason Bad Request. Error content: b'{"labels":[{"attributes":[{"values":["This field is required."]},{"values":["This field is required."]},{"values":["This field is required."]}]}]}'
```

**Comment by geoffrp** [comment]
Was just about to create an issue for this, thanks @ehofesmann!
