### ISSUE TITLE
[BUG]coco format bbox/segmentation has shifted

### ISSUE THREAD

**Issue by Goooyi** [voxel51/fiftyone#3387]
### System information

-   **OS Platform and Distribution** (WIndows 10):
-   **Python version** (`python 3.9.17`):
-   **FiftyOne version** (`fiftyone v0.21.4`):
-   **FiftyOne installed from** (pip):

### Describe the problem

coco format bbox/segmentation has shifted for my dataset when I view them in fifityone
![image](https://github.com/voxel51/fiftyone/assets/83227264/0e63c54f-e108-4f76-ab7f-2f4b88a63102)
When it suppose to like this when I use another [cocoviewer](https://github.com/trsvchn/coco-viewer)
![image](https://github.com/voxel51/fiftyone/assets/83227264/6510d4f3-af4f-4a87-821c-35e5e248d9ae)

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Please do not use screenshots for sharing text. Code snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @Goooyi. Can you share a small example of the coco data with issues? A code snippet of the dataset import would also help debug.

There haven't been major changes to COCO import recently and loading `coco-2017` from the dataset zoo yields correct labels.
```py
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("coco-2017", max_samples=25, label_types=["segmentations"])
session = fo.launch_app(dataset)
```
<img width="1470" alt="Screen Shot 2023-08-04 at 3 30 08 PM" src="https://github.com/voxel51/fiftyone/assets/19821840/f4723901-4dd2-4fdf-a1fe-80ec21433a0e">

**Comment by Goooyi** [comment]
This how I read my data :

```python
import fiftyone as fo


name = "RM_VPG_COCO_tmp"
data_path = "C:\\Users\\gg\\Documents\\dataset\\tmp_data"
labels_path = "C:\\Users\\gg\\Documents\\dataset\\tmp_data\\train.json"

# Import dataset by explicitly providing paths to the source media and labels
dataset = fo.Dataset.from_dir(
    dataset_type=fo.types.COCODetectionDataset,
    data_path=data_path,
    labels_path=labels_path,
    name=name,
)


session = fo.launch_app(dataset)

session.wait()
```

And I also send an example files link to your email.

I'll also check if someting is done wrong by me, thanks for the help.

**Comment by Goooyi** [comment]
I found the bug, it's on my side, when I convert to 2d binary mask to coco-format, I read the mask image using cv2, while cv2's nd-array's shape is in (h, w, c) format, I wrongly defined it as (w, h, c) and save the height, width reversed in coco-json. So I suppose fifityone use the `height`, `weight` annotation in coco-json which causing the scaling and shifiting I mentioned above. While I suppose [cocoviewer](https://github.com/trsvchn/coco-viewer) read the image height/width directly from the image so it annotate it correctly.
Thanks for your time.
