### ISSUE TITLE
[?] How to export open-images-v7 in YOLOv5Dataset format to train YOLOv8 

### ISSUE THREAD

**Issue by glenn-jocher** [voxel51/fiftyone#3392]
Hello, I'm the author of Ultralytics [YOLOv8](https://github.com/ultralytics/ultralytics) and am exploring using fiftyone for training some of our datasets, but there seems to be a bug.

Note that for our use case YOLOv5Dataset works fine, though also please be aware that we've updated the Ultralytics YOLOv3/5/8 data.yaml formats to use a class dictionary rather than a `names` list and `nc` class count. See https://docs.ultralytics.com/datasets/detect/

<img width="1427" alt="Screenshot 2023-08-05 at 13 34 51" src="https://github.com/voxel51/fiftyone/assets/26833433/da29d556-229e-438a-afc7-84df1add353f">

### System information

-   **OS Platform and Distribution**:  macOS Ventura 13.4.1)
-   **Python version** (`python --version`):  3.11
-   **FiftyOne version** (`fiftyone --version`): 0.21.4 (latest)
-   **FiftyOne installed from** (pip or source): pip install fiftyone

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```python
import shutil
from pathlib import Path
import fiftyone as fo

# Load Open Images dataset
dataset = fo.zoo.load_zoo_dataset("open-images-v7",
                                  #splits=["train", "validation"],
                                  label_types=["detections"],
                                  max_samples=10)

# Export to YOLO format
save_dir = "./datasets/open-images-v7"
if Path(save_dir).exists():
    shutil.rmtree(save_dir)
dataset.export(export_dir=save_dir, dataset_type=fo.types.YOLOv5Dataset)
```

Output:
```
Downloading split 'train' to '/Users/glennjocher/fiftyone/open-images-v7/train' if necessary
Necessary images already downloaded
Existing download of split 'train' is sufficient
Downloading split 'validation' to '/Users/glennjocher/fiftyone/open-images-v7/validation' if necessary
Necessary images already downloaded
Existing download of split 'validation' is sufficient
Loading 'open-images-v7' split 'train'
 100% |█████████| 10/10 [38.4ms elapsed, 0s remaining, 260.1 samples/s]     
Loading 'open-images-v7' split 'validation'
 100% |█████████| 10/10 [30.6ms elapsed, 0s remaining, 327.2 samples/s]    
Dataset 'open-images-v7-train-validation-10' created
 100% |█████████| 20/20 [49.1ms elapsed, 0s remaining, 407.0 samples/s] 
```

### Describe the problem

Only a 'Val' split appears when using the above command with 30 images if no `split` or `splits` are passed, or with 20 images if `splits=["train", "validation"]` is defined. It seems to be sourcing the correct number of images but depositing them all in the `val` directory rather than also in train or test.

<img width="990" alt="Screenshot 2023-08-05 at 13 27 44" src="https://github.com/voxel51/fiftyone/assets/26833433/248476c8-9739-4d70-8c64-8908b187c689">

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
@glenn-jocher when exporting multiple splits in YOLOv5 format, each split must be exported separately. [Here's our documentation on this](https://docs.voxel51.com/user_guide/export_datasets.html#yolov5dataset).

Here's how to export Open Images V7 in your example:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v7",
    splits=["train", "validation"],
    label_types=["detections"],
    max_samples=10,
)

# For YOLOv5, all splits must use the same classes list
classes = dataset.default_classes  # all classes
# classes = dataset.distinct("ground_truth.detections.label")  # only observed classes

for split in ("train", "validation"):
    view = dataset.match_tags(split)
    view.export(
        export_dir="/tmp/oiv7-yolov5",
        dataset_type=fo.types.YOLOv5Dataset,
        label_field="ground_truth",
        split=split,
        classes=classes,
    )
```

**Comment by brimoor** [comment]
@glenn-jocher thanks for pointing out the `names` change in your `data.yaml` format! I'll update our YOLO importer/exporters to support this 👍

**Comment by brimoor** [comment]
FYI @glenn-jocher and future readers of this issue, on Monday we're releasing `fiftyone==0.21.5` which includes a new PyTorch Hub integration that can be used to load [Ultralytics YOLOv5](https://docs.ultralytics.com/yolov5) and apply it to FiftyOne datasets like so 🚀 

```py
from PIL import Image
import numpy as np

import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.utils.torch as fout

class YOLOv5OutputProcessor(fout.OutputProcessor):
    """Transforms ``ultralytics/yolov5`` outputs to FiftyOne format."""

    def __call__(self, result, frame_size, confidence_thresh=None):
        batch = []
        for df in result.pandas().xywhn:
            if confidence_thresh is not None:
                df = df[df["confidence"] >= confidence_thresh]

            batch.append(self._to_detections(df))

        return batch

    def _to_detections(self, df):
        return fo.Detections(
            detections=[
                fo.Detection(
                    label=row.name,
                    bounding_box=[
                        row.xcenter - 0.5 * row.width,
                        row.ycenter - row.height,
                        row.width,
                        row.height,
                    ],
                    confidence=row.confidence,
                )
                for row in df.itertuples()
            ]
        )

dataset = foz.load_zoo_dataset("quickstart")

model = fout.load_torch_hub_image_model(
    "ultralytics/yolov5",
    "yolov5s",
    hub_kwargs=dict(pretrained=True),
    output_processor=YOLOv5OutputProcessor(),
    raw_inputs=True,
)

# Generate preditions for a single image
img = np.asarray(Image.open(dataset.first().filepath))
predictions = model.predict(img)
print(predictions)  # <Detections: {...}>

# Generate predictions for all images in a collection
dataset.limit(10).apply_model(model, label_field="yolov5")
dataset.count("yolov5.detections")  # 26
```

**Comment by glenn-jocher** [comment]
@brimoor awesome! The code works, thank you!

About the new dict structure, you can convert the list to a dict in your code very easily with:

```python
classes_dict = dict(enumerate(classes_list))
```

This new format is compatible and in use with all Ultralytics YOLO repos (v3/5/8) since about a year ago. One other minor bug is that the data.yaml requires a 'val' field rather than a 'validation' field, so I had to change this manually. After this fix training works correctly with YOLOv8 :)

<img width="616" alt="Screenshot 2023-08-05 at 18 26 58" src="https://github.com/voxel51/fiftyone/assets/26833433/72565a9b-93b2-4362-bae6-16367aabcb2c">

**Comment by glenn-jocher** [comment]
@brimoor stupid question here, but if we wanted to maintain a similar ratio to COCO, i.e. 120k train and 5k val, is that possible using the off-the-shelf API or would we have to do 120k of each and then do some manual deletion of files in the /val directory?

**Comment by brimoor** [comment]
@glenn-jocher yep, here's an example of exporting 100 train samples and 10 validation samples (using `val` for the validation split in the YOLO export):

```py
import fiftyone as fo
import fiftyone.zoo as foz

train = foz.load_zoo_dataset(
    "open-images-v7",
    splits="train",
    label_types=["detections"],
    max_samples=100,
)

# YOLOv5 requires a common classes list
classes = train.default_classes

train.export(
    export_dir="/tmp/oiv7-yolov5",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
    split="train",
    classes=classes,
)

val = foz.load_zoo_dataset(
    "open-images-v7",
    splits="validation",
    label_types=["detections"],
    max_samples=10,
)

val.export(
    export_dir="/tmp/oiv7-yolov5",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
    split="val",
    classes=classes,
)
```

**Comment by glenn-jocher** [comment]
@brimoor awesome, thank you!

**Comment by glenn-jocher** [comment]
@brimoor created PR #3393 for update dataset.yaml format.

**Comment by glenn-jocher** [comment]
Closing issue as everything resolved!

**Comment by Hestinorwu** [comment]
For example，i want to find some classes train data.Every class 1000samples . Make sure they are dicided,i use for LOOP to load different data in different folder and export to different folder. As a result, there is a problem：different classes's 'images/train' is all the same. But i use params(classes) to load different data,Some one can help me? 
```
import fiftyone as fo
import fiftyone.zoo as foz
import os
CLASSES=["Human hand",
         "Human foot",
         "Human head",
         "Baseball bat",
         "Baseball glove",
         "Dagger",
         "Human arm",
         "Human leg",
         "Knife",
         "Mobile phone",
         "Person",
         "Vehicle",
         "Briefcase",
         "Book"
         ]
for i in range(len(CLASSES)):
    print(CLASSES[i],"Processing-------------------------------------")
    filename=CLASSES[i]
    export_filename=CLASSES[i]+'-Export'
    dataset_dir = os.path.join("Open-Datasets",filename)
    export_dir = os.path.join("Open-Datasets",export_filename)
    # 创建文件夹（如果它不存在）
    if not os.path.exists(dataset_dir):
        os.makedirs(dataset_dir)
    if not os.path.exists(export_dir):
        os.makedirs(export_dir)
    print("Starting  load dataset.....................................")
    train = foz.load_zoo_dataset(
        "open-images-v7",
        split="train",
        label_types=["detections"],
        classes=CLASSES[i],
        max_samples=1000,
        dataset_dir=dataset_dir,
    )
    classes = train.default_classes
    train.export(
        export_dir=export_dir,
        dataset_type=fo.types.YOLOv5Dataset,
        label_field="ground_truth",
        split="train",
        classes=classes,
    )

```
