### ISSUE TITLE
[SETUP-BUG] Can't Even Run Quickstart

### ISSUE THREAD

**Issue by cm107** [voxel51/fiftyone#3395]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04.6 LTS
-   **Python version** (`python --version`):
3.10.6
-   **FiftyOne version** (`fiftyone --version`):
FiftyOne v0.21.4, Voxel51, Inc.
fiftyone                    0.21.4
fiftyone-brain              0.13.1
fiftyone-db                 0.4.0
-   **FiftyOne installed from** (pip or source):
pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue.

```bash
# commands here
python -m venv venv
source venv/bin/activate
pip install fiftyone
python -c "import fiftyone as fo; import fiftyone.zoo as foz; dataset = foz.load_zoo_dataset('quickstart'); session = fo.launch_app(dataset)"
```

### Describe the problem

Provide the exact sequence of commands / steps that you executed before running into the problem.

I just did a simple pip installation. Nothing seems to work. All of the tutorials give me errors. I can't even run the quickstart.

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
Downloading dataset to '/home/clayton/fiftyone/quickstart'
Downloading dataset...
 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|  187.5Mb/187.5Mb [2.9s elapsed, 0s remaining, 71.1Mb/s]       
Extracting dataset...
Parsing dataset metadata
Found 200 samples
Dataset info written to '/home/clayton/fiftyone/quickstart/info.json'
Loading 'quickstart'
 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [3.1s elapsed, 0s remaining, 56.5 samples/s]      
Dataset 'quickstart' created
App launched. Point your web browser to http://localhost:5151

Could not connect session, trying again in 10 seconds
```

**Comment by cm107** [comment]
When the application is launched in the web browser, it just shows the following text in the browser:
"TypeError: NetworkError when attempting to fetch resource."

**Comment by benjaminpkane** [comment]
HI @cm107, by default the `session` will not block, so running the snippet will cause an immediate shutdown which is why you are seeing network errors (the server has shutdown).

To keep a FiftyOne session open when using a script or command, you can call [`session.wait(-1)`](https://docs.voxel51.com/api/fiftyone.core.session.html#fiftyone.core.session.Session.wait). The below should work as expected:
```sh
python -c "import fiftyone as fo; import fiftyone.zoo as foz; dataset = foz.load_zoo_dataset('quickstart'); session = fo.launch_app(dataset); session.wait(-1)"
```

**But** note that FiftyOne has a CLI! The equivalent command line is:
```sh
fiftyone quickstart --wait -1
```

**Comment by cm107** [comment]
@benjaminpkane 
I understand the problem now.
When reading README.md, I guess I didn't realize how important the "by opening a Python shell" part was.
I now understand that, when not using the python shell or jupyter, it is necessary to use the ```session.wait(-1)``` to keep the session from closing.
Thanks!
