### ISSUE TITLE
[BUG] Failed to load model class 'FigureModel' from module 'jupyterlab-plotly'

### ISSUE THREAD

**Issue by pepijnob** [voxel51/fiftyone#3408]
### System information

-   **OS Platform and Distribution**  Ubuntu 20:
-   **Python version** Python 3.9.17 (also tried with 3.8):
-   **FiftyOne version** FiftyOne v0.21.6, Voxel51, Inc.
-   **FiftyOne installed from** pip:

### Commands to reproduce

I'm using FiftyOne in a jupyter notebook. My (basic) code used to work (few months back), but now does not anymore. 

Load in dataset like this:
```
# Create the dataset
dataset_class = fo.Dataset.from_dir(
    dataset_dir=dataset_dir,
    dataset_type=fo.types.ImageClassificationDirectoryTree,
    name=name,
)
```
Then compute embeddings:
```
# Load a resnet from the model zoo
model = foz.load_zoo_model("resnet18-imagenet-torch")

# Compute embeddings for each image
embeddings = dataset_class.compute_embeddings(model)

# Compute 2D representation using pre-computed embeddings
results = fob.compute_visualization(
    dataset_class,
    embeddings=embeddings,
    num_dims=2,
    brain_key="image_embeddings",
    verbose=True,
    seed=51,
)
```
Show images
```
session = fo.launch_app(dataset_class)
```
Untill here it all works fine. Then I want to plot the embeddings like in this tutorial: https://docs.voxel51.com/tutorials/image_embeddings.html
```
# Plot embeddings colored by ground truth label
plot = results.visualize(labels="ground_truth.label")
plot.show(height=720)

# Attach plot to session
session.plots.attach(plot)
```
I get this error:
Failed to load model class 'FigureModel' from module 'jupyterlab-plotly'
makeError@http://localhost:8968/static/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168:17

I tried downgrading / upgrading the ipywidgets to different versions (7.8, 7.6), this does not work. This is the only solution I found online and seems to work for some. However, it does not work for me. 

### What areas of FiftyOne does this bug affect? ( I think)

-   [ ] `App`: FiftyOne application issue
-   [ x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @pepijnob. I can reproduce, and am looking into it. It looks like dependencies and documentation need to be tweaked. But I am still figuring out a solution. Thanks!

**Comment by brimoor** [comment]
We believe that updating the following package versions should resolve this issue:

```shell
# If using Jupyter notebooks
pip install "notebook>=6" "ipywidgets>=8,<9"
  
# If using JupyterLab
pip install "jupyterlab>=4" "ipywidgets>=8,<9"
```
