### ISSUE TITLE
Add subsection headers to API reference

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#343]
Porting request from https://github.com/voxel51/fiftyone/pull/330 to an issue:

@brimoor On the API reference page, can we:
- upgrade the `Classes` and `Functions` headings in the autosummary to RST section headings so that they appear in the RH sidebar, can be linked to, etc?
- add another heading between the functions table and the actual class/func documentation? To make it clear that the function listing in the autosummary has ended. Maybe call it `Documentation`?

@tylerganter I briefly looked into this but ... these sphinx extensions are horribly difficult to customize. What you're describing would involve customizing the `.. automodule::` directive and/or the `autodocsumm` source code. I'm going to merge this as is, calling it an imperfect improvement

**Comment by swheaton** [comment]
believe this is OBE
