### ISSUE TITLE
[BUG] Different samples chosen by take() on Linux and macOS

### ISSUE THREAD

**Issue by craston** [voxel51/fiftyone#3433]
### System information

-   **OS Platform and Distribution** : Ubuntu 20.04.6 LTS and macOS 13.4.1
-   **Python version** : 3.10.10
-   **FiftyOne version** : v0.21.6
-   **FiftyOne installed from** : pip

### Commands to reproduce
```
import fiftyone.zoo as foz

ds = foz.load_zoo_dataset("quickstart")

ds1 = ds.take(2, seed=51)

print(ds1.first().filepath)
print(ds1.last().filepath)
```

### Describe the problem
When I run this code on the Linux and macOS, I get different results:
* On the macOS:
`fiftyone/quickstart/data/003154.jpg`
`fiftyone/quickstart/data/001191.jpg`

* On the Linux machine:
`fiftyone/quickstart/data/000575.jpg`
`fiftyone/quickstart/data/003541.jpg`

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @craston. I believe this is expected behavior. `Take` will behave deterministically with respect to a MongoDB installation, but not across different installations. If a common `FIFTYONE_DATABASE_URI` is used, results should match.

**Comment by craston** [comment]
Hi @benjaminpkane, 

Thanks for your reply. However, when I run the script on two different Linux machines (and therefore, different MongoDB installations), I get the same result.

**Comment by benjaminpkane** [comment]
Ok, interesting. It may be that Python's random is generating different values. We rely on it [here](https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/core/stages.py#L8120)

**Comment by brimoor** [comment]
`take()` uses two pieces of random information:

1. every `Sample` has a `_rand` field populated based on its absolute filepath when it is originally created:
https://github.com/voxel51/fiftyone/blob/a1c6c8fccc68ba002643ba6a3b7b5c819732286e/fiftyone/core/odm/sample.py#L61-L70

2. every `Take()` instance has a `_randint` value populated as @benjaminpkane described:
https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/core/stages.py#L6617

Given those two pieces of information, the random ordering is deterministically computed via this `$sort`:
https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/core/stages.py#L6627C14-L6634
 
If the `filepath` of each sample is different on different machines, then `take(seed=seed)` will return different orderings.

It wasn't necessarily a design goal of ours to ensure that `take(seed=seed)` is platform independent. Only that it deterministic for a given `dataset` object.

**Comment by craston** [comment]
Thanks!
