### ISSUE TITLE
[BUG] could not connect to mongod on colab

### ISSUE THREAD

**Issue by Ihateyoudattebayo** [voxel51/fiftyone#3455]
### System information

google colab
### Commands to reproduce

```
!pip install fiftyone
import fiftyone as fo

```

### Describe the problem
I was running the fancaps dataset-maker colab and other google colabs involving fifityone and I keep getting this error

ServerSelectionTimeoutError               Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/fiftyone/core/odm/database.py in _validate_db_version(config, client)
    289     try:
--> 290         version = Version(client.server_info()["version"])
    291     except Exception as e:

13 frames
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64eb8d4fce66066cdbd72753, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

The above exception was the direct cause of the following exception:

ConnectionError                           Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/fiftyone/core/odm/database.py in _validate_db_version(config, client)
    291     except Exception as e:
    292         if isinstance(e, ServerSelectionTimeoutError):
--> 293             raise ConnectionError("Could not connect to `mongod`") from e
    294 
    295         raise RuntimeError("Failed to validate `mongod` version") from e

ConnectionError: Could not connect to `mongod`

This was not an issue until very recently.

### Code to reproduce the issue

Just search up fancaps-dataset-maker colab and run the cells until you get the error after importing fiftyone

**Comment by benjaminpkane** [comment]
Hi @Ihateyoudattebayo! For the time being, installing in Google's Colab with the below.
```
!pip install fiftyone
!pip install fiftyone-db-ubuntu2204
```

See https://github.com/voxel51/fiftyone/issues/3073
