### ISSUE TITLE
about frontend-backend separation

### ISSUE THREAD

**Issue by hellolixy** [voxel51/fiftyone#3456]
Hello everyone, I have a requirement to implement frontend-backend separation instead of binding a client through the launch_app method. Could you please guide me on how to modify the existing source code to achieve this?
thanks！

**Comment by benjaminpkane** [comment]
Hi @hellolixy. FiftyOne has the notion of the App and Session clients. `launch_app` is a convenience method to create a [Session](https://github.com/voxel51/fiftyone/blob/9ff834d53416117e622e3803bcc1a17d5d8789c7/fiftyone/core/session/session.py#L255) client and start the [server](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/server/main.py), if required.

Note that the project is focused on individual use. If you're interested in scaling FiftyOne to multiple users for collaboration, I encourage you to [schedule a Teams workshop](https://voxel51.com/schedule-teams-workshop/)!
