### ISSUE TITLE
Is there a way to skip non annotated images during conversion from coco to kitti?

### ISSUE THREAD

**Issue by nasserdr** [voxel51/fiftyone#3653]
I am trying to convert a dataset from coco to kitti as follows:

```
fiftyone convert \
    --input-dir /home/dataset_coco 
    --input-type fiftyone.types.COCODetectionDataset \
    --output-dir /home/data/dataset_kitti \
    --output-type fiftyone.types.KITTIDetectionDataset
```

I have already tried this command on another dataset and it worked well. However, on this particular dataset, it throws an error telling that there is an image not found.

Indeed, I verified, and the image was not found. However, this image does not contain any annotation and that's why it does not exist. The COCO file contains all the images and their IDs, but only images with objects have entries further down the json coco.

Is there any way to skip non annotated images during the image conversion?

Best

**Comment by brimoor** [comment]
Hi @nasserdr! The way to achieve this would be to use the Python SDK:

Specifically you can [create a view](https://docs.voxel51.com/user_guide/using_views.html#filtering) and then export that:

```py
import fiftyone as fo
from fiftyone import ViewField as F

dataset = fo.Dataset.from_dir(
    dataset_dir="/home/dataset_coco",
    dataset_type=fo.types.COCODetectionDataset,
    label_field="ground_truth",
    label_types="detections",
)

# Depending on your use case, you might want either of these:

# If you only want samples where detections != None
# This could include samples that were annotated but happened to have zero
# objects of interest
view = dataset.exists("detections")

# If you only want samples where there are at least one object
view = dataset.match(F("ground_truth.detections").length() > 0)

view.export(
    export_dir="/home/data/dataset_kitti",
    dataset_type=fo.types.KITTIDetectionDataset,
    label_field="ground_truth",
)
```

**Comment by nasserdr** [comment]
Thanks @brimoor . That works like honey :)
