### ISSUE TITLE
[BUG] IOU threshold does not change results.plot_pr_curve() 

### ISSUE THREAD

**Issue by hg6185** [voxel51/fiftyone#3669]
### Instructions

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md) for information on what types of issues we address.

1. Please fill in this template to ensure a timely and thorough response
2. Place an "x" between the brackets next to an option if it applies. For example:
    -   [x] Selected option
3. **Please delete everything above this line before submitting the issue**

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): MACOS Ventura 13.4 (M1 & Linux Skylake)
-   **Python version** (`python --version`): 3.8.17
-   **FiftyOne version** (`fiftyone --version`): 0.22.0
-   **FiftyOne installed from** (pip or source):pip

### Commands to reproduce
As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
dataset = fo.Dataset.from_dir(
    dataset_dir=dataset_name,
    dataset_type =fo.types.FiftyOneDataset,
)
view = dataset.filter_labels("predictions", F("confidence") > 0.1)
results = view.evaluate_detections(
            "predictions",
            gt_field=gt_field,
            compute_mAP=False,
            iou=0.95
        )
results.plot_pr_curves(classes=classes, )
```

### Describe the problem

Changing the IOU, does not change the graph?
### Code to reproduce issue

See above. Switch iou from 0.01 to 0.95 - no change
### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Please do not use screenshots for sharing text. Code snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time, genuinely sorry

**Comment by brimoor** [comment]
Hi @hg6185 👋 

The `plot_pr_curves()` method is only available when you pass `compute_mAP=True` to `evaluate_detections()`. And in that case, you can configure what IoU thresholds are used via the optional [`iou_threshs` argument](https://docs.voxel51.com/api/fiftyone.utils.eval.coco.html#fiftyone.utils.eval.coco.COCOEvaluationConfig)

By default, `plot_pr_curves()` plots curves averaged over all IoU thresholds, but you can choose a specific threshold by passing the [`iou_thresh` argument](https://docs.voxel51.com/api/fiftyone.utils.eval.coco.html#fiftyone.utils.eval.coco.COCODetectionResults.plot_pr_curves):

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")

view = dataset.filter_labels("predictions", F("confidence") > 0.5)

iou_threshs = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]

results = view.evaluate_detections(
    "predictions",
    gt_field="ground_truth",
    compute_mAP=True,
    iou_threshs=iou_threshs,
    classwise=False,  # allow matches between object classes
)

# By default, data is averaged over all IoUs
plot = results.plot_pr_curves()
plot.show()

# But you can plot curves for a specific one like this
plot = results.plot_pr_curves(iou_thresh=0.5)
plot.show()
```

**Comment by hg6185** [comment]
Thank you for the example!
That's very niceee
