### ISSUE TITLE
[BUG] Reloading the dataset page causes app to quit

### ISSUE THREAD

**Issue by Rusteam** [voxel51/fiftyone#3696]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Apple M1 Max Ventura 13.6
-   **Python version** (`python --version`): 3.10.8
-   **FiftyOne version** (`fiftyone --version`): v0.22.1
-   **FiftyOne installed from** (pip or source): pip 

### Commands to reproduce

```
# Just create a quickstart image/video dataset
```

### Describe the problem

After opening the app `fiftyone app launch <dataset>` in Firefox and making few clicks (sample tag filter, hiding labels), reloading the page with Ctrl+R causes the App quit.

### Other info/logs

no logs in the terminal

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by Rusteam** [comment]
Just realised there's no issues in the Chrome browser. Is it possible to add a browser param to `fiftyone app launch --browser chrome` to select a non-default browser?

**Comment by Rusteam** [comment]
actually while the app is open with a dataset and if the dataset is changed from the python package, reloading the page (which is needed to get latest updates) causes the app to quit.

**Comment by benjaminpkane** [comment]
HI @Rusteam. I believe adding `--wait -1` to `fiftyone app launch` will prevent the App server from exiting. See [here](https://docs.voxel51.com/cli/index.html#launch-the-app) for more details

**Comment by Rusteam** [comment]
Sounds good, I'll try that

**Comment by benjaminpkane** [comment]
I believe it should resolve the issue. If not, feel free reopen
