### ISSUE TITLE
Fix KITTIDetectionDataset table column widths

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#370]
<img width="1278" alt="Screen Shot 2020-08-10 at 11 15 51 PM" src="https://user-images.githubusercontent.com/25985824/89853474-7d5f6000-db5f-11ea-82c8-62f22995f54f.png">

**Comment by lethosor** [comment]
Duplicate of #572

**Comment by lethosor** [comment]
Appearance as of #575:
![image](https://user-images.githubusercontent.com/3719547/95116008-5e6eeb80-0714-11eb-92f3-a17183850927.png)
