### ISSUE TITLE
[FR] .TIFF support

### ISSUE THREAD

**Issue by tugcekiziltepe** [voxel51/fiftyone#3717]
I have .tiff images. I want to show these images in the browser using fiftyone app. There used to be some extentions but they are no longer used. I want to convert the images to 8 bit within fiftyone and show them. But I don't know where I should modify the data. Are the images printed directly to the browser from the file path? Or are the images read somewhere and printed on the screen? If so, where is the data read from? What can I do if there is no such feature?

**Comment by benjaminpkane** [comment]
Hi @tugcekiziltepe. Safari is the one browser that I know that supports TIFF. We rely on the process to process images, and unfortunately other browsers no longer offer support (or an extension).

But, to support any browser, you can transform your images with [fiftyone.utils.image](https://docs.voxel51.com/api/fiftyone.utils.image.html#fiftyone.utils.image.transform_images) and configure a [custom media field](https://docs.voxel51.com/user_guide/app.html#multiple-media-fields) to view them in the App

**Comment by tugcekiziltepe** [comment]
Thank you for your answer @benjaminpkane. Both methods store the images again, right?

**Comment by benjaminpkane** [comment]
An `output_dir` should be provided to [fiftyone.utils.image.transform_images()](https://docs.voxel51.com/api/fiftyone.utils.image.html#fiftyone.utils.image.transform_images) so the converted images are placed a new directory. The custom media field is just an App setting, it will not store any new images.

Here is an example using the `quickstart` Zoo dataset. It creates a copy of `jpg` images as `png` images.
```py
import fiftyone.zoo as foz
import fiftyone.utils.image as foui

dataset = foz.load_zoo_dataset("quickstart")
foui.transform_images(dataset, ext=".png", output_dir="/tmp", output_field="png_path")

dataset.app_config.media_fields = ["filepath", "png_path"]
dataset.app_config.grid_media_field = "png_path"
dataset.app_config.modal_media_field = "png_path"
dataset.save()

session = fo.launch_app(dataset)
```
