### ISSUE TITLE
[BUG] ctx.selected_labels is still empty in resolve_input in v0.22.1 and v0.22.2

### ISSUE THREAD

**Issue by msamadony** [voxel51/fiftyone#3740]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
-   **Python version** (`python --version`): Ubuntu 20.04
-   **FiftyOne version** (`fiftyone --version`): 0.22.1 and 0.22.2
-   **FiftyOne installed from** (pip or source): pip

### Describe the problem

With reference to a previously reported issue #3557, the ctx.selected_labels still returns an empty list in v0.22.1 and v0.22.2, even though the issue is marked as resolved in the v0.22.1 release notes.

The App shows the number of selected labels correctly:
![image](https://github.com/voxel51/fiftyone/assets/224718/865f0d3b-a832-42d5-ad97-8f6b58dc1e46)

However, the operator `resolve-type` request has an empty `selectedLabels` field:
![image](https://github.com/voxel51/fiftyone/assets/224718/42f70e61-b678-4eb6-a57e-a5b40c884bae)

I checked the code again, and it seems that another commit has removed the `selectedLabels` from the `globalContextSelector`. I suspect that this might be the root cause (I haven't tested it though).

https://github.com/voxel51/fiftyone/blob/4ad742a75d3f931198e0ec49576f22f7e804a7a6/app/packages/operators/src/state.ts#L78-L89

Commit Reference:
https://github.com/voxel51/fiftyone/commit/7d6de86eadba791f8483ffa05c3663fe4c4af2d9#diff-c4910bb1f5e42c2989667f7c357d1a520608050168897d95429e1ac0bb9eda4f

### Code to reproduce issue

Same as #3557

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Please do not use screenshots for sharing text. Code snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Will be patched in v0.22.3. Thanks @msamadony!
