### ISSUE TITLE
[BUG] Wrong image dimensions when image has any rotation in the exif orientation entry

### ISSUE THREAD

**Issue by Fraccalo** [voxel51/fiftyone#3778]
### Describe the problem

See discussion on Slack: https://fiftyone-users.slack.com/archives/C0189A476EQ/p1698408138572119

When importing an image that has an orientation entry in its exif, fiftyone imports the wrong image dimension, and consequently the annotations are displayed in the wrong position.  

### Code to reproduce issue

```
import fiftyone as fo
from fiftyone.utils.coco import add_coco_labels

ds = fo.Dataset()
ds.add_images_dir("dataset")

add_coco_labels(sample_collection = ds,
                label_field = "test",
                labels_or_path = "anno.json",
                classes = ["0","test"],
                label_type = "detections")

fo.launch_app(ds)
```

Here a sample image can be used for the test:
![img_rot](https://github.com/voxel51/fiftyone/assets/33780601/9c0fe485-2cf8-4b29-bd6b-2ad30cbf84fa)
While the annotation file is simply:
```
{"images": [{"id": 1, "width": 1200, "height": 841, "file_name": "img_rot.jpg"}], 
 "annotations": [{"id": 1, "iscrowd": 0, "image_id": 1, "category_id": 1, "extra": {}, "bbox": [641, 100, 200, 100], "area": 20000}], 
 "categories": [{"id": 1, "name": "test"}]}
```

This is what happens when loading the annotation into fiftyone:
<img width="959" alt="image" src="https://github.com/voxel51/fiftyone/assets/33780601/73f04b65-67cb-40a6-999b-20df8e9fc60f">
you can see that the image dimension is w:841, h:1200, while it should be the other way around (the width of the image is bigger than its height).
Also, the bounding box right end coincides with the image right edge, but the annotation is x:641, w:200, so it should arrive at 841, which shouldn't be the edge of the image (as the real width is 1200).

This is due to PIL library that messes up with the exif orientation entry. In fact, if I try to load the image with PIL it is actually loaded in a rotated fashion:
<img width="622" alt="image" src="https://github.com/voxel51/fiftyone/assets/33780601/f1c05e24-4786-44e7-aae3-0283845f730f">

This can be fixed by using ImageOps from the PIL library to rotate images according to the exif:
```ImageOps.exif_transpose(Image.open("dataset/img_rot.jpg"))```

<img width="868" alt="image" src="https://github.com/voxel51/fiftyone/assets/33780601/d7a84b9f-aceb-405b-9951-3974de2a7333">

### System information

-   **OS Platform and Distribution**: both Windows 11 and MacOS 13.6
-   **Python version**: python 3.9, 3.10, 3.11
-   **FiftyOne version**: 22.3
-   **FiftyOne installed from**: pip

### Willingness to contribute

I am already preparing a small PR  (https://github.com/voxel51/fiftyone/pull/3779) with a suggested fix as suggested in the slack channel by Stuart Wheaton 

-   [x] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by swheaton** [comment]
Further comments will be made in the PR.

Just want to point out if anyone else sees this issue that your image appears to have corrupted EXIF data somehow. However that does not affect the reported issue - I created a minimal EXIF with just "Orientation=6" and that transposed without errors but had the same rotated behavior.

**Comment by Fraccalo** [comment]
> Further comments will be made in the PR.
> 
> Just want to point out if anyone else sees this issue that your image appears to have corrupted EXIF data somehow. However that does not affect the reported issue - I created a minimal EXIF with just "Orientation=6" and that transposed without errors but had the same rotated behavior.

Yeah, I noticed that but couldn't be bothered to fix it (it's weekend after all :D). I couldn't share the original image that gave me the error, so I just got a random image from the internet, rotated it and added the orientation exif "by hand", but I might have also introduced an error somehow, thanks for double-checking this with another image.
