### ISSUE TITLE
Add support for cloning and renaming datasets

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#385]
Use case:

```py
import fiftyone.zoo as foz

# Load COCO validation split
dataset = foz.load_zoo_dataset("coco-2017", split="validation")

# Do stuff to dataset, like adding model predictions, removing samples, apply Brain methods, etc

# Now I have a  dataset with name `coco-2017-validation` that is actually my customized version of the dataset
# I may want to store this dataset separately, or perform multiple such analyses, without affecting my ability 
# to reload the original COCO-2017 validation split again in the future from the Zoo via the above command
```

To support this common use case, I propose the following two features:

1. Renaming a dataset

```py
#
# Renames the dataset (and the underlying collection in the database)
#
# Now `dataset` has a new name, so if I load COCO-2017 from the zoo again,
# I'll get a fresh copy of the dataset that does not interfere with the customized
# version with name `new_name` that I created here
#
dataset.rename(new_name)

# I proposed the above over property-setting syntax below because renaming a
# dataset feels like a bigger deal than just `dataset.persistent = True`, for example
dataset.name = new_name
```

2. Forking a dataset

Name inspired by GitHub, and Scale Nucleus' usage of the term ([cf here](https://dashboard.scale.com/nucleus/ds_bwm61zzb8mjksanms4wg), for example)

```py
#
# Creates a fork of dataset with name `new_name`
#
# This creates a copy of the backing collection in the database with the `new_name`
# Raw source data is not copied or modified
#
# Now I can manipulate my new copy of this dataset without affecting the other copy of the dataset
# However, sample IDs are the same, so merging my changes into the source dataset is plausible
#
new_dataset = dataset.fork(new_name)
```

**Comment by tylerganter** [comment]
1. this can either be done in the database [like so](https://api.mongodb.com/python/current/api/pymongo/collection.html?highlight=rename#pymongo.collection.Collection.rename) or we can keep track of database names separately, which is something mongoengine does, because, for example, there are restrictions on MongoDB collection names. I think this would be a fine option

2. this seems pretty unnecessary. We can copy a dataset with something as simple as:
```python
dataset_copy = fo.Dataset()
dataset_copy.add_samples(dataset)
```
And keeping the same IDs seems to me like over engineering. We can match on `filepath` for all intents and purposes

**Comment by brimoor** [comment]
1. I like the idea of the collection name being immutable and internal only, and storing the user-facing `name` of the dataset in the dataset's meta document. That sounds like the right design, regardless of this issue. Also, it makes updating the name of the dataset as trivial as it should be

2. It depends on whether we're talking about implementing `dataset.clone()` or `dataset.fork()`. Choosing the name fork would explicitly imply that we intend for the user to be able to merge changes to the new copy of the dataset back into the other dataset. If we were to implement this, I don't think matching by filepaths is enough, because the raw sample data is part of the sample, just like other fields. For example, one could update a sample by replacing it's backing image with a higher resolution one. So, if we really were going to implement forking, I'd say it is in fact essential to keep the same sample IDs, since those are the UUIDs for the samples.

However, your comment did make me realize that I don't really want `dataset.fork()` just yet, I really just want `dataset.clone()`, analogous to the `dataset.clone_field()` method that already exists. As you point out, `dataset.clone()` could be implemented as:

```py
def clone(self, name=None):
    dataset = Dataset(name=name)
    dataset.add_samples(self)
    return self
```

However this implementation is not as efficient as it could be. I'm sure there's a way to copy the entire collection w/o reading into memory and writing back out.

**Comment by tylerganter** [comment]
Wow, just found this:
```python
pipeline = [ {"$match": {}}, 
             {"$out": "destination_collection"},
]
db.source_collection.aggregate(pipeline)
```

It would be more complicated because we need to update to the `DatasetDocument` meta collection, but looks pretty easy and probably a lot faster, as you pointed out

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/pull/407
