### ISSUE TITLE
[FR] Improve Label Studio support to work with multiple fields

### ISSUE THREAD

**Issue by bonlime** [voxel51/fiftyone#3888]
### Proposal Summary

Currently Label Studio (LS) backend only supports passing single field to be labeled. ([Enforced here](https://github.com/voxel51/fiftyone/blame/26866c5a37e2dff83fee0f18bbde9f7153ff0e99/fiftyone/utils/labelstudio.py#L226)). I propose to fix this and allow more complex workflows. 

### Motivation

-   **What is the use case for this feature?** Examples when user need to label more than one thing. Or needs to pass some existing predictions to be classified.
-   **Why is this use case valuable to support for FiftyOne users in general?** LS has smoother UI than CVAT and is being developed rapidly, would be good to better support it. 
-   **Why is it currently difficult to achieve this use case?** Current code doesn't support this functionality

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

In my opinion the implementation is straightforward:
1. create a more complex labeling config for LS
2. correctly parse it back to 51

I've already patched this to work for me locally, and it only requires minor modifications. 

### Willingness to contribute

-   [x] Yes. I can contribute this feature independently
-   [ ] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by brimoor** [comment]
hi @bonlime this would be a fantastic addition. I see that you're willing to contribute this feature, thank you! 🙌

If you run into any questions along the way, feel free to reach out and we'll be happy to assist.

The CVAT and Labelbox backend implementations may be good points of reference for you:
- https://github.com/voxel51/fiftyone/blob/develop/fiftyone/utils/cvat.py
- https://github.com/voxel51/fiftyone/blob/develop/fiftyone/utils/labelbox.py
