### ISSUE TITLE
Don't prepend field names to box labels in expanded sample view

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#389]
Currently bounding boxes have `FIELD_NAME:LABEL` as their titles. Since we have the color code conveniently on the RHS menu, we can save space in the viewer by just rendering `LABEL`:

(ignore the fact that the colors are too close to distinguish ground truth vs predictions in this particular screenshot; that's another issue: https://github.com/voxel51/fiftyone/issues/386)

<img width="1796" alt="Screen Shot 2020-08-13 at 3 02 03 PM" src="https://user-images.githubusercontent.com/25985824/90175883-1e276880-dd76-11ea-9134-4f8677b64d51.png">

**Comment by lethosor** [comment]
This will require a bit of refactoring, because the `FIELD_NAME:` portion is what is currently used to determine the color. (Unsure how time-consuming it will be relative to other player51-related work)

**Comment by benjaminpkane** [comment]
This has already been addressed in #444. Removing the prefix proved to be helpful with respect to filtering.

**Comment by lethosor** [comment]
Thanks! Is that an app-side or player51-side change (or both)? i.e. should I base my changes on #444 or just use the player51 branch you're using in #444?

**Comment by benjaminpkane** [comment]
It is both. Branching off #444 is probably best, although the modal is currently broken. I'm going to try to fix that right now. I would hold off on modal work until I do, if possible.

**Comment by lethosor** [comment]
Fixed in #444
