### ISSUE TITLE
[BUG] App is stuck on "Pixelating.." screen when loading COCO custom dataset.

### ISSUE THREAD

**Issue by felipe-parodi** [voxel51/fiftyone#3898]
### Describe the problem

When loading my custom COCO dataset, I cannot launch the app on my Windows PC. The dataset is successfully created, but when I launch the app either in a script or in a jupyter notebook, it remain on the "Pixelating..." screen, even for a sample of 5 images.

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. Please avoid sharing code that relies on your local data or
datasets. Include a short video or screenshot if the bug is in the App.

```
import os

import fiftyone as fo
import fiftyone.zoo as foz

# The directory containing the source images
data_path = r"...\data"

# The path to the COCO labels JSON file
labels_path = r"...\val.json"

# Import the dataset
dataset = fo.Dataset.from_dir(
    dataset_type=fo.types.COCODetectionDataset,
    data_path=data_path,
    labels_path=labels_path,
    label_types=["detections"],
    max_samples=1
)

session = fo.launch_app(dataset)
```

### System information

-   **OS Platform and Distribution**: Windows 10
-   **Python version** (`python --version`): 3.8.16
-   **FiftyOne version** (`fiftyone --version`): v0.23.0
-   **FiftyOne installed from** (pip or source): pip

### Other info/logs

![Screenshot 2023-12-07 at 2 32 04 PM](https://github.com/voxel51/fiftyone/assets/53239931/50a7c963-0215-44a0-8875-2de03ad8d1d3)

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @felipe-parodi. Are there any [logs/errors](https://developer.chrome.com/docs/lighthouse/best-practices/errors-in-console) in your browser console that you can share?

**Comment by felipe-parodi** [comment]
Hi @benjaminpkane , thanks for the quick response. No errors in console. i've loaded one test image here:
 
![Screenshot 2023-12-07 at 2 45 49 PM](https://github.com/voxel51/fiftyone/assets/53239931/e0ba205e-b283-4286-aa46-86b157d9861a)

**Comment by allenleetc** [comment]
@benjaminpkane we seemed to see a very similar manifestation importing a YOLOv5 dataset in 0.23.

**Comment by benjaminpkane** [comment]
@felipe-parodi it looks like you connected to an existing session. That is what `Connected to FiftyOne on port 5151 at localhost` indicates. Could an older version of an App session be running?

**Comment by felipe-parodi** [comment]
I cleared browser cache and restarted PC but still get the error. When I refreshed the page, I received the following error: TypeError: Error in input stream. Pressing the "x" takes you back to the "Pixelating..." screen.

![Screenshot 2023-12-07 at 3 39 36 PM](https://github.com/voxel51/fiftyone/assets/53239931/0d417400-b128-4862-b5ff-8fad3ef3d8d4)

**Comment by benjaminpkane** [comment]
Are you running any plugins? There should definitely be errors in your _browser_ console

**Comment by benjaminpkane** [comment]
Fixed in `0.23.1`! Thanks @felipe-parodi 🙌

**Comment by visionNoob** [comment]
I had the same error in that it says "Pixelating..." and I noticed this error "only" on my PC. (It worked fine on different computers in the same docker container env). And I noticed this was an issue related to my chrome extensions, and after disabling some chrome extensions, I found it working fine.

**Comment by SergiyShebotnov** [comment]
Have the same issue now in 0.20.1 and also in 0.23.1 etc. 
Everything work fine couple of month ago.

Chrome consoles shows: 
![image](https://github.com/voxel51/fiftyone/assets/133217140/94bf61b5-985c-4508-b1fe-786ef2bf9973)

51 does this:
![image](https://github.com/voxel51/fiftyone/assets/133217140/cfec612b-2766-474b-a388-3844749a9046)

**Comment by SergiyShebotnov** [comment]
Fixed by updating the SSH plug-in in VS code

**Comment by dstkibrom** [comment]
I was also having this issue but after i disabled my extension called 'Proxy SwitchyOmega [used for switching proxies]' it started working. Make sure to disable some extensions and see if the problem resolves. 


> I had the same error in that it says "Pixelating..." and I noticed this error "only" on my PC. (It worked fine on different computers in the same docker container env). And I noticed this was an issue related to my chrome extensions, and after disabling some chrome extensions, I found it working fine.
