### ISSUE TITLE
[BUG] Ubuntu 23.10 desktop app (and web) is not working

### ISSUE THREAD

**Issue by AISTALK** [voxel51/fiftyone#3950]
### OS Platform and Distribution:
    Distributor ID: Ubuntu
    Description: Ubuntu 23.10
    Release: 23.10
    Codename: mantic

### Python version (python --version):
    Python 3.11.6

### FiftyOne version (fiftyone --version):
    (venv) aitalent@aitalent-1-0:~/Code/fiftyone$ fiftyone --version
    FiftyOne v0.23.1, Voxel51, Inc.
### FiftyOne installed from (pip or source):
    pip

### Commands to reproduce
pip install "fiftyone[desktop]"

#app.py
import fiftyone as fo
import fiftyone.zoo as foz

#app.py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset, desktop=True)

(venv) aitalent@aitalent-1-0:~/Code/fiftyone$ /home/aitalent/Code/fiftyone/venv/bin/python /home/aitalent/Code/fiftyone/app.py

### Describe the problem
Desktop app is not launching, though no visible errors

(.venv) aitalent@aitalent-1-0:~/Code/fiftyone$ /home/aitalent/Code/fiftyone/.venv/bin/python /home/aitalent/Code/fiftyone/app.py
Dataset already downloaded
Loading 'quickstart'
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [2.0s elapsed, 0s remaining, 99.2 samples/s]          
Dataset 'quickstart' created
Installing FiftyOne App
Desktop App launched.

**Comment by AISTALK** [comment]
UPD:
If turn off desktop=True, the web is not working also

#app.py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset, desktop=False)

(.venv) aitalent@aitalent-1-0:~/Code/fiftyone$ /home/aitalent/Code/fiftyone/.venv/bin/python /home/aitalent/Code/fiftyone/app.py
Dataset already downloaded
Loading 'quickstart'
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [2.0s elapsed, 0s remaining, 102.7 samples/s]         
Dataset 'quickstart' created
App launched. Point your web browser to http://localhost:5151

firefox:
http://localhost:5151/
TypeError: NetworkError when attempting to fetch resource.

opera:
http://localhost:5151
This site can’t be reached
localhost refused to connect.

**Comment by benjaminpkane** [comment]
Hi @AISTALK. Are you launching the App from a script? If so, you'll need to use [session.wait()](https://docs.voxel51.com/faq/index.html#why-isn-t-the-app-opening-not-connected-to-a-session) so the script does not exit and cause a server shutdown

**Comment by AISTALK** [comment]
# Answer
## Make sure, you have installed libfuse2 and if running from script add session.wait()
sudo add-apt-repository universe
sudo apt install libfuse2

### In case you don't have it, the code
#app.py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset, desktop=True)
session.wait()

### will cause to error
(.venv) aitalent@aitalent-1-0:~/Code/fiftyone$ /home/aitalent/Code/fiftyone/.venv/bin/python /home/aitalent/Code/fiftyone/app.py
Dataset already downloaded
Loading 'quickstart'
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [2.0s elapsed, 0s remaining, 100.0 samples/s]         
Dataset 'quickstart' created
Desktop App launched.
Subprocess ['/home/aitalent/Code/fiftyone/.venv/lib/python3.11/site-packages/fiftyone/desktop/bin/FiftyOne-0.0.0.AppImage'] exited with error 1:
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
