### ISSUE TITLE
Image wrapping edge case bug

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#396]
I loaded 10 images from `coco-2017` validation and the last image overflows the second line.

You should be able to reproduce as follows:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

images = [
    "001348.jpg", "004329.jpg", "003969.jpg", "000868.jpg", "000035.jpg",
    "002645.jpg", "004965.jpg", "000641.jpg", "004510.jpg", "001147.jpg"
]

dataset = foz.load_zoo_dataset("coco-2017", split="validation")

view = dataset.match(F("filepath").re_match("(%s)$" % ("|".join(images))))

session = fo.Session(view=view)
```

<img width="1176" alt="Screen Shot 2020-08-13 at 11 44 04 PM" src="https://user-images.githubusercontent.com/25985824/90211517-e7297500-ddbe-11ea-8d93-dce265ced8c2.png">

**Comment by lethosor** [comment]
What version of the app are you using? Wrapping behavior has changed in a couple ways since 0.5.0.

**Comment by brimoor** [comment]
latest `develop`

**Comment by brimoor** [comment]
Confirmed that https://github.com/voxel51/fiftyone/pull/398 fixes the above case
