### ISSUE TITLE
[INSTALL] Installation failed on macOS python 3.7

### ISSUE THREAD

**Issue by dai-shuo** [voxel51/fiftyone#3970]
There's a dependency problem where fiftyone requires inflate64>=1.0.0, but the latter requires python 3.8+.
See the error messages below.

Installation with python 3.8 succeeded.

### System information

-   **macOS 13.4.1**
-   **Python version 3.7**
-   **FiftyOne version 0.23.2**

### Commands to reproduce

```
pip install fiftyone
```

### Describe the problem

ERROR: Could not find a version that satisfies the requirement inflate64<1.1.0,>=1.0.0 (from py7zr->voxel51-eta<0.13,>=0.12.1->fiftyone) (from versions: 0.1.2, 0.1.3, 0.1.4, 0.2.0, 0.3.0, 0.3.1)
ERROR: No matching distribution found for inflate64<1.1.0,>=1.0.0 (from py7zr->voxel51-eta<0.13,>=0.12.1->fiftyone)

**Comment by benjaminpkane** [comment]
Hi @dai-shuo. This looks like a [`py7zr`](https://github.com/miurahr/py7zr/tree/master) issue. I believe `py7zr<=0.20.6` should fix the issue. Also note that Python 3.7 has reached EOL and FiftyOne will drop support in an upcoming release.
