### ISSUE TITLE
FiftyOne Walkthrough Images

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#399]
(this Issue exists so that GitHub's CDN can be used to host the screenshots in it 😄 )

<img width="1422" alt="01-overivew" src="https://user-images.githubusercontent.com/25985824/90993132-ac26fe80-e581-11ea-9efc-c3e1a0f876d8.png">

<img width="1422" alt="02-dataset" src="https://user-images.githubusercontent.com/25985824/90993147-b9dc8400-e581-11ea-81ba-3c48527c55da.png">

<img width="1651" alt="03-detail" src="https://user-images.githubusercontent.com/25985824/90993152-be08a180-e581-11ea-96a8-1d7b2e4fe702.png">

<img width="1422" alt="04-person" src="https://user-images.githubusercontent.com/25985824/90993172-c6f97300-e581-11ea-93ff-7e1a39a651d9.png">

<img width="1422" alt="05-unique" src="https://user-images.githubusercontent.com/25985824/90993177-cd87ea80-e581-11ea-9ebe-c59dbd3cbdde.png">

<img width="1422" alt="06-similar" src="https://user-images.githubusercontent.com/25985824/90993183-d11b7180-e581-11ea-8183-1f02a3943804.png">

<img width="1422" alt="07-pred-grid" src="https://user-images.githubusercontent.com/25985824/90993211-ebede600-e581-11ea-8d28-252a94a93c54.png">

<img width="1422" alt="08-pred-expanded" src="https://user-images.githubusercontent.com/25985824/90993217-f314f400-e581-11ea-927f-826ca608511c.png">

<img width="1422" alt="09-eval-all-grid" src="https://user-images.githubusercontent.com/25985824/90993233-f8723e80-e581-11ea-9166-6d4c059f4dca.png">

<img width="1422" alt="10-eval-high-conf-grid" src="https://user-images.githubusercontent.com/25985824/90993235-00ca7980-e582-11ea-9b79-cfea5d8978a3.png">

<img width="1422" alt="11-eval-high-conf-expanded" src="https://user-images.githubusercontent.com/25985824/90993239-032cd380-e582-11ea-9ac5-d6dc076d9651.png">

**Comment by tylerganter** [comment]
Thanks so much for doing this @brimoor! My only concern is the same one you brought up, that this may be a bit long.

Are we imagining a full walkthrough video? Which would be probably on the order of 20 minutes, or are we shooting for the 1-5 minute preview video? This script covers the important topics and I think it could be shrunk down to <5 minutes but that would imply only a few seconds scrolling through the result for each step (load, uniqueness, add predictions, evaluation)

I'd like to get @koberly51 and @briankelly 's thoughts on this.

**Comment by brimoor** [comment]
I think it would be possible to get through this pretty quickly, especially if you skip over the part about adding the model predictions. I see this as something where we say "and now let's add model predictions from our favorite model; the FiftyOne API makes it easy to attach arbitrary model predictions to your samples..." We could then provide a link to download the actual code (or is this really an `getting started tutorial` that can be linked to?)

The rest of the walkthrough is very minimal in terms of code. Although it does cover some concepts that could be delved deeper into (and will be in the future), I see merit in a walkthrough that goes very quickly through the code bits and focuses on the kinds of insights that you can _visualize_ in the App

With that said, I do still see this as a backend-focused version of the walkthrough, because the actual view operations and evaluation is performed via code, and not via the App, for example.

The view bar in the App needs a bit more usability work before I'm ready to do a walkthrough that 100% uses the App (but we're getting there)

**Comment by tylerganter** [comment]
@brimoor I was working on some small modifications to this to help it read a little more smoothly. Thought I'd share in case it's of use to you

```python
"""

Intro
- What is FiftyOne?
- Basic chatter about [the docs](https://voxel51.com/docs/fiftyone)

"""

'''
python -V
pip list
'''

'''
# Install FiftyOne
pip install --index https://pypi.voxel51.com fiftyone

# Install PyTorch (used by the Brain algo + the pre-trained model in this walkthrough)
# mention that ipython is also helpful and that we're going to use it in the walkthrough
pip install ipython torch torchvision
'''

###############################################################################
# Load dataset
###############################################################################

import fiftyone as fo
import fiftyone.zoo as foz

# Load COCO validation split
dataset = foz.load_zoo_dataset("coco-2017", split="validation")

dataset

dataset.first()

# Explore the dataset in the App
session = fo.launch_app()

session.dataset = dataset

###############################################################################
# Index images by uniqueness
###############################################################################

import fiftyone.brain as fob

fob.compute_uniqueness(dataset)

dataset

dataset.first()

# Explore most unique samples
session.view = dataset.sort_by("uniqueness", reverse=True)

# Explore the least unique samples
session.view = dataset.sort_by("uniqueness")

# Select 15 random samples to process
'''
(In the App)
take(15)
'''
predictions_view = session.view

###############################################################################
# Add some model predictions
###############################################################################

import torch
import torchvision
from torchvision.transforms import functional as func

import eta.core.image as etai

def run_inference(sample, model, device, classes):
    # Load image
    img = etai.read(sample.filepath)
    img_tensor = func.to_tensor(img).to(device)
    _, height, width = img_tensor.shape

    # Perform inference
    predictions = model([img_tensor])[0]
    labels = predictions["labels"].cpu().detach().numpy()
    scores = predictions["scores"].cpu().detach().numpy()
    boxes = predictions["boxes"].cpu().detach().numpy()

    # Convert detections to FiftyOne format
    detections = []
    for label, score, box in zip(labels, scores, boxes):
        # Convert to [top-left-x, top-left-y, width, height] format with
        # relative coordinates in [0, 1] x [0, 1]
        x1, y1, x2, y2 = box
        rel_box = [
            x1 / width, y1 / height, (x2 - x1) / width, (y2 - y1) / height
        ]

        detections.append(
            fo.Detection(
                label=classes[label],
                bounding_box=rel_box,
                confidence=score,
            )
        )

    return fo.Detections(detections=detections)

# Load pre-trained model
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

# get label map from dataset
classes = dataset.info["classes"]

# Add model predictions to dataset
with fo.ProgressBar() as pb:
    for sample in pb(predictions_view):
        sample["faster_rcnn"] = run_inference(sample, model, device, classes)
        sample.save()

###############################################################################
# Perform some evaluation
###############################################################################

import fiftyone.utils.eval as foue
from fiftyone import ViewField as F

# Evaluate raw predictions
foue.evaluate_detections(predictions_view, "faster_rcnn")

# Visual result: too many false positives!
session.view = predictions_view

# Let's try filtering the predictions by confidence
high_conf_predictions_view = predictions_view.filter_detections(
    "faster_rcnn", F("confidence") > 0.8
)

# Re-evaluate
foue.evaluate_detections(high_conf_predictions_view, "faster_rcnn")

# Visual result: much better!
session.view = high_conf_predictions_view
```

**Comment by brimoor** [comment]
<img width="1406" alt="fiftyone-hero" src="https://user-images.githubusercontent.com/25985824/94950264-5ca4ee00-04b0-11eb-9369-97265ef62681.png">

**Comment by brimoor** [comment]
<img width="1406" alt="fiftyone-hero" src="https://user-images.githubusercontent.com/25985824/94950670-fd93a900-04b0-11eb-8f70-89d405b0c965.png">

**Comment by brimoor** [comment]
<img width="1232" alt="fiftyone-hero" src="https://user-images.githubusercontent.com/25985824/94951173-cffb2f80-04b1-11eb-8ae2-3a7c3658e71d.png">

**Comment by brimoor** [comment]
Full resolution (144 PPI)

<img width="1424" alt="homepage1-full" src="https://user-images.githubusercontent.com/25985824/94951983-346abe80-04b3-11eb-9717-9fb47fc8e5b2.png">

<img width="1424" alt="homepage2-full" src="https://user-images.githubusercontent.com/25985824/94951997-392f7280-04b3-11eb-91dc-87d053f20196.png">

Half resolution (77 PPI)

![homepage1](https://user-images.githubusercontent.com/25985824/94952029-4187ad80-04b3-11eb-9441-2e36338f545c.png)

![homepage2](https://user-images.githubusercontent.com/25985824/94952038-451b3480-04b3-11eb-927f-b989f07365e1.png)

**Comment by brimoor** [comment]
![Uploading fiftyone-v0.6.1.png…]()

**Comment by brimoor** [comment]
**Full size (144ppi)**

<img width="1655" alt="fiftyone-v0 6 1" src="https://user-images.githubusercontent.com/25985824/96069942-39455000-0e6d-11eb-8f7c-a0ee34e09d4c.png">

**Half size (77ppi)**

![fiftyone-v0 6 1-optimized](https://user-images.githubusercontent.com/25985824/96070012-5c6fff80-0e6d-11eb-84d0-a88f8b026ee1.png)

**Comment by brimoor** [comment]
README images

![voxel51_300dpi](https://user-images.githubusercontent.com/25985824/106288517-2422e000-6216-11eb-871d-26ad2e7b1e59.png)
![fiftyone](https://user-images.githubusercontent.com/25985824/106288518-24bb7680-6216-11eb-8f10-60052c519586.png)
