### ISSUE TITLE
[BUG] Not able to use GUI through script

### ISSUE THREAD

**Issue by Ariiio** [voxel51/fiftyone#4012]
### Describe the problem

When I try to look at a dataset through the GUI (doesnt matter if desktop or web) it doesnt show my dataset and tells me to load one to view it, which I did (view screenshot). However when I use the CLI and do a quickstart it works flawlessly.

### Code to reproduce issue

```py
import fiftyone as fo
import fiftyone.zoo as foz

# Load the CIFAR-10 test split
# Downloads the dataset from the web if necessary
dataset = foz.load_zoo_dataset("cifar10", split="test")

session = fo.launch_app(dataset)
```

![Screenshot 2024-01-16 211343](https://github.com/voxel51/fiftyone/assets/77200189/0dc02dc4-84e6-45ee-b668-d71456191521)

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04): Windows 11
-   **Python version** (`python --version`): Python 3.10
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.23.2
-   **FiftyOne installed from** (pip or source): pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Note that if you're running the above code in a script (as opposed to from the REPL or in a notebook), then you must add `session.wait()`, otherwise the script will complete and then the App session will be immediately killed just after launching!

```py
import fiftyone as fo
import fiftyone.zoo as foz

# Load the CIFAR-10 test split
# Downloads the dataset from the web if necessary
dataset = foz.load_zoo_dataset("cifar10", split="test")

session = fo.launch_app(dataset)
session.wait()  # block execution until App is closed if running in script
```
