### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mihawk1303** [voxel51/fiftyone#4031]
I have a problem when i try to start FiftyOne. I installed it without problem, but, when i want to launch app to see the dataset i downloaded, the terminal says "App launched. Point your web browser to http://localhost:5151". But, when i go the the url, there is the error connection refused.

I'm on Windows 11 and i'm using the latest version of Python and FiftyOne.

**Comment by benjaminpkane** [comment]
Hi @Mihawk1303. Are you launching the App in a script? If so, you will need to use `session.wait()`. https://github.com/voxel51/fiftyone/issues/4012 has more info
