### ISSUE TITLE
[FR]Create New Directory for Filtered COCO Dataset in FiftyOne

### ISSUE THREAD

**Issue by Buddies-as-you-know** [voxel51/fiftyone#4045]
### Proposal Summary

I need to create a new directory to store a filtered version of the COCO 2017 dataset in FiftyOne. This dataset will only include samples where the predictions made by the `clip-vit-base32-torch` model have a confidence level above 0.5.

### Motivation

- **Use Case**: To have a dedicated directory for a curated dataset where all predictions meet a minimum confidence threshold, enhancing dataset quality and usability for specific analytical needs.
- **Value for FiftyOne Users**: This would demonstrate a clear method for organizing datasets based on specific criteria, benefiting users who work with large and complex datasets.
- **Value for Specific Projects/Organizations**: For my project, having a well-organized directory structure is crucial for efficient data management and retrieval.
- **Current Difficulty**: There is a lack of clear documentation or examples on how to create and manage new dataset directories in FiftyOne, especially for datasets filtered based on prediction confidence.

### Affected Areas

- [x] Core: Core `fiftyone` Python library
- [ ] App: FiftyOne application
- [ ] Server: FiftyOne server

### Details

I require assistance in creating a new directory within FiftyOne to store a subset of the COCO 2017 dataset. This subset will only include data where the model predictions have a confidence level above 0.5. Guidance on how to export this filtered dataset to the new directory and how to access it for future use is also needed.

### Willingness to Contribute

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="validation",
    label_types="detections",
    max_samples=25,
    only_matching=True,
)

model = foz.load_zoo_model("clip-vit-base32-torch")
dataset.apply_model(model, label_field="predictions")

# Option 1: only contains predictions with high confidence
view = dataset.filter_labels("predictions", F("confidence") > 0.5)

# Option 2: only contains samples with at least one high confidence prediction,
# but does not actually filter the labels in those samples
# view = dataset.match_labels(fields="predictions", filter=F("confidence") > 0.5)

# Option A: export dataset to disk
view.export(
    export_dir="/tmp/coco-2017-high-conf",
    dataset_type=fo.types.COCODetectionDataset,
    label_field="ground_truth",  # or 'predictions'
)

# Option B: clone matching samples to a new dataset
high_conf_dataset = view.select_fields("ground_truth").clone()
print(high_conf_dataset)
```
