### ISSUE TITLE
[DOCS] Error in the example on how to initialize a custom run 

### ISSUE THREAD

**Issue by gboeer** [voxel51/fiftyone#4057]
### URL(s) with the issue

https://docs.voxel51.com/plugins/developing_plugins.html#managing-custom-runs

### Description of proposal (what needs changing)

The example how to initialize a custom run:
```py
config = dataset.init_run(run_key)
config.foo = "bar"  # add as many key-value pairs as you need
dataset.register_run(run_key, config)
```

Will throw an exception (assuming run_key is supposed to be the run's name):
    `<class 'TypeError'>: SampleCollection.init_run() takes 1 positional argument but 2 were given`

It should be:
```py
config = dataset.init_run()
config.foo = "bar"  # add as many key-value pairs as you need
dataset.register_run(run_key, config)
```

### Willingness to contribute

-   [X] Yes. I can contribute a documentation fix independently
-   [ ] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a documentation fix at this time

**Comment by brimoor** [comment]
@gboeer thanks for catching this! It was actually already fixed in https://github.com/voxel51/fiftyone/pull/4036 and will be deployed to fiftyone.ai when we next update the docs
