### ISSUE TITLE
 could not found  mongo db   (fiftyone.core.config.FiftyOneConfig)

### ISSUE THREAD

**Issue by cr7Alex** [voxel51/fiftyone#4074]
![mongo](https://github.com/voxel51/fiftyone/assets/145112424/ea31b0a3-54b6-4708-9e30-56eb617d6891)
After creating a main.exe file using Pyinstaller for a project, when I open the main.exe file, this error occurs. but a manual project works in Editor, where Python and 51 are installed. 
Please, someone help me with this error.  @benjaminpkane @brimoor 

"MongoDB could not be installed on your system. Please "
"define a `database_uri` in your "
"'fiftyone.core.config.FiftyOneConfig` to connect to your"
                "own MongoDB instance or cluster "

**Comment by benjaminpkane** [comment]
Hi @cr7Alex. Can you share your platform info? Code snippet below
```python
from platform import platform
print(platform())
```

**Comment by cr7Alex** [comment]
Thanks for the reply @benjaminpkane      Windows-10-10.0.19045-SP0

**Comment by benjaminpkane** [comment]
Thanks. Can you also share the below? Currently, MongoDB only supports Windows x86_64

```python
import platform
print(platform.system(), platform.machine())
```

**Comment by cr7Alex** [comment]
Thanks @benjaminpkane platform machine  Windows AMD64

**Comment by benjaminpkane** [comment]
Thanks! I have a proposed fix that you can test with an RC.

```shell
pip install fiftyone fiftyone-db==1.1.2rc1
``` 

If you can confirm that this fixes importing fiftyone, we can publish that patch!

**Comment by benjaminpkane** [comment]
Should be fixed in [fiftyone-db==1.1.2](https://pypi.org/project/fiftyone-db/1.1.2)

**Comment by GeLink9999** [comment]
Hi，@benjaminpkane, i also have the simimlar issue:
ython 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiftyone
Traceback (most recent call last):
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/core/odm/database.py", line 200, in establish_db_conn
    _db_service = fos.DatabaseService()
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/core/service.py", line 80, in __init__
    self.start()
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/core/service.py", line 209, in start
    super().start()
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/core/service.py", line 118, in start
    + self.command,
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/core/service.py", line 238, in command
    DatabaseService.find_mongod(),
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/core/service.py", line 286, in find_mongod
    raise ServiceExecutableNotFound("Could not find `mongod`")
fiftyone.core.service.ServiceExecutableNotFound: Could not find `mongod`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/__public__.py", line 16, in <module>
    _foo.establish_db_conn(config)
  File "/home/xiaoqiang/Documents/fiftyone/fiftyone/core/odm/database.py", line 206, in establish_db_conn
    raise FiftyOneConfigError(
fiftyone.core.config.FiftyOneConfigError: MongoDB could not be installed on your system. Please define a `database_uri` in your `fiftyone.core.config.FiftyOneConfig` to connect to yourown MongoDB instance or cluster


my platform info :
>>> print(platform.system(), platform.machine())
Linux x86_64

>>> print(platform())
Linux-5.15.0-92-generic-x86_64-with-glibc2.17

Thanks @benjaminpkane 
Looking forward  to your feedback

**Comment by benjaminpkane** [comment]
Hi @GeLink9999. What does `cat /etc/os-release` show you? Specifically the `id` entry?

`fiftyone-db==1.1.2` has been released, so the rc does not need to be used. Does that work for you?

I am realizing my instructions were slightly incorrect. If you are installing an rc, the `RELEASE_VERSION` environment variable should be set.
```
RELEASE_VERSION=1.1.2rc2 pip install fiftyone-db==1.1.2rc2
```
