### ISSUE TITLE
[BUG] Mongodb gets wipe out in unexpected intervals, all datasets lost!

### ISSUE THREAD

**Issue by ggrrin** [voxel51/fiftyone#4102]
### Describe the problem

I want to store datasets to Fiftyone database and from then on use it for dataset curation. 
Unfortunately, in undefined times database is wipeout. I tried to use dedicated mongo db 
using Docker, but it didnt help.

### Code to reproduce issue

There is code I am using to store dataset into Fiftyone/Mongo.

```py
import fiftyone as fo
import fiftyone.brain as fob
from tqdm import tqdm
from pathlib import Path
import sys


GROUP =  "11"
dataset = fo.Dataset.from_images_dir(f"/mnt/c/path/{GROUP}", name=f'Group{GROUP}', overwrite=True)

for sample in tqdm(dataset):
    *_, dataset_name, scan, filename = Path(sample['filepath']).parts
    sample['dataset'] = dataset_name
    sample['scan'] = scan
    sample['filename'] = filename

    test_field_parts = str(Path(filename).with_suffix("")).split('_')
    number = test_field_parts[-1] if len(test_field_parts) == 2 else -1

    sample['number'] = number
    sample.save()


fob.compute_uniqueness(dataset)
```

# commands and/or screenshots here

### System information

-   **OS Platform and Distribution** (Linux Ubuntu 22.04 / WSL):
-   **Python version** (Python 3.12.1):
-   **FiftyOne version** (FiftyOne v0.23.5, Voxel51, Inc.):
-   **FiftyOne installed from** (pip):

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @ggrrin, to clarify- FiftyOne datasets are non-persistent by default, which means that they will be automatically deleted when your current Python session ends.

If you want a dataset to persist between sessions, just include the `persistent=True` kwarg when creating datasets:

```py
# At dataset creation time
dataset = fo.Dataset(..., persistent=True)
dataset = fo.Dataset.from_dir(..., persistent=True)

# Make an existing dataset persistent
dataset = fo.load_dataset(...)
dataset.persistent = True
```

Documentation on this topic: https://docs.voxel51.com/user_guide/using_datasets.html#dataset-persistence

**Comment by ggrrin** [comment]
Omg, I can't believe I did such a stupid mistake, thank you very much.
