### ISSUE TITLE
[BUG] fiftyone-db cannot be installed anymore with poetry and pip 24

### ISSUE THREAD

**Issue by ClementPinard** [voxel51/fiftyone#4117]
### Describe the problem

Realted issue on pypa : https://github.com/pypa/pip/issues/12550

### Code to reproduce issue

```console
pip wheel --no-cache-dir --use-pep517 fiftyone-db
```

will fail on linux and pip version 24.

This is most likely related with the fact that no pre-built wheel exists for linux. pip will then pull the source and try to build it itself. However, pip's default build creates a virtual environment solely for the build, which no longer includes `wheel` since version 24, while `fiftyone-db`'s setpu.py does import it. See related PR that was included in version 24 : https://github.com/pypa/pip/pull/12449

I asked pip devs how to solve the issue, but a working (albeit not necessarily the cleanest) solution is to add a small `pyroject.toml` file at the root of the `db` folder with the following info :

```toml
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
```

Unless something better is suggested, I can make a PR to add it

### System information

-   **OS Platform and Distribution**: ubuntu 22.04
-   **Python version** (`python --version`): 3.11
-   **FiftyOne version** (`fiftyone --version`): N/A
-   **FiftyOne installed from** (pip or source): pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [X] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by ClementPinard** [comment]
After some more tests, fiftyone can be installed with `pip` itself, it's only the `pip wheel` that fails.

The error is raised when installing from poetry, probably because they internally call the `pip wheel` command. So issue is about people trying to install with poetry, but I do believe many people use this tool for their projects.

**Comment by benjaminpkane** [comment]
Hi @ClementPinard. I believe you are correct about that a `pyproject.toml` and `build-system` should be added to `fiftyone-db`. Will work on a patch

**Comment by ClementPinard** [comment]
Hi thanks, for the quick answer !

From what I understand, we just need to add the pyproject.toml file and call `python -m build -s`  instead of `python setup.py sdist` in the github actions and we should be good to go.

Another solution would be, as suggested by @webknjaz on the original issue, to provide a fallback to the import for the wheel related class :

```python
try:
    from wheel.bdist_wheel import bdist_wheel  # building wheels/editables
except ImportError:
    bdist_wheel = object  # building sdists
```

The code is run twice : first to get package metadata, second to actually build it. The wheel module is only available at build time. This little modifications works on my side, but I do concede that a proper build mechanism with explicit dependencies would be cleaner.

**Comment by webknjaz** [comment]
> From what I understand, we just need to add the pyproject.toml file and call `python -m build -s` instead of `python setup.py sdist` in the github actions and we should be good to go.

Here as well: https://github.com/voxel51/fiftyone/blob/233f7c6/Makefile#L9C3-L9C36.

Note that it's not recommended to pass both `--sdist` and `--wheel` to `python -Im build`. Instead, don't pass them at all. When they are passed, the artifacts are built from the Git checkout each. When they aren't, it's a smoke test for free because it will first build an sdist from the project directory, and then build a wheel *from that previously made sdist*, mimicking what pip does and making sure that enough files are actually included into the sdist to produce the resulting wheel.

**Comment by webknjaz** [comment]
@ClementPinard note that both sdist and wheel are published on the PyPI. So pip will always download wheel during the dependency resolution by default, and unzip it during the installation. So in the "happy path" no build will be performed at all.

**Comment by webknjaz** [comment]
@benjaminpkane while on it, looked at your https://github.com/voxel51/fiftyone/blob/develop/.github/workflows/publish.yml and it could benefit from more updates. I recommend upgrading to the tokenless publishing mechanism we implemented almost a year ago though the official PyPA-blessed GitHub action. My PyPUG guide has an complete workflow example of how to use it: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/.

**Comment by benjaminpkane** [comment]
Thanks @webknjaz! I will take a look!
