### ISSUE TITLE
Can't open the session anymore - _HAS_DEFAULT_FACTORY Error

### ISSUE THREAD

**Issue by fernandorovai** [voxel51/fiftyone#4121]
After restarting the notebook, I started having the error GraphQL API Error - name '_HAS_DEFAULT_FACTORY' is not defined after doing session = fo.launch_app().

The error persists even trying with an empty dataset:
session = fo.launch_app(fo.Dataset())

Any idea how to solve it?

I'm using:
fiftyone                      0.23.5
fiftyone-brain                0.16.1
fiftyone-db                   1.1.1
fiftyone-desktop              0.33.4

![image](https://github.com/voxel51/fiftyone/assets/3229701/6cfc60b5-375a-43c6-ae5c-b86006e5a8d3)

**Comment by benjaminpkane** [comment]
Hi @fernandorovai 👋. Can you share the full stack trace? I don't believe `_HAS_DEFAULT_FACTORY` is part of the `fiftyone` codebase and the screenshot is missing the last few lines

**Comment by dilipdhapse** [comment]
can you share what is resolution here? it got closed without any resolution provided?

**Comment by fernandorovai** [comment]
@dilipdhapse, I had to access the db and remove the color entry from there. Something is buggy on the colors settings.
