### ISSUE TITLE
[DOCS] reencode_video clarifications

### ISSUE THREAD

**Issue by apourchot** [voxel51/fiftyone#4124]
### URL(s) with the issue

https://docs.voxel51.com/api/fiftyone.utils.video.html#fiftyone.utils.video.reencode_video

### Description of proposal (what needs changing)

According to the documentation, `**kwargs` passed to the `fiftyone.utils.video.reencode_video` represent "keyword arguments for `eta.core.video.FFmpeg(**kwargs)`. However, under the hood, `reencode_video` calls `_transform_video`, with parameters `reencode=True, force_reencode=True,`, which in turn disregard the parameters passed through `**kwargs`. I'm not sure whether this behavior is ill-documented, or if this is a bug. It seems however that without the default parameters used for reencoding the videos are not displayed within the app. Some feedback on this matter would be greatly appreciated.

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently
-   [ ] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [x] No. I cannot contribute a documentation fix at this time

**Comment by brimoor** [comment]
Hi @apourchot 👋 

I can see how this is slightly confusing. Let me explain ourselves and we'll see what you think!

The `reencode_video()` and `reencode_videos()` methods were really intended to only be used in "easy mode": they hard code H.264 MP4 as the codec, as that is a common codec that all browsers support and thus the FiftyOne App will reliably be able to render videos in this format. `**kwargs` should probably just be removed from that method.

The `transform_video()` and `transform_videos()` methods are more general versions of `reencode_video()` and `reencode_videos()` that *do* actually pass any `**kwargs` that you provide (namely `in_opts` and `out_opts`) directly through to `eta.core.video.FFmpeg`, allowing you to have fine-grained control over the `ffmpeg` commands that are ultimately executed.

**Comment by apourchot** [comment]
Thanks @brimoor, this clarifies things a bit :smile: 

I'm still confused as to which ffmpeg options are supported by fiftyone. I don't think that this is documented anywhere. I'm working with medical data and trying to display videos with the highest quality possible, but using simple presets like `VIDEO_ENCODING_OPTS = [
    "-c:v",
    "libx264",
    "-preset",
    "slow",
    "-crf",
    "18",
    "-profile:v",
    "high",
]` will generate videos which are fine on their own, but are not displayed within the app. 

I realize this might be beyond the scope of this issue but any knowledge that you could share on this matter would be greatly appreciated.

**Comment by brimoor** [comment]
FiftyOne just relies on the standard HTML5 `<video>` tag to render videos in the App, which implicitly relies on your web browser's ability to render the video you've provided.

It is a bit surprising that the `VIDEO_ENCODING_OPTS` you mention aren't renderable in the browser, because in general H.264 seems pretty stable in browsers, but certainly many non-H.264 codecs aren't supported, so I'm not *that* surprised.

Just to clarify, you have some video, say `/path/to/video.mp4`, that you can view using something like quicktime, but when you do this, the video doesn't render in the FiftyOne App?

```py
import fiftyone as fo

dataset = fo.Dataset()
dataset.add_sample(fo.Sample(filepath="/path/to/video.mp4"))

session = fo.launch_app(dataset)
```

**Comment by apourchot** [comment]
Yes, I can visualize them fine using any standard video player, but the app won't display them, saying "This video failed to load. The file may not exist, or its type (video/mp4) may be unsupported. You can use fiftyone.utils.video.reencode_videos() to re-encode videos in a supported format.". [Here](https://drive.google.com/file/d/1_IqeJeXj9RUxXIj1QJ1KyMjbY0vYlN8v/view?usp=sharing) is an example of such a video.

**Comment by brimoor** [comment]
Yeah sorry, there's just something unsupported about that codec by your (and my) browser

```py
import fiftyone as fo
import fiftyone.utils.video as fouv

sample = fo.Sample(filepath="/Users/Brian/Desktop/unsupported.mp4")

dataset = fo.Dataset()
dataset.add_sample(sample)

# video doesn't load
session = fo.launch_app(dataset)

fouv.reencode_videos(dataset)

# now it does
session.refresh()
```
