### ISSUE TITLE
[BUG] Shuffle stage random number bug

### ISSUE THREAD

**Issue by evatt-harvey-salinger** [voxel51/fiftyone#4146]
### Describe the problem

Looks to me like [this bug fix](https://github.com/voxel51/fiftyone/blob/7853d085f398d9d2d47e356da822f65f725d98db/fiftyone/core/stages.py#L6672) for the Shuffle stage on the develop branch, didn't make it into the [most recent release](https://github.com/voxel51/fiftyone/blob/2086f90ec77e0a764c8d915a306b1f8677e55b12/fiftyone/core/stages.py#L6672), so .shuffle and .take are currently throwing an error.
The solution is in hand, on dev. Just some simple int(...) Just putting it on the radar for the next release :)

### Code to reproduce issue

```
dataset.shuffle()
dataset.take(10)
```

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04): Linux Ubuntu 22.04
-   **Python version** (`python --version`): 3.12
-   **FiftyOne version** (`fiftyone --version`): 0.23.6
-   **FiftyOne installed from** (pip or source): pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Ah yes, we haven't released a new minor version `fiftyone==0.XX` since https://github.com/voxel51/fiftyone/pull/4052 was merged, so the patch is not yet available in a public release.

I've cherry-picked the change in https://github.com/voxel51/fiftyone/pull/4144 so that this bug will be resolved as of `fiftyone==0.23.7`.

**Comment by evatt-harvey-salinger** [comment]
Thank Brian!
