### ISSUE TITLE
localhost Not found [BUG]

### ISSUE THREAD

**Issue by barzan-hayati** [voxel51/fiftyone#4156]
### Describe the problem

I have downloaded zip file from instead of `git clone` or not download the `released versions`.
Everything installed successfully. By launching `http://localhost:5151` in the browser, I'm encountering **Not Found** error.

### Code to reproduce issue

```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

### System information

-   **OS Platform and Distribution** (Linux Ubuntu 18.04):
-   **Python version** (`3.8`):
-   **FiftyOne version** (`FiftyOne v0.24.0, Voxel51, Inc.`):
-   **FiftyOne installed from** (source):

**Comment by benjaminpkane** [comment]
Hi @barzan-hayati. If you are using a source install of FiftyOne, I would double check the App is being built when using the install script.

https://github.com/voxel51/fiftyone/blob/7baa04b07a517e8a7c90073c8ca04d5440eb171e/install.bash#L133

A Not Found error usually means there is no built App in the `fiftyone/server/static` directory, which is what the above link accompishes
