### ISSUE TITLE
[BUG] Run fiftyone on specific domaine and path

### ISSUE THREAD

**Issue by safwanghamrawi** [voxel51/fiftyone#4158]
We have jupyterhub runing for ex on https://mywebsite.com.

We want to run a fiftyone application on https://mywebsite.com/my/specific/path/

I cannot found any configuration to do this. and specially for the request /events and /graphql which will call https://mywebsite.com/events instead of https://mywebsite.com/my/specific/path/events

Is there any way to achieve this ? 

Thanks

**Comment by benjaminpkane** [comment]
Hi @safwanghamrawi! FiftyOne can be used through a proxy URL. We have documentation for that [here](https://docs.voxel51.com/user_guide/config.html#configuring-a-proxy-url).

Note the `session.url` should be used to for loading the App in a new tab. See https://github.com/voxel51/fiftyone/issues/2995#issuecomment-1958456736

**Comment by safwanghamrawi** [comment]
It works, Thanks for your help !
