### ISSUE TITLE
[QUESTION] Customising "category_id" values when exporting a COCO-formatted dataset

### ISSUE THREAD

**Issue by astringfield** [voxel51/fiftyone#4162]
I have a custom COCO-formatted dataset loaded into FiftyOne and I'm trying to export the images and annotations in COCO format:

```
import fiftyone as fo

custom_coco_dataset_view.export(
        export_dir=str(output_path),
        dataset_type=fo.types.COCODetectionDataset,
        label_field="segmentations",
    )
```

Currently, the COCO `category_id` values in the export COCO JSON file start at `0`. 

**Is it possible to modify this behaviour so that the `category_id` values start at `1`?**

Examples below of the current export results and the export results I'm hoping to see.

**Current export format (categories start at `0`)**
```json
"categories": [
    {
        "id": 0,
        "name": "apple",
        "supercategory": ""
    },
    {
        "id": 1,
        "name": "orange",
        "supercategory": ""
    },
    {
        "id": 2,
        "name": "banana",
        "supercategory": ""
    },
]
```

**Desired export format (categories start at `1`)**
```json
"categories": [
    {
        "id": 1,
        "name": "apple",
        "supercategory": ""
    },
    {
        "id": 2,
        "name": "orange",
        "supercategory": ""
    },
    {
        "id": 3,
        "name": "banana",
        "supercategory": ""
    },
]
```

Appreciate any help - thanks!

**Comment by benjaminpkane** [comment]
HI @astringfield. I do not believe supported this is by default. One option is subclass [COCODetectionDatasetExporter](https://github.com/voxel51/fiftyone/blob/83cc723dc5f306830fb8e9ff5c4e7ecbfd332d0f/fiftyone/utils/coco.py#L612) and override the `_parse_classes` method.  It looks like that is where the class mapping is initialized. (Note the safer solution is to re-implement the entire [setup](https://github.com/voxel51/fiftyone/blob/83cc723dc5f306830fb8e9ff5c4e7ecbfd332d0f/fiftyone/utils/coco.py#L765) method as that is public contract.

Contributions are also welcome if you see an opportunity to add `category_id` configuration out of the box!

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/pull/4354 adds support for this!

```py
categories = [
    {'supercategory': 'person', 'id': 1, 'name': 'person'},
    {'supercategory': 'vehicle', 'id': 2, 'name': 'bicycle'},
    ...
    {'supercategory': 'indoor', 'id': 90, 'name': 'toothbrush'}
]

dataset.export(
    export_dir="/path/for/export",
    dataset_type=fo.types.COCODetectionDataset,
    categories=categories,
)
```
