### ISSUE TITLE
[BUG] Issue with Orthographic Projection when supplied projection_normal=(0, 0, -1)

### ISSUE THREAD

**Issue by SergioRAgostinho** [voxel51/fiftyone#4203]
### Describe the problem

The method [`_rotation_matrix_from_vectors`](https://github.com/voxel51/fiftyone/blob/7bea0c2b4aae5cad19d84c1ac49e0baa65fbe817/fiftyone/utils/utils3d.py#L777-L786) is ill-defined and returns `NaN` when the angle between `vec1` and `vec2` is 180º. 

From a geometrical standpoint the issue is being cause by the fact that there is no longer a single "shortest" rotation that transforms `vec1` to `vec2` There are now infinite perpendicular axes to `vec1` and `vec2` that can be used to rotate `vec1` onto `vec2`.

From a numerical perspective, what is happening is that `s` in this [line](https://github.com/voxel51/fiftyone/blob/7bea0c2b4aae5cad19d84c1ac49e0baa65fbe817/fiftyone/utils/utils3d.py#L786) is 0. And the rotation matrix returned becomes `NaN`.

A solution would would be to pick a random axis perpendicular to `vec1` and `vec2` and apply rotation 180º around it. 

### Code to reproduce issue

I triggered the issue when calling  `fiftyone.utils.utils3d.compute_orthographic_projection_images`, with 

```python
compute_orthographic_projection_images(
    ...
    projection_normal=(0, 0, -1),
)
```

But you can shortcut all the stack call and simply call 

```python
fiftyone.utils.utils3d. _rotation_matrix_from_vectors((0, 0, -1), (0, 0, 1))
```

In general, it would be ideal if one could specify one not only the projection normal, but an actual full rotation matrix to fully define the camera orientation. As things are, the pose still has some degrees of freedom.

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04): macOS Sonoma 14.4 (23E214)
-   **Python version** (`python --version`): 3.10.14
-   **FiftyOne version** (`fiftyone --version`): v0.23.7
-   **FiftyOne installed from** (pip or source): pip

### Other info/logs

n.a

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by swheaton** [comment]
Thanks @SergioRAgostinho !
I'll admit I did not know much about this but after doing some background research I understand, and what you're saying makes sense!

You seem very knowledgeable about this subject, would you be willing to submit a PR?

> but an actual full rotation matrix to fully define the camera orientation. As things are, the pose still has some degrees of freedom.

We'll take a PR for this too if you can!!

**Comment by SergioRAgostinho** [comment]
Hi @swheaton. I think I might need a bit more guidance. I'm fighting a bit the import structure of fiftyone and maybe you have good suggestions.

I started working on this by adding a unit test test under `tests/unittests/utils/utils3d_tests.py`, but ran into problems. To give a sample of what happened, here are the steps I followed.


1. Clone the latest `develop`
2. `cd` into it
3. Create a conda env for Python 3.8 (no 3.7 for macOS arm apparently) and activate it.
4. `bash install.bash -d -p`
5. Added unit test under  `tests/unittests/utils/utils3d_tests.py`
6. Added the code below

    ```python
    from fiftyone.utils.utils3d import _rotation_matrix_from_vectors
    ```

7. Ran `pytest tests/unittests/utils/utils3d_tests.py`
8. Was met with

    ```
    ========================================================================= ERRORS =========================================================================
    ________________________________________________ ERROR collecting tests/unittests/utils/utils3d_tests.py _________________________________________________
    tests/unittests/utils/utils3d_tests.py:10: in <module>
        from fiftyone.utils.utils3d import compute_cuboid_iou
    fiftyone/utils/utils3d.py:17: in <module>
        import fiftyone.core.fields as fof
    fiftyone/core/fields.py:22: in <module>
        import fiftyone.core.odm as foo
    fiftyone/core/odm/__init__.py:10: in <module>
        from .database import (
    fiftyone/core/odm/database.py:69: in <module>
        class DatabaseConfigDocument(Document):
    fiftyone/core/odm/database.py:75: in DatabaseConfigDocument
        version = fof.StringField()
    E   AttributeError: partially initialized module 'fiftyone.core.fields' has no attribute 'StringField' (most likely due to a circular import)
    ================================================================ short test summary info =================================================================
    ERROR tests/unittests/utils/utils3d_tests.py - AttributeError: partially initialized module 'fiftyone.core.fields' has no attribute 'StringField' (most likely due to a circular import)
    ```

I assume this is something very specific of the repo structure and import strategy.

1. Should the test file be added somewhere else?
2. Am I invoking pytest incorrectly?
3. Is there some special way to import things that I'm missing?

**Comment by swheaton** [comment]
@SergioRAgostinho Thanks for trying it!
That should work, however I have 2 suggestions:
1. Just use `fou3d._rotation_matrix_from_vectors()` in your test
2. I think if you set `PYTHONPATH` it will work. `PYTHONPATH=/path/to/fiftyone pytest tests/unittests/utils/utils3d_tests.py`

**Comment by swheaton** [comment]
Regarding 
> In general, it would be ideal if one could specify one not only the projection normal, but an actual full rotation matrix to fully define the camera orientation. As things are, the pose still has some degrees of freedom.

Does [this](https://docs.voxel51.com/user_guide/app.html#configuring-the-3d-visualizer) help with what you want, as you can set the default camera position?

**Comment by SergioRAgostinho** [comment]
> Does [this](https://docs.voxel51.com/user_guide/app.html#configuring-the-3d-visualizer) help with what you want, as you can set the default camera position?

It kinda does, but at the same time it doesn't. 

With the camera position, up vector and "look at" (projection_normal) vector, the camera is fully specified. So yeah, this would do it. However, having to set the camera position and up vector defined somewhere completely different in the API is not nice. Ideally,  they should be parameters in  `compute_orthographic_projection_images`'s  signature, and defined just for this purpose of generating thumbnails.
