### ISSUE TITLE
[DOCS] Detectron example raising ValueError

### ISSUE THREAD

**Issue by Tropingenie** [voxel51/fiftyone#4208]
### URL(s) with the issue

https://docs.voxel51.com/tutorials/detectron2.html

### Description of proposal (what needs changing)

Running the Detectron2 tutorial in Colab, a `ValueError: DatasetView has no field 'segmentations'` is raised  from `dataset.filter_labels("segmentations", F("label") == "Vehicle registration plate").save()` while preparing the dataset. As I am using these docs to learn the tools, I do not have the experience necessary to propose a fix. However, running `print(dataset.exists("segmentations"))` implies that field indeed does not exist:
```
Dataset:     open-images-v6-validation
Media type:  image
Num samples: 0
Sample fields:
    id:           fiftyone.core.fields.ObjectIdField
    filepath:     fiftyone.core.fields.StringField
    tags:         fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    ground_truth: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
View stages:
    1. Exists(field='segmentations', bool=True)
```

A full trace is as follows:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-21-de488dc4068e>](https://localhost:8080/#) in <cell line: 5>()
      3 # Remove other classes and existing tags
      4 print(dataset.exists("segmentations"))
----> 5 dataset.filter_labels("segmentations", F("label") == "Vehicle registration plate").save()
      6 dataset.untag_samples("validation")

8 frames
/usr/local/lib/python3.10/dist-packages/fiftyone/core/collections.py in _get_label_field_type(self, field_name)
  10101         if field_name not in schema:
  10102             ftype = "frame field" if is_frame_field else "field"
> 10103             raise ValueError(
  10104                 "%s has no %s '%s'"
  10105                 % (self.__class__.__name__, ftype, field_name)

ValueError: DatasetView has no field 'segmentations'
```

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently
-   [ ] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [x] No. I cannot contribute a documentation fix at this time

**Comment by swheaton** [comment]
By default, if there is one label field, `load_zoo_dataset()` will name it `ground_truth`. You can change this with the `label_field` argument. I can propose a fix.

However it looks like your dataset has 0 samples. So I would check that the dataset was loaded properly from the zoo also.

**Comment by Tropingenie** [comment]
> However it looks like your dataset has 0 samples. So I would check that the dataset was loaded properly from the zoo also.

Thanks for PRing a fix, hopefully it is in soon so I can keep working through the tutorial. Addressing the above note, I did confirm the dataset was loaded properly; shown is the output of the `exists()` method showing that there are no samples with the 'segmentations' field (i.e. it is not the full dataset).

**Comment by swheaton** [comment]
> > However it looks like your dataset has 0 samples. So I would check that the dataset was loaded properly from the zoo also.
> 
> Thanks for PRing a fix, hopefully it is in soon so I can keep working through the tutorial. Addressing the above note, I did confirm the dataset was loaded properly; shown is the output of the `exists()` method showing that there are no samples with the 'segmentations' field (i.e. it is not the full dataset).

Ah I see. Well don't let this stop you from continuing, you can do a number of things to continue the tutorial.
1. Change the `load_zoo_dataset()` call to add the parameter `label_field="segmentations"`
2. Rename the field after loading. `dataset.rename_sample_field("ground_truth", "segmentations")`
3. (don't recommend) Replace field name of "segmentations" with "ground_truth" in the remaining cells
