### ISSUE TITLE
Don't show attribute panel when no attributes are selected

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#421]
When no frame attributes are selected, the attribute panel in the upper left of Player51 should be completely hidden; currently there is still a small gray box

**Frame attributes selected:**
<img width="1136" alt="Screen Shot 2020-08-18 at 9 10 56 PM" src="https://user-images.githubusercontent.com/25985824/90581455-4ad5e880-e199-11ea-99bc-4606101de157.png">

**No frame attributes selected:**
<img width="1136" alt="Screen Shot 2020-08-18 at 9 11 02 PM" src="https://user-images.githubusercontent.com/25985824/90581449-41e51700-e199-11ea-9833-9c0597fd76d9.png">

**Comment by lethosor** [comment]
Addressed in https://github.com/voxel51/player51/commit/b4da14b3fdc3f92cbab6c341f9f845a13c67c30c, which should be included in #444 or another update before 0.5.2
