### ISSUE TITLE
[FR] Support setting tags in custom importer class

### ISSUE THREAD

**Issue by CourchesneA** [voxel51/fiftyone#4305]
### Proposal Summary

When creating a dataset importer, it would be great to have a way to specify what split the item belongs to. It seems fy.Sample have a `tags` field that can be used for that, but in the [importer](https://docs.voxel51.com/user_guide/dataset_creation/datasets.html#writing-a-custom-dataset-type), the `__next__` function returns `(image_path, image_metadata, label)`, and I didn't find a way to set a `Sample` property from there.

### Motivation

-   What is the use case for this feature?
I would like to keep track of splits on my datasets, since I often only want to perform some operations on a subset of my dataset
-   Why is this use case valuable to support for FiftyOne users in general?
I expect other people also want to keep track of their splits
-   Why is it currently difficult to achieve this use case?
I don't see a way to set `fo.Sample` attributes from the importer class

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [X] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

Maybe the `__next__` [function](https://docs.voxel51.com/user_guide/dataset_creation/datasets.html#writing-a-custom-dataset-type) could return a `fo.Sample`

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [X] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by brimoor** [comment]
@CourchesneA there is a [GenericSampleDatasetImporter](https://github.com/voxel51/fiftyone/blob/36d4be22d94d6dca386e6db5e58059b1850fe032/fiftyone/utils/data/importers.py#L1005) interface that you can subclass from that allows the `__next__` method to return an entire `Sample` object as you suggest!
