### ISSUE TITLE
Add slack, github, and docs icons to the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#431]
The app has links to `email`, `documentation`, and `slack` under the help menu, but I think we should be very direct and put icon links in the upper right of the actual header bar in the App that contains our logo, dataset name, etc

```
[Cube] | FiftyOne                                             [Slack icon] [GitHub icon] [Book icon]
----------------------------------------------------------------------------------------------------
```

Slack link: https://join.slack.com/t/fiftyone-users/shared_invite/zt-gtpmm76o-9AjvzNPBOzevBySKzt02gg)
GitHub link: https://github.com/voxel51/fiftyone
Book link: https://voxel51.com/docs/fiftyone/user_guide/app.html

Note that the latter links directly to the App page of the user guide.

Side comment: for Mac users, the help menu literally never enters my mind, as it is disconnected from the actual App. I strongly suspect Mac users will never click up there.

**Comment by lethosor** [comment]
I've used the native "help" menu (and other menus) in Mac apps relatively often, although I agree that not everyone will look there. Usually I expect to find native help only, and am pleasantly surprised when I find links to other documentation pages.
(Adding in-app links is straightforward, and I'm in favor of that, - just not planning on removing the help menu)

**Comment by brimoor** [comment]
Yeah the help menu can stay. I just want some big, obvious click targets to drive engagement while the App is young. I use the links at the top of https://voxel51.com/docs/fiftyone/ very often, for example
