### ISSUE TITLE
[BUG] Sample shown in App is not the same as expanded view

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#433]
I loaded coco-2017 validation from the FiftyOne zoo.

1) Get the id of an image
2) ```session.view = dataset.select(id)```
3) `x` out the view stage from the App
4) ```session.view = dataset.select(id)```

Now the image that shows in the main App window is not the same image that shows when expanded.

![image](https://user-images.githubusercontent.com/21222883/90921792-df6a6180-e3b8-11ea-97aa-65c687b0d97a.png)

![image](https://user-images.githubusercontent.com/21222883/90921868-f90ba900-e3b8-11ea-966e-5268e6637fd9.png)

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

**Comment by lethosor** [comment]
Is this reproducible? Have you seen it with other datasets? I wasn't able to reproduce with a relatively-small test dataset (100 sampels).

**Comment by ehofesmann** [comment]
> Is this reproducible? Have you seen it with other datasets? I wasn't able to reproduce with a relatively-small test dataset (100 sampels).

I was just able to reproduce it on `coco-2017-validation` with 5000 samples. I tried it with `cifar10` and it wasn't happening. 

I also have multiple model predictions and evaluations stored in my `coco-2017-validation` and it takes a few seconds for view updates to take place which might have something to do with it.

**Comment by brimoor** [comment]
This has been resolved for quite awhile.
