### ISSUE TITLE
[BUG] operator set_progress error

### ISSUE THREAD

**Issue by yrrah** [voxel51/fiftyone#4387]
### Describe the problem

The source comments indicate that set_progress should accept a float & string...
https://github.com/voxel51/fiftyone/blob/a9d02f2d3898e87a57a3c57ce1925c451cb85259/fiftyone/operators/executor.py#L726-L727

...but later attempts to access progress.progress
[`self.log(f"Progress: {progress.progress} - {progress.label}")`](https://github.com/voxel51/fiftyone/blob/a9d02f2d3898e87a57a3c57ce1925c451cb85259/fiftyone/operators/executor.py#L735)

Proposed fix:
`self.log(f"Progress: {progress} - {label}")`

### Code to reproduce issue

```
class SetProgressError(foo.Operator):
    @property
    def config(self):
        return foo.OperatorConfig(
            name="set_progress_error",
            label="Set Progress Error"
        )

    def execute(self, ctx):
        ctx.set_progress(progress=0.5,label="half way") 
```

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04): Ubuntu 20.04.6 LTS
-   **Python version** (`python --version`): Python 3.10.13
-   **FiftyOne version** (`fiftyone --version`): v0.23.7
-   **FiftyOne installed from** (pip or source): pip

### Other info/logs

```
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/operators/executor.py", line 728, in set_progress
    self.log(f"Progress: {progress.progress} - {progress.label}")
AttributeError: 'float' object has no attribute 'progress'
```

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
@yrrah thanks for catching this 😅 

Fixed in https://github.com/voxel51/fiftyone/pull/4417 and will be released in `fiftyone==0.24.0` (coming next week).
