### ISSUE TITLE
Add a show confidence toggle to expanded sample view

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#439]
A common workflow is to filter detections and classifications based on their confidences.

Currently, the only way to inspect object confidences from the App is to view the sample JSON, but it would be desirable to see the confidences directly on the image, to inform filtering via the label filter, for example (dragging the confidence slider).

I propose that we add a “show confidence” toggle to the expanded sample view that controls whether confidences (if present) are rendered on all Label instances that have confidences.

Note that this applies to both object detections and the frame-level label attributes rendered in the attribute panel of Player51, as both Detection and Classification instances can have confidences.

When this mode is enabled, labels with confidences should be rendered as `"%s (%.2f)" % (label, confidence)`. Objects with no confidence (or when this mode is disabled) should be rendered as `label`.

~~We may have more such options in the future, but, until then, this can be positioned as a `Show/Hide Confidences` button in the bottom right next to the `Show/Hide JSON` button~~

<img width="1651" alt="root 2" src="https://user-images.githubusercontent.com/25985824/91065765-e2569380-e5fe-11ea-8276-1bb720c9b1c2.png">

**Comment by lethosor** [comment]
This may actually be easiest to implement under the player51 settings menu (gear icon), and fits with some of the existing object-related settings there. Agreed that a temporary design for this is fine.

Looks like confidence is already passed into player51: https://github.com/voxel51/fiftyone/blob/772d750e885b93262d3e0560dc973888264eb86e/electron/app/components/Player51.tsx#L15
Hopefully displaying it isn't too hard, but it depends on how this is passed around within player51.

**Comment by brimoor** [comment]
> This may actually be easiest to implement under the player51 settings menu (gear icon), and fits with some of the existing object-related settings there. Agreed that a temporary design for this is fine.

yeah that makes sense, I like it
