### ISSUE TITLE
How to rename the dataset to groundtruth using the frontend [BUG]

### ISSUE THREAD

**Issue by ragahdtareg** [voxel51/fiftyone#4426]
How to rename the dataset to groundtruth using the frontend not the code!

**Comment by benjaminpkane** [comment]
Hi @ragahdtareg. The `rename_sample_field` is a builtin operator available in the App. See recording. I believe that should unblock you, so I will close this issue 🚀 

https://github.com/voxel51/fiftyone/assets/19821840/4b4b7a95-9d10-44ad-a256-c88ef4d644e2
