### ISSUE TITLE
[FR] Reasonable frame selection for `video` datasets with 2+ video samples

### ISSUE THREAD

**Issue by evatt-harvey-salinger** [voxel51/fiftyone#4447]
### Proposal Summary

The `dataset.annotate()` method accepts kwargs `frame_start`, `frame_stop` and `frame_step` for the CVAT labeling backend. This works for video datasets that only include one video sample. But when there are multiple video samples, each sample includes frames with overlapping frame numbers. `annotate` end up pulling from frames from the sample.

(In general, it seems like videos are treated more like datasets, rather than samples by many functions/methods in FiftyOne.)

This would help build FO's capabilities for managing video datasets.

### Motivation

-   What is the use case for this feature?
    - Allow partial labelling of specific clips of videos, in dataset with multiple videos.
-   Why is this use case valuable to support for FiftyOne users in general?
    - Enhance the usefulness of datasets with multiple videos. 
-   Why is this use case valuable to support for your project(s) or organization?
    - I have many videos I need to label, that I want to be able to treat as a contiguous dataset.
-   Why is it currently difficult to achieve this use case?
    - Impossible, as far as I'm aware. Can't send FrameViews for annotation, no way to refer to specific samples within a particular dataset.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

I'm proposing a new parameter that allows the user to pass a dict with a key for each sample id, and optional kwargs for [`frame_start`, `frame_stop` and `frame_step`, `frame_num_list`, `frame_ids`] that are used to select the frames from each sample that should be sent to CVAT.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

I've gotten fairly comfortable with using fiftyone as a developer, but haven't really explored the backend and CVAT API specifically. I'm willing to consult, but probably don't have the time to learn enough of the CVAT integration backend to actually implement this myself.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by ehofesmann** [comment]
Hey @evatt-harvey-salinger ! Those kwargs should also accept a list and dictionary in the case that you are annotating multiple video samples at once: https://docs.voxel51.com/integrations/cvat.html#requesting-annotations

Let me know if that is what you have in mind

**Comment by evatt-harvey-salinger** [comment]
Ah, of course you're right. Apologies for suggesting feature that already exists. I hadn't had the page up, and had trouble tracing the kwargs for dataset.annotate back through the code base. I finally have the CVATBackendConfig pulled up, which would've answered my questions.
