### ISSUE TITLE
[BUG] OperationFailure when filtering a partly labeled dataset

### ISSUE THREAD

**Issue by sanjeev-sudarsan** [voxel51/fiftyone#4473]
### Describe the problem

I have a dataset with around 14,000 images, of which 2,500 are labeled. When I try to filter the samples that only have the `car` label, I get the following error.

```
raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: PlanExecutor error during aggregation :: caused by :: both operands of $setIsSubset must be arrays. First argument is of type: missing, full error: {'ok': 0.0, 'errmsg': 'PlanExecutor error during aggregation :: caused by :: both operands of $setIsSubset must be arrays. First argument is of type: missing', 'code': 17046, 'codeName': 'Location17046'}
```

I observed that this error does not occur if I run the same code on a dataset where all the samples are labeled.

I also tried creating a view with only the labeled samples and then applying the filter but the error still occurs.

### Code to reproduce issue

```
import fiftyone as fo
from fiftyone import ViewField as F

# load the dataset
dataset = fo.load_dataset(<DATASET_NAME>)

# specify the name of the field
field_name = (
    <FIELD_NAME>
)
# filter samples that contains only the specified label
filter = F(field_name + ".detections.label").is_subset(["car"])
# apply filter
view = dataset.match(filter)

session = fo.launch_app(
    dataset=view,
    address="0.0.0.0",
)
session.wait()

```

The error
![Screenshot from 2024-06-10 11-44-19](https://github.com/voxel51/fiftyone/assets/82379301/453bafa0-8f74-417b-a648-ad3133296edd)

### System information

-   **OS Platform and Distribution** (Linux Ubuntu 22.04):
-   **Python version** (`3.10.12`):
-   **FiftyOne version** (`0.24.0`):
-   **FiftyOne installed from** (pip):

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @sanjeev-sudarsan 👋 

This is unfortunately a limitation of MongoDB, which is used to perform the filtering under the hood. Many aggregations gracefully handle missing data, but set operations unfortunately do not in general.

There is a builtin [`match_labels()`](https://docs.voxel51.com/api/fiftyone.core.collections.html#fiftyone.core.collections.SampleCollection.match_labels) stage that gracefully handles missing data though!

```py
view = dataset.match_labels(fields=field_name, filter=F("label").is_in(["car"]))
```

If you want to use `match()` directly, you'd have to manually omit unlabeled samples using [`if_else()`](https://docs.voxel51.com/api/fiftyone.core.expressions.html#fiftyone.core.expressions.ViewExpression.if_else) like so:

```py
filter = F(field_name).exists().if_else(
    F(field_name + ".detections.label").contains("car"),
    False,
)
view = dataset.match(filter)
```

FYI, I think you want to use `contains()`, not `is_subset()`:

```py
# Matches samples that contain at least one car, and possibly other objects
filter = F(field_name + ".detections.label").contains("car")

# Matches samples that contain *only* cars
filter = F(field_name + ".detections.label").is_subset("car")
```

**Comment by sanjeev-sudarsan** [comment]
Hi @brimoor 

Thank you very much for the quick reply. `match_labels()` works for my use case. 

I wanted to use `is_subset()` so that I can find samples that have only the labels I specify. However, I can make do with `match_labels()` for now.

**Comment by brimoor** [comment]
Ah you can still use `is_subset()` like this:

```py
filter = F(field_name).exists().if_else(
    F(field_name + ".detections.label").is_subset(["car"]),
    False,
)
view = dataset.match(filter)
```

**Comment by sanjeev-sudarsan** [comment]
Thank you so much. This is exactly what I was looking for.
