### ISSUE TITLE
[BUG] Jinja2 requirement has medium CVE

### ISSUE THREAD

**Issue by pseudotensor** [voxel51/fiftyone#4480]
https://github.com/voxel51/fiftyone/blob/develop/requirements/common.txt#L11

**Comment by benjaminpkane** [comment]
Thanks @pseudotensor. https://github.com/voxel51/fiftyone/pull/4481 will resolve this

**Comment by pseudotensor** [comment]
Great thanks!

**Comment by pseudotensor** [comment]
It is safe to say that if one deleted jinja2 or (say) forced an upgrade of it, that fiftyone would not changes its functioning because it was only used to build the docs?

**Comment by benjaminpkane** [comment]
> It is safe to say that if one deleted jinja2 or (say) forced an upgrade of it, that fiftyone would not changes its functioning because it was only used to build the docs?

Yes, that should have no effect. `Jinja>=3` is sufficient 👍
