### ISSUE TITLE
[FR] Support Ubuntu 24.04

### ISSUE THREAD

**Issue by TvdrBurgt** [voxel51/fiftyone#4526]
### Proposal Summary

Support [Ubuntu 24.04](https://releases.ubuntu.com/noble/).

### Motivation

For all users eager to work with the latest Ubuntu release, they would see Fiftyone fail because `MongoDB` could not be installed on your system. [MongoDB](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/) does not support Ubuntu 24.04 yet, but it would be very nice to have Fiftyone working again out-of-the-box when MongoDB is ready!

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

We don't know how long it takes for MongoDB to support Ubuntu 24.04.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [ ] Yes. I can contribute this feature independently
-   [ ] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [x] No. I cannot contribute this feature at this time

**Comment by benjaminpkane** [comment]
Hi @TvdrBurgt. A [MongoDB](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection) can be configured for systems without a compatible `fiftyone-db` binary.

If you are able to confirm MongoDB 22.04 works on 24.04 we can add built-in support for Ubuntu 22.04

**Comment by CourchesneA** [comment]
Seems like mongo db isn't officially supported on 24.04 yet. I was able to install it using

```
echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
sudo apt install -y mongodb-org
```
Fiftyone work as expected after that

**Comment by TvdrBurgt** [comment]
> Hi @TvdrBurgt. A [MongoDB URI](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection) can be configured for systems without a compatible built-in `fiftyone-db` binary.
> 
> If you are able to confirm MongoDB 22.04 works on 24.04 we can add built-in support for Ubuntu 22.04

Like @CourchesneA suggested, you can install MongoDB with a workaround and configure Fiftyone with the database URI. That works like a charm.
