### ISSUE TITLE
take(seed=None) does not appear properly in App

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#455]
If a seed is not set when running `take()`, then every time the session is refreshed in the app, a new set of samples will be displayed.

```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("cifar10", split="test")

subset = dataset.take(10)
print([s.filename for s in subset])
```

```
['06659.jpg',
 '00419.jpg',
 '01536.jpg',
 '00330.jpg',
 '02030.jpg',
 '04888.jpg',
 '08857.jpg',
 '00971.jpg',
 '04324.jpg',
 '04081.jpg']
```

```python
session = fo.launch_app(view=subset)
# App shows a different set of images than in the subset
```
![image](https://user-images.githubusercontent.com/21222883/91335066-e371f700-e79d-11ea-9db7-54423b59faad.png)

```
session.view = subset
# App shows yet another different set of images
```
![image](https://user-images.githubusercontent.com/21222883/91335123-f8e72100-e79d-11ea-9dd6-3faf3aa1024f.png)

```
print([s.filename for s in subset])  # Still the same subset in python
```
```
['06659.jpg',
 '00419.jpg',
 '01536.jpg',
 '00330.jpg',
 '02030.jpg',
 '04888.jpg',
 '08857.jpg',
 '00971.jpg',
 '04324.jpg',
 '04081.jpg']
```

If you set a seed then everything works as expected. The App must be generating a random seed every time the session is refreshed, it should just be taking the seed from the existing view. 

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

**Comment by benjaminpkane** [comment]
This is a serialization issue.

`view.take(1).serialize()` yields:

```
{'dataset': {'name': '...'},
 'view': '[{"kwargs": [["size", 1], ["seed", null]], "_cls": "fiftyone.core.stages.Take"}]'}
```

So the server finds it's own seed when instantiating its version of the view. The "hidden" seed value needs to be serialized and acknowledged when instantiating the stage on the server (in `from_dict`).

**Comment by benjaminpkane** [comment]
I'll note it will take a couple of small changes in the App if we want to achieve similar behavior in the view bar. It can be a separate PR.

**Comment by brimoor** [comment]
Closing this PR as per https://github.com/voxel51/fiftyone/pull/459.

Will make a separate PR to avoid `Take(seed=None)` refreshing when the view bar is modified.
