### ISSUE TITLE
[BUG] Adding 'sample tag' in UI causes image viewer to close.

### ISSUE THREAD

**Issue by oliviajbreen** [voxel51/fiftyone#4564]
### Problem

When using the UI, (both the desktop app and the web browser) the viewer closes when attempting to add a 'sample tag' to an image. Images can only be tagged from the 'home' view. 

Below, I use screenshots from the 'quickstart' dataset to demonstrate, but the bug does not occur with this dataset.

When selecting 'sample' under 'labels' within the image viewer, the image closes.

![bug image 1](https://github.com/voxel51/fiftyone/assets/150411293/ec9b45b3-7bd5-42da-b927-c6bb057a6f7e)

Images can be tagged from this view only.

![bug image 2](https://github.com/voxel51/fiftyone/assets/150411293/acb7396a-6966-4e5d-9162-552e848d2fef)

### System information

-   **OS Platform and Distribution** (Linux Ubuntu 20.04, Windows 11 Pro):
-   **Python version** (`python --version`): 3.11.5, 3.11.8
-   **FiftyOne version** (`fiftyone --version`): v0.24.1
-   **FiftyOne installed from** (pip or source): pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [X] No. I cannot contribute a bug fix at this time (I don't know enough yet, sorry!)

**Comment by benjaminpkane** [comment]
Hi @oliviajbreen. Do you see any errors in the develop tools console when this issue occurs?

**Comment by benjaminpkane** [comment]
Resolved by https://github.com/voxel51/fiftyone/pull/4621
