### ISSUE TITLE
[DOCS] Serve multiple remote sessions from a machine without session.wait() blocking

### ISSUE THREAD

**Issue by cs-mshah** [voxel51/fiftyone#4572]
### URL(s) with the issue

https://docs.voxel51.com/faq/index.html#can-i-serve-multiple-remote-sessions-from-a-machine

### Description of proposal (what needs changing)

After trying this the session closes since there is no `session.wait()`. If we add `session1.wait()`, then this is blocking the serving of `session2`. For my use case, I want to serve multiple datasets on different ports and then connect to them remotely so that I can compare different datasets.

How do I achieve this?

**Comment by benjaminpkane** [comment]
Hi @cs-mshah. This can be accomplished with multi-threading or multi-processing but documentation currently out of scope for the open source project. If you have team, please [reach out](https://voxel51.com/book-a-demo/)! 🚀
