### ISSUE TITLE
[BUG] The transformer models are not using GPU

### ISSUE THREAD

**Issue by sanjeev-sudarsan** [voxel51/fiftyone#4585]
### Describe the problem

I am trying to create image visualizations for a dataset using the `detection-transformer-torch` model. The model takes 2 hours for 7000 images. I checked the GPU usage and it was not being used. The same thing happened with the `classification-transformer-torch` model as well.

All the pytorch models use the GPU, I am only facing this problem with the transformers.

### Code to reproduce issue

```
import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.brain as fob


model = foz.load_zoo_model("detection-transformer-torch")

dataset = fo.load_dataset("test_dataset")

results = fob.compute_visualization(
    dataset,
    model=model,
    seed=51,
    brain_key="img_viz_detection_transformer",
)
```
![Screenshot from 2024-07-19 13-28-03](https://github.com/user-attachments/assets/67e712eb-f77e-410b-9f9f-5d9d9111addf)

### System information

-   **OS Platform and Distribution**: 22.04
-   **Python version** : 3.10.12
-   **FiftyOne version**: 0.24.0
-   **FiftyOne installed from**: pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
This is resolved by https://github.com/voxel51/fiftyone/pull/4587 and is available on `develop` now. It will be released as part of `fiftyone==0.25`, which is scheduled for August 13.
