### ISSUE TITLE
[BUG] Cannot download plugins from branches that contain slashes '/'

### ISSUE THREAD

**Issue by mbaut** [voxel51/fiftyone#4610]
### Describe the problem

Parser for downloading plugins from github repo is not working correctly.

### Code to reproduce issue

Lets say you have company A that has a github org, with a repo named B, and on that a branch called prod the link would be

github.com/A/B/prod

but if we have a look at the github parser in the following line, we can see the regex is ignoring "prod":

https://github.com/voxel51/fiftyone/blob/fd846d20c88a43077b96ce6b4b56f10524e3fe1f/fiftyone/utils/github.py#L219

### System information

not needed

### Other info/logs

If other people have the same problem a way to fix it is just having another word at the end
github.com/A/B/prod/this-is-ignored

the sad part is if you have a branch that is not only a word, but has a slash like "bugfix/branch" This way you will not be  able to download your plugin sadly.

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @mbaut 👋 

As documented by [`download_plugin()`](https://docs.voxel51.com/api/fiftyone.plugins.html#fiftyone.plugins.download_plugin), when downloading from a specific branch, the syntax is `https://github.com/<user>/<repo>/tree/<branch>`, not `https://github.com/<user>/<repo>/<branch>`.

That said, you are 100% correct that there is a bug with the current implementation if you try to download a plugin from a branch that contains a slash. I've fixed this bug in https://github.com/voxel51/fiftyone/pull/4614 and it will be released as of `fiftyone==0.25`, scheduled for release on August 13 🙌

**Comment by mbaut** [comment]
Hi @brimoor,
Thank you very much for the fast reply!! Great that there already is a fix!!
Just wanted to also comment, as regex is always a bit hard to get, how it works with the fix, if I understand correctly is declared with following examples:

github.com/a/b/c
Would take User a repo b and branch c

github.com/a/b/c/d
Would take user a repo b and branch d

If you add anything after d the branch would be d/e/f...

While this works as described in the Readme provided (you should add /tree/) the fact that you should give /tree/ is not enforced and people could end up into giving a branch like github.com/user/repo/this/is/a/branch and ending up downloading branch /is/a/branch.

(I think all this is not really too important just an interesting quirk if somebody had the same problems that I did :), thanks for your effort @brimoor )
