### ISSUE TITLE
Line wrapping for filepath on expanded sample view is not happening

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#464]
Long filepaths in expanded sample view no longer seem to be line-wrapping as of v0.5.2

<img width="1008" alt="Screen Shot 2020-08-26 at 10 14 49 PM" src="https://user-images.githubusercontent.com/25985824/91375971-088c5700-e7ea-11ea-9f33-c74bf696b421.png">

**Comment by benjaminpkane** [comment]
Working on it.

**Comment by brimoor** [comment]
Addressed in v0.5.3
