### ISSUE TITLE
App cannot handle empty views

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#466]
The App hits an error when trying to load an empty view, e.g., `Exists("field_that_does_not_exist")`.

**Comment by benjaminpkane** [comment]
I'm not seeing this on `develop`.
![Screenshot from 2020-08-27 09-56-00](https://user-images.githubusercontent.com/19821840/91451570-8e8cba00-e84b-11ea-8da4-ea062b19cf27.png)

**Comment by benjaminpkane** [comment]
Disregard, I am able to find issues like this when there are labels present. Working on it.

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/pull/459
