### ISSUE TITLE
[BUG] Pixelating following "at onclose" error

### ISSUE THREAD

**Issue by SombreroMickey** [voxel51/fiftyone#4675]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

1. Please fill in this template to ensure a timely and thorough response
2. Remove the section instructions but leave the section header
3. Place an "x" between the brackets next to an option if it applies. For
   example:
    - [x] Selected option
4. **Please delete everything above this line before submitting the issue**

### Describe the problem

Hello, I tried to attach to session with my browser and immediatelyit stopped on Pixelating, following by this error after while:

Error
    at onclose (https://my_ip/assets/index-CZbjPy2v.js:880:1049)
    at A (https://my_ip/assets/index-CZbjPy2v.js:879:1487)
Is there any way to avoid this? 

### Code to reproduce issue
I installed these version:
fiftyone==0.24.1
fiftyone-brain==0.16.1
fiftyone-db==0.4.0

then I tried updatiny fiftyone-brain and dbmanually as well
fiftyone==0.24.1
fiftyone-brain==0.17.0
fiftyone_db==1.1.5
but issue persists

`session = fone.launch_app(port=1550)`

```
# commands and/or screenshots here
```

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04):
-   **Python version** (`python --version`):
- Python 3.8.10
-   **FiftyOne version** (`fiftyone --version`):
- FiftyOne v0.24.1, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source):
pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [*] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @SombreroMickey 👋  This [FAQ](https://docs.voxel51.com/faq/index.html#why-isn-t-the-app-opening-not-connected-to-a-session) might help
