### ISSUE TITLE
[FR] Save screen real estate by minimizing display options bar

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#471]
From @briankelly: Consider saving some screen real estate by eliminating this `Display Options` toggle and using a simple visual hint that this section is a drawer.

Here's some inspiration:

![image](https://user-images.githubusercontent.com/25985824/91578491-3ff92180-e918-11ea-9c09-8a7edc206cb0.png)

**Comment by lethosor** [comment]
I don't think this is necessary to change. There's already a row in use at the top, where more controls will be added, so the toggle isn't taking up any additional vertical space (at least, it won't be when more controls are added). Adding a drawer will take away space from the entire sample grid, even when the sidebar is hidden.

**Comment by brimoor** [comment]
I think the impetus for the request is that this UI element just looks really big. It doesn't really make sense to take up so much visual attention for a simple show/hide operation. That's why it has already been decreased in size w.r.t. the original design.

We'll have to solicit feedback from designer Claire before acting on this

**Comment by briankelly** [comment]
> I think the impetus for the request is that this UI element just looks really big.

This is accurate. I hear you regarding vertical space, @lethosor. Ideally we could get a win there, too, but if not, simply taking away a huge label `[Display Options        ^]` will improve the user's experience by not having so many things that are grabbing the user's attention.

**Comment by benjaminpkane** [comment]
Stale
