### ISSUE TITLE
[FR] Provide a more discoverable way to toggle between image grid view and expanded sample view

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#472]
From @briankelly: I totally get why double-clicking was chosen as the way to get detail about the image, but it’s not discoverable. I can’t think of any contemporary UI that requires a double-click to invoke an action. There should be some other way to view the horse llama in all its glory

![image (1)](https://user-images.githubusercontent.com/25985824/91578633-7171ed00-e918-11ea-9265-478230d11ad6.png)

**Comment by brimoor** [comment]
I definitely agree with this one. Early on in the design, we had the typical `list view` vs `grid view` toggle where it says `viewing X samples` in the screenshot below. However, that went away when we dropped support for list view (for now).

Since this is a familiar location to put a toggle that controls visual layout, I think we should reintroduce a two icon toggle there:

```
Viewing X samples     [grid icon] [single image icon]
```

`[grid icon]` would be selected when viewing the image grid view, and clicking `[single image icon]` would open up the modal.

<img width="732" alt="Screen Shot 2020-08-28 at 10 24 12 AM" src="https://user-images.githubusercontent.com/25985824/91578809-b72eb580-e918-11ea-8c49-f811ad427657.png">

**Comment by lethosor** [comment]
This is essentially already covered by #113 and #139.

> `[grid icon]` would be selected when viewing the image grid view, and clicking `[single image icon]` would open up the modal.

I think having an icon like this open a *modal* is unintuitive, as well as hard to implement - how do you decide which image to display in the modal if no images or more than one image are selected?

**Comment by benjaminpkane** [comment]
Stale
