### ISSUE TITLE
[FR] Add start and end frame argument for Sample of video type

### ISSUE THREAD

**Issue by AntonClaesson** [voxel51/fiftyone#4749]
### Proposal Summary

Add optional start and end frames as arguments when creating a video Sample. This would allow the user to upload a video sample containing only relevant parts of a longer source video. 

### Motivation

- **Use Case:** I find myself working on video data where samples are obtained using a sliding window over the source video. I want to be able to upload these video samples to fiftyone without having to save each individual video slice to disk, which would be resource intensive and lead to data duplication. In other words, all samples coming from the same source video can use the same filepath, but with different start and end frames. 
- **Why It Matters:** This feature would save time and storage by eliminating the need to create new video snippets for relevant part of the source video, making workflows more efficient for users who deal with large video files.

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Willingness to contribute

-   [ ] Yes. I can contribute this feature independently
-   [x] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by AntonClaesson** [comment]
To make this clear, I would like to specify the start and end of the video samples in some similar way to this:

```python
source_video = "example.mp4"

# Snippet 1
sample1 = fo.Sample(filepath=source_video)
sample1.frames.start = 300
sample1.frames.end = 1000

# Snippet 2
sample2 = fo.Sample(filepath=source_video)
sample2.frames.start = 34123
sample2.frames.end = 45253
```

**Comment by benjaminpkane** [comment]
Hi @AntonClaesson. [TemporalDetections](https://docs.voxel51.com/user_guide/using_datasets.html#temporal-detection) may suit your use case.

If one video only has one frame range, then a single `TemporalDetection` per sample would be sufficient. And you can then create a [clips view ](https://docs.voxel51.com/user_guide/app.html#viewing-video-clips) against the temporal detection field

```python
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video")
for sample in dataset:
    sample["clips"] = fo.TemporalDetection(support=[1, 60], label="first-sixty")
    sample.save()

clips = dataset.to_clips("clips")
session = fo.launch_app(clips)
```

**Comment by AntonClaesson** [comment]
@benjaminpkane 

This is kind of what I was looking for, thanks! Will solve my use-case good enough.
I do have multiple clips per source video, and I wish each clip to be considered a unique sample.

I discovered I can modify your code to something like this, to only have to compute metadata once for a single source video:

```python
base = fo.Sample(filepath="video.mp4")
base.compute_metadata()

sample1 = base.copy()
sample1["clips"] = fo.TemporalDetection(support=[1, 60], label="1")
dataset.add_sample(sample1)

sample2 = base.copy()
sample2["clips"] = fo.TemporalDetection(support=[61, 120], label="2")
dataset.add_sample(sample1)

clips = dataset.to_clips("clips")
session = fo.launch_app(clips)
```

**Comment by benjaminpkane** [comment]
Yes, there can be multiple samples with the same filepath in a dataset. Glad you're unblocked! 🚀
