### ISSUE TITLE
[INSTALL] obtaining quickstart.zip file

### ISSUE THREAD

**Issue by apiszcz** [voxel51/fiftyone#4760]
Is there an alternative method to obtain the qickstart.zip file? Company firewall/policy does not permit access to google drive.
Thank you.

**Comment by swheaton** [comment]
[quickstart.zip](https://github.com/user-attachments/files/16850170/quickstart.zip)

It's small enough that I can just upload it here. Enjoy.

But currently we do not have plans to change the hosting location for the quickstart datasets.
