### ISSUE TITLE
[BUG] Unable to get `Frames` info after serializing/de-serializing the video samples

### ISSUE THREAD

**Issue by CompilerBian** [voxel51/fiftyone#4762]
### Describe the problem

I am using apache beam framework to process my dataset. This requires serializing samples before creating an iterator for the beam pipeline(as is suggested [here](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/utils/beam.py#L118-L120)), my sample media type is video and I need to extract annotation info from sample's `frames`. But after I serialized the samples and de-serialized it back, the sample.frames became empty. Here is the sample code I used to test this issue:

```
serialized_sample = original_sample.to_mongo_dict()
deserialized_sample = fo.Sample.from_dict(serialized_sample)
old_frames = original_sample.frames
new_frames = deserialized_sample.frames
print(f"  Frame counts before serialization: {sum(1 for _, _ in old_frames.items())}")
print(f" Frame counts after serialization: {sum(1 for _, _ in new_frames.items())}")
```
The output of the sample code is 

```
Frame counts before serialization: 100
Frame counts after serialization: 0
```
I can confirm that all the rest of the fields of the samples can be deserialized correctly, only the `frames` is totally lost, not sure if it is a bug or I didn't use the serialization correctly. Any insight would be appreciated. 

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04):
-   **Python version** (`python --version`): 3.10.8
-   **FiftyOne version** (`fiftyone --version`): 0.25.0
-   **FiftyOne installed from** (pip or source): pip

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached. Please do not use screenshots for sharing text. Code
snippets should be used instead when providing tracebacks, logs, etc.

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @CompilerBian 👋 

You can use `sampleto_dict(include_frames=True)` for this case:

```py
import fiftyone as fo

sample = fo.Sample(filepath="video.mp4")
sample.frames[1] = fo.Frame(foo="bar")
sample.frames[2] = fo.Frame(spam="eggs")

dataset = fo.Dataset()
dataset.add_sample(sample)

d = sample.to_dict(include_private=True, include_frames=True)
s = fo.Sample.from_dict(d)
```
