### ISSUE TITLE
[BUG] Text similarity cannot be computed using embeddings

### ISSUE THREAD

**Issue by sanjeev-sudarsan** [voxel51/fiftyone#4848]
### Describe the problem

After computing embeddings using the model `clip-vit-base32-torch`, if I compute similarity using these embeddings, image similarity is calculated instead of text similarity. However, if I use the model directly in the `compute_similarity()` function, text similarity is computed.

This means that if I add new images to a dataset, I have to recompute both the embeddings and similarity for all the images. Instead I would like to just compute embeddings for the new images and then compute text similarity for all the images.

### Code to reproduce issue

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
model = foz.load_zoo_model("clip-vit-base32-torch")

dataset.compute_embeddings(
    model, embeddings_field="clip_embeddings"
)

image_index = fob.compute_similarity(
    dataset, embeddings="clip_embeddings", brain_key="text_sim_clip"
)

assert image_index.config.supports_prompts
```

### System information

-   **OS Platform and Distribution** : Linux Ubuntu 22.04
-   **Python version** : 3.10.12
-   **FiftyOne version** : 0.25.0
-   **FiftyOne installed from**: pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @sanjeev-sudarsan 👋 

You can declare the model that was used to generate the precomputed embeddings by including the `model="clip-vit-base32-torch"` parameter in addition to `embeddings=` like so:

Now the similarity index supports text similarity while avoiding recomputing the embeddings when `compute_similarity()` is called:

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
model = foz.load_zoo_model("clip-vit-base32-torch")

dataset.compute_embeddings(model, embeddings_field="clip_embeddings")

image_index = fob.compute_similarity(
    dataset,
    model="clip-vit-base32-torch",  # declare model that was used
    embeddings="clip_embeddings",
    brain_key="text_sim_clip",
)

# Now works!
assert image_index.config.supports_prompts
```

**Comment by brimoor** [comment]
Regarding adding new samples, you can achieve this like so:

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
model = foz.load_zoo_model("clip-vit-base32-torch")

view1 = dataset[:100]
view1.compute_embeddings(model, embeddings_field="clip_embeddings")

image_index = fob.compute_similarity(
    dataset,
    model="clip-vit-base32-torch",  # declare model that was used
    embeddings="clip_embeddings",
    brain_key="text_sim_clip",
)

# Now works!
assert image_index.config.supports_prompts

print(image_index.total_index_size)  # 100

view2 = dataset[100:]
view2.compute_embeddings(model, embeddings_field="clip_embeddings")

image_index.reload()

print(image_index.total_index_size)  # 200
```

The above assumes you're using the default `sklearn` backend. If you're using another backend (say `pinecone`), then you'll need to use `add_to_index()` to add the new embeddings to the index as described here:
https://docs.voxel51.com/brain.html#adding-embeddings-to-an-index
