### ISSUE TITLE
[BUG] YoloV5 bboxes treated as x-min y-min width height but should be x-center y-center width height

### ISSUE THREAD

**Issue by daniel-bogdoll** [voxel51/fiftyone#4887]
### Describe the problem

YoloV5 bbox format is defined as ```x-center y-center width height``` in rel. coordinates between [0,1]:

- https://docs.voxel51.com/user_guide/export_datasets.html#yolov5dataset
- https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#21-create-datasetyaml
- https://roboflow.com/formats/yolov5-pytorch-txt?ref=ultralytics

However, fiftyone seems to treat it as ```x-min y-min width height```

For a ```sample``` of a ```fo.types.YOLOv5Dataset```, when I draw a rectangle manually under the ```center``` assumption:

```
img_width = sample.metadata.width
img_height = sample.metadata.height

x_center, y_center, width, height = bbox.bounding_box

# Convert into absolute coordinates
x_center *= img_width
y_center *= img_height
width *= img_width
height *= img_height

# Compute corners from center coordinates
x_min = int(x_center - width / 2)
x_max = int(x_center + width / 2)
y_min = int(y_center - height / 2)
y_max = int(y_center + height / 2)

draw.rectangle([x_min, y_min, x_max, y_max], outline=255)
```

In fiftyone, the rectangles do not align with the automatically visualized bounding boxes:

![image](https://github.com/user-attachments/assets/1f919a19-d677-47c5-ada7-5a5e5e5068fd)

However, when I treat the bbox with the ```min``` assumption, it works:

```
# Convert into absolute coordinates
x_min_rel, y_min_rel, width_rel, height_rel = bbox.bounding_box
x_min = int(x_min_rel * img_width)
y_min = int(y_min_rel * img_height)
x_max = int((x_min_rel + width_rel) * img_width)
y_max = int((y_min_rel + height_rel) * img_height)
```

![image](https://github.com/user-attachments/assets/d1ad607e-4cf6-47da-b1a4-a89dfabbc7f9)

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @daniel-bogdoll 👋 

The [YOLOv5 importer](https://docs.voxel51.com/user_guide/dataset_creation/datasets.html#yolov5dataset) does correctly assume that the input `.txt` files contain object detections in this format:

```
<target> <x-center> <y-center> <width> <height>
```

However, whenever data of any kind is imported into a FiftyOne dataset, it is always normalized to [FiftyOne format](https://docs.voxel51.com/user_guide/using_datasets.html#object-detection) so that the FiftyOne App knows how to visualize it:

```
detection.bounding_box = [<top-left-x>, <top-left-y>, <width>, <height>]
```

I think this is the missing context in your case 😄
