### ISSUE TITLE
[BUG] `fiftyone app launch` terminates instantly in v1.0.0

### ISSUE THREAD

**Issue by Laurent2916** [voxel51/fiftyone#4889]
### Describe the problem

In v0.25.2 I used to start fiftyone by doing: `fiftyone app launch` and everything worked fine.
I upgraded to v1.0.0, but now executing the same command doesn't work like it used to (see "Code to reproduce issue" below).

Current work-around is to start the server directly:
```shell
python $(python -c "from fiftyone.server import main; print(main.__file__)") --port 4545
```
As a side-note, is it possible to downgrade (temporarily) ? It seems the app won't let me re-use v0.25.2 now that it migrated to v1.0.0. 

### Code to reproduce issue

```shell
(.venv) laurent@laptop:~/fiftyone_data$ fiftyone app launch --port 4545
App launched. Point your web browser to http://localhost:4545

To exit, close the App or press ctrl + c
# the server terminates instantly here, without any error message
```

### System information

-   **OS Platform and Distribution**: Ubuntu 24.04 LTS
-   **Python version**: Python 3.10.14
-   **FiftyOne version**: FiftyOne v1.0.0
-   **FiftyOne installed from**: [rye](https://github.com/astral-sh/rye) (which uses [uv](https://github.com/astral-sh/uv))

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Apologies, this is fixed by https://github.com/voxel51/fiftyone/pull/4888 and will be released as part of `fiftyone=1.0.1`.

In the meantime, on `fiftyone==1.0.0` you'll need launch the App via `launch_app()` in Python.
