### ISSUE TITLE
[BUG] `fo.Classifications` labels aren't displayed in UI in v1.0.0

### ISSUE THREAD

**Issue by Laurent2916** [voxel51/fiftyone#4890]
### Describe the problem

It seems `fo.Classifications` fields aren't displayed in the UI from v1.0.0 (they were correctly displayed in v0.25.2).
![image](https://github.com/user-attachments/assets/a4f57c69-1952-4b91-a4cb-48e7544d8766)
From the code snippet below, we should see "three" and "four" on the sample.

From looking at [the release note for v1.0.0](https://docs.voxel51.com/release-notes.html#fiftyone-1-0-0), I guess the culprit would be https://github.com/voxel51/fiftyone/pull/4747

### Code to reproduce issue

```python
import fiftyone as fo

dataset = fo.load_dataset("tmp_dataset_laurent")
for sample in dataset:
    sample["classification1"] = fo.Classification(label="one")
    sample["classification2"] = fo.Classification(label="two")
    sample["classifications1"] = fo.Classifications(classifications=[fo.Classification(label="three")])
    sample["classifications2"] = fo.Classifications(classifications=[fo.Classification(label="four")])
    sample.save()
```

### System information

-   **OS Platform and Distribution**: Ubuntu 24.04 LTS
-   **Python version**: Python 3.10.14
-   **FiftyOne version**: FiftyOne v1.0.0
-   **FiftyOne installed from**: [rye](https://github.com/astral-sh/rye) (which uses [uv](https://github.com/astral-sh/uv))

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Thanks @Laurent2916. This will be fixed in 1.0.1
