### ISSUE TITLE
Limit number of significant digits shown for floating point numbers in Player51

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#491]
Floating point attribute values can show too many decimal places in Player51 currently. It takes up visual space without providing any value.

I request that the same logic used by ETA is used here:
- if the data is an int, render as `%d`
- if the data is any other numeric, render as `%.2g` (or a JS equivalent)

https://github.com/voxel51/eta/blob/ec7752c4dff1b750a3eb902b9ea5becc73f9e440/eta/core/annotations.py#L1491-L1495

<img width="1623" alt="Screen Shot 2020-09-01 at 6 10 11 PM" src="https://user-images.githubusercontent.com/25985824/91911787-cea2d100-ec7f-11ea-8ae2-1a7c541ee631.png">

**Comment by lethosor** [comment]
I added optional support for applying the standard fiftyone-side formatting to numbers in #487, but had it disabled since I wasn't sure if the player51-side defaults were reasonable. I'll enable it - note that it will round to 3 decimal places, since that's what the rest of the app does.
