### ISSUE TITLE
Confidence slider labels don't disappear and are slightly misaligned

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#493]
This issue applies both to the sliders in expanded view and image grid view.

On v0.5.3, the labels on the confidence sliders never disappear. Previously they would only appear when the slider was hovered or selected, which I thought was really effective and avoided them overlapping other content unless you were actively manipulating them.

Also, they are offset to the left of the actual endpoints on the number line.

Finally, in a dev build on my mac, the orange teardrops aren't visible (but they are in production):

Prod build:
<img width="1180" alt="Screen Shot 2020-09-01 at 10 41 39 PM" src="https://user-images.githubusercontent.com/25985824/91926623-a29a4680-eca5-11ea-91a3-cf055d5fc12a.png">

Dev build:
<img width="1136" alt="Screen Shot 2020-09-01 at 10 52 06 PM" src="https://user-images.githubusercontent.com/25985824/91926687-c8bfe680-eca5-11ea-83ea-2ebb1503bf6d.png">

**Comment by benjaminpkane** [comment]
This is very odd. My initial attempt proved to be unsuccessful. I will need to circle back to this. I have no explanation for this at the moment, and am not sure how to understand this without building the App with dev tools available, etc. (set up work).

Another reason why I don't like frameworks.

**Comment by lethosor** [comment]
Another question (for @brimoor) is whether you're using a dev build of the same commit that was used in the prod build (i.e. `git checkout v0.5.3`). If not, it's possible that something changed between the two versions.
