### ISSUE TITLE
This is ridiculous

### ISSUE THREAD

**Issue by Seedmanc** [voxel51/fiftyone#4935]
![image](https://github.com/user-attachments/assets/18ba26eb-4781-4e8a-a132-d4167af55bec)
![image](https://github.com/user-attachments/assets/7ca7370a-a4a6-4e3e-b4b8-e6dc8f63fd98)

every fucking time

**Comment by thesteve0** [comment]
Can you please show the code you are using. That would help us diagnose the problem

**Comment by brimoor** [comment]
@Seedmanc apologies, this was fixed in https://github.com/voxel51/fiftyone/pull/4888 and has been released as part of `fiftyone==1.0.1`.

`pip install --upgrade fiftyone` should resolve this ✅
