### ISSUE TITLE
[BUG] - Patch view of samples loses crop view if toggling to the left

### ISSUE THREAD

**Issue by quitmeyer** [voxel51/fiftyone#5050]
### Describe the problem

if you are in patch view, and click a thumbnail to see a specific image you will see a fullscreen-ish image cropped to the view of the patch. Great, that's what i expect. 

Next if you press right on the keyboard, or press the right arrow, you will see the next patch in the queue, again with the default view of the patch cropped to the patch. 
![image](https://github.com/user-attachments/assets/94014b6f-7e15-410d-869c-741505a6d641)

IF you happen to go back though, or press the left arrow, the default crop to patch view is messed up

![image](https://github.com/user-attachments/assets/9cdef875-fe90-4e42-8c29-11a591fc43e8)
and look it still thinks "crop to patch" is selected, but now it's stuck at the full image instead of the patch.

if i hit the "esc" key from this zoomed out view, it will change the view to the crop-to patch view

![image](https://github.com/user-attachments/assets/dfa91613-efd9-4459-91c8-4cfe0d23f4c7)

### System information

windows
firefox/chrome
just updated fiftyone

**Comment by brimoor** [comment]
@quitmeyer thanks for reporting, we'll get this fixed 🫡

**Comment by quitmeyer** [comment]
cool!

**Comment by benjaminpkane** [comment]
Due to routing changes. This has been fixed (incidentally) in the upcoming patch release `1.0.2`

**Comment by quitmeyer** [comment]
super cool!
