### ISSUE TITLE
How to annotate in CVAT both Classifications and Detections simultaneously?

### ISSUE THREAD

**Issue by thiagoribeirodamotta** [voxel51/fiftyone#5107]
Hello there,

I'm working on a dataset that consists both of bounding boxes (as fo.Detections) and labels (as fo.Classifications).

I can use fiftyone to upload those to CVAT, which will automatically create a CVAT project, task and job with the desired images, but I can only upload one field at a time:

```
curr_view.annotate(
        'uploading_bb',
        label_field='ground_truth',
        project_name=project_name,
        organization=organization,
        launch_editor=False,
        url=url)

curr_view.annotate(
        'upload_tags',
        label_field='TAGs',
        label_type='classifications',
        classes=[x for x in classes_datalake if 'TAG' in x],
        project_name=project_name,
        organization=organization,
        launch_editor=False,
        url=url)
```

Which results in two different tasks being created, one just with bounding boxes and another just with CVAT TAGs. 

How can I create a job that simultaneously have both bounding boxes and TAGs?

**Comment by brimoor** [comment]
Hi @thiagoribeirodamotta 👋 

Here's how to annotate multiple label fields in a single job: 
https://docs.voxel51.com/integrations/cvat.html#annotating-multiple-fields
