### ISSUE TITLE
[BUG] Video playback not working

### ISSUE THREAD

**Issue by leemengtw** [voxel51/fiftyone#5199]
### Describe the problem

As title, the video playback is not working thus one can't view all the video frames except the first one.

### Code to reproduce issue

The issue can be reproduced by following the official FiftyOne example:
- https://github.com/voxel51/fiftyone-examples/blob/master/examples/Video%20Labels.ipynb

Minimal code to reproduce (adapted from above notebook):
```
!pip install kaggle
!kaggle datasets download -d risangbaskoro/wlasl-processed
!mkdir wlasl-processed
!unzip wlasl-processed.zip -d wlasl-processed

main_path = './wlasl-processed/'
mp4_dir = main_path + "videos"

import fiftyone as fo

dataset = fo.Dataset.from_dir(dataset_dir=mp4_dir,dataset_type=fo.types.VideoDirectory)
session = fo.launch_app(dataset)
```

![image](https://github.com/user-attachments/assets/f1c45285-333c-4eb9-a4ba-870a8efbc14c)

Note the video playback icon at the bottom left will keep circling thus the user can't play the video. Manual drag to other frame does not work neither.

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04): Linux Ubuntu 20.04.6
-   **Python version** (`python --version`): Python 3.10.14
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v1.0.2, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Other info/logs

- None of the following work: Chrome, Safari, embedded app inside Jupyter 

Possible relevant js issue:

![image](https://github.com/user-attachments/assets/df7f7970-f98a-4546-af6a-b801eff496b6)
 
### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [x] No. I cannot contribute a bug fix at this time

**Comment by VictorZuanazzi** [comment]
I am having the same issue. Video does not play, only the thumbnail is visible.  I am using fiffyone version 1.0.2 and python 3.11. 

I see the same js issue with the invalid range on my browser (chrome).

Any suggested workarounds?

**Comment by benjaminpkane** [comment]
This will be fixed in the next release. I can recommend `fiftyone==1.0.1` in the meantime. Resolved by https://github.com/voxel51/fiftyone/pull/5139

**Comment by Vinno97** [comment]
> This will be fixed in the next release. I can recommend `fiftyone==1.0.1` in the meantime.

With "the next release", do you mean `1.1.0`? Because I still have this behavior in that version. 1.0.1 works, though

**Comment by benjaminpkane** [comment]
Apologies. Will fix this today

**Comment by benjaminpkane** [comment]
This will be fixed in the forthcoming release, `fiftyone==1.2.0`

**Comment by orvisevans** [comment]
Is there an expected release date for `1.2.0`? This bug is tripping me up as well after I using some `1.1.0` features I'd like to continue using.

**Comment by benjaminpkane** [comment]
Yes! Tomorrow is the current plan.
