### ISSUE TITLE
[BUG] Images downloaded from COCO dataset are from the wrong class

### ISSUE THREAD

**Issue by torydebra** [voxel51/fiftyone#5210]
### Describe the problem
Hi, I am trying to download a subset of the COCO dataset, specifying only some classes. 

Hence, I have tried both the `fiftyone.zoo.load_zoo_dataset()` and `fiftyone.utils.coco.download_coco_dataset_split()`, specifying the `label_types`, and `classes` argument, respectively. The problem is that images of different class than the one I am requesting are downloaded.

### Code to reproduce issue
Here I am asking for bears, but cows are downloaded
```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    label_types=["detections", "segmentations"],
    classes=["bear"],
    only_matching=True,
    max_samples=10,
)
```

Same here, asking for "stop sign", but hydrants are given:
```python
import fiftyone as fo
import fiftyone.zoo as foz
fo.utils.coco.download_coco_dataset_split(dataset_dir="~/coco-2017", split="train", classes=["stop sign"], max_samples=5)
```

### System information

-   **OS Platform and Distribution** Ubuntu 20.04
-   **Python version** (`python --version`): Python 3.8.10
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.25.2, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @torydebra 👋 

This was fixed by https://github.com/voxel51/fiftyone/pull/4884. Upgrading `pip install fiftyone>=1.01` should resolve for you ✅

**Comment by torydebra** [comment]
Hi @brimoor, thanks, but unfortunately it seems that the last version for my system is the 0.25.2 : 
```
pip install "fiftyone>=1.01"
ERROR: Could not find a version that satisfies the requirement fiftyone>=1.01 (from versions: 0.1.0, 0.1.0.1, 0.1.2, 0.1.3, 0.2.0rc1, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.2.1, 0.5.3, 0.5.3.1, 0.5.4, 0.5.5, 0.5.5.1, 0.5.6, 0.6.0, 0.6.0.1, 0.6.1, 0.6.1.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.5.1, 0.6.5.2, 0.6.6, 0.7.0, 0.7.0.1, 0.7.1, 0.7.1.1, 0.7.1.2, 0.7.1.3, 0.7.1.4, 0.7.2, 0.7.3, 0.7.3.1, 0.7.3.2, 0.7.3.3, 0.7.3.4, 0.7.4, 0.8.0, 0.8.0.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.2.1, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.0.1, 0.15.0.2, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.18.0rc0, 0.18.0, 0.18.1rc0, 0.18.1rc1, 0.18.1rc2, 0.18.1rc3, 0.18.1rc4, 0.18.1rc5, 0.18.1rc6, 0.18.1rc7, 0.18.1rc8, 0.18.1rc9, 0.18.1rc10, 0.18.1rc11, 0.18.1rc12, 0.18.1rc13, 0.18.1rc14, 0.18.1rc15, 0.18.1rc16, 0.18.1rc17, 0.18.1rc18, 0.18.1rc19, 0.18.1rc20, 0.18.1rc21, 0.18.1rc22, 0.18.1rc23, 0.18.1rc24, 0.18.1rc25, 0.18.1rc26, 0.19.0, 0.19.1rc0, 0.19.1rc1, 0.19.1, 0.20.0, 0.20.1rc1, 0.20.1rc2, 0.20.1rc3, 0.20.1, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.21.4, 0.21.5, 0.21.6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.23.0rc1, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3rc1, 0.23.3, 0.23.4, 0.23.5, 0.23.6, 0.23.7, 0.23.8, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.25.2)
```

**Comment by brimoor** [comment]
In `fiftyone>=1.0` we dropped support for Python 3.8 as it has reached [end of life](https://devguide.python.org/versions/). I bet that's the reason.

Hopefully you can upgrade to `Python >=3.9` as FiftyOne has enjoyed some big upgrades since v0.25.2!
