### ISSUE TITLE
[FR] Add support for segmentation labels

### ISSUE THREAD

**Issue by qingzi02010** [voxel51/fiftyone#554]
I searched in https://voxel51.com/docs/fiftyone/, but I did not find the case related to segmentation labels.
All of the "segmentation" is set to  []. The segmentation task is so common that I am wonder whether it is supported on fiftyone or whether there are some plans for the segmentation support.

**Comment by brimoor** [comment]
Hi @qingzi02010, thanks for the question. FiftyOne will support both semantic segmentation and instance segmentation very soon, likely in the next release or two (we do weekly releases). I'll follow-up here when it is released!

**Comment by qingzi02010** [comment]
cool, thanks!

**Comment by brimoor** [comment]
Hey @qingzi02010 this is now supported! You can attached both semantic and instance segmentation masks to samples as of v0.6.0, and they will be rendered in the App if you load up a dataset that has such labels. Check out https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#semantic-segmentation for more details.

You can upgrade to the latest version by running:

```
pip install --index https://pypi.voxel51.com --upgrade fiftyone
```

Here's a toy example:

```py
import numpy as np
import fiftyone as fo

sample = fo.Sample(filepath="/path/to/white-image.png")

# Random instance mask
instance_mask = np.random.randn(32, 32) > 0

sample["detection"] = fo.Detection(
    label="cat",
    bounding_box=[0.3, 0.3, 0.4, 0.4],
    mask=instance_mask,
    confidence=0.9,
)

# Random segmentation mask
segmentation_mask = np.random.randn(64, 64) > 0

sample["segmentation"] = fo.Segmentation(mask=segmentation_mask)

dataset = fo.Dataset()
dataset.add_sample(sample)

session = fo.launch_app(dataset)
```

<img width="1443" alt="Screen Shot 2020-10-08 at 12 33 20 PM" src="https://user-images.githubusercontent.com/25985824/95487582-818eda80-0962-11eb-8b09-d5e3e6b3707a.png">

**Comment by qingzi02010** [comment]
Got it! Thanks so much for your share!
