### ISSUE TITLE
[FR] Add support for keypoints and polylines

### ISSUE THREAD

**Issue by qingzi02010** [voxel51/fiftyone#560]
The following two types of labels are used in automatic driving area:
1. The key points fitting of the lane , which can be inferenced and masked by point, similar to cv.circle function in python.
It is also important for the landmark annotation, for example facial landmark.
2. Lane area segmentation which can be inferenced and masked by polygon, similar to function  cv2.polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]) in python.

Is there any plan for these two labels? Thanks!

**Comment by brimoor** [comment]
Yes, another good point @qingzi02010. We don't currently have support for visualizing keypoints, polylines, and polygons in the App, but these are also on our short term roadmap. Stay tuned!

**Comment by brimoor** [comment]
Hey @qingzi02010 this is now supported! You can attach polylines, polygons, and keypoints to samples as of v0.6.1, and they will be rendered in the App if you load up a dataset that has such labels. Check out https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#polylines-and-polygons for more details.

You can upgrade to the latest version by running:

```
pip install --index https://pypi.voxel51.com --upgrade fiftyone
```

For example, here's what the Berkeley DeepDrive dataset looks like in FiftyOne:

<img width="1655" alt="fiftyone-v0 6 1" src="https://user-images.githubusercontent.com/25985824/95487842-d4689200-0962-11eb-9983-1061fbf6020e.png">

**Comment by qingzi02010** [comment]
Got it! Thanks so much for your share!
