### ISSUE TITLE
Support for pythonic sample matching in views

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#57]
The discussion below was prompted by the following command:

```py
view.match({"metadata.num_channels": 3, "metadata.size_bytes": {"$gt": 1200}})
```

Having the user write things like `"metadata.size_bytes": {"$gt": 1200}` is getting a little too close to exposing the user to MongoDB syntax for my taste.

In an ideal pythonic interface, one could write:

```py
view.match(lambda sample: sample.metadata.num_channels == 3)
```

Now, of course this would have to be implemented as a pipeline stage that read the samples into memory and applied the function, so it may not be as efficient as possible, but it would be very easy for the user to understand, and powerful.

Maybe the operation is reasonably fast even for datasets with 100K+ samples, and so we can just do it. Or maybe it's a bit slow so we expose the functionality and then suggest to the user that there are faster ways to implement certain operations.

This is analogous to https://www.tensorflow.org/api_docs/python/tf/py_function.

For any "optimized" operations we support, how about a more generic syntax like:

```py
view.match("'metadata.size_bytes' > 1200")
```

where we would have a simple whitespace-based parser that would translate the string into `"metadata.size_bytes": {"$gt": 1200}`.

The syntax of the match string `"'metadata.size_bytes' > 1200"` vs `"metadata.size_bytes": {"$gt": 1200}` is a small point.

The real ask here is implementing `view.match(<function>)` rather than `view.match(<match-string-using-either-syntax>)`. In the former case, the user has ultimate power to define a match operation that depends on 15 different fields in strange ways, which they can put in their custom, IDE-friendly function, at the cost of a potentially small performance overhead of reading the samples into memory during that stage.

**Comment by tylerganter** [comment]
Resolved by #290
