### ISSUE TITLE
[BUG] Fix width of first table columns in the docs

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#572]
The width of the first column of some tables in the docs is too large, for some reason that I don't understand.

By default, Sphinx seems to set column widths based on the relative sizes of the actual columns in `.rst` format in the source, which is weird. But, that doesn't explain why the first columns are too big in the screenshots below.

The pattern below was successfully used in various places in the docs to override the default column sizing described above. However, that's not having any effect on the tables in the screenshots below, either...

Perhaps some CSS is getting in the way somewhere? I need help on this one.

```
.. table::
    :widths: 20 20 40 20
    
    <rst-table-contents>
```

Some borked tables in the docs:

<img width="1271" alt="Screen Shot 2020-10-01 at 11 20 57 AM" src="https://user-images.githubusercontent.com/25985824/94830917-11b8a700-03da-11eb-9936-624fc1c40827.png">

<img width="1273" alt="Screen Shot 2020-10-01 at 11 25 20 AM" src="https://user-images.githubusercontent.com/25985824/94830926-14b39780-03da-11eb-8454-a53d3d6afdbb.png">

<img width="1274" alt="Screen Shot 2020-10-01 at 11 24 10 AM" src="https://user-images.githubusercontent.com/25985824/94830933-154c2e00-03da-11eb-8719-b66d97e429de.png">

**Comment by lethosor** [comment]
This appears to be due to a rule introduced in c9bb15f83 making the first cells of *all* tables 70% wide. This is likely treated as a ratio instead of an absolute measurement - e.g. the column widths in the first table ("media type") above have a 70:30:40 ratio.
For reference, without that rule, here's what all of the autodoc-generated pages look like: 
![image](https://user-images.githubusercontent.com/3719547/94933601-9b2eae80-0498-11eb-8e09-3c9a441f4260.png)

These are given 10% and 90% column widths for some reason - maybe it's possible to change on the backend instead.

**Comment by brimoor** [comment]
Hmm, nice find. I wonder why the 70% rule was introduced. That PR was from when Tyler was working on tweaking how the API docs look. Perhaps he was adjusting how these tables are rendered https://voxel51.com/docs/fiftyone/api/fiftyone.core.dataset.html but didn't realize other changes that were happening.

**Comment by lethosor** [comment]
It was introduced to stop some tables from rendering like in my screenshot above. It seems that the `10%, 90%` widths of those tables are hardcoded in the `sphinx.ext.autosummary` package, but they ordinarily look fine - the [autosummary documentation](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) has a table with these rules, for instance:
![image](https://user-images.githubusercontent.com/3719547/94939856-b8677b00-04a0-11eb-8b1d-0d42bd42f4c0.png)

I've tracked down one rule in pytorch's `theme.css` that is causing part of the issue, but there is at least one other that I haven't found yet.
