### ISSUE TITLE
[FR] Add support for importing/exporting video datasets in FiftyOneDataset format

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#580]
When you iterate over frames of a video, you should get the frame objects instead of the indices to the frames:
```python
import fiftyone as fo

dataset, session = fo.quickstart(video=True)

for frame in dataset.first().frames:
    print(frame)
```
```
1, 
2, 
3, 
4, ....
```

Additionally, this may be causing some issues with exporting videos. Currently, when I tried to export the quickstart video dataset as a `fo.types.FiftyOneDataset`, the only labels were frame ids. This issue can be seen when calling `sample.to_dict()`:
```python
import fiftyone as fo

dataset, session = fo.quickstart(video=True)

dataset.first().to_dict()
```
```
{'media_type': 'video',                                                                              
 'filepath': '/home/erich/fiftyone/quickstart-video/data/Ulcb3AjxM5g_053-1.mp4',                     
 'tags': [],                                                                                         
 'metadata': None,                                                                                   
 'frames': {'1': {'$oid': '5f7ce349e3b06648bf0d1d0a'},                                               
  '2': {'$oid': '5f7ce349e3b06648bf0d1d0b'},                                                         
  '3': {'$oid': '5f7ce349e3b06648bf0d1d0c'},                                                         
  '4': {'$oid': '5f7ce349e3b06648bf0d1d0d'},                                                         
  '5': {'$oid': '5f7ce349e3b06648bf0d1d0e'},                                                         
  '6': {'$oid': '5f7ce349e3b06648bf0d1d0f'},                                                         
  '7': {'$oid': '5f7ce349e3b06648bf0d1d10'},                                                         
  '8': {'$oid': '5f7ce349e3b06648bf0d1d11'},                                                         
  '9': {'$oid': '5f7ce349e3b06648bf0d1d12'},                                                         
  '10': {'$oid': '5f7ce349e3b06648bf0d1d13'},        
...
```

**Comment by brimoor** [comment]
`sample.frames` behaves like a dict. You can use `keys()` `values()` and `items()` to iterate over frame numbers, frames, or both, respectively

**Comment by brimoor** [comment]
```py
import fiftyone as fo

dataset, session = fo.quickstart(video=True)

for frame_number, frame in dataset.first().frames.items():
    print(frame_number)
    print(frame)
```

**Comment by brimoor** [comment]
The second comment is a known issue- we haven't gotten to supporting video datasets when exporting in `FiftyOneDataset` format.

FYI- the frame labels are stored in a separate DB collection. What you're seeing there are the IDs that can be used to lookup the frame labels in the other collection. We'll need to take that into account when importing/exporting in `FiftyOneDataset format`. We'll probably introduce a `frames/` subdirectory that contains the per-frame labels for the samples.

I will try to squeeze that into the release tomorrow, depending on how much coffee I have tonight ;-)

**Comment by ehofesmann** [comment]
> `sample.frames` behaves like a dict. You can use `keys()` `values()` and `items()` to iterate over frame numbers, frames, or both, respectively

Ah, duh, that makes sense.
