### ISSUE TITLE
[FR] Allow toggling fields to affect z-order in Player51

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#587]
Player51 currently decides its own z order when rendering a bunch of labels.

A common problem I encounter when performing visual error analysis is wishing that I could see ground truth detections on top of predictions, or vice versa. Or, in the screenshot below, one would prefer to see the polylines below the object detections.

My proposal is to make FiftyOne respect the order in which fields are toggled- fields that have been toggled on more recently are rendered on top. And therefore by toggling in different orders I can see whatever I want on top.

This would be in addition to the existing "on top when hovering" capability, which is nice but not sufficient to visually inspect multiple detections at a time, for example.

<img width="1541" alt="Screen Shot 2020-10-07 at 3 08 57 PM" src="https://user-images.githubusercontent.com/25985824/95377286-5a77d080-08b0-11eb-9809-d44da1b9aa90.png">

**Comment by benjaminpkane** [comment]
Resolved in 0.8.0 by #838
