### ISSUE TITLE
[BUG] Fix size of ragged videos in App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#605]
The tenth video in `fiftyone quickstart --video` is a bit too wide

<img width="1347" alt="Screen Shot 2020-10-14 at 11 45 47 AM" src="https://user-images.githubusercontent.com/25985824/96013160-f3f43480-0e12-11eb-9279-78457e829d90.png">

**Comment by lethosor** [comment]
I think this is intentional - incomplete rows default to a fixed height as of #382.

**Comment by brimoor** [comment]
Can we intentionally change it? 😄 In the context of a >1 video grid, we effectively have a new default aspect ratio

**Comment by lethosor** [comment]
Hm, I'm also seeing it on develop (6bd335582e8ec47bfa63f068a593a54319bca234) which doesn't have the margins. @brimoor can you include the branch/commit you were seeing this on?

![image](https://user-images.githubusercontent.com/3719547/96017584-294f5100-0e18-11eb-8315-c4502316480b.png)

**Comment by brimoor** [comment]
My branch isn't important. I've always seen this since video was launched and am finally getting around to make an issue for it

**Comment by lethosor** [comment]
It's generally helpful information when reporting an issue - that's why we ask for version information in the issue template. Evidently it wasn't just introduced when adding the margins that are in your screenshot.
Good to know that it's longstanding, though.
