### ISSUE TITLE
[BUG] Field vs expression issue with SortBy view stage

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#634]
If a `SortBy` stage contains an expression, its display text should show `{...}`, and clicking into the field should open the JSON editor.

(Just like what happens if you click into the filter expression in the `FilterDetections` stage in the App in the example below)

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("coco-2017", split="validation")

person_view = (
    dataset
    .filter_detections("ground_truth", F("label") == "person")
    .sort_by(F("ground_truth.detections").length(), reverse=True)
)

# Show the view in the App
session = fo.launch_app(view=person_view)
```

<img width="1188" alt="Screen Shot 2020-10-26 at 11 40 36 AM" src="https://user-images.githubusercontent.com/25985824/97194129-2c373380-1780-11eb-98a4-d16eb092d3c0.png">

**Comment by lethosor** [comment]
I think this is the same as #639 - in the case you gave, I see `{...}` in a newly-created stage until I click in and out of it.

**Comment by brimoor** [comment]
Close but probably not quite the same because `SortBy` has some additional logic for handling "field" vs "expression" type values differently
