### ISSUE TITLE
[BUG] Label stats don't update when views are created on remote sessions

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#673]
Environment: prod v0.6.4

I load the quickstart in a remote session and open a view with one random sample:

```py
import fiftyone as fo

dataset, session = fo.quickstart(remote=True)
session.view = dataset.take(1)
```

However, the App incorrectly shows label stats and sample counts for the entire dataset, not the view:

<img width="1136" alt="Screen Shot 2020-11-04 at 10 34 38 PM" src="https://user-images.githubusercontent.com/25985824/98194872-5d390600-1eee-11eb-92c9-ab50c89d97ee.png">

**Comment by benjaminpkane** [comment]
This is resolved by #669
