### ISSUE TITLE
[BUG] Memory issues with large video datasets

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#675]
When working on the deepfake blog post I loaded a dataset of around 400 videos each a few seconds long. 

Everything ran smoothly at first but after applying a few filters and loading a couple of different views in the app, the memory usage of FiftyOne kept increasing up to the limit of my laptop. It was using about 13 of my 16 gb of RAM. 

I'm assuming video examples in the grid view are being loaded into memory and never removed. Whatever it is, it made it really difficult to work with the data because I had to restart FiftyOne every few minutes to clear my memory.

**Comment by benjaminpkane** [comment]
I can certainly reproduce this. Beginning my investigations...

**Comment by benjaminpkane** [comment]
Resolved in part by #681, specifically https://github.com/voxel51/fiftyone/commit/16f5887458ae855aa664f1533e9170394f3591f0.

Updating the view or dataset will now "clear out" the memory usage. Though, I think this issue should not be closed until the grid is virtualized and it is not within the users control to cause memory issues (by continuing to scroll).

**Comment by diegochine** [comment]
Any news about this? I'm having a similar problem with a large image dataset. 
The app is running on a remote server, images are pretty big (3k resolution on average) and there are about 1500 samples. The app works ok at first, but after applying even just one filter and scrolling a bit the browser the memory usage of increases up to the limit (16 GB in this case as well), giving an out of memory error.

**Comment by benjaminpkane** [comment]
Hi @diegochine. I want resolve this in the next week or two.

**Comment by benjaminpkane** [comment]
This was resolved by Flashlight. See #1459 for issues with large media (dimensions).
