### ISSUE TITLE
[FR] Add color by label support for classifications, and update checkbox look-and-feel

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#689]
```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("bdd100k", split="validation")

session = fo.launch_app(dataset)
```

When `Color by label` is active, colors in the App no longer correspond to field colors. Therefore, I'd say that the checkboxes should all be a neutral color (say primary orange? or maybe gray --- whatever is chosen, the same color would be used for the `Color by label` checkbox itself, which is currently orange), since they no longer correspond to the colors in the media player.

<img width="1348" alt="Screen Shot 2020-11-13 at 1 46 12 PM" src="https://user-images.githubusercontent.com/25985824/99109615-18c8fc80-25b7-11eb-88c5-9e9e72dcd9a5.png">

**Comment by benjaminpkane** [comment]
I'm not seeing the polyline issue (on `release-notes` with player51 updated).

Will address the final point in `release-notes`.

**Comment by benjaminpkane** [comment]
Classification(s) colors are still useful. Keep their colors?

**Comment by brimoor** [comment]
Hmm I'm not sure what branch I was using when I didn't see per-polyline-label colors, but I agree that I do see them now. Apologies for the red herring.

I was just about to comment on classifications as well. I'd say that "per-label coloring" should apply to classifications as well. For example, with `Color by label` on, then, if you have a single `Classification` field with `cat` and `dog` values, they'd appear as different colors. You generally wouldn't choose this visualization strategy when you're showing multiple classification fields simultaneously, but it is useful when comparing labels within a single field.

**Comment by benjaminpkane** [comment]
Resolved
