### ISSUE TITLE
[FR] Support for TIFF images in the App

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#703]
Chromium does not support .tiff images out of the box. It would be possible to support TIFF with a javascript library.

https://conceptclarity.ca/display-tiff-files-web/#:~:text=TIFF%20files%20are%20often%20much,Safari%20and%20Microsoft%20Edge%20do.

**Comment by brimoor** [comment]
A few more resources:

ootb browser support for images:
https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

For when arbitrary browsers are being used: an example TIFF plugin for Chrome:
https://chrome.google.com/webstore/detail/tiff-viewer/fciggfkkblggmebjbekbebbcffeacknj?hl=en

**Comment by brimoor** [comment]
Great new! As long as you have `fiftyone>=0.7` installed and are working with the App in your web browser or a notebook (as opposed to the desktop version of the App, which was the only option prior to v0.7), then you should be able to work with TIFF images with no problem.

Some browsers like Safari natively support TIFF images, but (strangely) other browsers like Chrome don't support it natively. However, you can typically install a simple browser extension to support viewing TIFF images. For example, I've installed [this Chrome extension](https://chrome.google.com/webstore/detail/tiff-viewer/fciggfkkblggmebjbekbebbcffeacknj?hl=en
) and can now view TIFF images in Chrome.

Here's some code that you can test with:

```shell
# Make sure you have fiftyone>=0.7 installed
pip install --upgrade fiftyone
```

```py
import fiftyone as fo

dataset = fo.Dataset()
sample = fo.Sample(filepath="/path/to/image.tiff")
dataset.add_sample(sample)
session = fo.launch_app(dataset)
```

**Comment by brimoor** [comment]
Closing per the last comment above. We do not have plans to support TIFF images in the desktop App at this time.
