### ISSUE TITLE
[BUG] App UI errors after using label selection filter

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#705]
After using the label search UI to select a label to view, some App features stop working.

For example, in the state below, the checkbox to toggle the label field on and off no longer works after selecting the `person` label via the UI:

<img width="1392" alt="Screen Shot 2020-12-04 at 1 17 57 PM" src="https://user-images.githubusercontent.com/25985824/101199669-38da6180-3633-11eb-9b4f-8ab8d60ccf95.png">

**Comment by benjaminpkane** [comment]
Resolved in 00ce78c8265ce3b810378b828b29ca44ad1cc4e4 on `colab`

Essentially, there was a recursion bug which froze up the window. I will say more when I have the PR up.
