### ISSUE TITLE
[FR] Flag to avoid copying data when exporting Dataset labels

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#707]
I updated labels for a dataset in FiftyOne and want to use them in my own scripts to train a new model. The images are the same and I don't want to have to copy 118K images that I can just link back to them using the new labels. 

It's easy enough to take an `Exporter` and remove the step where files are copies but it would be nice to have a flag for copying data or just exporting labels. This would also be nice to have in the `fiftyone convert` command.

**Comment by brimoor** [comment]
yep makes sense, I like it.
