### ISSUE TITLE
[FR] Render screenshot in notebook Apps that are deactivated

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#715]
As of v0.7.0, `session.show()` can be used to open App instances in notebook cells. Currently, if multiple `session.show()` commands are run, only the most recently run instance will be a live App connected to the `session`, while the other instances will be deactivated as shown in the screenshots below.

This behavior works fine for interactive use, but for "publishing" notebooks, it would be amazing if deactivated Apps would have their contents replaced with a screenshot of the current window state before becoming deactivated. There could still be a spinning icon in the top right corner (say), that allows the App instance to be reactivated. Having screenshots there would enable the user to "freeze" certain interesting findings in the notebook, making its contents digestible without necessarily running the notebook cells yourself. This would make the process of publishing recipes/tutorials very easy, for example.

**Active notebook output**
<img width="1105" alt="Screen Shot 2020-12-17 at 5 15 17 PM" src="https://user-images.githubusercontent.com/25985824/102573472-85568000-40bc-11eb-908b-70e72b8e6ec1.png">

**Deactivated notebook output**
<img width="1112" alt="Screen Shot 2020-12-17 at 5 15 06 PM" src="https://user-images.githubusercontent.com/25985824/102573497-91dad880-40bc-11eb-91a5-43677dbe0b65.png">

**Comment by benjaminpkane** [comment]
Resolved by #730
