### ISSUE TITLE
[BUG] Sample stats don't load when creating `Take()` stages from the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#719]
On `develop`, I observe that creating a `Take(10)` stage from the App loads the view (10 random samples), but the sample stats in the Fields Sidebar are stuck in spinning-icon state. However, if I then do `session.view = session.view`, then everything loads appropriately.

So it seems randomized views can be loaded via `session.view` but not created via the App.

<img width="1277" alt="Screen Shot 2020-12-21 at 9 50 07 AM" src="https://user-images.githubusercontent.com/25985824/102789302-ee1a5280-4371-11eb-958b-7e9baf3d601b.png">

**Comment by benjaminpkane** [comment]
Resolved by #710
