### ISSUE TITLE
[BUG] White box appearing at bottom of App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#755]
On https://github.com/voxel51/fiftyone/pull/747, there is a small white box appearing at the bottom left of the App. It is present in both the browser and desktop versions of the App.

<img width="1278" alt="Screen Shot 2021-01-08 at 2 02 41 PM" src="https://user-images.githubusercontent.com/25985824/104054350-ed2f5080-51ba-11eb-9049-bc630f3c68bc.png">

**Comment by brimoor** [comment]
Hmm, I don't see it using `fiftyone==0.7.1rc66` and `fiftyone-desktop==0.8.0rc0` though.

**Comment by benjaminpkane** [comment]
Working on it. This arises when long field names are in the dataset. Likely affects `fiftyone==0.7.1rc66` though I haven't checked yet.

**Comment by benjaminpkane** [comment]
Resolved by #747
