### ISSUE TITLE
[BUG] session.show() does not preserve view state

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#779]
In a Jupyter/Colab notebook, running the following two cells will result in different samples in each view, whereas one would like to see the exact same samples.

The issue is that the `Shuffle()` stage is being recreated, which generates a new random seed internally.

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("coco-2017", split="validation", max_samples=100)
view = dataset.shuffle().limit(10)

session = fo.launch_app(view=view)
```

```
session.show()
```

**Comment by brimoor** [comment]
A related observation is that label colors change when a new App is launched.

I did intentionally say "preserve **view state** in the issue title, as opposed to preserve **app state**. Label colors would fall under the latter, as would remembering scrolling state, window expansion, etc. which is too much to do right now.

With this said, it is a bit strange to have label colors change every time `session.show()` is issued, since the user may have spent some time refreshing colors to get ones that they like... Perhaps label colors should be pulled into the backend `Session` object.

**Comment by brimoor** [comment]
Clarified that this is **Colab** specifically; the observed behavior does not happen in Jupyter notebooks.

**Comment by benjaminpkane** [comment]
Can you still produe this issue? I cannot.
![Screenshot from 2021-01-21 13-13-55](https://user-images.githubusercontent.com/19821840/105407140-90845a80-5bea-11eb-8336-5ee482e4e7d7.png)

**Comment by brimoor** [comment]
I just tried with `develop` in a Jupyter notebook and didn't see it 👍 .

Any reason why this might be a colab-specific issue? I tried to do a source install in a colab notebook and it failed for some reason so I wasn't able to check. If you think colab should be fine, feel free to close this.

**Comment by benjaminpkane** [comment]
No, I don't think so. I'm not seeing the issue in Colab either.
