### ISSUE TITLE
[FR] Allow App label colors to be set via Session object

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#781]
Continuing from https://github.com/voxel51/fiftyone/issues/779#issuecomment-760395980, it would be convenient as a user who is particular about colors (e.g., colorblind), to be able to manually set label colors used in the App via their `session` object.

A related comment: I've never particularly liked the `Refresh field colors` option because it causes some people (asking for a... friend) to endlessly click refresh and get frustrated as to why they are having to waste time doing that. This latter comment has two distinct aspects:
- Can better colors be chosen by default? (some unfinished work on this exists in https://github.com/voxel51/fiftyone/pull/494)
- Let the user customize via session object (this issue)

**Comment by brimoor** [comment]
As of FiftyOne v0.7.2, the color pool from which colors are chosen can be configured via `session.config.color_pool`.

An open question is whether we should allow control of individual field colors as well rather than just the color pool. Leaving this issue open in a `needs-discussion` state until we make a decision on the latter point.

**Comment by joihn** [comment]
Any workaround to achieve this feature ?

**Comment by brimoor** [comment]
The `color_pool` defines the pool of colors from which field colors are chosen. So the closest workaround is to set that to the list of acceptable colors for you:

```py
import fiftyone as fo
import fiftyone.zoo as foz

fo.app_config.color_pool = ["#ff0000", "#00ff00"]

dataset = foz.load_zoo_dataset("quickstart")

session = fo.launch_app(dataset)

# You can also modify it dynamically like this
session.config.color_pool = ["#ff0000", "#00ff00"]
session.refresh()
```

As a matter of implementation, I believe field colors are chosen sequentially in the order that they appear in `print(dataset)`. So in this case, `ground_truth` gets `"ff0000"` and `predictions` gets `#00ff00`. This may change though.

As the screenshot below shows, if you have more fields, you'll get duplicate colors:

<img width="1275" alt="Screen Shot 2022-01-18 at 12 28 19 PM" src="https://user-images.githubusercontent.com/25985824/149987951-b78fda58-d8b7-4245-8957-79b69d5f927f.png">

**Comment by brimoor** [comment]
One idea to allow these colors to be customized would be to add an optional `field_colors` setting that contains a `field -> color` mapping dict that takes precedence over `color_pool` when `field` is int it.

We could also add a `value_colors` or `label_colors` setting that provides a similar mapping dict when rendering colors in the App's "Color by value" mode.

**Comment by joihn** [comment]
`session.config.color_pool = ["#ff0000", "#00ff00"]`
This workaround is working, thanks for the quick and efficient answer :)

**Comment by benjaminpkane** [comment]
Resolved with [Color Schemes](https://docs.voxel51.com/user_guide/app.html#color-schemes)
