### ISSUE TITLE
[FR] Add a utils library for generating plots of-interest for native FiftyOne data types

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#784]
From https://github.com/voxel51/fiftyone/pull/777#issuecomment-760443580:

It would be nice to expose a utils module that contains methods for things like my `plot_hist()` code in the description of the PR above that can be used to generate plots of our `Aggregation`s.

Similarly, we could provide utils for generating confusion matrix plots, PR curves, and other items related to evaluation. All with native support for FiftyOne data types as input.

Now that FiftyOne works natively in notebooks, leveraging matplotlib for these kind of outputs is at 50% towards native in-App plots (same information, minus the interactively), while also being significantly easier to implement.

**Comment by benjaminpkane** [comment]
I think we'll get the best flexibility out of plotting if we add the option to (or make the default) output to `Aggregation` results Pandas Dataframes.

**Comment by brimoor** [comment]
This was largely addressed in v0.7.3, where a convention was established that things like evaluation results come in an `EvaluationResults` class, which provides methods for generating various supported plots, etc.

Note that `AggregationResult` was removed in favor of returning the raw aggregation results, which means that FiftyOne is shirking responsibility for things like `plot_hist()` (the user has the raw data, so they can do it themselves).
