### ISSUE TITLE
[BUG] Closing the App does not exit the CLI

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#790]
When running something like 
```
fiftyone quickstart
```
The app is launched in a browser window, but when it's closed, the command line is not returned.

Similarly, `fiftyone app launch dataset` even states 
```
To exit, close the App or press ctrl + c
```

but does not exit when closing the App. Not sure if this is just a new bug from switching to browser support.

**Comment by brimoor** [comment]
Not sure that we want to kill the session when a browser-tab-version of the App is closed (if that's even possible).

So per the second comment, we should probably hide the `To exit, close the App or press ctrl + c` text in browser mode since that behavior would only be true in desktop App mode.

**Comment by brimoor** [comment]
I merged https://github.com/voxel51/fiftyone/pull/791 and marked this as `needs-discussion` in case @ehofesmann wants to leave any comments here

**Comment by ehofesmann** [comment]
I think it would be nice to exit when closing the app from the browser, but if that's difficult then the change in #791 is good. 

There are also a lot of errors that get printed exiting with ctrl+c that should be suppressed if possible. 

This mainly came up when talking to Michael as he was concerned that he wasn't closing it properly.
