### ISSUE TITLE
[BUG] Cannot read property 'slice' of null when launching App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#795]
On `develop`, I run `fiftyone app launch` and then select any dataset that I've created from the dropdown. This leads to the following App error:

<img width="1275" alt="Screen Shot 2021-01-19 at 12 12 14 AM" src="https://user-images.githubusercontent.com/25985824/104990856-79c3e500-59eb-11eb-8bd5-634b19ab9d65.png">

**Comment by benjaminpkane** [comment]
I am unable to reproduce this exact on `develop` at the moment, but I will say I rushed my approval of #777. It introduced handful of bugs in `fiftyone.core.state` and `fiftyone.server.main`, and needed some App changes, as well. I have been doing damage control, and cleaning things up in general in #778.

I had seen this error while working on #778. Perhaps you test on #778?

**Comment by brimoor** [comment]
Resolved by https://github.com/voxel51/fiftyone/pull/778.
