### ISSUE TITLE
[FR] Enhance usability of numeric distribution graphs

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#798]
I have some reactions after using the current state of numeric distribution graphs in the App (see screenshots below for a typical use case).

Note that I'm marking this as `needs-discussion` to avoid wasting too much effort in the current graphing library if we will soon be moving away from it. But, I'm creating this issue nonetheless to document my thoughts on making the graphs as usable as possible.

Enhancements for numeric graphs
- Clarify in the graph that "other" bucket is exclusively `None`-valued fields. The actual aggregation uses `other` as a catch-all for any data outside of the specified bin edges, but we're in control of the bin edges and know that anything outside must be `None` 
- Hide the `other` bin when its count is zero

Integer-field-specific enhancements:
- Suppose the range of the field is `[0, n]`. For reasonably small values of `n`, say `n <= DEFAULT_NUM_BINS`, it would be desirable for the bins to be `[-0.5, 0.5, 1.5, ..., n + 0.5]` with tick labels `0, 1, ..., n` rather than the strange floating point values observed below
- When the range `[0, n]` is too large, I would revert to floating point-type style where where are a fixed number of equal-width bins and a small number of tick labels like ~5 or so

Example graph for an int field defined on 15 out of many samples in a dataset
("other" means `None`-valued, but this is not readily apparent to users from the current display):

<img width="1272" alt="Screen Shot 2021-01-19 at 2 48 15 PM" src="https://user-images.githubusercontent.com/25985824/105086532-20999700-5a67-11eb-8298-4702a2d5f11b.png">

The same graph after applying an `Exists(field, True)` view stage. The tick labels are undesirable because this is an int-valued field with a small range (`[0, 8]` in this case):

<img width="1274" alt="Screen Shot 2021-01-19 at 2 48 49 PM" src="https://user-images.githubusercontent.com/25985824/105086331-e4663680-5a66-11eb-8974-1516f3bf5c29.png">

**Comment by benjaminpkane** [comment]
Addressing all comments shouldn't take long. I can resolve tomorrow.
