### ISSUE TITLE
[FR] Launch the App in a remote Jupyter notebook

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#805]
I want to process a model in a jupyter notebook on a remote machine so I use:
```
jupyter notebook --no-browser --port=XXXX
```
and connect to it on my local machine through `ssh`.

Trying to launch the App inside of this notebook results in the following:
![image](https://user-images.githubusercontent.com/21222883/105418003-72c6ed80-5c0a-11eb-8238-15ccfcec6d4a.png)

**Comment by benjaminpkane** [comment]
This requires some manual effort at the moment. You have to setup port forwarding for `fiftyone`, as well. And the local port must match the remote port.

This should be simplified, of course.

**Comment by ehofesmann** [comment]
Oh that's awesome! I figured it might be difficult to get it to work at all, but it's good to know that it's already possible.

**Comment by brimoor** [comment]
Sounds like a good FAQ solution. No need to engineer anything
