### ISSUE TITLE
[FR] Consider removing `AggregationResult` classes

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#811]
As I was working on https://github.com/voxel51/fiftyone/pull/809, I wondered if the `AggregationResult` class should be deprecated in favor of just returning the aggregation result itself. If there are multiple fields, as in the (only, currently) case of `HistogramValues`, they would be returned as a dict:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

# current

avg = dataset.sum("uniqueness").sum / view.count("uniqueness").count

result = dataset.histogram_values("uniqueness", bins=50, range=(0, 1))
result.edges
result.counts

# proposed

avg = dataset.sum("uniqueness") / view.count("uniqueness")

result = dataset.histogram_values("uniqueness", bins=50, range=(0, 1))
result["edges"]
result["counts"]
```

The primary function of the `AggregationResult` is to give the results a `name` field, which I'm guessing came about because aggregations were originally *always* computed via `results = dataset.aggregate([agg1, agg2, agg3, ...])`. But, even then, the order of `results` is preserved between input and output, so it seems that the user should always know what aggregations they ran.

For Python users of aggregations, it seems that the more concise syntax may be appreciated.

**Comment by benjaminpkane** [comment]
This is probably best. `AggregationResult`s were part of the initial Aggregations implementation to encapsulate the needs of the App server, i.e. identifying a result by `(type, field_path)`. This can be handled without `AggregationResult`s, though.
