### ISSUE TITLE
[BUG] Labelbox import is creating incorrect filepath for samples when downloading the media

### ISSUE THREAD

**Issue by luke-iqt** [voxel51/fiftyone#825]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.15.7
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone v0.7.1.4, Voxel51, Inc.
-   **Python version**: 3.8.3

### Commands to reproduce

Note: Here is a sample row from my labelbox export json file. If you save this to a .json file and then use it for the import, it should reproduce the error:
```json
[
{"ID":"ckjzt1cct00013e5m0c72wqh9","DataRow ID":"ckjzsvs55oavs0re7guxvceeg","Labeled Data":"https://storage.labelbox.com/ck80sulie7xig0874x0d7e4u6%2Ffc97f777-db33-8528-6474-2214f8fdeca6-A5E900_2021-01-10-19-45-46.jpg?Expires=1613052183272&KeyName=labelbox-assets-key-1&Signature=r08-aYrZGf9rMDGa1uCSG_-mYvw","Label":{"objects":[],"classifications":[{"featureId":"ckjzt17wz0xlo0yan65x8htwi","schemaId":"ckjzssie90ukv0y9c0k0jg4vq","title":"ICAO24","value":"icao24","answer":"a5e900"},{"featureId":"ckjzt17wz0xlp0yan6jho6wto","schemaId":"ckjzssie80ukr0y9c106gcjdo","title":"Operator","value":"operator","answer":"none"},{"featureId":"ckjzt17wz0xlq0yand5nc97zr","schemaId":"ckjzssie80ukt0y9cdyw04gjf","title":"Manufacturer","value":"manufacturer","answer":"Dassault Aviation"},{"featureId":"ckjzt17wz0xlr0yanekon843s","schemaId":"ckjzssie80ukp0y9c6tm47ske","title":"Model","value":"model","answer":"FALCON 2000EX"}]},"Created By":"lberndt@iqt.org","Project Name":"skyscan","Created At":"2021-01-16T14:27:14.000Z","Updated At":"2021-01-16T14:27:20.000Z","Seconds to Label":10.565999999999999,"External ID":"A5E900_2021-01-10-19-45-46","Agreement":-1,"Benchmark Agreement":-1,"Benchmark ID":null,"Dataset Name":"planes","Reviews":[],"View Label":"https://editor.labelbox.com?project=ckjzssg5qo80507369why6cev&label=ckjzt1cct00013e5m0c72wqh9"},
]
```

```python
# Imports and configuration 
import fiftyone as fo

labelboxExportJson =  "./export-2021-01-28T14-03-02.769Z.json" # Download the exported JSON and update this
mediaDir = "./media"

# Do the groundwork for importing, setup the dataset
import fiftyone.utils.labelbox as foul
from uuid import uuid4
labelbox_id_field = "labelbox_id"

# expect an error here if the dataset already exists
dataset = fo.Dataset(name="skyscan")
dataset.persistent = True

# This seems dumb, but it looks like you have to create a dummy record so you can have an instance with that field name
sample = fo.Sample(filepath="./sample.jpg")
dataset.add_samples([sample])
for sample in dataset:
    print(sample)
    sample[labelbox_id_field] = str(uuid4())
    sample.save()

# Imports the Data from Labelbox into a Voxel51 Dataset
foul.import_from_labelbox(dataset, labelboxExportJson, download_dir=mediaDir, labelbox_id_field=labelbox_id_field)
```

### Describe the problem

I uploaded the media I was labeling in Labelbox directly to them using the Python SDK. I think this puts it in a Google Cloud bucket. The URL that gets stored in the "Labeled Data" key has a bunch of URI parameters hanging off of it. I have the voxel51 labelbox_import function set to download the media locally. When the importer does this, it simply saves the file with the filename from the URI. However, it does not properly parse the URI to remove the parameters. The result is that you end up with a messy filename, without an extension. This mess up the mime_type detection that is does because it doesn't see a ".jpeg" at the end. As a result, the UI doesn't work because it doesn't think they are images because the mime type guessing fails.

I think if you did some better processing of the URL here to extract the filename here, it should fix things:
https://github.com/voxel51/fiftyone/blob/8fa0e03aef1aadbe83d6bd166c6ec2991a7ec1e2/fiftyone/utils/labelbox.py#L137

### What areas of FiftyOne does this bug affect?

-   [ X] `App`: FiftyOne application issue
-   [ X] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ X] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by benjaminpkane** [comment]
Thanks for descriptive bug report! And apologies for the issue itself. I was able to reproduce it. We'll be looking into things in more detail over the next day or two at most, but I agree with your initial suggestion.

`get_output_path` will need to be generalized. I want to make sure we consider files that may change when supplied with different URL parameters, e.g. height and width, rather than just stripping the parameters. 

https://github.com/voxel51/fiftyone/blob/8fa0e03aef1aadbe83d6bd166c6ec2991a7ec1e2/fiftyone/core/utils.py#L497



Also, below is a modified version of the snippet provided. I thought I'd share it to help with the field problem you encountered. `dataset.add_sample_field()` will fix the call `import_from_labelbox()`. We could probably improve `improve_from_labelbox()` so it handles the issue, thought.
```py
labelboxExportJson =  "./labelbox.json" 
mediaDir = "./media" 

import fiftyone.utils.labelbox as foul 
labelbox_id_field = "labelbox_id" 

dataset = fo.Dataset(name="skyscan") 
dataset.add_sample_field(labelbox_id_field, fo.StringField) 
foul.import_from_labelbox(dataset, labelboxExportJson, download_dir=mediaDir, labelbox_id_field=labelbox_id_field)  
```

**Comment by benjaminpkane** [comment]
@luke-iqt you should be all set now. I snuck in a quick fix in today's release. Certainly let us now if you continue to have any issues. Cheers!

```
pip install --upgrade fiftyone
```
![Screenshot from 2021-01-28 15-22-52](https://user-images.githubusercontent.com/19821840/106206105-c7271b80-617c-11eb-8ade-bd7a65f0de92.png)

**Comment by luke-iqt** [comment]
Wow!! Thank you so much for the quick work. And thanks for the `dataset.add_sample_field()` that is a lot more elegant. I just stole some code from the unit-test.
