### ISSUE TITLE
Add simple API to run migrations

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#826]
_Originally posted by @benjaminpkane in https://github.com/voxel51/fiftyone/issues/824#issuecomment-769216125_:

> The only problem is that the down migration will not run for users.
> 
> The only way to get down migrations to run for users is to introduce logic in the migrations runner that downloads "future" revisions from the web at runtime. A `v0_7_2.py` revision will never exist in a `0.7.1` install...

I haven't thought deeply about this, but what about introducing an API that lets the user run a quick command to upgrade or downgrade their DB to any desired package version. Then they install the appropriate version of the tool:

```shell
# I'd like to downgrade
fiftyone --version
# 0.7.2

# Let me prep my DB for this
fiftyone migrate --version 0.7.0

# And now I can downgrade
pip install fiftyone==0.7.0
```

**Comment by benjaminpkane** [comment]
This is manageable. Shouldn't take more than a few hours to stand something up.
