### ISSUE TITLE
[BUG] Can't visualize images on D:\\ drive in Windows

### ISSUE THREAD

**Issue by sourabhyadav** [voxel51/fiftyone#839]
### Instructions
Not getting image visualization on Windows localhost.

### System information

-   **OS Platform and Distribution**: Windows 10
-   **FiftyOne installed from (pip or source)**: pip3 install fiftyone
-   **FiftyOne version (run `fiftyone --version`)**: Default
-   **Python version**: python 3.9

### Commands to reproduce
I tried to create a session after adding dataset
```
dataset = fo.Dataset.from_images_dir("D:\\Datacluster_algo\\Duplicate_Similarity_image_dataset\\5PK3KvYIeQgVza6P1hkL", recursive=True, name="DC-images")
print(dataset) # this works fine as I can see the same number of images loaded with correct paths
session = fo.launch_app(dataset)
```

### Describe the problem

On http://localhost:5151/ I do not get thumbnails of the images not even on double-clicking it.

![Capture](https://user-images.githubusercontent.com/5621042/106779185-c145a480-666c-11eb-8340-f8922bd3e409.PNG)

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [x] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by sourabhyadav** [comment]
![Capture](https://user-images.githubusercontent.com/5621042/106780912-7a58ae80-666e-11eb-8ff9-c5dc365f4054.PNG)

I can see that the **filepath is not correct** on Windows. It should have started with ```D"\\Datacluster....```   

However, on the command line it seems correct:  
```
>>> dataset.first()
<Sample: {
    'id': '601ace484a853f57ac54262c',
    'media_type': 'image',
    'filepath': 'D:\\Datacluster_algo\\Duplicate_Similarity_image_dataset\\5PK3KvYIeQgVza6P1hkL\\1589964287376.jpg',
    'tags': BaseList([]),
    'metadata': None,
```  

I hope this might give a clue to find the bug.

**Comment by benjaminpkane** [comment]
Hi @sourabhyadav. Apologies for the trouble. For now, visualization should work if the images are on your `C:` drive.

I'll have to write a bug fix that supports any drive on Windows. I'll respond here when a fix is out. Monday or Tuesday of next week at latest. Thanks for making the issue!

**Comment by benjaminpkane** [comment]
@sourabhyadav just pinging you to let you should now be able to see your images. We still need to get to #840, bear with us. Thanks!

```
pip install -U fiftyone
```
