### ISSUE TITLE
[BUG] Classification label is incorrectly filtered in expanded sample mode

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#843]
I have a dataset with an `eval` field with `Classification` instances with labels `{tp, fp, fn, tn}`. When I view the sample below in expanded sample mode, I see (very small in upper left corner of media viewer) that `eval: fn`, but when I apply the `fn` only label filter on the right, the label disappears from the media viewer even though it does match my filter.

This also happens for the other fields of this dataset too, so I don't think it is label-specific.

<img width="1151" alt="Screen Shot 2021-02-03 at 9 30 36 PM" src="https://user-images.githubusercontent.com/25985824/106836721-b1779180-6667-11eb-949a-72c98fafaab3.png">

<img width="1152" alt="Screen Shot 2021-02-03 at 9 30 47 PM" src="https://user-images.githubusercontent.com/25985824/106836728-b3d9eb80-6667-11eb-9ac3-b29453f98c0e.png">

**Comment by benjaminpkane** [comment]
Resolved by #848
