### ISSUE TITLE
[BUG] AppConfig settings reset whenever filters are applied

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#855]
With FiftyOne v0.7.2, if I open the expanded sample modal and then adjust an AppConfig setting, eg toggling `Show attributes ` to False in the media player settings, I observe that this flag is reset to its AppConfig value every time I take an action such as applying a label filter or selecting/deselecting fields that updates the App state.

Ideally any manual modifications I make to App settings would not be overridden until I do something more permanent (I believe that previously our convention has been that modal settings are reset when the modal is closed, which would be fine by me here).

<img width="1220" alt="Screen Shot 2021-02-10 at 11 56 52 PM" src="https://user-images.githubusercontent.com/25985824/107603740-b73b1d00-6bfb-11eb-8930-834366786205.png">

**Comment by benjaminpkane** [comment]
I will try to respond to this today.

**Comment by brimoor** [comment]
Resolved in v0.7.3 release!
