### ISSUE TITLE
[BUG] You can select objects in the App from unselected fields

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#883]
Related to https://github.com/voxel51/fiftyone/pull/877 and https://github.com/voxel51/fiftyone/issues/876

When in the expanded view, if I open up an image with detection and unselect all fields, I can click where the boxes were and the `X objects selected` increases.

Not sure if this should be fixed by #877 , but when I tried that PR it still seemed to be happening.

![image](https://user-images.githubusercontent.com/21222883/108772312-da829800-752a-11eb-8d05-c6a98daed90b.png)

**Comment by benjaminpkane** [comment]
Good catch, I'll ensure this is fixed with #838

**Comment by benjaminpkane** [comment]
Reolved by #877
