### ISSUE TITLE
[FR] Add support for selecting objects using *only* their IDs

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#891]
The [select_objects()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.collections.html#fiftyone.core.collections.SampleCollection.select_objects) view stage supports creating a view that only contains certain objects, and, as shown in the example code in the docs, it works very naturally with `session.selected_objects`, which provides the necessary info automatically from a user's mouse clicks.

However, it also may be useful for a user to select objects using only their `IDs`, without having to worry about what field or sample the object is in. One way to accomplish this is via the pattern below:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F
from fiftyone.core.expressions import ObjectId

dataset = foz.load_zoo_dataset("quickstart")

# Grab some object IDs
object_ids = [
    dataset.first().ground_truth.detections[0].id,
    dataset.last().predictions.detections[0].id,
]

# Create a view that only contains these objects
_object_ids = [ObjectId(_id) for _id in object_ids]
view = (
    dataset
    .filter_labels(
        "ground_truth", F("_id").is_in(_object_ids), only_matches=False
    ).filter_labels(
        "predictions", F("_id").is_in(_object_ids), only_matches=False
    ).match(
        (F("ground_truth.detections").length() > 0)
        | (F("predictions.detections").length() > 0)
    )
)

session = fo.launch_app(view=view)
```

The following ideas come to mind:
(a) add optional support for passing a simple list of IDs to `select_objects()`, in which case the stage will internally use the pattern above to construct the view
(b) deprecate the more expressive but clunky current syntax and *only* support the above
(c) add a new stage that allows for selection via the above syntax

Perhaps (a) is the best best for now?

An important observation is that the pattern shown above will be quite slow for datasets with many `Label` fields.

Usage of the existing `select_objects()` stage:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

#
# Only include the objects currently selected in the App
#

session = fo.launch_app(dataset)

# Select some objects in the App...

view = dataset.select_objects(session.selected_objects)
```

**Comment by brimoor** [comment]
Another option could be to add a `SampleCollection.find_objects()` method that uses the above construction to locate the objects and return information about them in the format expected by `select_objects()`. The benefit here would be that you run `find_objects()` (slow) only once, and then use `select_objects()` (fast) in your subsequent operations

**Comment by benjaminpkane** [comment]
(a) would probably be an improvement, especially now that it seems like ids being used by other parts of FiftyOne.

I also think it would be nice to simplify our approach to `_id`, `id`, and `ObjectId`s for users so they never have to think about it...

**Comment by ehofesmann** [comment]
I agree with Ben, I think `select_objects()` should support both the current input and just a list of object ids. It should probably support different versions of the current input as well, for example, a dict with just object ids and associated label fields, or just sample ids and object ids without label fields. The more information you add the faster the method becomes.

Though most importantly, I really we should get rid of the need to use `ObjectId`. Just doing this through `filter_labels` on the `id` of objects was the most natural/first thing that I wanted to do.
