### ISSUE TITLE
[FR] Add option to toggle `only_matches` behavior in App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#917]
As of #793, the default behavior is to always omit samples that do not match the filters in the sidebar. This is definitely the right default behavior, and it works beautifully.

However, there are some use cases where one would rather the samples not change. A good example of wanting the sample list to stay fixed is when you are adjusting the confidence filter for a label field and trying to understand how different confidence values affect the results. It's harder to understand this if the samples in the grid change every time you adjust your search.

This effectively amounts to toggling the `only_matches=True/False` flag in the relevant stages.

This could be added as a toggle-able setting under the settings icon introduced in https://github.com/voxel51/fiftyone/pull/906.

**Comment by benjaminpkane** [comment]
Resolved with https://github.com/voxel51/fiftyone/pull/3248
