### ISSUE TITLE
[BUG] Installing model zoo packages

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#919]
Update the [basic model zoo docs](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/index.html) to mention the `install_requirements` parameter.

Fix install errors found by @jasoncorso when trying to load a model requiring `tensorflow-gpu|tensorflow>=2`:
```python
import fiftyone.zoo as foz

model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf", install_requirements=True)
```
```shell
OSError: Failed to install package 'tensorflow-gpu|tensorflow>=2'
ERROR: Invalid requirement: 'tensorflow-gpu|tensorflow>=2'
```

System: Linux, Python 3.8

**Comment by brimoor** [comment]
@ehofesmann https://github.com/voxel51/eta/pull/505.
