### ISSUE TITLE
[BUG] Settings menu erroneously appears in App screenshots

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#921]
On `develop`, when freezing a session in a Jupyter notebook via `session.freeze()`, I often see this:

![download](https://user-images.githubusercontent.com/25985824/112070854-f33f9700-8b44-11eb-958c-5c934e0e79c7.png)

**Comment by benjaminpkane** [comment]
I'm having trouble reproducing, but will add logic to p51 to force hide options in thumbnail mode.

**Comment by brimoor** [comment]
Haven't seen this in ages.
