### ISSUE TITLE
[FR] Snap to integers for int field filters in App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#927]
It would be nice if scalar filters for `IntField`s would snap to integers (with the filter being inclusive of both endpoints). Currently the filter is floating point

```py
import random

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart").clone()

dataset.add_sample_field("int_field", fo.IntField)
values = [random.randint(0, 100) for _ in range(len(dataset))]
dataset.set_values("int_field", values)

session = fo.launch_app(dataset)
```

<img width="276" alt="Screen Shot 2021-03-23 at 5 33 51 PM" src="https://user-images.githubusercontent.com/25985824/112221674-1d08c480-8bfe-11eb-9b70-f7d9a12f13c8.png">

**Comment by benjaminpkane** [comment]
Resolved by #963
