### ISSUE TITLE
[BUG] Image Selection in app is not working

### ISSUE THREAD

**Issue by antys10g** [voxel51/fiftyone#928]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  ubuntu 18
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**:
fiftyone v0.7.4, Voxel51, Inc.
-   **Python version**:
Python 3.8.6

### Commands to reproduce

```
fiftyone quickstart
```
2. select some images
3. https://voxel51.com/docs/fiftyone/user_guide/app.html#selecting-samples
do this
![reproduce](https://voxel51.com/docs/fiftyone/_images/app-selection.gif)

and then nothing happends and app prints error WebSocketClosedError
![bug](https://user-images.githubusercontent.com/16255998/112233491-d4bbc780-8c3a-11eb-9f9f-44c25b8a6c27.gif)
# Stacktrace
Server Error

An exception has been raised by the server. Your session has been reverted to its previous state.

Traceback (most recent call last):
  File "main.py", line 181, in wrapper
    result = await func(self, *args, **kwargs)
  File "main.py", line 444, in on_message
    await event(self, **message)
  File "main.py", line 625, in on_add_selection
    await self.send_updates(ignore=self)
  File "main.py", line 799, in send_updates
    client.write_message(response)
  File "main.py", line 410, in write_message
    return super().write_message(message)
  File "/home/michal/anaconda3/envs/ml_workspace/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

### Details
It is weird but after uninstalling fifty one and installing it freshly it has been working for some time.
also session.selected is empty
![image](https://user-images.githubusercontent.com/16255998/112233918-a12d6d00-8c3b-11eb-986b-291f561cd579.png)

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [x] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by benjaminpkane** [comment]
Thanks for the issue @antys10g!

Our next release is coming very soon, and will have this issue resolved. I will close this issue with a message mentioning you when the new version is available. Cheers!

**Comment by benjaminpkane** [comment]
@antys10g this is now resolved in `0.8.0`

`pip install -U fiftyone`
