### ISSUE TITLE
[FR] Consider allowing multiple rows of image tags in the sample grid

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#934]
The old behavior in the App was to let image tags stack up into multiple rows. More recently, the design was changed to always squash labels onto one row, which, as the example below illustrates, can make them rather unreadable for more densely annotated datasets.

There's at least two separate decision axes here:
- How to handle long individual tags?
- One row or multiple rows?

On balance, I find that the current design abbreviates tags too aggressively such that I can't fully read them. A recent example I had was an image with two tags: `[Parasitized] [Parasitized]`, but it was abbreviated as something like `[Pa...] [Pa...]` in a Jupyter notebook, which made it tough to parse.

On balance, I'm inclined to say that allowing multiple rows may be better. With that said, baking some level of abbreviation to handle `very long tags when they appear` would be appropriate. Perhaps the ideal would be some intelligent logic that would abbreviate more aggressively when there are more tags?

A related thought is that implementing a grid zoom option per https://github.com/voxel51/fiftyone/issues/749 would help to provide more real estate for individual samples in an environment with a fixed width App with dense annotations.

![download](https://user-images.githubusercontent.com/25985824/112703947-31072d00-8e6f-11eb-92ef-e06e5a26beef.png)

**Comment by ehofesmann** [comment]
I agree, the abbreviation should exist for longer tags but needs to be much less aggressive, and that they should be expanded to multiple rows as needed. My main concern is coving images completely with tags. Maybe making the tag backgrounds slightly transparent could help.

More aggressive abbreviation for longer labels makes sense but I would still not go too far with it. You should retain at least 3 or 4 characters per label.
