### ISSUE TITLE
[BUG] Add segmentation support for video samples in the App

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#940]
Currently, the first frame's mask will render in the grid and expanded sample view, but later frames will not be updated.

Fully supporting this feature has been overlooked and is blocked ETA's `VideoLabels` supporting only one mask per frame, and the default serialization of numpy arrays by ETA.

More generally, this issue arises from the fact that Player51 does not natively support serialized FiftyOne `Sample`s.

**Comment by brimoor** [comment]
I was thinking earlier today that it is time to replace `VideoLabels` with FiftyOne `Label` types as the native format in the media player.

It will help with performance overall, especially video datasets with many frames, where there can be a substantial amount of time spent converting formats on the backend, and it will also unblock this issue.

**Comment by benjaminpkane** [comment]
Yes, I will work on supporting FiftyOne `label` types in the media player in the background. It is correct way to resolve this issue, and improve performance, in general.

I do not see this work being completed before the release, though, without a delay.
