### ISSUE TITLE
[BUG] Error when opening histograms in the App

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#952]
When I click on `Labels`, `Scalars`, `Tags`, or `Show`, I the App errors out and asks to revert to an old view. The inspector shows the following error. 

I have tried restarting FiftyOne and clearing my browser cache but that didn't help. I tried this in both `oi-dataset` and `develop` branches.

```shell
TypeError: n.default is not a constructor
    at v (index.js:1357)
    at y (index.js:1357)
    at Object.<anonymous> (index.js:1357)
    at GSe (index.js:1357)
    at index.js:1386
    at Array.reduce (<anonymous>)
    at WOe (index.js:1386)
    at index.js:1386
    at Array.forEach (<anonymous>)
    at d.value (index.js:1386)
```

![image](https://user-images.githubusercontent.com/21222883/113314697-92e5ed80-92da-11eb-93aa-da27d2a14129.png)

**Comment by benjaminpkane** [comment]
Resolved by https://github.com/voxel51/fiftyone/pull/943/commits/6638597d4bf1a330c721fbce0e6ad2af7c9b9998 in https://github.com/voxel51/fiftyone/pull/943
