### ISSUE TITLE
[DOCS] Show how to add COCO style predictions

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#960]
From the a post in help, there is no clear documentation showing how to iterate through existing predicted detections and add them to a dataset. For example, if you have a json file full of predictions looking like this:
```json
  {
        "image_id": 0,
        "category_id": 1,
        "score": 0.27732887864112854,
        "bbox": [
            940.6213989257812,
            221.6245574951172,
            99.18878173828125,
            106.35011291503906
        ]
    },
```

The [existing recipe](https://voxel51.com/docs/fiftyone/recipes/adding_detections.html#) generates predictions from a model and adds them which is a slightly different workflow. That recipe should be expanded to include something like the following:
```python
import fiftyone as fo
import json

dataset = YOUR_FIFTYONE_DATASET

# We will need image height and width to convert bounding boxes to relative coordinates
dataset.compute_metadata()

image_filepaths = {0: "/path/to/image1.png", ...}
classes = ["class1", ....]

with open("predictions.json", 'r') as f:
    json_data = json.load(f)

predictions = {}

# Create Detection objects
for prediction in json_data:
    image_id = prediction["image_id"]
    filepath = image_filepaths[image_id]
    sample = dataset[filepath]
    img_w = sample.metadata["width"]
    img_h = sample.metadata["height"]

    category_id = prediction["category_id"]
    confidence = prediction["score"]
    x,y,w,h = prediction["bbox"]
    bounding_box = [x / img_w, y / img_h, w / img_w, h / img_h]

    detection = fo.Detection(
        label = classes[category_id],
        confidence = confidence,
        bounding_box = bounding_box,
    )

    if filepath not in predictions:
        predictions[filepath] = []
    predictions[filepath].append(detection)

PREDICTION_FIELD_NAME = "predictions"

# Add predictions to dataset
for filepath, detections in predictions.items():
    sample = dataset[filepath]   
    sample[PREDICTION_FIELD_NAME] = fo.Detections(detections=detections)
    sample.save()    
```

**Comment by brimoor** [comment]
Closing this because, as of `fiftyone=0.12.0`, we provide an API method for natively loading COCO predictions into a dataset, as [described here](https://voxel51.com/docs/fiftyone/integrations/coco.html#loading-coco-formatted-data).

Also, [this section](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/index.html#custom-formats) prominently displayed in the `Loading datasets` section of the user guide shows similar code to what is written above, and the [existing recipe](https://voxel51.com/docs/fiftyone/recipes/adding_detections.html) continues to show a nice practical example of adding model predictions.

**Comment by ted8201** [comment]
> Closing this because, as of `fiftyone=0.12.0`, we provide an API method for natively loading COCO predictions into a dataset, as [described here](https://voxel51.com/docs/fiftyone/integrations/coco.html#loading-coco-formatted-data).
> 
> Also, [this section](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/index.html#custom-formats) prominently displayed in the `Loading datasets` section of the user guide shows similar code to what is written above, and the [existing recipe](https://voxel51.com/docs/fiftyone/recipes/adding_detections.html) continues to show a nice practical example of adding model predictions.

thanks for this awesome tools, I am exploring the wonderful functions. However,
as the tutorial shows `import fiftyone.utils.coco as fouc

#
# Mock COCO predictions, where:
# - `image_id` corresponds to the `coco_id` field of `coco_dataset`
# - `category_id` corresponds to classes in `coco_dataset.default_classes`
#
predictions = [
    {"image_id": 1, "category_id": 18, "bbox": [258, 41, 348, 243], "score": 0.87},
    {"image_id": 2, "category_id": 11, "bbox": [61, 22, 504, 609], "score": 0.95},
]

# Add COCO predictions to `predictions` field of dataset
fouc.add_coco_labels(coco_dataset, "predictions", predictions)

# Verify that predictions were added to two images
print(coco_dataset.count("predictions"))  # 2`
however when performing detection evaluation you need predictions.detections `print(coco_dataset.count("predictions.detections"))` we could not get predictions.detections in this way. I think the doc should be more specific, and make a demo evaluation using custom coco format dataset and coco detection result json file.

**Comment by ted8201** [comment]
`predictions = [
    {"image_id": 1, "category_id": 18, "bbox": [258, 41, 348, 243], "score": 0.87},
    {"image_id": 2, "category_id": 11, "bbox": [61, 22, 504, 609], "score": 0.95},
]

# Add COCO predictions to `predictions` field of dataset
fouc.add_coco_labels(coco_dataset, "predictions", predictions)

# Verify that predictions were added to two images
print(coco_dataset.count("predictions"))  # 2`

However what we need is "predictions.detections"
