### ISSUE TITLE
[FR] Add support for subclassing datasets and samples

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#987]
There have been user requests to be able to use FiftyOne with data stored in an existing format without explicitly copying the data into MongoDB.

One approach for implementing this would be to let users subclass `Dataset` and `Sample` and implement all the relevant methods like `Dataset.__len__()`, `Sample.from_dict()`, `Sample.save()` and so on such that they can use FiftyOne with their own dataset format. This would enable, for example, using FiftyOne without MongoDB.

FiftyOne's dataset/sample API is quite extensive, so it would take a fair bit of code to fully implement one's own `Dataset`/`Sample` classes.

**Comment by brimoor** [comment]
Upon further thought, a proper implementation of such subclasses would be *very* extensive as the user would need to provide implementations of all `ViewStage`s that they would like to use, for example.

**Comment by swheaton** [comment]
seems clear to me this is a "not going to do" FR, closing.
