### ISSUE TITLE
[BUG] Cannot load any COCO dataset

### ISSUE THREAD

**Issue by KosayJabre** [voxel51/fiftyone#993]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
-   **FiftyOne installed from (pip or source)**: Pip
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone v0.8.0.1, Voxel51, Inc.
-   **Python version**: Python 3.8.5

### Commands to reproduce

I created a test COCO dataset that looks like this:

```
/my_dir
    /dataset
        /data
            frame1.PNG
        labels.json
    test.py
```

My labels.json looks like this:

```
{
    "licenses": [
        {
            "name": "",
            "id": 0,
            "url": ""
        }
    ],
    "info": {
        "contributor": "",
        "date_created": "",
        "description": "",
        "url": "",
        "version": "",
        "year": ""
    },
    "images": [
        {
            "id": 1,
            "width": 640,
            "height": 480,
            "file_name": "frame1.PNG",
            "license": 0,
            "flickr_url": "",
            "coco_url": "",
            "date_captured": 0
        }
    ],
    "annotations": [
        {
            "id": 1,
            "image_id": 1,
            "category_id": 1,
            "segmentation": [
                [
                    270.15,
                    251.69,
                    300.92,
                    230.15,
                    340.31,
                    213.54,
                    375.38,
                    196.31,
                    423.38,
                    197.54,
                    448.62,
                    209.23,
                    456.0,
                    236.31,
                    456.0,
                    256.0,
                    417.23,
                    260.92,
                    364.92,
                    264.0,
                    323.08,
                    262.15,
                    267.08,
                    267.69
                ]
            ],
            "area": 9221.0,
            "bbox": [
                267.08,
                196.31,
                188.92,
                71.38
            ],
            "iscrowd": 0,
            "attributes": {
                "occluded": false,
                "track_id": 0,
                "keyframe": true
            }
        }
    ]
}
```

My test.py looks like this:

```
import os
import fiftyone

SCRIPT_PATH = os.path.dirname(os.path.abspath(__file__))
DATASET_PATH = os.path.join(SCRIPT_PATH, "dataset")

dataset = fiftyone.Dataset(DATASET_PATH, fiftyone.types.COCODetectionDataset, overwrite=True)
session = fiftyone.launch_app(dataset, port=5151)
session.wait()
```

### Describe the problem

When I try to load any COCO dataset, it shows up as having 0 images. I cannot load any COCO dataset exported by CVAT or any dataset that I manually create, like above.

If I try to print the dataset object, I get:
```
Name:           /mnt/c/Users/kosay/Desktop/fiftyonetest/dataset
Media type:     None
Num samples:    0
Persistent:     False
Tags:           []
Sample fields:
    filepath: fiftyone.core.fields.StringField
    tags:     fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.Metadata)
App launched. Point your web browser to http://localhost:5151
```

Any ideas how to fix this? 

Also, if I mess up the path to the dataset, it does not raise an exception. Can give it a completely garbage path, and it doesn't complain. 

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x ] No. I cannot contribute a bug fix at this time.

**Comment by KosayJabre** [comment]
I just exported my dataset as CVAT Image format from CVAT, and the CVAT Image dataser loader in fiftyone is also failing to load that. Same thing, it shows 0 images loaded.

**Comment by brimoor** [comment]
Hi @KosayJabre, this fix should do the trick for you (tested on your data):

```py
# wrong syntax
dataset = fiftyone.Dataset(DATASET_PATH, fiftyone.types.COCODetectionDataset, overwrite=True)

# correct syntax
dataset = fiftyone.Dataset.from_dir(DATASET_PATH, fiftyone.types.COCODetectionDataset)
```

**Comment by brimoor** [comment]
The [Dataset()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.dataset.html#fiftyone.core.dataset.Dataset) class constructor syntax is only used for creating empty datasets. We should probably validate the parameters better, as the second argument is actually a `persistent=True/False` flag that controls whether the dataset will persist between sessions.

The [Dataset.from_dir()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.dataset.html#fiftyone.core.dataset.Dataset.from_dir) factory method creates a dataset from an existing directory on disk.

**Comment by brimoor** [comment]
The fact that FiftyOne lets you create a dataset with filepaths that don't actually exist is by design. If you view such a dataset in the App, you'll see a missing image icone to alert you to the issue.

**Comment by KosayJabre** [comment]
That worked! Thanks very much.

I agree, maybe that second parameter could use some validation to make sure it's a boolean.
