### ISSUE TITLE
[BUG] session.wait() does not detect closing the web interface

### ISSUE THREAD

**Issue by jneeven** [voxel51/fiftyone#998]
### System information
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Manjaro Linux
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: v0.8.0.1,
-   **Python version**: 3.8.8

### Describe the problem
If I launch the FiftyOne app from a non-interactive Python script and call `session.wait()`, the web app is automatically opened in my (already open) browser, but closing it doesn't seem to trigger anything. The script blocks forever until I shut it down manually with CTRL + C, and then the code below `session.wait()` is never executed.

From the docs this seems like a pretty standard use-case, so I suspect I may be doing something wrong? Any help would be greatly appreciated! I intend to use the app as a somewhat standalone interface; I would strongly prefer not having to wrap it in a notebook. Thanks!

### Code to reproduce issue

```python
    directory = "some_directory"
    dataset = fo.Dataset.from_dir(directory, fo.types.ImageDirectory, name="Local data")
    session = fo.launch_app(dataset)
    session.wait()
    dataset.save()
    print("Saved FiftyOne dataset")
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by jneeven** [comment]
Ah, I've now tried launching it with `desktop=True` and that works as intended. Is this behaviour not supported with the web interface? It would make complete sense if not, but then perhaps it would be nice to add that to the docs :)

**Comment by benjaminpkane** [comment]
Hi @jneeven. Thanks for the issue! Browser support for `session.wait()` was previously overlooked, apologies. I'll be adding support, barring any browser limitations. Stay tuned!
